<div class="page-header">
    <?php if (isset($this->company) and $this->company):?>
        <h1>Edit Company</h1>
    <?php else:?>
        <h1>Create Company</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<div class="row-fluid">
    <div class="span6">
        <form role="form" id="form" class="form-horizontal" action="<?php echo HOST.'manage/company-save';?>" method="post">
            <div class="row-fluid">  
                <div class="control-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" required="required" value="<?php if (isset($this->company) && $this->company) echo $this->company['name']; ?>">
                </div>
            </div>
            <div class="row-fluid">  
                <div class="control-group">
                    <input type="hidden"  name="id" id="id" value="<?php isset($this->company) and $this->company and printf($this->company['id']);?>">
                    <button type="submit" id="submit_btn" class="btn btn-primary ">Submit</button>
                    <button type="button" class="btn btn-danger" onclick="window.location='<?php echo HOST ?>manage/company'">Go back</button>
                </div>
            </div>
        </form>
    </div>
</div>