<table class="table table-bordered">
    <thead>
    <tr>
        <th>No.</th>
        <th>Staff code</th>
        <th>Staff name</th>
        <th>Area</th>
        <th>Regional Market</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $db = Zend_Registry::get('db');
    $QSalesCheckInLog = new Application_Model_SalesCheckInLog();

    if (isset($this->sales_check_in) and $this->sales_check_in)
        foreach ($this->sales_check_in as $k=>$sales_check_in): ?>
            <tr>
                <td>
                    <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                    ?>
                </td>
                <td><?php echo $sales_check_in['staff_code'];?></td>
                <td><?php echo $sales_check_in['staff_name'];?></td>
                  <td><?php echo $sales_check_in['regional_name'];?></td>
                <td><?php echo $sales_check_in['area_name'];?></td>

                <td>
                    <a title="View" href="/trainer/sales-report-check-in-edit?id=<?php echo $sales_check_in['staff_id'];?>&month_year=<?php echo date('Y-m'); ?>"> <i class="icon-eye-open"></i></a>

                    <a title="Report Web" href="/trainer/sales-report-check-in-web?id=<?php echo $sales_check_in['staff_id'];?>&start_date=<?php echo date('Y-m'); ?>" target="_blank"> <i class="icon-print"></i></a>
                    <a title="Report Excel" href="/trainer/sales-report-check-in-excel?id=<?php echo $sales_check_in['staff_id'];?>&start_date=<?php echo date('Y-m'); ?>" target="_blank"> <i class="icon-list-alt"></i></a>
                </td>

            </tr>

        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>



<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>


<script>

    function saveRemark(status_id) {

        var ti_id       = $('#modal_ti_id').val();
        var remark      = $('#modal_remark').val();

        $.post('<?php echo HOST ?>timing/timing-issue-remark-save',
        {
            ti_id       : ti_id,
            remark      : remark,
            status_id   : status_id
        },
        function(data){
            //alert("Update Successful!");
            location.reload();
            //refreshMarketName();
        });
    }

    $(document).ready(function () {

        $modal = $('#modal');
        $('.icon-edit').click(function(){

            _self = $(this);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>timing/timing-issue-remark',
                {
                    ti_id : _self.data('ti-id')
                },
                function(data){
                    //alert(data);
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(7)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
        });

    });

</script>

<?php //echo $this->load();?>