<style>
    .target { width:100px; }
    .target_hero { width:100px; }
    .target_price { width:100px; }
</style>

<?php 
    
    $disabled = '';
    $save_flag = 1;
    $rd_flag = $sd_flag = 1;

    if ($this->sales_target) {
        foreach ($this->sales_target as $key => $value) { if ( $value['rd_approve_by'] != '' ) { $rd_flag = 0; $save_flag = 0; break; } }
        foreach ($this->sales_target as $key => $value) { if ( $value['sd_approve_by'] != '' ) { $sd_flag = 0; break; } }
    }
    
?>

<div class="page-header">
    <div class="row">
        <div class="span6 pull-left">
            <h1>Sale Target : <?php echo $this->params['area_name']; ?></h1>
            <br/>
            <?php 
                if ( $rd_flag == 0 ) { echo "<span class='label label-success'>RD Approved</span>"; }
                if ( $sd_flag == 0 ) { echo "&nbsp;<span class='label label-success'>Sale Director Approved</span>"; }
            ?>
        </div>
        <div class="span6 pull-right" align="right">
            <h2>Target :<b id='area_target' name='area_target'></b></h2>
            <h2><b id='area_target_hero' name='area_target_hero'></b></h2>
            <h2><b id='area_target_hero' name='area_target_hero'></b></h2>
            <h2 align="right">Hero Product : <b style="color:darkcyan;"><?php echo $this->hero['hero_product_name']; ?></b></h2>
            <!-- <div style="border: 2px solid red;border-radius: 8px;" align="center"><h3>** Total Sale Target cannot higher or lower than 50% of Area Target.</h3></div> -->
        </div>
    </div>
</div>

<form role="form" action="<?php echo HOST.'manage/oppo-sale-target-save';?>" method="post">

<table class="table table-bordered">
    <thead>
    <tr>
        <th style="width:3%"><div align="center">No.</div></th>
        <th style="width:10%"><div align="center">Staff Code</div></th>
        <th style="width:27%"><div align="center">Staff Name</div></th>
        <th style="width:10%"><div align="center">Group</div></th>
        <!-- <th style="width:50%"><div align="center">Remark</div></th> -->
    </tr>
    </thead>
    <tbody>

        <?php 

            if ($this->leader_list) {

                $leader_data = $this->leader_list;
                $cnt = 0;

                for($i=0;$i<count($leader_data);$i++) { 

                    // Leader Remark
                    if ( isset($leader_data[$i]['otr_remark']) ) {
                        $leader_remark = "value='".$leader_data[$i]['otr_remark']."' ".$disabled;
                        $otr_id = "value='".$leader_data[$i]['otr_id']."|".$leader_data[$i]['otr_remark']."' ";

                    } else {
                        $leader_remark = "value=''";
                        $otr_id = "value=''";
                    }

                    $cnt = $i + 1;
                    echo "<tr>";
                    echo    "<td><div align='center'>".$cnt."</div></td>";
                    echo    "<td><div align='center'>".$leader_data[$i]['staff_code']."</div></td>";
                    echo    "<td><div align='center'>".$leader_data[$i]['staff_name']."</div></td>";
                    echo    "<td><div align='center'>".$leader_data[$i]['group_name']."</div></td>";

                    // echo    "<td><div align='center'>
                    //             <input type='text' id='leader_remark[".$leader_data[$i]['staff_id']."]' name='leader_remark[".$leader_data[$i]['staff_id']."]' style='width:500px;' $leader_remark /> 
                    //             <input type='hidden' id='otr_id[".$leader_data[$i]['staff_id']."]' name='otr_id[".$leader_data[$i]['staff_id']."]' $otr_id /> 
                    //         </div></td>";
                    echo "</tr>";
                }

            }

        ?>

    </tbody>
</table>

<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align="center">No.</div></th>
        <th><div align="center">Sub Area</th>
        <th><div align="center">Staff Code</div></th>
        <th><div align="center">Staff Name</div></th>
        <!-- <th><div align="center">Store</div></th> -->
        <!-- <th><div align="center"><?php echo $this->params['last_03']; ?></div></th> -->
        <!-- <th><div align="center"><?php echo $this->params['last_02']; ?></div></th> -->
        <th><div align="center"><?php echo $this->params['last_01']; ?></div></th>
        <!-- <th><div align="center">Avg.</div></th> -->
        <th><div align="center">Target</div></th>
        <th><div align="center">Hero Target</div></th>
        <!-- <th><div align="center">Price Target</div></th> -->
        <!-- <th><div align="center">COM.</div></th> -->
        <!-- <th><div align="center">Remark</div></th> -->
    </tr>
    </thead>
    <tbody>
        <?php 
            $userStorage = Zend_Auth::getInstance()->getStorage()->read();

            $params = $this->params;
            $data = $this->lists;
            $data2 = $this->sales_target;

            $cnt = 0;
            $sum_target = 0;
            $sum_target_hero = 0;

            $sellout_avg = 0;

            $now = date('Y-m-d H:i:s');
            $tmp = explode("-", $params['from']);

            $allow_range_start = $tmp[0]."-".$tmp[1]."-01 00:00:00";
            $allow_range_end = $tmp[0]."-".$tmp[1]."-15 23:59:59";

            if ($this->lists) {

                //if ( $now >= $allow_range_start && $now <= $allow_range_end ) { $save_flag = 1; }

                //if ( $allow_range_start >= '2017-11-01 00:00:00' ) { $save_flag = 1; }  

                if ( $userStorage->group_id == ADMINISTRATOR_ID || $userStorage->group_id == 2024 || $userStorage->group_id == RM_ID || $userStorage->group_id ==  ASM_ID) { $disabled = ''; $save_flag = 1; } else { $disabled = ''; } // Disable after 10th 'readonly'

                for($i=0;$i<count($data);$i++) { 

                    $com = '';

                    // Normal Target 
                    if ( isset($data2[ $data[$i]['sub_id'] ]['target']) ) {
                        $target = "value='".$data2[ $data[$i]['sub_id'] ]['target']."' ".$disabled;
                        $ost_id = "value='".$data2[ $data[$i]['sub_id'] ]['ost_id']."|".$data2[ $data[$i]['sub_id'] ]['target']."|".$data2[ $data[$i]['sub_id'] ]['com']."' ";

                        $sum_target = $sum_target + $data2[ $data[$i]['sub_id'] ]['target'];
                    } else {
                        $target = "value=''";
                        $ost_id = "value=''";
                        //$save_flag = 1;
                    }

                    // Hero Target
                    if ( isset($data2[ $data[$i]['sub_id'] ]['target_hero']) ) {
                        $target_hero = "value='".$data2[ $data[$i]['sub_id'] ]['target_hero']."' ".$disabled;
                        $hero_ost_id = "value='".$data2[ $data[$i]['sub_id'] ]['ost_id']."|".$data2[ $data[$i]['sub_id'] ]['target_hero']."' ";

                        $sum_target_hero = $sum_target_hero + $data2[ $data[$i]['sub_id'] ]['target_hero'];
                    } else {
                        $target_hero = "value=''";
                        $hero_ost_id = "value=''";
                        //$save_flag = 1;
                    }

                    // // Price Target 
                    // if ( isset($data2[ $data[$i]['staff_id'] ]['target_price']) ) {
                    //     $target_price = "value='".$data2[ $data[$i]['staff_id'] ]['target_price']."' ".$disabled;
                    //     $price_ost_id = "value='".$data2[ $data[$i]['staff_id'] ]['ost_id']."|".$data2[ $data[$i]['staff_id'] ]['target_price']."' ";

                    //     $sum_target_price = $sum_target_price + $data2[ $data[$i]['staff_id'] ]['target_price'];
                    // } else {
                    //     $target_price = "value=''";
                    //     $price_ost_id = "value=''";
                    //     //$save_flag = 1;
                    // }

                    // // Remark
                    // if ( isset($data2[ $data[$i]['staff_id'] ]['remark']) ) {
                    //     $remark = "value='".$data2[ $data[$i]['staff_id'] ]['remark']."' ";
                    //     $remark_ost_id = "value='".$data2[ $data[$i]['staff_id'] ]['ost_id']."|".$data2[ $data[$i]['staff_id'] ]['remark']."' ";

                    // } else {
                    //     $remark = "value=''";
                    //     $remark_ost_id = "value=''";
                    //     //$save_flag = 1;
                    // }


                    if ( $data2[ $data[$i]['staff_id'] ]['com'] == 1 ) { $com = "checked"; }

                    // $sellout_avg = ($data[$i]['last_03'] + $data[$i]['last_02'] + $data[$i]['last_01']) / 3;
                    $sellout_avg = ($data[$i]['last_02'] + $data[$i]['last_01']) / 2;

                    if ($userStorage->group_id == SALES_ADMIN_ID) {
                        $data[$i]['cnt_store'] = '';
                        $data[$i]['last_03'] = '';
                        $data[$i]['last_02'] = '';
                        $data[$i]['last_01'] = '';
                        $sellout_avg = '';
                    }

                    // Reset Store Target of this Area 
                    $reset_btn = "";
                    if ($userStorage->group_id == ADMINISTRATOR_ID) {
                        $reset_btn = "<br/>
                            <a title='Reset Store Target of this Area' href='".HOST."manage/oppo-sale-target-reset-sale?staff_id=".$data[$i]['staff_id']."&staff_name=".$data[$i]['staff_name']."&from_date=".$params['from']."&to_date=".$params['to']."&area_id=".$params['area_id']."' onclick=\"return confirm('ຕ້ອງການຢືນຢັນການ Reset Store Target ທົງໝົດຂອງ Sale : ".$data[$i]['staff_name'] ." ຫຼືບໍ?')\">
                                <span class='label label-warning'>Reset</span>
                            </a>";
                    }

                    $cnt = $i + 1;
                    echo "<tr>";
                    echo    "<td><div align='center'>".$cnt."</div></td>";
                    echo    "<td><div align='center' style='color: red'>".$data[$i]['sub_area_name']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['staff_code']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['staff_name']."</div></td>";

                    // echo    "<td><div align='center'>".$data[$i]['cnt_store']."</div></td>";
                    // echo    "<td><div align='center'>".number_format($data[$i]['last_03'])."</div></td>";
                    // echo    "<td><div align='center'>".number_format($data[$i]['last_02'])."</div></td>";
                   echo    "<td><div align='center'>".number_format($data[$i]['last_01'])."</div></td>";
                    // echo    "<td><div align='center'>".number_format($sellout_avg)."</div></td>";

                    echo    "<td><div align='center'>
                                <input type='number' required='required' style='text-align:center; color:blue;' class='target' id='target[".$data[$i]['sub_id']."]' name='target[".$data[$i]['sub_id']."]' $target /> 
                                <input type='hidden' style='text-align:center;' id='ost_id[".$data[$i]['sub_id']."]' name='ost_id[".$data[$i]['sub_id']."]' $ost_id /> 
                            </div></td>";

                    echo    "<td><div align='center'>
                                <input type='number' required='required' style='text-align:center; color:blue;' class='target_hero' id='target_hero[".$data[$i]['sub_id']."]' name='target_hero[".$data[$i]['sub_id']."]' $target_hero /> 
                                <input type='hidden' style='text-align:center;' id='hero_ost_id[".$data[$i]['sub_id']."]' name='hero_ost_id[".$data[$i]['sub_id']."]' $hero_ost_id /> 
                            </div></td>";

                    // echo    "<td><div align='center'>
                    //             <input type='number' style='text-align:right;' class='target_price' id='target_price[".$data[$i]['staff_id']."]' name='target_price[".$data[$i]['staff_id']."]' $target_price /> 
                    //             <input type='hidden' style='text-align:right;' id='price_ost_id[".$data[$i]['staff_id']."]' name='price_ost_id[".$data[$i]['staff_id']."]' $price_ost_id /> 
                    //         </div></td>";

                    // echo    "<td><div align='center'><input type='checkbox' disabled='disabled' checked='checked' id='com[".$data[$i]['staff_id']."]' name='com[".$data[$i]['staff_id']."]' value=check $com />".$reset_btn."</div></td>";

                    // echo    "<td><div align='center'>".$data2[ $data[$i]['staff_id'] ]['set_date']."</div></td>";
                    // echo    "<td><div align='center'>
                    //             <input type='text' id='remark[".$data[$i]['staff_id']."]' name='remark[".$data[$i]['staff_id']."]' $remark /> 
                    //             <input type='hidden' id='remark_ost_id[".$data[$i]['staff_id']."]' name='remark_ost_id[".$data[$i]['staff_id']."]' $remark_ost_id /> 
                    //         </div></td>";

                }

            }

            

        ?>
    </tbody>
</table>

<?php if ($this->lists2) { ?>
    <!-- <table class="table table-bordered">
        <thead>
        <tr>
            <th colspan="12"><div align="left"><h4><font color="red">*ລາຍຊື່ພະນັກງານທີ່ບໍ່ມີການຜູກຮ້ານຄ້າ</font></h4></div></th>
        </tr>
        <tr>
            <th><div align="center">No.</div></th>
            <th><div align="center">Staff Code</div></th>
            <th><div align="center">Staff Name</div></th>
            <th><div align="center">Store</div></th>
            <th><div align="center"><?php echo $this->params['last_03']; ?></div></th>
            <th><div align="center"><?php echo $this->params['last_02']; ?></div></th>
            <th><div align="center"><?php echo $this->params['last_01']; ?></div></th>
            <th><div align="center">Avg.</div></th>
            <th><div align="center">Target</div></th>
            <th><div align="center">Hero Target</div></th>
            <th><div align="center">Price Target</div></th>
            <th><div align="center">COM.</div></th>
             <th><div align="center">Remark</div></th> 
        </tr>
        </thead>
        <tbody>

            <?php 
                // Table #2 : Sale With No Store But Have Target
                if ($this->lists2) {

                    $data3 = $this->lists2;
                    $cnt = 0;

                    echo "<br/><br/>";

                    for($i=0;$i<count($data3);$i++) { 

                        $com = '';

                        // Normal Target
                        if ( isset($data3[$i]['target']) ) {
                            $target = "value='".$data3[$i]['target']."' ".$disable;
                            $ost_id = "value='".$data3[$i]['ost_id']."|".$data3[$i]['target']."|".$data3[$i]['com']."' ";

                            $sum_target = $sum_target + $data3[$i]['target'];
                        } else {
                            $target = "value=''";
                            $ost_id = "value=''";
                            //$save_flag = 1;
                        }

                        // Hero Target
                        if ( isset($data3[$i]['target_hero']) ) {
                            $target_hero = "value='".$data3[$i]['target_hero']."' ".$disable;
                            $hero_ost_id = "value='".$data3[$i]['ost_id']."|".$data3[$i]['target_hero']."' ";

                            $sum_target_hero = $sum_target_hero + $data3[$i]['target_hero'];
                        } else {
                            $target_hero = "value=''";
                            $hero_ost_id = "value=''";
                            //$save_flag = 1;
                        }

                        // Price Target
                        if ( isset($data3[$i]['target_price']) ) {
                            $target_price = "value='".$data3[$i]['target_price']."' ".$disable;
                            $price_ost_id = "value='".$data3[$i]['ost_id']."|".$data3[$i]['target_price']."' ";

                            $sum_target_price = $sum_target_price + $data3[$i]['target_price'];
                        } else {
                            $target_price = "value=''";
                            $price_ost_id = "value=''";
                            //$save_flag = 1;
                        }

                        // Hero Target
                        if ( isset($data3[$i]['remark']) ) {
                            $remark = "value='".$data3[$i]['remark']."' ".$disable;
                            $remark_ost_id = "value='".$data3[$i]['ost_id']."|".$data3[$i]['remark']."' ";

                        } else {
                            $remark = "value=''";
                            $remark_ost_id = "value=''";
                            //$save_flag = 1;
                        }


                        if ( $data3[$i]['com'] == 1 ) { $com = "checked"; }

                        $cnt = $i + 1;
                        // echo "<tr>";
                        // echo    "<td><div align='center'>".$cnt."</div></td>";
                        // echo    "<td><div align='center'>".$data3[$i]['staff_code']."</div></td>";
                        // echo    "<td><div align='center'>".$data3[$i]['staff_name']."</div></td>";
                        // echo    "<td><div align='center'>-</div></td>";
                        // echo    "<td><div align='center'>-</div></td>";
                        // echo    "<td><div align='center'>-</div></td>";
                        // echo    "<td><div align='center'>-</div></td>";
                        // echo    "<td><div align='center'>-</div></td>";

                        // echo    "<td><div align='center'>
                        //             <input type='number' required='required' style='text-align:right;' class='target' id='target[".$data3[$i]['staff_id']."]' name='target[".$data3[$i]['staff_id']."]' $target /> 
                        //             <input type='hidden' style='text-align:right;' id='ost_id[".$data3[$i]['staff_id']."]' name='ost_id[".$data3[$i]['staff_id']."]' $ost_id /> 
                        //         </div></td>";

                        // echo    "<td><div align='center'>
                        //         <input type='number' required='required' style='text-align:right;' class='target_hero' id='target_hero[".$data3[$i]['staff_id']."]' name='target_hero[".$data3[$i]['staff_id']."]' $target_hero /> 
                        //         <input type='hidden' style='text-align:right;' id='hero_ost_id[".$data3[$i]['staff_id']."]' name='hero_ost_id[".$data3[$i]['staff_id']."]' $hero_ost_id /> 
                        //     </div></td>";

                        // echo    "<td><div align='center'>
                        //         <input type='number' style='text-align:right;' class='target_price' id='target_price[".$data3[$i]['staff_id']."]' name='target_price[".$data3[$i]['staff_id']."]' $target_price /> 
                        //         <input type='hidden' style='text-align:right;' id='price_ost_id[".$data3[$i]['staff_id']."]' name='price_ost_id[".$data3[$i]['staff_id']."]' $price_ost_id /> 
                        //     </div></td>";

                        echo    "<td><div align='center'><input type='checkbox' disabled='disabled' checked='checked' id='com[".$data3[$i]['staff_id']."]' name='com[".$data3[$i]['staff_id']."]' value=check $com /></div></td>";

                        // echo    "<td><div align='center'>".$data3[$i]['set_date']."</div></td>";
                        // echo    "<td><div align='center'>
                        //         <input type='text' id='remark[".$data3[$i]['staff_id']."]' name='remark[".$data3[$i]['staff_id']."]' $remark /> 
                        //         <input type='hidden' id='remark_ost_id[".$data3[$i]['staff_id']."]' name='remark_ost_id[".$data3[$i]['staff_id']."]' $remark_ost_id /> 
                        //     </div></td>";
                    }

                }

            ?>

        </tbody>
    </table> -->

<?php } ?>

<?php 
    $target_max_20 = round($this->target_max * 3);
    $target_hero_max_20 = round($this->target_hero_max * 3);

    $target_max1 = $this->target_max - $target_max_20;
    $target_max2 = $this->target_max + $target_max_20;

    $target_hero_max1 = $this->target_hero_max - $target_hero_max_20;
    $target_hero_max2 = $this->target_hero_max + $target_hero_max_20;

    // echo "<h4 id='msg_target' name='msg_target'><font color='red'>Target Range : ".number_format($target_max1)." - ".number_format($target_max2)."</font></h4>";
    // echo "<h4 id='msg_target_hero' name='msg_target_hero'><font color='#04B431'>Hero Target Range : ".number_format($target_hero_max1)." - ".number_format($target_hero_max2)."</font></h4>";
?>



<br/>

<input type="hidden" name="month_year" id="month_year" value="<?php echo $this->params['from']; ?>">
<input type="hidden" name="area_id" id="area_id" value="<?php echo $this->params['area_id']; ?>">
<input type="hidden" name="back_url" id="back_url" value="<?php echo $this->back_url; ?>">

<!-- Old Start -->
<!-- <?php 
    // if ($save_flag == 1) { 

    //     $now = date('Y-m-d');
    //     $dealine = date('Y-m-7');
    //     $tmp = $this->params['from']." 00:00:00";

    //     if ( ( (strtotime($tmp) >= strtotime(date('Y-m-t 00:00:00')) ) || strtotime(date('Y-m-d 00:00:00')) < strtotime(date('Y-m-10 00:00:00')) || $sum_target == 0 ) || $userStorage->group_id == ADMINISTRATOR_ID ) {
    //     if($now >= $dealine){

            
    //     }else{
    //         echo "<button type='submit' class='btn btn-success' id='btn_save' name='btn_save' value='2'>Save</button>";
    //     }
        
    //     } else {
    //         echo "<button type='submit' class='btn btn-success' id='btn_save' name='btn_save' value='2'>Save</button>";
    //     }

    // }
?> -->
<!-- Old End -->


<?php 
    $date2 = date('d');
 if($userStorage->group_id == ADMINISTRATOR_ID){

    echo "<button type='submit' class='btn btn-success' id='btn_save' name='btn_save' value='2'>Save</button>";
    }else{
       if($date2 < 7){
        echo "<button type='submit' class='btn btn-success' id='btn_save' name='btn_save' value='2'>Save</button>";
    }
    
    }
?>



<button type="button" class="btn btn-danger go-back">Go Back</button>
<!-- <h3 style='display: inline-block;'><font color='red'>&nbsp;&nbsp;&nbsp;&nbsp; **WARNING!!! Target Cannot Edit After Save</font></h3> -->
<!-- <?php
 if ( in_array($userStorage->group_id, array(ADMINISTRATOR_ID,RM_ID,RMSTANDBY_ID)) ) {
        echo "<span> ຖ້າຈະເເກ້ເປົ້າ Heror Product ຈະຕ້ອງ ພິມເປົ້າ Normal Target ຄືນໃໝ່</span>";
     }
?>
 -->

<?php 
    if ($save_flag == 1) { 

        if ( in_array($userStorage->group_id, array(ADMINISTRATOR_ID,RM_ID,RMSTANDBY_ID)) ) {
            if ( ( (strtotime($tmp) >= strtotime(date('Y-m-t 00:00:00')) ) || strtotime(date('Y-m-d 00:00:00')) < strtotime(date('Y-m-10 00:00:00')) || $sum_target == 0 ) || $userStorage
                ->group_id == ADMINISTRATOR_ID || $userStorage->group_id == 5 || $userStorage->group_id == 7 || $userStorage->group_id == 28 ) {
            
                echo "<br/><br/>";
                // echo "<button type='submit' class='btn btn-primary' id='btn_save' name='btn_save' value='2'>RD Approve</button>";
            }
        }
    }
?>

</form>

<script type="text/javascript">
    $(document).ready(function () {

        // Check for First Load
        var target_sum = <?php echo $sum_target; ?>;
        var target_hero_sum = <?php echo $sum_target_hero; ?>;

        var target_max = <?php echo isset($this->target_max) ? $this->target_max : 0; ?>;
        var target_hero_max = <?php echo isset($this->target_hero_max) ? $this->target_hero_max : 0; ?>;

        var target_max_20 = Math.round(target_max * 3);
        var target_hero_max_20 = Math.round(target_hero_max * 3);

        if ( target_sum >= target_max) {
            $('#area_target').html("<font color='green'>"+ target_sum.toLocaleString() + "</font> / " + target_max.toLocaleString());
        } else {
            $('#area_target').html("<font color='red'>"+ target_sum.toLocaleString() + "</font> / " + target_max.toLocaleString());
        }

        if ( target_hero_sum >= target_hero_max) {
            $('#area_target_hero').html("Hero Target : <font color='green'>"+ target_hero_sum.toLocaleString() + "</font> / " + target_hero_max.toLocaleString());
        } else {
            $('#area_target_hero').html("Hero Target : <font color='red'>"+ target_hero_sum.toLocaleString() + "</font> / " + target_hero_max.toLocaleString());
        }

        //$('#area_target_hero').html("Hero Target : " + target_hero_sum.toLocaleString());
        
        // Check for Input Number [Normal Target]
        $(".target").keyup(function(){
            var sum = 0;

            $(".target").each(function(){
                sum += +$(this).val();
            });

            // Check Exceed 20% Target
            // if ( sum >= (target_max + target_max_20) ) { 
            //     alert("Target Exceed 50% of Target Acquire! This Sale Target will set to zero!"); 
            //     $(this).val(0);

            //     sum = 0;
            //     $(".target").each(function(){
            //         sum += +$(this).val();
            //     });
            // } 

            // Check less than 20% Target
            if ( sum < (target_max - target_max_20) ) { $("#btn_save").attr('disabled','disabled'); } 
            else { $("#btn_save").removeAttr('disabled'); }

            if ( sum >= target_max) {
                $('#area_target').html("<font color='green'>"+ sum.toLocaleString() + "</font> / " + target_max.toLocaleString());
            } else {
                $('#area_target').html("<font color='red'>"+ sum.toLocaleString() + "</font> / " + target_max.toLocaleString());
            }

        });

        // Check for Input Number [Hero Target]
        $(".target_hero").keyup(function(){
            var sum_hero = 0;

            $(".target_hero").each(function(){
                sum_hero += +$(this).val();
            });

            // Check Exceed 20% Target
            // if ( sum_hero >= (target_hero_max + target_hero_max_20) ) { 
            //     alert("Target Exceed 20% of Target Acquire! This Sale Target will set to zero!"); 
            //     $(this).val(0);

            //     sum_hero = 0;
            //     $(".target_hero").each(function(){
            //         sum_hero += +$(this).val();
            //     });
            // } 

            // Check less than 20% Target
            if ( sum_hero < (target_hero_max - target_hero_max_20) ) { $("#btn_save").attr('disabled','disabled'); } 
            else { $("#btn_save").removeAttr('disabled'); }


            if ( sum_hero >= target_hero_max) {
                $('#area_target_hero').html("Hero Target : <font color='green'>"+ sum_hero.toLocaleString() + "</font> / " + target_hero_max.toLocaleString());
            } else {
                $('#area_target_hero').html("Hero Target : <font color='red'>"+ sum_hero.toLocaleString() + "</font> / " + target_hero_max.toLocaleString());
            }

            //$('#area_target_hero').html("Hero Target : " + sum_hero.toLocaleString());

        });

        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();
            return false;
        });
    });
</script>