<div class="page-header">
    <?php if (isset($this->regional_market) and $this->regional_market):?>
        <h1>Edit District <small><?php echo $this->regional_market['name'] ?></small></h1>
    <?php else:?>
        <h1>Create District</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<form action="<?php echo HOST ?>manage/district-save" method="post" class="form-horizontal">
    <div class="control-group">
        <label class="control-label" for="name">District Name</label>
        <div class="controls">
            <input type="text" id="name" name="name" placeholder="Name" required 
                value="<?php if (isset($this->regional_market['name']) && $this->regional_market['name']) 
                            echo $this->regional_market['name'] ?>">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="name">Province</label>
        <div class="controls">
            <select name="province" id="province" required>
                <option value>---</option>
                <?php if (isset($this->provinces) && $this->provinces): ?>
                    <?php foreach ($this->provinces as $key => $value): ?>
                        <option value="<?php echo $key ?>" 
                            <?php if (isset($this->regional_market['parent']) && $key == $this->regional_market['parent']) 
                                    echo "selected" ?>><?php echo $value ?></option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>
        </div>
    </div>

    <div class="form-actions">
        <input type="hidden" name="id" value="<?php if(isset($this->regional_market['id']) && $this->regional_market['id']) echo$this->regional_market['id'] ?>">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-danger" onclick="window.location='<?php echo HOST ?>manage/district'">Go Back</button>
    </div>
</form>