<!--     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css ">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script> -->

<?php
$userStorage = Zend_Auth::getInstance()->getStorage()->read();
$group_id = $userStorage->group_id;
?>
<?php if ($group_id == ADMINISTRATOR_ID): ?>
<!-- <div class="pull-right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
<div class="pull-right">
    <div class="dropdown">
        <button class="dropbtn">Option</button>
        <div class="dropdown-content">
            <a class="btn-warning" onclick="bulk_delete(1)">Distrcts</a>
            <a class="btn-primary" onclick="bulk_delete(2)">Sub-District</a>
            <a class="btn-success" onclick="bulk_delete(3)">ID Oppo Store</a>
        </div>
    </div>
</div> -->
<?php endif; ?>

<table class="table table-bordered" width="100%">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
                '#',
                'Store Code',
                'name'              =>'STORE Name',
                // 'Store Type',
                'retailer_name' => 'Affiliated Distributor',
                'Warehouse Name',
                'regional_market' => 'Area',
                'Office',

                // 'RD',
                // 'asm_name'         =>'ASM',
                'sale_name'        =>'Sale',
                // 'Stock',
                // 'PCM',
                'PCDB',
                'PC',
                'Status',
                'Action',
            ),
            $this->url, $this->sort, $this->desc); ?>
        </tr>
    </thead>
    <tbody>
        <?php

        $QStoreMarket = new Application_Model_StoreMarket();
        $StoreMarket = $QStoreMarket->get_cache();


        if (isset($this->stores) and $this->stores)
            foreach ($this->stores as $k => $store): ?>
                <tr>
                    <td>
                     <?php
                         $inc = $this->offset + $k + 1;
                         echo $inc;
                        ?>
                    </td>
                    <td><?php echo $store['store_code']; ?></td>
                    <td><a href="<?php echo HOST ?>manage/store-edit?id=<?php echo $store['id'];?>" ><?php echo $store['name'] ?></td>
                    <!-- <td><?php echo $this->org[$store['org_dealer']] ?></td> -->
                    <!-- <td>[<?php if ($store['distributor_code']) { echo $store['distributor_code']; } else { echo "-"; } ?>] <?php if ($store['d_name']) { echo $store['d_name']; } else { echo "-"; } ?></td> -->
                    <td><?php if ($store['d_name']) { echo $store['d_name']; } else { echo "-"; } ?></td>
                    <td><?php if ($store['w_id']) { echo $store['w_name']; } else { echo "-"; } ?></td>
                    <!-- <td>(<?php echo $store['area_name'];?>) <?php echo $store['regional_market_name'];?></td> -->
                    <td><?php echo $store['regional_market_name'];?></td>
                    <td><?php echo $this->subArea[$store['agency']] ?></td>

                    <!--   <td>
                        <?php 
                        $QStoreStaff = new Application_Model_StoreStaff();
                        $staff_list = $QStoreStaff->getRD($store['id']);

                        $cnt = count($staff_list);

                        if ($cnt > 0 ) {
                            for ($i=0;$i<$cnt;$i++) {
                                echo "<strong style='color: red'>[".$staff_list[$i]['rd_code']."]. </strong>".$staff_list[$i]['rd_name'];
                                if ($i != $cnt-1) { echo "<strong> <br> </strong>"; }
                            }
                        } else { echo "-"; }

                        ?>
                    </td> -->
                    <!-- <td><?php if ($store['asm_code']) { echo "<strong style='color: red'>[".$store['asm_code']."]. </strong>".$store['asm_fname']; } else { echo "-"; } ?></td> -->
                    <td><?php if ($store['sale_code']) { echo "<strong style='color: red'>[".$store['sale_code']."]. </strong>".$store['sale_fname']; } else { echo "-"; } ?></td>
<!-- 
                    <td>
                       <?php 

                       $QStoreStaff = new Application_Model_StoreStaff();
                       $stock_list = $QStoreStaff->getStock($store['id']);

                       $cnt = count($stock_list);
                       $num = 1;
                       if ($cnt > 0 ) {
                        for ($i=0;$i<$cnt;$i++) {
                            echo "<strong style='color: red'>[".$stock_list[$i]['stock_code']."]. </strong>".$stock_list[$i]['stock_name'];
                            if ($i != $cnt-1) { echo "<strong> <br> </strong>"; }
                        }
                    } else { echo "-"; }
                    ?>
                </td> -->
                <!-- <td>
                    <?php 

                    $QStoreStaff = new Application_Model_StoreStaff();
                    $staff_list2 = $QStoreStaff->getPCM($store['id']);

                    $cnt = count($staff_list2);
                    $num = 1;
                    if ($cnt > 0 ) {
                        for ($i=0;$i<$cnt;$i++) {
                            echo "<strong style='color: red'>[".$staff_list2[$i]['pcm_code']."]. </strong>".$staff_list2[$i]['pcm_fname'];
                            if ($i != $cnt-1) { echo "<strong> <br> </strong>"; }
                        }
                    } else { echo "-"; }
                    ?>
                </td> -->
                <td>
                    <?php 
                    $QStoreStaff = new Application_Model_StoreStaff();
                    $staff_list = $QStoreStaff->getPCDB($store['id'],0,7);

                    $cnt = count($staff_list);

                    if ($cnt > 0 ) {
                        for ($i=0;$i<$cnt;$i++) {
                            echo "<strong style='color: red'>[".$staff_list[$i]['pcdb_code']."]. </strong>".$staff_list[$i]['pcdb_name'];
                            if ($i != $cnt-1) { echo "<strong> <br> </strong>"; }
                        }
                    } else { echo "-"; }

                    ?>
                </td>
                <td>
                    <?php 

                    $staff_list = $QStoreStaff->getPC($store['id'],0,1);

                    $cnt = count($staff_list);
                    $num = 1;
                    if ($cnt > 0 ) {
                        for ($i=0;$i<$cnt;$i++) {
                            echo "<strong style='color: red'>[".$staff_list[$i]['pc_code']."]. </strong>".$staff_list[$i]['pc_name'];
                            if ($i != $cnt-1) { echo "<strong> <br> </strong>"; }
                        }
                    } else { echo "-"; }
                    ?>
                </td>
		<td> 
                    <?php if($store['store_status'] == 1 ) { $store_status = "<span style='color: green'> Enable </span>"; } elseif ($store['store_status'] == 2) { $store_status = 'Suspend Cooperation'; } elseif ($store['store_status'] == 3) { $store_status = "<span style='color: red'> Disable </span>"; } else { $store_status = ''; } ?>
                    <?php echo $store_status; ?>
                    
                </td>
                <!-- <td style="color: green;"><?php echo $store['oppo_name']; ?></td> -->
                <td class="">

                    <a href="<?php echo HOST ?>manage/store-detail?id=<?php echo $store['id'] ?>" title="Details"><i class="icon-eye-open"></i> </a>


		<?php $userStorage = Zend_Auth::getInstance()->getStorage()->read();
                   if ($userStorage->group_id == ADMINISTRATOR_ID || $userStorage->group_id == 7): ?>

                <?php if($store['status'] == 1) : ?>
                    <a href="<?php echo HOST ?>manage/store-edit?id=<?php echo $store['id'];?>" title="Edit">&nbsp;&nbsp;<i class="icon-edit"></i></a>
                <?php endif; ?>

                <?php if(in_array($store['status'], array(1,2))) : ?>
                    <a href="#myModal" 
                        data-sid="<?php echo $store['id'] ?>" 
                        data-name="<?php echo $store['name'] ?>" 
                        data-event ="close" 
                        data-title ="Close"
                        style="color: red;" data-toggle="modal" role="button" class="modal-function" title="Close" ><br>&nbsp;<i class="icon-trash"></i></a> 
                <?php endif; ?>

                <?php if(in_array($store['status'], array(1))) : ?>
                    <a href="#myModal"
                        data-sid="<?php echo $store['id'] ?>"
                        data-name="<?php echo $store['name'] ?>"
                        data-event="puss"
                        data-title="Suspend Distributor"
                        style="color: orange;" data-toggle="modal" role="button" class="modal-function" title="Suspend Cooperation">&nbsp; <i class="icon-pause"></i></a> 
                <?php endif; ?>


                <?php if(in_array($store['status'], array(3,2))) : ?>
                     <a href="#myModal"
                        data-sid="<?php echo $store['id'] ?>"
                        data-name="<?php echo $store['name'] ?>"
                        data-event="restart"
                        data-title="Restart cooperation"
                        data-toggle="modal" role="button" class="modal-function" title="Restart cooperation" >&nbsp;<i class="icon-repeat"></i></a>
                <?php endif; ?>





            <!--  <?php if ($this->access('manage', 'store-edit')): ?>
                        <a title="Edit" href="/manage/store-edit?id=<?php echo $store['id'];?>"> <i class="icon-edit"></i></a>
                    <?php endif ?> -->

            <!--  <?php if ($this->access('manage', 'store-del') && ( !isset($store['del']) || !$store['del'] ) ): ?>
                    <a title="Delete" class="confirmLink" href="/manage/store-del?id=<?php echo $store['id'];?>"> <i class="icon-trash"></i></a>
                <?php endif ?> -->

            <!--    <?php if ($this->access('manage', 'store-undel') && isset($store['del']) && $store['del']): ?>
                <a title="Undelete" class="confirmLink" href="/manage/store-undel?id=<?php echo $store['id'];?>"> <i class="icon-repeat"></i></a>
            <?php endif ?> -->

            <!-- <span class="badge badge-default" data-store-id="<?php echo $store['id']; ?>">Log</span> -->

            <!--  <a class="badge-view" data-store-id="<?php echo $store['id']; ?>"><i class="icon-eye-open"></i></a>

            <span class="badge badge-default" data-store-id="<?php echo $store['id']; ?>">Log</span>
            <span class="badge badge-data" data-store-id="<?php echo $store['id']; ?>">Edit</span> -->
            </td>
            <!--    <td>
                    <input type="checkbox" class="data-check" value="<?php echo $store['id'];?>">
                </td> -->

	     <?php endif;?>
            </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<!-- <div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
 -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="ModalLabel"></h3>
    </div>
    <form action="<?php echo HOST.'manage/store-event';?>" method="post">
        <div class="modal-body">
            <div class="span5">
                <div class="control-group">
                    <label class="control-label span2">Store Name :  </label>
                    <div class="controls">
                        <input type="text" name="name" id="name" value="" readonly />
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label span2">Reason : </label>
                    <div class="controls">
                        <textarea cols="2" rows="2" name="remark"></textarea>
                    </div>
                </div>
                <p style="color: orange;">Close Store is irrevocable. Please enable it with</p>
            </div>

        </div>
        <div class="modal-footer">
            <input type="hidden" name="id" id="s_id">
            <input type="hidden" name="event" id="event">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-success">Save changes</button>
        </div>
    </form>

</div>

<!-- <script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/> -->

<script type="text/javascript">

    $(document).on("click", ".modal-function", function () {

        var Id = $(this).data('sid');
        var Name = $(this).data('name');
        var Event = $(this).data('event');
        var Title = $(this).data('title');

        console.log(Id);

        $(".modal-body #name").val(Name);
        $("#s_id").val(Id);
        $("#event").val(Event);
        $("#ModalLabel").text(Title);

    });


    // $(document).ready(function () {

    //     $modal = $('#modal');
    //     $('.badge.badge-default').click(function(){

    //         _self = $(this);
    //         $('body').modalmanager('loading');
            
    //         $.post('<?php echo HOST ?>manage/storestaff-log-short-report',
    //         {
    //             store_id : _self.data('store-id')
    //         },
    //         function(data){
    //                 //alert(data);
    //                 $modal.html(data);
    //                 $modal.modal();
    //                 var name = _self.parents('tr').children('td:nth-child(3)').html();
    //                 $modal.find('h3').append(' <small>&bull; '+name+'</small>');
    //             });
    //     });

    // });
    
</script>

<?php //echo $this->load();?>