<form class="form-search form-horizontal" method="get" action="/manage/store-leader">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="name" class="span2">Name</label>
                <input id="name" name="name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
            </div>
            <div class="control-group">
                <label for="address" class="span2">Address</label>
                <input id="address" name="address" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['address']) and printf($this->params['address']);?>">
            </div>
            <div class="control-group">
                <label for="staff_email" class="span2">Staff email</label>
                <input id="staff_email" name="staff_email" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['staff_email']) and printf($this->params['staff_email']);?>">
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and $this->params['area_id']==$area->id):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and $this->params['regional_market']==$regional_market->id):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <div class="control-group">
                <label for="" class="span2">Assign Staff Status</label>
                <span class="span2">
                    <label for="have_leader"><input type="checkbox" id="have_leader" name="have_leader" value="1"
                        <?php if(isset($this->params['have_leader']) && $this->params['have_leader'] == 1) echo 'checked' ?> /> Has Leader</label>
                </span>
                <span class="span2">
                    <label for="no_leader"><input type="checkbox" id="no_leader" name="no_leader" value="1"
                        <?php if(isset($this->params['no_leader']) && $this->params['no_leader'] == 1) echo 'checked' ?> /> No Leader</label>
                </span>
                <span class="span2">
                    <label for="pending"><input type="checkbox" id="pending" name="pending" value="1"
                        <?php if(isset($this->params['pending']) && $this->params['pending'] == 1) echo 'checked' ?> /> Pending</label>
                </span>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <!-- <button type="submit" name="export" value="1" class="btn btn-success">Export</button> -->
</form>
<script>
    $(document).ready(function () {
        $('#area_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                    _self.nextAll('.loading').remove();
                });
        });

        $("#have_leader, #no_leader, #pending").change(function() {
            _self = $(this);
            
            $("#have_leader, #no_leader, #pending").each(function() {
                _this = $(this);
                if (_self.attr("id") != _this.attr('id')) {
                    _this.prop('checked', false);
                }
            });
        });
    });
</script>