

<div class="modal-header" align="center">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Store Name</h3>
</div>
<div class="modal-body">
<table border=1 width="100%">
  <tr>
    <th colspan="2" align="center" style="font-size: 20px;" height="40px">Documents</th>
  </tr>
  <?php 
    foreach($this->stores as $store_log){ ?>
    <tr style="font-size: 15px;" height="20px">
      <th>Phone</th>
      <td><?php echo $store_log['phone_number'];?></td>
    </tr>
    <tr style="font-size: 15px;" height="50px">
      <th>Address</th>
      <td><?php echo $store_log['address'];?></td>
    </tr>
  <?php  }
  ?>
</table>

</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
</div>