<form action="<?php echo HOST ?>manage/sales-pg" method="get" class="form-horizontal form-search">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="name">Staff Name</label>
                <div class="controls">
                    <input type="text" id="name" name="name" placeholder="Staff Name" 
                        value="<?php if(isset($this->params['name']) && $this->params['name']) echo$this->params['name'] ?>">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="name">Staff Code</label>
                <div class="controls">
                    <input type="text" id="staff_code" name="staff_code" placeholder="Staff Code" 
                        value="<?php if(isset($this->params['staff_code']) && $this->params['staff_code']) echo$this->params['staff_code'] ?>">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="email">Email</label>
                <div class="controls">
                    <input type="text" id="email" name="email" placeholder="Email" 
                        value="<?php if(isset($this->params['email']) && $this->params['email']) echo$this->params['email'] ?>">
                </div>
            </div>
        </div>

        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="name">Area</label>
                <div class="controls">
                    <select name="area_id" id="area_id">
                        <option value>---</option>
                        <?php if (isset($this->areas) && $this->areas): ?>
                            <?php foreach ($this->areas as $key => $value): ?>
                                <option value="<?php echo $key ?>"
                                    <?php if(isset($this->params['area_id']) && $this->params['area_id'] == $key)
                                            echo "selected" ?>><?php echo $value ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="regional_market">Province</label>
                <div class="controls">
                    <select name="province" id="regional_market">
                        <option value>---</option>
                        <?php if (isset($this->regions_search) && $this->regions_search): ?>
                            <?php foreach ($this->regions_search as $key => $value): ?>
                                <option value="<?php echo $value['id'] ?>"
                                    <?php if(isset($this->params['province']) && $this->params['province'] == $value['id']) 
                                        echo "selected" ?>><?php echo $value['name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="district">District</label>
                <div class="controls">
                    <select name="district" id="district">
                        <option value>---</option>
                        <?php if (isset($this->district_search) && $this->district_search): ?>
                            <?php foreach ($this->district_search as $key => $value): ?>
                                <option value="<?php echo $value['id'] ?>"
                                    <?php if(isset($this->params['province']) && $this->params['province'] == $value['id']) 
                                        echo "selected" ?>><?php echo $value['name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="store">Store Name</label>
                <div class="controls">
                    <input type="text" id="store" name="store" placeholder="Store Name" 
                        value="<?php if(isset($this->params['store']) && $this->params['store']) echo$this->params['store'] ?>" />
                </div>
            </div>
            <div class="control-group">
                <!-- <p>Ghi chú: Khi tìm theo tên cửa hàng (Store Name), số cửa hàng ở cộ Current Store hoặc Pending Store là số cửa hàng ứng với kết quả tìm kiếm theo Store Name. Để xem số cụ thể, vui lòng bấm vào tên Leader tương ứng.</p> -->
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <div class="control-group">
                <button type="submit" class="btn btn-primary">Search</button>
                <button type="reset" class="btn btn-warning">Reset</button>
            </div>
        </div>
    </div>
</form>