<form class="form-horizontal" onsubmit="return false;">
    <div class="row-fluid">
        <div class="span4">
            <div class="control-group">
                <label class="control-label" for="a_area">Area</label>
                <div class="controls">
                    <select name="a_area" id="a_area">
                        <option value>---</option>
                        <?php if (isset($this->areas) && $this->areas): ?>
                            <?php foreach ($this->areas as $key => $value): ?>
                                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="a_province">Province</label>
                <div class="controls">
                    <select name="a_province" id="a_province">
                        <option value>---</option>
                        <?php if (isset($this->regions) && $this->regions): ?>
                            <?php foreach ($this->regions as $key => $value): ?>
                                <option value="<?php echo $key ?>"><?php echo $value['name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="a_district">District</label>
                <div class="controls">
                    <select name="a_district" id="a_district">
                        <option value>---</option>
                        <?php if (isset($this->districts) && $this->districts): ?>
                            <?php foreach ($this->districts as $key => $value): ?>
                                <option value="<?php echo $key ?>"><?php echo $value['name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="a_storename">Store Name</label>
                <div class="controls input-append">
                    <input type="text" class="form-control" id="a_storename" placeholder="Enter Store name, press ENTER" name="a_storename" />
                    <button type="button" class="btn btn-info" id="a_storename_btn"><span class="icon-search"></span></button>
                </div>
            </div>
        </div>
        <div class="span8">
            
            <div class="control-group">
                <label class="control-label" for="a_storeresult">Result</label>
                <div class="controls">
                    <div class="load-ajax">
                        <select name="a_storeresult" id="a_storeresult" multiple="multiple" size="10"></select>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <button type="button" id="btn_bind" class="btn btn-primary pull-right">Assign</button>
            </div>  
        </div>
    </div>
</form>