<style>
    .modal {
        width: 1024px;
        margin: -23% 0 0 -520px;
    }

    .modal-body {
        max-height: 700px;
    }
</style>

<div class="page-header">
    <?php if (isset($this->info) and $this->info):
        $title = 'Edit';
    else:
        $title = 'Create';
    endif; ?>
    <h1><?php echo $title; ?> Product Info Topic</h1>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">' . $message . '</div>';
    endforeach;
// print_r($this->info);
?>
<div class="row">
    <div class="row-fluid">
        <form role="form" id="form" enctype="multipart/form-data"
              action="<?php echo HOST . 'trainer/product-info-new-save'; ?>" method="post">
            <div class="span6">
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="topic">Topic</label>
                        <input type="text" class="span6" id="topic" name="topic" required="required"
                               value="<?php if (isset($this->info)): echo $this->info->topic; endif; ?>">
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="topic">Sort</label>
                        <input type="number" class="span2" id="sort" name="sort" required="required"
                               value="<?php if (isset($this->info)): echo $this->info->sort; endif; ?>">
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="row-fluid">
                    <div class="form-group">
                        <label>Display</label>
                        <div class="radio">
                            <label>
                                <input type="radio" name="enable"
                                       value="P" <?php if (isset($this->info) && ($this->info->enable == 'P')): echo "checked";
                                else: echo "checked"; endif; ?>>Preview
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="enable"
                                       value="Y" <?php if (isset($this->info) && ($this->info->enable == 'Y')): echo "checked"; endif; ?>>Enable
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="enable"
                                       value="N" <?php if (isset($this->info) && ($this->info->enable == 'N')): echo "checked"; endif; ?>>Disable
                            </label>
                        </div>
                    </div>
                </div>
            </div>


            <div class="clearfix"></div>

            <?php if (isset($this->info)) { ?>
                <hr>
                <div class="span6"><h2>Sub Topic List :</h2></div>
                <div class="span6" style="text-align: right;">
                    <a href="/trainer/product-info-new-sub-edit?topic_id=<?php echo $this->info->id; ?>">
                    <button id="add_question" class="btn btn-success" type="button"><i class="icon-plus"></i> Add
                        Sub Topic
                    </button>
                    </a>
                </div>
                <!-- Question List -->
                <div class="span12">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="text-align: center;" width="5%">No.</th>
                            <th style="text-align: center;" width="75%">Sub Topic</th>
                            <th style="text-align: center;" width="10%">Enable</th>
                            <th style="text-align: center;" width="10%">Sort</th>
                            <th style="text-align: center;" width="10%">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $db = Zend_Registry::get('db');

                        $query = $db->select()
                            ->from(array('pit' => 'product_info_title'))
                            ->where('pit.topic_id = ?', $this->info->id)
                            ->order('pit.sort', 'asc');


                        $questions = $db->fetchAll($query);

                        if ($questions) {
                            $i = 1;
                            foreach ($questions as $value) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php echo $i; ?></td>
                                    <td><?php echo $value['title']; ?></td>
                                        <td style="text-align: center;"><?php echo $value['enable']; ?></td>
                                        <td style="text-align: center;"><?php echo $value['sort']; ?></td>
                                    <td title="View" style="text-align: center;">
                                        <a title="Edit" href="/trainer/product-info-new-sub-edit?id=<?php echo $value['id']; ?>"
                                           style="padding-right: 0.4em;"><i class="icon-edit"></i></a>&nbsp;
                                        <a title="Delete"
                                           href="/trainer/product-info-new-sub-delete?id=<?php echo $value['id']; ?>"
                                           onclick="return confirm('Are you sure to remove?');"><i
                                                    class="icon-trash"></i></a>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            }
                        }

                        ?>
                        </tbody>
                    </table>
                </div>
            <?php } ?>

            <input type="hidden" name="back_url" id="back_url"
                   value="<?php isset($this->back_url) and $this->back_url and printf($this->back_url); ?>">
            <input type="hidden" name="id" id="id"
                   value="<?php isset($this->info) and $this->info and printf($this->info->id); ?>">
            <div class="clearfix">
                <div class="span12 control-group" style="padding-bottom: 1em; padding-top: 1em">
                    <!--                    <button type="button" class="btn btn-inverse go-back">Go Back</button>-->
                    <button id="add_btn" class="btn btn-primary" type="submit">Submit</button>
                </div>
                <div class="clearfix">
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $('.go-back').click(function (e) {
            window.location.href = $('#back_url').val();
            return false;
        });
    });
</script>