<table class="table table-bordered">
    <thead>
    <tr>
        <th style="vertical-align: middle;"><div align="center">No.</div></th>
        <th style="vertical-align: middle;"><div align="center">Channel</div></th>
        <th style="vertical-align: middle;"><div align="center">Total Sellin</div></th>
        <th style="vertical-align: middle;"><div align="center">Total Activated</div></th>
        <th style="vertical-align: middle;"><div align="center">Stock</div></th>
        <th style="vertical-align: middle;"><div align="center">Activated</div></th>
        <th style="vertical-align: middle;"><div align="center">Selling Rate</div></th>
        <th style="vertical-align: middle;"><div align="center">Safety Stock</div></th>
    </tr>
    </thead>
    <tbody>
        <?php 
            if ($this->lists) {
                $data = $this->lists;

                for ($i=0;$i<count($data);$i++) {

                    $color = '';
                    if ( $data[$i]['indicator'] < 0 ) { $color = "red"; } 

                    $cnt = $this->offset + $i + 1;

                    echo "<tr>";
                    echo    "<td><div align='center'>".$cnt."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['channel']."</div></td>";
                    echo    "<td><div align='center'>".number_format($data[$i]['total_sellin'])."</div></td>";
                    echo    "<td><div align='center'>".number_format($data[$i]['total_activated'])."</div></td>";
                    echo    "<td><div align='center'>".number_format($data[$i]['stock'])."</div></td>";

                    echo    "<td><div align='center'>".number_format($data[$i]['sellout'])."</div></td>";
                    echo    "<td><div align='center'>".number_format($data[$i]['selling_rate'])."</div></td>";
                    echo    "<td><div align='center'><font color='".$color."'>".number_format($data[$i]['safety_stock'])."</font></div></td>";
                    echo "</tr>";

                }

            }
        ?>
    </tbody>
</table>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
