    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="text-align: center;" width="5%">No.</th>
            <th style="text-align: center;" width="35%">Name</th>
            <th style="text-align: center;" width="20%">Question type</th>
            <th style="text-align: center;" width="20%">From Date</th>
            <th style="text-align: center;" width="20%">To Date</th>
            <th style="text-align: center;" width="10%">Number of questions</th>
            <th style="text-align: center;" width="10%">Status</th>
            <th style="text-align: center;" width="10%">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php
        $question_type = array('แบบทดสอบความรู้', 'แบบทดสอบความรู้ PC Active', 'แบบทดสอบความรู้ ก่อน Cheick in');

        $count = 0;
        if (isset($this->list) and $this->list)
            foreach ($this->list as $k => $item):
                ?>
                <tr>
                    <td style="text-align: center;"><?php echo $this->offset + $k + 1; ?></td>
                    <td><?php echo isset($item['name']) ? $item['name'] : ''; ?></td>
                    <td><?php echo isset($item['question_type']) ? $question_type[$item['question_type']] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['from_date']) ? $item['from_date'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['to_date']) ? $item['to_date'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['count_questions']) ? $item['count_questions'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['id']) ? EnableDisplay($item['enable']) : ''; ?></td>
                    <td title="View" style="text-align: center;">
                        <a title="Edit" href="/trainer/e-test-info-create?id=<?php echo $item['id']; ?>"
                           style="padding-right: 0.4em;"><i class="icon-edit"></i></a>&nbsp;
                        <a title="Delete" href="/trainer/e-test-info-delete?id=<?php echo $item['id']; ?>" onclick="return confirm('Are you sure to remove?');"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>