<form class="form-search form-horizontal" method="get" action="/timing/staff-resign/staff-resign">
    <div class="row">
        <div class="span5">

            <div class="control-group">
                <label for="grand_area_id" class="span2">Grand Area</label>
                <select id="grand_area_id" name="grand_area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->grand_areas) :
                        foreach ($this->grand_areas as $grand_area):
                            ?>
                            <option value="<?php echo $grand_area['id'];?>" <?php if (isset($this->params['grand_area_id']) and ( (is_array($this->params['grand_area_id']) && in_array($grand_area['id'], $this->params['grand_area_id']) || $id==$this->params['grand_area_id'])) ):?>selected<?php endif;?>><?php echo $grand_area['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area['id'];?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="group_id" class="span2">Staff Group</label>
                <select id="group_id" name="group_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->groups) :
                        foreach ($this->groups as $group):
                            ?>
                            <option value="<?php echo $group['id'];?>" <?php if (isset($this->params['group_id']) and ( (is_array($this->params['group_id']) && in_array($group['id'], $this->params['group_id']) || $group['id']==$this->params['group_id'])) ):?>selected<?php endif;?>><?php echo $group['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

        </div>
        <div class="span5">

            <div class="control-group">
                <label for="date" class="span2">From</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>

        </div>
    </div>
<button type="submit" class="btn btn-primary">Submit</button>
<button type="submit" name="export" value="1" class="btn btn-success">Export</button>
<!-- <button type="submit" name="export" value="2" class="btn btn-success">By Position</button> -->
</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>


<script type="text/javascript">

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    // Multi-Select
    function multi() {
        $('.multiselect').multiselect(options);
    }

    $('.date').datepicker({ dateFormat: "dd/mm/yy" });


    $(document).ready(function () {

        $('#search_bar').trigger('click');

        multi();

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $('#grand_area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var grand_area_id = $(this).val();
            
            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-area",
                {grand_area_id: grand_area_id}
                ,function(data,status){  
                    var obj = $.parseJSON( data );
                    $('#area_id').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#area_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    //$('button, .btn, input').prop('disabled', false);
                    $('#area_id').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

    });

</script>