<style>
    select {
        max-width: 100%;
    }

    #tab_show label:not(.checkbox) {
        font-weight: bold;
    }

</style>

<div class="page-header">
    <?php if (isset($this->inform) and $this->inform):?>
        <h1>Edit Inform</h1>
    <?php else:?>
        <h1>Create Inform</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>
<div class="row-fluid">
    <div class="span12">
        <iframe src="" name="frame" frameborder="0" style="display:none;height=0;"></iframe>
        <form role="form" id="form" target="frame" action="<?php echo HOST.'manage/inform-save';?>" method="post">

            <div class="row-fluid">
                <div class="span12">
                    <p class="pull-right">
                        <input type="hidden" name="id" id="id" value="<?php isset($this->inform) and $this->inform and printf($this->inform->id);?>">
                        <button type="submit" id="submit_btn" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-danger" onclick="window.location='<?php echo HOST ?>manage/inform'">Go back</button>
                    </p>
                </div>
            </div>

            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_content" data-toggle="tab">Content</a></li>
                <li><a href="#tab_show" data-toggle="tab">Display to</a></li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="tab_content">
                    <?php echo $this->render('manage/inform/partials/tab-content.phtml') ?>
                </div>

                <div class="tab-pane" id="tab_show">
                    <?php echo $this->render('manage/inform/partials/tab-show.phtml') ?>
                </div>

            </div>
        </form>
    </div>
</div>

<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>js/file-uploader/fileuploader.css"/>
<script src="<?php echo HOST ?>js/file-uploader/fileuploader.js" type="text/javascript"></script>
<script src="<?php echo HOST ?>js/ckeditor.js"></script>
<script src="<?php echo HOST ?>js/jsrender.min.js"></script>
<script>
config = {};
config.toolbar = [
	{ name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
	{ name: 'about', items: [ 'Source' ] },
	'/',

	{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
	{ name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
	{ name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
	'/',
	{ name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
	{ name: 'colors', items: [ 'TextColor', 'BGColor' ] },
	{ name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
	{ name: 'others', items: [ '-' ] }
];

    CKEDITOR.replace( 'content' , config);
</script>

<script id="file_item_div" type="text/x-jsrender">
    <div class="span2 file_item">
        <div class="thumbnail">
            <span><i class="icon-file"></i></span>
        </div>
        <p class="attachment_name">{{:file_display_name}}</p>

        <input type="hidden" name="nfile_id[]" value="" />
        <input type="hidden" name="key[]" value="{{:keypass}}" />
        <input type="hidden" name="file_id[]" value="{{:file_id}}" />
        <input type="hidden" name="hash[]" value="{{:hashstr}}" />
    </div>
</script>

<script id="alert_div" type="text/x-jsrender">
    <div class="alert alert-{{:type}}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{:message}}
    </div>
</script>


<script type="text/javascript">
    $(document).ready(function () {
        $new_category_modal = $("#modal_new_category");

        $("#add_category_btn").click(show_new_category_modal);
        $("#save_category_btn").click(save_category);
        init_uploader();
       

        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });

        $( "#s_name" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();
                $('.loading').remove();
                var _self = $(this);
                var targetUrl = '<?php echo HOST."staff?sname=1&name=" ?>' + $('#s_name').val();

                //get ajax content
                var aj = _self.parent().parent().next().find('.load-ajax');
                if (aj.length){
                    _self.after("<span class=\'loading\'></span>");
                    $.get(targetUrl
                        ,function(data,status){
                            aj.html(data);
                            _self.next('.loading').remove();
                        });
                }

                return false;
            }
        });

        $('#add_pg_btn').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists( $(item[i]).attr('value'), false) ) {
                    _des = $('#pg_name');
                    _des.append(item[i]);
                }
            }
        });

        $('#remove_pg_btn').click(function(){
            _self = $('#pg_name');
            item = _self.children('option:selected').remove();

            _name = $('#pg_name option');
            id_str = '';

            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }

            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);
        });

        $('#form').submit(function(event){
            event.preventDefault();
            _name = $('#pg_name option');
            id_str = '';

            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }

            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);

            $(this).unbind( event );

            //submit
            $(this).submit();

        });


    });

	function is_exists(id, is_leader) {
        if(is_leader) {
            _des = $('#leader_name');
        } else {
            _des = $('#pg_name');
        }

        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function palert(msg){
        $('.alert-error').remove();
        $('.page-header').after('<div class="alert alert-error">'+msg+'</div>');
        $('form button[type=submit]').prop('disabled', false);
        return;
    }

    function show_new_category_modal(e) {
        $new_category_modal.modal({backdrop: 'static'})
    }
    
    function init_uploader() {
        $('.file-uploader').each(function (){
            var _self = $(this);
            var uploader = new qq.FileUploader({
                element: _self[0],
                action: '<?php echo HOST ?>manage/inform-upload',
                multiple: false,
                allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar'],
                sizeLimit: 5 * 1024 * 1024,
                onProgress: function(id, fileName, loaded, total){
                    $('.fix-msg').addClass('show');

                    $("form").submit(function (e) {
                        e.preventDefault();
                    });

                    $(window).on('beforeunload', function() {
                        return 'Please wait your upload proccess complete!';
                    });
                },
                onComplete: function(id, fileName, responseJSON){
                    if ( responseJSON.success==true ){
                        var template = $.templates("#file_item_div");

                        try {
                            var htmlOutput = template.render(responseJSON);
                            $(".file_list").append(htmlOutput);
                        } catch(err) {}
                    }

                    $("form").unbind('submit');

                    window.onbeforeunload = null;

                    $('.fix-msg').removeClass('show');
                },
                onCancel: function(id, fileName){},
                onError: function(id, fileName, xhr){}
            });
        });
    }

    function save_category(e) {
        console.log(e.target);
        name = $("#category_name").val().trim();
        current_category = $('#category').val();
        $(".loading").remove();
        var template = $.templates("#alert_div");

        if (!name) {
            $(".alert").remove();
            
            try {
                var htmlOutput = template.render({
                                        type: "danger", 
                                        message: "Name cannot be blank"
                                    });
                $new_category_modal.find(".modal-body").append(htmlOutput);
            } catch(err) {}

            return false;
        }

        $("#category_name").after('<span class="loading"></span>');

        try {
            $.ajax({
                url: '<?php echo HOST ?>manage/inform-category-save',
                type: 'post',
                dataType: 'json',
                data: {
                    name: name,
                },
            })
            .done(function(data) {
                console.log("success");

                if (typeof data.error === "undefined" && data.type && data.message) {
                    var htmlOutput = template.render({
                                            type: data.type, 
                                            message: data.message
                                        });
                    $new_category_modal.find(".modal-body").append(htmlOutput);

                    if (typeof data.new_data !== "undefined" && data.new_data) {
                        $("#category option").not(':first').remove();
                        $("#category_parent option").not(':first').remove();

                        for (cat_id in data.new_data) {
                            option_modal = '<option value="'+cat_id+'">'
                                            + data.new_data[cat_id]
                                            + '</option>';
                            option_ = '<option value="'+cat_id+'" '
                                            + (cat_id == current_category ? 'selected' : '')
                                            + '>'
                                            + data.new_data[cat_id]
                                            + '</option>';

                            $("#category_parent").append(option_modal);
                            $("#category").append(option_);
                        }
                    }

                    if (data.type == "success") {
                        setTimeout(function() {
                            $("#category_name").val('');
                            $("#category_parent").val('');
                            $(".alert").remove();
                            $new_category_modal.modal('hide');
                        }, 2000);
                    }

                } else {
                    
                    var htmlOutput = template.render({
                                            type: "danger", 
                                            message: "Error"
                                        });
                    $new_category_modal.find(".modal-body").append(htmlOutput);
                }
            }) // END done
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                console.log("complete");
                $(".loading").remove();
            });
        } catch (err) {}
        
    }
</script>
