<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<div id="modal_email" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Add Emaill Address</h3>
	</div>
	<div class="modal-body">
		<p>For staff : <strong><span id="staff_name_email"></span></strong></p>
		<div class="input-append">
			<input type="text" name="dashboard_email" id="dashboard_email" value="" />
			<span class="add-on"><?php echo EMAIL_SUFFIX ?></span>
		</div>
	</div>
	<div class="modal-footer">
		<input type="hidden" name="staff_id_email" id="staff_id_email" />
		<button class="btn btn-info" id="btn_save_email" aria-hidden="true">OK</button><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>

<div id="modal_dashboard" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Confirm</h3>
	</div>
	<div class="modal-body">
		<p>Dismiss Staff <strong><span id="staff_name"></span></strong> from Dashboard <strong><span id="dashboard_name"></span></strong>?</p>
	</div>
	<div class="modal-footer">
		<button class="btn btn-info" id="btn_save_dismiss" aria-hidden="true">OK</button><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>