<style type="text/css">
.main-timeline{
    overflow: hidden;
    position: relative;
    padding: 60px 30px;
}
.main-timeline:before{
    content: "";
    width: 1px;
    height: 100%;
    background: #cfcdcd;
    position: absolute;
    top: 0;
    left: 50%;
}
.main-timeline .timeline{
    width: 50%;
    clear: both;
    position: relative;
}
.main-timeline .timeline:before,
.main-timeline .timeline:after{
    content: "";
    display: block;
    clear: both;
}
.main-timeline .timeline:first-child:before,
.main-timeline .timeline:last-child:before{
    content: "";
    width: 11px;
    height: 11px;
    background: #cfcdcd;
    box-sizing: content-box;
    border: 5px solid #f9f6f1;
    box-shadow: 0 0 0 2px #cfcdcd;
    position: absolute;
    top: -54px;
    right: -11px;
    transform: rotate(45deg);
}
.main-timeline .timeline:last-child:before{
    top: auto;
    bottom: -54px;
}
.main-timeline .timeline:last-child:nth-child(even):before{
    right: auto;
    left: -11px;
}
.main-timeline .timeline-icon{
    width: 24px;
    height: 24px;
    background: #f9f6f1;
    border: 1px solid #cfcdcd;
    position: absolute;
    top: 17px;
    right: -13px;
    z-index: 1;
    transform: rotate(45deg);
}
.main-timeline .timeline-icon:before{
    content: "";
    display: block;
    width: 15px;
    height: 15px;
    background: #f9f6f1;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    transition: background-color 0.2s ease 0s;
}
.main-timeline .timeline:hover .timeline-icon:before{ background: #00ba8b; }
.main-timeline .timeline-content{
    width: 74%;
    padding: 18px 30px;
    background: #f9f6f1;
    text-align: right;
    float: left;
    border: 1px solid transparent;
    position: relative;
    transition: all 0.3s ease 0s;
}
.main-timeline .timeline:hover .timeline-content{
    border: 1px solid #cfcdcd;
}
.main-timeline .timeline-content:before{
    content: "";
    display: block;
    width: 14px;
    height: 14px;
    background: #f9f6f1;
    border: 1px solid #cfcdcd;
    position: absolute;
    top: 21px;
    right: -7.3px;
    transform: rotate(45deg);
    transition: all 0.2s ease 0s;
}
.main-timeline .timeline:hover .timeline-content:before{
    background: #00ba8b;
    border-color: #00ba8b;
}
.main-timeline .timeline-content:after{
    content: "";
    width: 11%;
    height: 1px;
    background: #cfcdcd;
    position: absolute;
    top: 28px;
    right: -14%;
}
.main-timeline .date{
    display: block;
    font-size: 15px;
    font-weight: 600;
    color: #00ba8b;
    margin: 0 0 8px;
    transition: all 0.3s ease 0s;
}
.main-timeline .timeline:hover .date{ color: #444; }
.main-timeline .title{
    font-size: 18px;
    color: #444;
    margin-top: 0;
    transition: all 0.3s ease 0s;
}
.main-timeline .timeline:hover .title{ color: #00ba8b; }
.main-timeline .description{
    font-size: 16px;
    color: #777;
    line-height: 28px;
    margin-top: 8px;
}
.main-timeline .timeline:nth-child(2n),
.main-timeline .timeline:nth-child(2n) .timeline-content{
    float: right;
    text-align: left;
}
.main-timeline .timeline:nth-child(2n) .timeline-icon{
    right: 0;
    left: -12px;
}
.main-timeline .timeline:nth-child(2n) .timeline-content:before{ left: -7.3px; }
.main-timeline .timeline:nth-child(2n) .timeline-content:after{ left: -14%; }
@media only screen and (max-width: 767px){
    .main-timeline{ padding-left: 20px; }
    .main-timeline:before{ left: 20px; }
    .main-timeline .timeline{ width: 100%; }
    .main-timeline .timeline,
    .main-timeline .timeline-content{
        float: right;
        text-align: left;
    }
    .main-timeline .timeline:first-child:before,
    .main-timeline .timeline:last-child:nth-child(odd):before{
        right: auto;
        left: -11px;
    }
    .main-timeline .timeline-icon{
        right: 0;
        left: -12px;
    }
    .main-timeline .timeline-content:before{ left: -7.3px; }
    .main-timeline .timeline-content:after{ left: -14%; }
}
</style>

<div class="page-header">
   <?php 
        echo "<h1>PC : ".$this->pc_info[0]['staff_code']." - ".$this->pc_info[0]['staff_name']."</h1>";
   ?>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>
<!--
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    //echo $this->render('trainer/pc-level-detail/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
-->
<div class="table-responsive">
    <?php
    echo $this->render('trainer/pc-level-detail/partials/list.phtml');
    ?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>
<?php echo $this->confirm();?>