<?php 
    //print_r($this->params);

    if (isset($this->store_acc_list) and $this->store_acc_list) {

        $data = $this->store_acc_list;
        // echo "<pre>"; print_r($data);

        echo "<h3 class='pull-left'>".$data[0]['area_name']." [".$data[0]['st_id']."] ".$data[0]['st_name']."</h3>";
        echo "<h3 class='pull-right'>".$data[0]['st_type']."</h3>";
        echo "<br/><br/>";

        echo "<table class='table table-bordered'>";
        echo    "<thead>";
        echo        "<tr>";
        echo            "<th style='vertical-align:middle;'><div align='center'>No.</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Model Code</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Model Name</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Color</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>IN / OUT</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Unit</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Record By</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Record Date</div></th>";
        echo        "</tr>";
        echo    "</thead>";
        echo    "<tbody>";

        for ($i=0;$i<count($data);$i++) {

            // <i class='icon-caret-up'></i>
            // <i class='icon-caret-down'></i>
            if ( $data[$i]['record_type'] == 1 ) {
                $show_type = "<font color='green'><i class='icon-caret-up' style='font-size:18px;'></i>  IN</font>";
            } else {
                $show_type = "<font color='red'><i class='icon-caret-down' style='font-size:18px;'></i>  OUT</font>";
            }

            // Data for List
            $cnt = $i + 1;

            echo    "<tr>";
            echo        "<td width='5%'><div align='center'>".$cnt."</div></td>";
            echo        "<td width='8%'><div align='center'>".$data[$i]['good_code']."</div></td>";
            echo        "<td><div align='left'>".$data[$i]['good_name']."</div></td>";
            echo        "<td width='8%'><div align='center'>".$data[$i]['color_name']."</div></td>";
            echo        "<td width='8%'><div align='center'>".$show_type."</div></td>";
            echo        "<td width='8%'><div align='center'>".$data[$i]['unit']."</div></td>";
            echo        "<td width='20%'><div align='center'>[".$data[$i]['staff_code']."] ".$data[$i]['staff_name']."</div></td>";
            echo        "<td width='15%'><div align='center'>".$data[$i]['record_date']."</div></td>";
            echo    "</tr>";  

        } 

        echo    "</tbody>";
        echo    "</table>";

    }

?>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">

    $(document).ready(function () {


    });

</script>