<form class="form-search form-horizontal" method="get" action="/timing/acc-report-log/acc-report-log">
    <div class="row">
        <div class="span5">

            <div class="control-group">
                <label for="good_id" class="span2">Model</label>
                <select id="good_id" name="good_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    $data = $this->goods;
                    if ($this->goods) :
                        foreach ($this->goods as $good_list):
                            ?>
                            <option value="<?php echo $good_list['id'];?>" <?php if (isset($this->params['good_id']) and ( (is_array($this->params['good_id']) && in_array($good_list['id'], $this->params['good_id']) || $good_list['id']==$this->params['good_id'])) ):?>selected<?php endif;?>><?php echo $good_list['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="color_id" class="span2">Color</label>
                <select id="color_id" name="color_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    $data = $this->colors;
                    if ($this->colors) :
                        foreach ($this->colors as $color_list):
                            ?>
                            <option value="<?php echo $color_list['id'];?>" <?php if (isset($this->params['color_id']) and ( (is_array($this->params['color_id']) && in_array($color_list['id'], $this->params['color_id']) || $color_list['id']==$this->params['color_id'])) ):?>selected<?php endif;?>><?php echo $color_list['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

        </div>
        <div class="span5">

            <div class="control-group">
                <label for="date" class="span2">From</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>

        </div>
    </div>

    <input type="hidden" id="store_id" name="store_id" value="<?php echo $this->params['store_id']; ?>" />

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-primary">Export Excel</button>
    <!-- <button type="submit" name="export" value="2" class="btn btn-primary">Product Report</button> -->
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        multi();
        
        $('#good_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var good_id = $(this).val();
            
            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/hr-report/load-good-color",
                {good_id: good_id}
                ,function(data,status){  
                    var obj = $.parseJSON( data );
                    $('#color_id').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#color_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    //$('button, .btn, input').prop('disabled', false);
                    $('#color_id').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

    });
</script>