<div class="page-header">
    <h1>Add time check in for ASM</h1>
</div>
<style>
    .numbering {
    counter-reset: rowNumber;
    }

    .numbering tbody tr {
        counter-increment: rowNumber;
    }

    .numbering tbody tr td:first-child::before {
        content: counter(rowNumber);
        min-width: 1em;
        margin-right: 0.5em;
    }

    .input-append .date {
        width: 50%;
    }

    .edit_date {
        min-width: 180px;
    }

    .edit_date input {
        min-width: 70px;
    }

    .edit_lbl {
        cursor: pointer;
    }

    .modified {
        background: #fed !important;
    }

    .table td:nth-child(2) {
        width: 35%;
    }

    .table td:nth-child(3) {
        width: 10%;
    }

    .table td:nth-child(4) {
        width: 10%;
    }

    .table td:nth-child(5) {
        width: 10%;
    }

    #a_staffresult {
        width: 100%;
    }

    .input-append {
        display: inline-block;
        float: left;
        margin-left: 20px !important;
        width: 50% !important;
    }

    .input-append .form-control {
        width: 70%;
    }
</style>

<div class="container">
   <iframe name="ifrmSave" id="ifrmSave" width="100%" style="display:none;"></iframe>
   <form id="form" class="form-horizontal" action="<?Php echo HOST ?>time/add-save" target="ifrmSave" method="POST">
    <div class="row-fluid">
        <div class="span4">
            <div class="control-group">
                <label class="control-label" for="a_area">Area</label>
                <div class="controls">
                    <select name="a_area" id="a_area">
                        <option value>---</option>
                        <?php if (isset($this->areas) && $this->areas):
                        ?>
                            <?php foreach ($this->areas as $key => $value): ?>
                                <option value="<?php echo $value['area_id'] ?>"><?php echo $value['area_name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                        
                        <?php if (isset($this->areas_all) && $this->areas_all):
                        ?>
                            <?php foreach ($this->areas_all as $key => $value): ?>
                                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                        
                    </select>
                </div>
            </div>
          
             <div class="control-group">
                <label class="control-label" for="team">Team</label>
                <div class="controls">
                    <select name="team" id="team">
                        <option value>---</option>
                        <?php if (isset($this->team) && $this->team): ?>
                            <?php foreach ($this->team as $key => $value): ?>
                                     <option value="<?php echo $value['team_id'] ?>"><?php echo $value['team_name'] ?></option>
                            <?php endforeach ?>
                        <?php endif ?>
                        
                          <?php if (isset($this->team_all) && $this->team_all):
                        ?>
                            <?php foreach ($this->team_all as $key => $value): ?>
                            
                                <?php if(in_array($key, array(75,119))): ?>
                                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                                   <?php endif ?>
                            <?php endforeach ?>
                        <?php endif ?>
                    </select>
                </div>
            </div>
            
             <div class="control-group">
                <label class="control-label" for="from_date">Date</label>
                <div class="controls">
                    <input type="text" class="form-control search-query <?php if(HAPPY_TIME_CHECKIN == 1) echo 'date'; ?> span2" id="from_date" name="from_date" value="<?php isset($this->date) and printf($this->date);?>" <?php if(HAPPY_TIME_CHECKIN != 1) echo 'readonly'; ?>>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="a_staff">Staff Name</label>
                <div class="controls input-append">
                    <input type="text" class="form-control" id="a_staffname" placeholder="Enter Staff name, press ENTER" name="a_storename" />
                    <button type="button" class="btn btn-info" id="a_storename_btn"><span class="icon-search"></span></button>
                </div>
            </div>
            
             <div class="control-group">
                <label class="control-label" for="a_staffresult">Shift </label>
                <div class="controls">
                   <input type="checkbox" class="form-control" name="shilf" />
                </div>
            </div>
          
            
        </div>
        <div class="span8">
            
            <div class="control-group">
                <label class="control-label" for="a_staffresult">Result</label>
                <div class="controls">
                    <div class="load-ajax">
                        <select name="a_staffresult[]" id="a_staffresult" multiple="multiple" size="10"></select>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <input type="hidden" value="1" name="asm" />
                <button type="button" id="btn_save" class="btn btn-primary pull-right">Check in</button>
            </div>  
        </div>
    </div>
</form>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-datetimepicker.min.css"/>
<link rel="stylesheet" type="text/css" href="/css/jquery.ui.timepicker.css"/>
<script type="text/javascript">
  $(document).ready(function() {
              $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });            
              $('.go-back').click(function(e){

                window.location.href = $('#back_url').val();    
                return false;
              });
       });
       
        function palert(msg){
        $('.alert-error').remove();
        $('.page-header').after('<div class="alert alert-error">'+msg+'</div>');
        $('button').prop('disabled', false);
        return;
    }

    $(document).ready(function() {
        search_filter();
        remove_store();
    

        $('#myTab a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
        })

        $( "#a_storename" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();
                
                search_staff(this);
                return false;
            }
        });

        $('#a_storename_btn').click(function() {
            search_staff(this);
        });

        $('#btn_save').click(function(){
         //   $('button').prop('disabled', true);
            $('#form').submit();
        });

    });

    function search_staff(elm) {
        $('button, input, select').prop('disabled', true);
                
        area_id    = $('#a_area').val();
        team_id  = $('#team').val();
        staff_name = $('#a_staffname').val();
        
        if(!area_id && team_id != <?php echo ACCESSORIES_TEAM; ?>)
        {
            alert('Please Choose Area');
            $('button, input, select').prop('disabled', false);
            return false;
        }
        

        $('.loading').remove();
        var _self = $(elm);
        var targetUrl = '<?php echo HOST."ajax/get-staff-for-time" ?>';

        //get ajax content
        var aj = $('.load-ajax');
        if (aj.length && (area_id || team_id || staff_name)){
            _self.parents('.control-group').append("<span class=\'loading\'></span>");

            $.post(targetUrl, {
                area_id : area_id,
                team_id : team_id,
                staff_name : staff_name,
                asm     : 1,
                
            }, function(data){
                $('button, input, select').prop('disabled', false);
                aj.html(data);                            
                $('.loading').remove();
            });
        }
    }

    function is_exists(id) {
        _des = $('.store_list');
        items = _des.children('.store');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).data('id') == id) {
                return true;
            }
        }
        return false;
    }

    function search_filter() {
        $('#btn_f_search').click(function() {
            area      = $('#f_area').val();
            region    = $('#f_province').val();
            storename = $('#f_storename').val();
            $('.store').show();

            $('.store').each(function() {
                _self = $(this);
                if (area && _self.data('area') != area) 
                    _self.hide();

                if (region && _self.data('region') != region) 
                    _self.hide();

                var reg = new RegExp(storename, 'gi');
                if (storename && !_self.data('name').match(reg)) 
                    _self.hide();
            });
        });

        $('#btn_f_reset').click(function() {
            $('#f_area').val('');
            $('#f_province').val('');
            $('#f_storename').val('');
            $('.store').show();
        });
    }

    function remove_store() {
        $('.btn_remove').click(function(){
            _self = $(this);
            _self.parents('tr').remove();
        });
    }

    

   

 
       
</script>
