<table class="table table-bordered">
    <thead>
        <tr>
            <?php echo $this->sorting(array(
				'#', 
				'name'              => 'Name',
                'code'              => 'Code',
				's.regional_market' => 'Province',
				's.phone_number'    => 'Phone Number',
				's.email'           => 'Email',
                'Last Year',
				'Date',
                'p.team'            => 'Team',
				'Note',
				'Action'
                ),
            $this->url, $this->current_col, $this->desc); 
            
            ?>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->off) and $this->off)
            foreach ($this->off as $k=>$timing): ?>
        <tr>
            <td><?php  $inc = $this->offset + $k + 1; echo $inc; ?></td>
            <td> <?php echo $timing['firstname'].' '.$timing['lastname'];?></td>
            <td> <?php echo $timing['code'];?></td>
            <td><?php if(isset($this->regional_market_all) && isset($this->regional_market_all[$timing['regional_market']])) echo $this->regional_market_all[$timing['regional_market']];?></td>
            <td><?php echo $timing['phone_number'];?></td>
            <td><?php @list($email, $domain) = @explode('@',$timing['email']); echo $email;?></td>
            <td><?php echo $timing['date_last_year'];?></td>
            <td><?php echo $timing['date'];?></td>            
            <td><?php if(isset($this->team) and $this->team ) echo $this->team[$timing['team']]; ?></td>
            <td class="relative">
            	<?php if (isset($timing['note']) && $timing['note']): ?>
            		<span 
            			class="label <?php if(isset($timing['note_updated']) && $timing['note_updated'] ) echo 'label-warning'; else echo 'label-info'; ?> note_label" 
            			title="Click to view" 
            			data-note="<?php if(isset($timing['note']) && $timing['note']) echo $timing['note'] ?>" 
            			data-timing-id="<?php if(isset($timing['id']) && $timing['id']) echo $timing['id'] ?>"><?php if(isset($timing['note_updated']) && $timing['note_updated'] ) echo 'New ' ?>Note</span>
					<?php if (isset($timing['note_read']) && $timing['note_read']): ?>
						<i class="icon-eye-open"></i>
					<?php endif ?>
        		<?php else: ?>
            		<span class="label note_label" title="Click to view" data-note="" data-timing-id="<?php if(isset($timing['id']) && $timing['id']) echo $timing['id'] ?>">Add Note</span>
            	<?php endif; ?>
            </td>
            <td>
            <a href="<?php echo HOST ?>time/off-history?id=<?php echo $timing['id'];?>"> <i class="icon-edit"></i></a>
                 <a href="#"> <i data-staff-id="<?php if(isset($timing['staff_id']) && $timing['staff_id']) echo $timing['staff_id'] ?>" class="add-off icon-plus"></i></a>
                 <a  href="#"> <i data-staff-id="<?php if(isset($timing['staff_id']) && $timing['staff_id']) echo $timing['staff_id'] ?>" class="decrease-off icon-minus"></i></a>
            </td>
        </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
	  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	  <h3 id="myModalLabel">Off Time Note</h3>
	</div>
	<div class="modal-body">
		<div class="control-group">
			<div class="controls">
				<textarea disabled="disabled" name="note_content" id="note_content" class="form-control note_content" rows="10"></textarea>
			</div>
		</div>
		<div class="control-group">
			<label for="note">Add a note</label>
			<div class="controls">
				<textarea name="note" id="note" class="form-control note_content" rows="4"></textarea>
				<input type="hidden" name="note_id" class="staff_id" value="" />
			</div>
		</div>
		
	</div>
	<div class="modal-footer">
	  <button class="btn btn-success" id="btn_save" aria-hidden="true">Save</button><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>


<div id="modal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
	  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	  <h3 id="myModalLabel">Plus Sabbatical</h3>
	</div>
	<div class="modal-body">
		
		<div class="control-group">
			<label for="note">Please insert number and reason for this staff</label>
            
             <div class="control-group">
                    <label for="month">Month</label>
                    <input type="text" class="form-control monthPicker" id="month_add" name="month" required="required" value="<?php echo date('m/Y');?>" />
             </div>
            
			<div class="controls">
				<input type="text" name="off" class="off control-group" placeholder="Insert Number Off You Want Add" />
				<input type="hidden" name="staff_id" class="staff_id" value="" />
			</div>
            <div class="controls">
				<input type="text" name="reason" class="reason control-group" placeholder="Reason" required="required" />
			</div>
            
		</div>		
	</div>
	<div class="modal-footer">
	  <button class="btn btn-success" id="btn_save_add" aria-hidden="true">Save</button><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>

<div id="modal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
	  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	  <h3 id="myModalLabel">Except Sabbatical</h3>
	</div>
	<div class="modal-body">
		
		<div class="control-group">
			<label for="note">Please insert number and reason for this staff</label>
            
             <div class="control-group">
                    <label for="month">Month</label>
                    <input type="text" class="form-control monthPicker" id="month_minus" name="month" required="required" value="<?php echo date('m/Y');?>" />
                </div>
            
			<div class="controls">
				<input type="text" name="off" class="off control-group" placeholder="Insert Number Off You Want Add" />
				<input type="hidden" name="staff_id" class="staff_id" value="" />
			</div>
            <div class="controls">
				<input type="text" name="reason" class="reason control-group" placeholder="Reason" required="required" />
			</div>
            
		</div>		
	</div>
	<div class="modal-footer">
	  <button class="btn btn-success" id="btn_save_minus" aria-hidden="true">Save</button><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">
    $modal = $('#modal');
	$timing_modal = $('#timing_modal');
    
	
    $('.add-off').click(function(){
        var _self = $(this);
	    $('#modal1').modal();
        $('.staff_id').val(_self.data('staff-id'));
    });
    
   $('#btn_save_add').click(function(){
            $modal = $('#modal1');
			$modal.modal('loading');
            var off_number = $(this).parent().parent().find('.off').val();
            var reason = $(this).parent().parent().find('.reason').val();
			$.post('<?php echo HOST ?>time/add-off',
	            {
					id   : $('.staff_id').val(),
					off_number : off_number,
                    reason : reason,
                    type : 1,
                    month : $('month_add').val(),
	            },
	            function(data){
	            	if (data == 1) {
	            	  
                      
                      
						$modal
							.modal('loading')
							.find('.modal-body')
					        .prepend('<div class="alert alert-info fade in">' +
					          'Updated!<button type="button" class="close" data-dismiss="alert">&times;</button>' +
					        '</div>');
                            location.reload().delay( 2000 );
	            	} else {
            			$modal
                            .modal('loading')
							.find('.modal-body')
					        .prepend('<div class="alert alert-error fade in">' +
					          'Update failed! Try again.<button type="button" class="close" data-dismiss="alert">&times;</button>' +
					        '</div>');
                            location.reload().delay( 2000 );
	            	}
        		}
        	);
	});
    
    $('#btn_save_minus').click(function(){
            $modal = $('#modal2');
			$modal.modal('loading');
            var off_number = $(this).parent().parent().find('.off').val();
            var reason = $(this).parent().parent().find('.reason').val();
			$.post('<?php echo HOST ?>time/add-off',
	            {
					id   : $('.staff_id').val(),
					off_number : off_number,
                    reason : reason,
                    type : 2,
                    month : $('month_add').val(),
	            },
	            function(data){
	            	if (data == 1) {
						$modal
							.modal('loading')
							.find('.modal-body')
					        .prepend('<div class="alert alert-info fade in">' +
					          'Updated!<button type="button" class="close" data-dismiss="alert">&times;</button>' +
					        '</div>');
                            
                             location.reload().delay( 2000 );
                            
	            	} else {
            			$modal
                            .modal('loading')
							.find('.modal-body')
					        .prepend('<div class="alert alert-error fade in">' +
					          'Update failed! Try again.<button type="button" class="close" data-dismiss="alert">&times;</button>' +
					        '</div>');
                            location.reload().delay( 2000 );
	            	}
	                
        		}
        	);
	});
    
    $('.decrease-off').click(function(){        
        var _self = $(this);
	    $('#modal2').modal();
        $('.staff_id').val(_self.data('staff-id'));
    });
    
	$('.note_label').click(function(){
	    var _self = $(this);

	    $('body').modalmanager('loading');
	    $('#note_content').html(_self.data('note'));
	    $('#note_id').val(_self.data('timing-id'));
	    $modal.modal('loading');

	    $.post('<?php echo HOST ?>/time/update-note-off',
            {
				id   : $('#note_id').val(),
				read : 1
            },
            function(data){
        		$modal.modal();
        		$modal.modal('loading');

        		if (_self.hasClass('label-info') || _self.hasClass('label-warning')) {
        			_self.next('.icon-eye-open').remove();
        			_self.after('<i class="icon-eye-open"></i>');
        			_self.removeClass('label-warning').addClass('label-info').html('Note');
        		}
    		}
    	);
	});

	$('#btn_save').click(function(){
		var _note_text = $('#note').val().trim();
		if (_note_text.length == 0) {
			$modal.modal('hide');
		} else {
			$modal.modal('loading');
			$.post('<?php echo HOST ?>/time/update-note-off',
	            {
					id   : $('#note_id').val(),
					note : _note_text
	            },
	            function(data){
	            	if (data == 1) {
	            		$('#note_content').append("\n"+_note_text);
	            		$('#note').val('');
						$modal
							.modal('loading')
							.find('.modal-body')
					        .prepend('<div class="alert alert-info fade in">' +
					          'Updated!<button type="button" class="close" data-dismiss="alert">&times;</button>' +
					        '</div>');
	            	} else {
            			$modal
                            .modal('loading')
							.find('.modal-body')
					        .prepend('<div class="alert alert-error fade in">' +
					          'Update failed! Try again.<button type="button" class="close" data-dismiss="alert">&times;</button>' +
					        '</div>');
	            	}
	                
        		}
        	);
		}		
	});

</script>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>
<?php echo $this->load();?>

