<table class="table table-bordered">
    <thead>
    <tr>
        <?php echo $this->sorting(array(
                '#',
                'staff_name'    => 'staff',
                'team'          => 'team',
                'title',
                'type',
                'from_date'     => 'from',
                'to_date'       => 'to',
                'Reason/Note',
                'Action'
            ),
            $this->url, $this->current_col, $this->desc);
        ?>
    </tr>
    </thead>
    <tbody>
            <?php
                $intCount = 0;
                if( isset($this->list) AND $this->list):
                    foreach($this->list as $item):
            ?>
                        <tr>
                            <td><?php echo ++$intCount;?></td>
                            <td><?php echo $item['staff_name'].' ('.$item['code'].')'; ?></td>
                            <td><?php echo $item['team']?></td>
                            <td><?php echo $item['title']?></td>
                            <td>
                                <?php
                                    if($item['off_type'] == CHILDBEARING){
                                        echo CHILDBEARING_NAME;
                                    }elseif($item['off_type'] == CHILDBEARING_KL){
                                        echo CHILDBEARING_KL_NAME;
                                    }
                                    elseif($item['off_type'] == OFF_KL){
                                        echo OFF_KL_NAME;
                                    }
                                ?>
                            </td>
                            <td>
                                  <?php echo ($item['from_date']) ? date('d/m/Y',strtotime($item['from_date'])): '';?>
                            </td>
                            <td>
                                <?php echo ($item['to_date'] AND $item['to_date'] != '0000-00-00 00:00:00') ? date('d/m/Y',strtotime($item['to_date'])): '';?>
                            </td>
                            <td><?php echo (isset($item['reason']) ? $item['reason'] : '')?></td>
                            <td>
                                
                                <a href="<?php echo HOST . 'time/create-childbearing?id=' . $item['id'] ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a href="<?php echo HOST . 'time/delete-childbearing?id=' . $item['id'] ?>" class="confirmLink">
                                    <i class="icon-trash"></i>
                                </a>
                                
                            </td>
                        </tr>
            <?php
                    endforeach;
                endif;
            ?>
    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php  echo $this->confirm();?>

