<style>
    .modal {
        width: 1024px;
        margin: -23% 0 0 -520px;
        padding: 10px;
    }

    .modal-body {
        max-height: 700px;
    }
</style>

<div class="page-header">
    <?php if (isset($this->info) and $this->info):
        $title = 'Edit : ' . ((isset($this->info)) ? $this->info->name : '');
    else:
        $title = 'Create';
    endif; ?>
    <h1><?php echo $title; ?></h1>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">' . $message . '</div>';
    endforeach;

//    echo '<pre>';
// print_r($this->info); die;
?>
<div class="row">
    <div class="row-fluid">
        <form role="form" id="form" enctype="multipart/form-data"
              action="<?php echo HOST . 'trainer/manage-shop-check-save'; ?>" method="post">
            <div class="span4">
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="name">Name : </label>
                        <input type="text" class="span4" id="name" name="name" required="required"
                               value="<?php if (isset($this->info)): echo $this->info->name; endif; ?>">
                    </div>
                    <div class="control-group">
                        <label for="name">Dscription : </label>
                        <input type="text" class="span4" id="description" name="description" required="required"
                               value="<?php if (isset($this->info)): echo $this->info->description; endif; ?>">
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="from_date">From Date : </label>
                        <input class="date" type="text" id="from_date" name="from_date" autocomplete="off"
                               required="required"
                               value="<?php if (isset($this->info)): echo date("Y/m/d H:i", strtotime($this->info->from_date)); endif; ?>">
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="to_date">To Date : </label>
                        <input class="date" type="text" id="to_date" name="to_date" autocomplete="off"
                               required="required"
                               value="<?php if (isset($this->info)): echo date("Y/m/d H:i", strtotime($this->info->to_date)); endif; ?>">
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="row-fluid">
                    <div class="form-group">
                        <label>Status :</label>
                        <div class="radio">
                            <label>
                                <input type="radio" name="enable" 
                                       value="Y" <?php if (isset($this->info) && ($this->info->enable == 'Y')): echo "checked"; endif; ?>>Enable
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="enable" required="required" 
                                       value="N" <?php if (isset($this->info) && ($this->info->enable == 'N')): echo "checked"; endif; ?>>Disable
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>

            <?php if (isset($this->info)) { ?>
                <hr>
                <div class="span6"><h2>Title List :</h2></div>
                <div class="span6" style="text-align: right;">
                    <button id="add_question" class="btn btn-success" type="button"><i class="icon-plus"></i> Add
                        Title
                    </button>
                </div>
                <!-- Question List -->
                <div class="span12">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th style="text-align: center;" width="5%">No.</th>
                            <th style="text-align: center;" width="75%">Title</th>
                            <th style="text-align: center;" width="10%">Choice</th>
                            <?php if ($this->info->id == 0) { ?>
                                <th style="text-align: center;" width="10%">Sort</th>
                            <?php } ?>
                            <th style="text-align: center;" width="10%">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $db = Zend_Registry::get('db');

                        //PC Active
                        if ($this->info->id == 0) {
                            $get = array(
                                'id' => 'paq.id',
                                'title' => 'paq.question',
                                'sort' => 'paq.sort',
                                'count_choice' => new Zend_Db_Expr('COUNT(paq.id)'),
                            );

                            $query = $db->select()
                                ->from(array('paq' => 'pc_active_questions'), $get)
                                ->join(array('paq2' => 'pc_active_questions'), 'paq2.parent_id  = paq.id', array())
                                ->group('paq.id')
                                ->order('paq.sort', 'asc');

                        } else {
                            $get = array(
                                'id' => 'clqt.id',
                                'title' => 'clqt.title',
                                'count_choice' => new Zend_Db_Expr('COUNT(clq.id)'),
                            );

                            $query = $db->select()
                                ->from(array('clq' => 'check_list_questions'), $get)
                                ->join(array('clqt' => 'check_list_questions_title'), 'clqt.id = clq.question_title_id', array())
                                ->join(array('clt' => 'check_list_topic'), 'clt.id = clq.topic_id', array())
                                ->where('clq.topic_id = ?', $this->info->id)
                                ->order('clqt.id', 'asc')
                                ->group('clqt.id');

                        }

                        $questions = $db->fetchAll($query);

                        if ($questions) {
                            $i = 1;
                            foreach ($questions as $value) { ?>
                                <tr>
                                    <td style="text-align: center;"><?php echo $i; ?></td>
                                    <td><?php echo $value['title']; ?></td>
                                    <td style="text-align: center;"><?php echo $value['count_choice']; ?></td>
                                    <?php if ($this->info->id == 0) { ?>
                                        <td style="text-align: center;"><?php echo $value['sort']; ?></td>
                                    <?php } ?>
                                    <td title="View" style="text-align: center;">
                                        <a title="Edit" onclick="editQuestion(<?php echo $value['id']; ?>)"
                                           style="padding-right: 0.4em;"><i class="icon-edit"></i></a>&nbsp;
                                        <a title="Delete"
                                           href="/trainer/manage-shop-check-question-delete?id=<?php echo $this->info->id; ?>&title_id=<?php echo $value['id']; ?>"
                                           onclick="return confirm('Are you sure to remove?');"><i
                                                    class="icon-trash"></i></a>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            }
                        }

                        ?>
                        </tbody>
                    </table>
                </div>
            <?php } ?>
            <input type="hidden" name="back_url" id="back_url"
                   value="<?php isset($this->back_url) and $this->back_url and printf($this->back_url); ?>">
            <input type="hidden" name="id" id="id"
                   value="<?php isset($this->info) and $this->info and printf($this->info->id); ?>">
            <div class="clearfix">
                <div class="span12 control-group" style="padding-bottom: 1em; padding-top: 1em">
                    <!--                    <button type="button" class="btn btn-inverse go-back">Go Back</button>-->
                    <button id="add_btn" class="btn btn-primary" type="submit">Submit</button>
                </div>
                <div class="clearfix">
        </form>
    </div>
</div>

<!-- Modal Add Question -->
<div id="form_question" class="modal hide fade" tabindex="-1" role="dialog"
     aria-labelledby="createTypeLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><i class="icon-plus"></i> Add Choice</h3>
    </div>
    <div class="modal-body">
        <form method="post" action="<?php echo HOST . 'trainer/manage-shop-check-question-save'; ?>">
            <input type="hidden" name="head_id" id="head_id">
            <input type="hidden" name="question_id" id="question_id">
            <div class="row-fluid">
                <div class="control-group">
                    <label for="questions">Title : </label>
                    <textarea class="span8" rows="4" cols="100" id="questions" name="questions"
                              required="required"><?php if (isset($this->data)): echo $this->data->questions; endif; ?></textarea>
                </div>
            </div>
            <?php if ($this->info->id == 0) { ?>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="questions">Sort : </label>
                        <input type="number" name="title_sort" id="title_sort">
                    </div>
                </div>
            <?php } ?>
            <hr>
            <div>
                <strong>List Choice :</strong>
                <button style="float: right;" id="add_choice_btn" class="btn btn-success" type="button"><i
                            class="icon-plus"></i> Add Choice
                </button>
                <table class="table table-bordered" style="margin-top: 10px;">
                    <thead>
                    <tr>
                        <th style="text-align: center;" width="5%">No.</th>
                        <th style="text-align: center;" width="75%">Choice</th>
                        <th style="text-align: center;" width="10%">Sort</th>
                        <th style="text-align: center;" width="10%">Action</th>
                    </tr>
                    </thead>
                    <tbody id="tbChoice"></tbody>
                </table>
            </div>
            <hr>
            <div class="control-group" style="text-align: right;">
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button type="submit" id="add_btn" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"/>

<script type="text/javascript">
    $(document).ready(function () {

        jQuery('.date').datetimepicker();

        $('.go-back').click(function (e) {
            window.location.href = $('#back_url').val();
            return false;
        });

        $('#add_question').click(function () {
            $('#form_question').modal('show');
            $(".modal-body #head_id").val($('#id').val());

            //Default
            $('#tbChoice').html('');
            $(".modal-body #question_id").val('');
            $(".modal-body #questions").val('');
            $(".modal-body #title_sort").val('');
        });

        $('#add_choice_btn').click(function () {
            var time = new Date().getTime();
            var rowNum = $('.tbRow').length;
            var add_choice = '<tr id="tbrow_' + time + '" class="tbRow">';
            add_choice += '<td style="text-align: center;" class="row_no">' + (rowNum + 1) + '</td>';
            add_choice += '<td id="questions"><input type="text" name="choice_list[' + time + '][questions]" style="margin-bottom: 0; width: 98%;"></td>';
            add_choice += '<td id="sort"><input type="number" name="choice_list[' + time + '][sort]" style="margin-bottom: 0; width: 90%;"></td>';
            add_choice += '<td style="text-align: center;"><button type="button" class="btn btn-default" onclick="removeChoice(tbrow_' + time + ')">×</button></td>';
            add_choice += '</tr>';

            $('#tbChoice').append(add_choice);
        });
    });

    function editQuestion(id) {
        var myData = {
            id: id,
            topic_id: <?php echo isset($this->info->id) ? $this->info->id : 0; ?>
        };

        $.ajax({
            type: 'POST',
            url: '<?php echo HOST . 'trainer/manage-shop-check-question'; ?>',
            data: myData,
            dataType: 'json',
            success: function (data) {
                if (data.msg === 'Success') {
                    $(".modal-body #head_id").val($('#id').val());
                    $(".modal-body #question_id").val(id);
                    $('#tbChoice').html('');
                    $.each(data.list, function (key, val) {
                        $(".modal-body #questions").val(val.title);
                        $(".modal-body #title_sort").val(val.title_sort);
                        var add_choice = '';
                        add_choice += '<tr id="tbrow_' + key + '" class="tbRow"><input type="hidden" name="choice_list[' + key + '][id]" value="' + val.id + '">';
                        add_choice += '<td style="text-align: center;" class="row_no">' + (key + 1) + '</td>';
                        add_choice += '<td id="questions"><input type="text" name="choice_list[' + key + '][questions]" style="margin-bottom: 0; width: 98%;" value="' + val.questions + '"></td>';
                        add_choice += '<td id="sort"><input type="number" name="choice_list[' + key + '][sort]" style="margin-bottom: 0; width: 90%;" value="' + val.sort + '"></td>';
                        add_choice += '<td style="text-align: center;"><button type="button" class="btn btn-default" onclick="removeChoice(tbrow_' + key + ')">×</button></td>';
                        add_choice += '</tr>';
                        $('#tbChoice').append(add_choice);
                    });
                }
            }
        });
        $('#form_question').modal('show');
    }

    function removeChoice(selector) {
        $(selector).remove();
        $('.row_no').each(function (i) {
            $(this).text(i + 1);
        });
    }
</script>