<link href="../css/select2.css" rel="stylesheet"/>
<script src="../js/select2.js"></script>

<form class="form-search form-horizontal" method="get" action="/report/inventory-turnover">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="category">Category :</label>
                <div class="controls">
                    <select class="form-control" name="category">
                        <option value="11"> Mobile Phone</option>
                    </select>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inventory_type">Inventory Type :</label>
                <div class="controls">
                    <select class="form-control" name="invertory_type">
                        <option value="11" <?php if( isset($this->params['invertory_type']) && $this->params['invertory_type'] == 11 ) echo "selected='selected'" ?>> RGM </option>
                        <option value="12" <?php if( isset($this->params['invertory_type']) && $this->params['invertory_type'] == 12 ) echo "selected='selected'" ?>> Model </option>
                        <!-- <option value="13" <?php if( isset($this->params['invertory_type']) && $this->params['invertory_type'] == 13 ) echo "selected='selected'" ?>> Warehouse </option> -->
                    </select>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inventory_by">Sellout Type :</label>
                <div class="controls">
                    <select class="form-control" name="invertory_by">
                        <option value="1" <?php if( isset($this->params['invertory_by']) && $this->params['invertory_by'] == 1 ) echo "selected='selected'" ?> > Verification  </option>
                        <option value="2" <?php if( isset($this->params['invertory_by']) && $this->params['invertory_by'] == 2 ) echo "selected='selected'" ?> > Activated </option>
                    </select>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="stock_by">Stock BY :</label>
                <div class="controls">
                    <select class="form-control" name="stock_by">
                        <option value="4" <?php if( isset($this->params['stock_by']) && $this->params['stock_by'] == 4 ) echo "selected='selected'" ?> > Not Timing and Not Activate </option>
                        <option value="2" <?php if( isset($this->params['stock_by']) && $this->params['stock_by'] == 2 ) echo "selected='selected'" ?> > Not Activate </option>
                        <option value="3" <?php if( isset($this->params['stock_by']) && $this->params['stock_by'] == 3 ) echo "selected='selected'" ?> > Not Timing </option>
                        <!-- <option value="1" <?php if( isset($this->params['stock_by']) && $this->params['stock_by'] == 1 ) echo "selected='selected'" ?> > All  </option> -->
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Brand :</label>
                <div class="controls">
                    <select class="js-example-basic-multiple span3" name="brand[]" id="brand" multiple="multiple">
                        <?php foreach($this->brands as $item) : ?>
                          <option value="<?php echo $item['id'] ?>" <?php if (isset($this->params['brand']) and ( (is_array($this->params['brand']) && in_array($item['id'], $this->params['brand']) || $item['id']==$this->params['brand'])) ):?>selected<?php endif;?>><?php echo $item['name'] ?>
                      </option>
                  <?php endforeach ?>
              </select>
          </div>
      </div>


      <div class="control-group">
        <label for="good" class="control-label">Products :</label>
        <div class="controls">
            <select id="good" name="good[]" class="js-example-basic-multiple span3" multiple="multiple">
                <?php
                    $data = $this->goods;
                    if ($this->goods) :
                        foreach ($this->goods as $good_list):
                            ?>
                            <option value="<?php echo $good_list['id'];?>" <?php if (isset($this->params['good']) and ( (is_array($this->params['good']) && in_array($good_list['id'], $this->params['good']) || $good_list['id']==$this->params['good'])) ):?>selected<?php endif;?>><?php echo $good_list['brand_name'] ?> <?php echo $good_list['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
            </select>
        </div>
    </div>



<!--       <div class="control-group">
        <label class="control-label">Product Name :</label>
        <div class="controls">
            <select class="form-control span3" name="good_id" id="good_id">
                <option value>Choose Product</option>
                <?php foreach ($this->goods as $good) :?>
                    <option value="<?php echo $good->id;?>" <?php if ($this->params['good_id']==$good->id):?> selected="selected"
                        <?php endif;?>>
                        <?php echo $this->brands[$good->brand_id]; ?> <?php echo $good->name;?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div> -->

    </div>
    <div class="span5">
     <div class="control-group">
        <label class="span2"> Invertory Date :</label>
        <input type="text" class="form-control search-query date span2" required id="date" name="date" value="<?php isset($this->params['date']) and printf($this->params['date']);?>">
    </div>

    <div class="control-group">
        <label for="date" class="span2">Sales From</label>
        <input type="text" class="form-control search-query date span2" required id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

    </div>
    <div class="control-group">
        <label for="date" class="span2">Sales To</label>
        <input type="text" class="form-control search-query date span2" required id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
    </div>

</div>
</div>
<div class="row">
    <div class="span5">
        <div class="control-group">
            <button type="submit" class="btn btn-success"> Search </button>
            <button type="submit" class="btn btn-success" value="1" name="export"> Export </button>
            <!-- <button type="submit" class="btn btn-primary" value="2" name="export"> Export By Model </button> -->
        </div>
    </div>
</div>

</form>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" media="screen" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<!-- <style>
    .year-month-calendar {
        display: none;
    }
</style> -->

<script type="text/javascript">

    $(".js-example-basic-multiple").select2();

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {
        // $("#good_id, #good_color").select2();

        multi();

        $('#search_bar').trigger('click');

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

         $('#brand').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var brand_id = $(this).val();
            $.get("/tool/get-product",
                {brand_id: brand_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    var obj = data.brands;

                    $("#good").empty();

                    for (var i = 0; i < obj.length; i++) {
                        $('#good').append('<option value="'+obj[i]['id']+'">'+obj[i]['brand_name']+' '+obj[i]['name']+'</option>');
                    }
                    _self.nextAll('.loading').remove();
                });
        });

    });

    // Calendar Year-Month
    $(function () {
        $('.date-picker').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'yy-mm',
            onClose: function (dateText, inst) {
                $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
            }
        });
    });

</script>