<div class="page-header">
    <h1>Diamond Plan - Configuration</h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<form role="form" method="post">

    <div class="row-fluid">
        <div class="span6">
            <div class="control-group">
                <label for="name" class="control-label">Name</label>
                <div class="controls">
                    <input type="text" id="name" required name="name" value="<?php isset($this->loyaltyPlan['name']) and printf($this->loyaltyPlan['name']);?>">
                </div>
            </div>
        </div>

    </div>

    <div class="row-fluid">
        <legend>
            CONDITION
        </legend>

        <div class="span4">

            <div class="control-group">
                <label for="sales" class="control-label">Sales</label>
                <div class="controls">
                    <select name="sales_comparison" id="sales_comparison" required="required">
                        <option value="">Choose</option>
                        <?php
                        $arrLoyaltyComparisons = array(
                            1 => '>=',
                            2 => '<=',
                        );
                        foreach ($arrLoyaltyComparisons as $id => $item){
                            ?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->distributorLoyalty['sales_comparison']) and $this->distributorLoyalty['sales_comparison'] == $id){?> selected<?php } ?>><?php echo $item;?></option>
                        <?php } ?>
                    </select>
                    <input type="number" id="sales" required name="sales" value="<?php isset($this->distributorLoyalty['sales']) and printf($this->distributorLoyalty['sales']);?>">
                    <span>per</span>
                    <select name="sales_per_unit" id="sales_per_unit" required="required">
                        <option value="">Choose</option>
                        <?php
                        $arrLoyaltyPer = array(
                            1 => 'Month',
                            2 => 'Year',
                        );
                        foreach ($arrLoyaltyPer as $id => $item){
                            ?>
                            <option value="<?php echo $id;?>" <?php if (isset($this->distributorLoyalty['sales_per_unit']) and $this->distributorLoyalty['sales_per_unit'] == $id){?> selected<?php } ?>><?php echo $item;?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>

        </div>

        <div class="span3">

            <div class="control-group">
                <label for="sales_share" class="control-label">Sales Share</label>
                <div class="controls">

                    <input type="number" id="sales_share" required name="sales_share" value="<?php isset($this->distributorLoyalty['sales_share']) and printf($this->distributorLoyalty['sales_share']);?>">
                    <span>%</span>
                </div>
            </div>

        </div>

        <div class="span3">

            <div class="control-group">
                <label for="pictures_share" class="control-label">Pictures Share</label>
                <div class="controls">

                    <input type="number" id="pictures_share" required name="pictures_share" value="<?php isset($this->distributorLoyalty['pictures_share']) and printf($this->distributorLoyalty['pictures_share']);?>">
                    <span>%</span>
                </div>
            </div>

        </div>
    </div>


    <div class="row-fluid">
        <div class="span2">
            <div class="control-group">
                <label for="memorandum" class="control-label">Memorandum</label>
                <div class="controls">
                    <input type="checkbox" name="memorandum" id="memorandum" <?php if (isset($this->distributorLoyalty['memorandum']) and $this->distributorLoyalty['memorandum']){?> checked="checked"<?php }?> />
                </div>
            </div>
        </div>

        <div class="span3">
            <div class="control-group">
                <label for="guarantee_money" class="control-label">Guarantee Money</label>
                <div class="controls">
                    <input type="text" name="guarantee_money" required="required" id="guarantee_money" value="<?php if (isset($this->distributorLoyalty['guarantee_money']) and $this->distributorLoyalty['guarantee_money']){ echo $this->distributorLoyalty['guarantee_money']; }?>" />
                </div>
            </div>
        </div>

        <div class="span4">
            <div class="control-group">
                <label for="note" class="control-label">Note</label>
                <div class="controls">
                    <textarea name="note"><?php echo ( isset($this->distributorLoyalty['note']) and $this->distributorLoyalty['note'] ? $this->distributorLoyalty['note'] : '' );?></textarea>
                </div>
            </div>
        </div>
    </div>



    <input type="hidden" name="dealer_id" id="dealer_id" value="<?php isset($this->distributor) and $this->distributor and printf($this->distributor->id);?>">
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="<?php if (isset($this->back_url) and $this->back_url){ echo $this->back_url; } else {echo '/loyalty';} ?>" class="btn btn-danger go-back">Go back</a>
</form>
<script type="text/javascript">
    $(document).ready(function () {
       /* $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });*/
    });
</script>