<script type="text/javascript" src="<?php echo HOST ?>js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/jquery.ui.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo HOST ?>css/jquery.ui.timepicker.css"/>
<div class="page-header">
    <h1>Leader Reports</h1>
</div>
<div class="row">
	<div class="span12">
		<?php
            echo $this->render('sales-report/partials/search-leader.phtml');
        ?>
	</div>
</div>
