<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<div class="page-header">
   <h1 style="font-family: noto sans lao;">Scan Into Store List ລາຍການສະແກນສະຕ໋ອກເຂົ້າຮ້ານ</h1>
</div>

<?php
if (isset($this->messages_success) and $this->messages_success)
 foreach ($this->messages_success as $message):
   echo '<div class="alert alert-success">'.$message.'</div>';
endforeach;

if (isset($this->messages) and $this->messages)
 foreach ($this->messages as $message):
   echo '<div class="alert alert-error">'.$message.'</div>';
endforeach;
?>

<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        <!-- Search --> <b style="color: #916b68; font-weight: bold; font-size:15px;" >Filter <b style="font-size:18px;"><span class="icon-filter"></span></b></b>
     </a>
  </div>
  <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
   <div class="accordion-inner">
     <?php
     echo $this->render('timing/scan-into/partials/search.phtml');
     ?>
  </div>
</div>
</div>
</div>

<div style="padding-bottom: 10px;">
   <a href="<?php echo HOST ?>timing/add-scan-into" class="btn btn-success"><i class="icon icon-plus"></i> Add</a>
</div>

<div class="table-responsive">
  <?php
  echo $this->render('timing/scan-into/partials/list.phtml');
  ?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
  $(document).ready(function () {
    $('.form-search button:reset').click(function (e){
      $('.form-search input, .form-search select').val('');
      $('.form-search').submit();
      return false;
   });
 });
</script>
