<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align="center">No.</div></th>
        <th><div align="center">Area</div></th>
        <th><div align="center">Store ID</div></th>
        <th><div align="center">Store Name</div></th>
        <th><div align="center">Store Type</div></th>
        <th><div align="center">Status</div></th>
        <th><div align="center">Action</div></th>
    </tr>
    </thead>
    <tbody>
        <?php 

            if ($this->store_list) {
                $data = $this->store_list;

                for($i=0;$i<count($data);$i++) { 

                    $cnt = $i + 1;
                    echo "<tr>";
                    echo    "<td><div align='center'>".$cnt."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['area_name']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['st_id']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['st_name']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['st_type']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['st_status']."</div></td>";
                    echo    "<td>
                                <div align='center'>
                                    <a title='Delete' class='confirmLink' href='/manage/store-focus-list-del?id=".$data[$i]['st_id']."'> <i class='icon-trash'></i></a>
                                </div>
                            </td>";
                    echo "</tr>";
                }

            }
        ?>
    </tbody>
</table>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script>
    $(document).ready(function () {
    
    });
</script>