<div class="page-header" style="background-color: #3f51b530; text-align: center; padding-top: 6px;">
    <h3 style="color: #673ab7;">Pre-Order List | <strong style="font-family: phetsarath OT; color: #9c27b0;"> ລາຍການສັ່ງຈອງ </strong></h3>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                <!-- Search --> <b style="color: #916b68; font-weight: bold; font-size:15px;" >Filter <b style="font-size:18px;"><span class="icon-filter"></span></b></b>
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('timing/preorder/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php echo $this->render('timing/preorder/partials/list.phtml'); ?>
</div>

