
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>
    .pics {
        height:  232px;
        width:   232px;
        padding: 0;
        margin:  0;
    }
 

    li img {
        padding: 15px;
        border: 1px solid #ccc;
        background-color: #eee;
        width: 427px;
        height: 500px;
        top: 0;
        left: 0;
    }
    .header {
        background: url('../img/bv.jpg') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }

    .title
    {
        font-size: 30px !important;
    }

    .jSlots-wrapper {
        overflow: hidden;
        height: 500px;
        display: inline-block;
        position: relative;
        top: 192px;
        /* border: 1px solid #999; */
    }
    .title-result
    {
          position: absolute;
          width: 591px !important;
          height: 90px !important;
          top: 378px !important;
          left: -128px !important;
          text-align: center;
          padding-top: 22px;
          font-size: 19px !important;
          color: white;
         
          -webkit-background-size: cover !important;
          -moz-background-size: cover !important;
          -o-background-size: cover !important;
          background-size: cover !important;
    }
</style>
<script src="<?php echo HOST ?>js/jquery-1.7.2.min.js"></script>
<script src="<?php echo HOST ?>js/jquery.easing.1.3.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo HOST ?>js/rolling.js"></script>
<link href="<?php echo HOST ?>css/rolling/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo HOST ?>css/rolling/animate.css" rel="stylesheet">
<link href="<?php echo HOST ?>css/rolling/owl.theme.css" rel="stylesheet">
<link href="<?php echo HOST ?>css/rolling/owl.theme.css" rel="stylesheet">
<link href="<?php echo HOST ?>css/rolling/style.css" rel="stylesheet">
<link href="<?php echo HOST ?>css/rolling/shake.css" rel="stylesheet">
<script src="<?php echo HOST ?>js/modernizr.custom.js"></script>
<script src="<?php echo HOST ?>js/rolling/libs.min.js"></script>
<script src="<?php echo HOST ?>js/rolling/jquery.nearest.min.js"></script>

<section id="header" class="header">
    <div class="top-bar">
        <div class="container">
            <div class="navigation" id="navigation-scroll">
                <div class="row">
                    <div class="col-md-4 col-xs-4">
                        <span id="logo"><img class="" src="<?php echo HOST ?>img/oppologo.png" /></span>
                    </div>
                    <div class="col-md-8 col-xs-2">
                        <h2 class="animation-box wow bounceIn animated animated" style="visibility: visible; animation-name: bounceIn; -webkit-animation-name: bounceIn;">Hội nghị khách hàng Diamond
                            <div id="demo"></div></h2>
                    </div>
                </div><!-- /.row -->
            </div><!-- /.navigation -->
        </div><!--/.container-->
    </div><!--/.top-bar-->

    <div class="container" >
        <div class="starting">
            <div class="row">
<audio class="audioDemo" id="sound" controls preload="none"> 
   <source src="<?php echo HOST?>sound.mp3"  type="audio/mpeg">   
</audio>
                <div style="  position: absolute;
  z-index: 999;
  top: 524px;
  left: 271px;">

                    <div id="title" style="display:none;position:absolute;background: url('../img/title.png'); width: 460px;
  height: 90px;top:250px;
  left: -125px; text-align: center ; padding-top: 22px;font-size:14px;color: white;">Nguyễn Huy Cường</div>

                </div>

                <div id="result" class="result" style="display: none">
                    <div class="col-md-6">
                        <img src="<?php echo HOST ?>img/r7.png" alt="LUCY" class="wow flipInY animated animated">
                       
                    </div>
                    <div class="col-md-6">
                        <div class="banner-text">
                            <h2 class="animation-box mini title fadeIn animated ">Xin chúc mừng quý khách hàng</h2>
                            <h2 class="animation-box  mini bounceIn animated">Khách hàng:<strong id="name" class="strong">Nguyễn Văn Nam</strong></h2>
                            <h2 class="animation-box wow  mini bounceIn animated">Shop:<strong id="shop" class="strong"> Smartmobile</strong></h2>
                            <h2 class="animation-box wow mini bounceIn animated">Khu vực :<strong id="area" class="strong"> Smartmobile</strong></h2>

                        </div> <!-- /.banner-text -->
                    </div>
                </div>


                <div id="contentContainer" class="trans3d" onclick="showCoords">
                    <section id="carouselContainer" class="trans3d">
                        <?php if(isset($this->data) and $this->data):
                                foreach($this->data as $item):
                        ?>
                        <figure id="fi<?php if(isset($item['id']) and $item['id']) echo $item['id']; ?>" class="carouselItem trans3d"><div class="carouselItemInner trans3d">

                              <?php if(isset($item['photo']) and $item['photo'])

                                {
                                    $url = '../photo'.DIRECTORY_SEPARATOR.'guest1'.DIRECTORY_SEPARATOR;

                                    $url = $url . $item['photo'];
                                }
                                    else

                                    $url = '../photo/guest1/1388613172161.jpg';
                                    ?>

                                <img id="<?php if(isset($item['id']) and $item['id']) echo $item['id']; ?>" src="<?php echo $url; ?>" ></div></figure>

                        <?php
                                endforeach;
                                    endif;

                        ?>
                    </section>
                </div>

            </div>
        </div>
        <!-- /.starting -->
    </div>
    <!-- /.container -->
</section>

   <!-- <ul class="slot">
        <li><img src="<?php echo HOST ?>images/1.jpg"></li>
        <li><img src="<?php echo HOST ?>images/2.jpg"></li>
        <li><img src="<?php echo HOST ?>images/3.jpg"> </li>
    </ul>
-->
<div class="notificationNum1" style="display: none;"></div>
    <!-- button click to play game-->
    <input type="button" id="playBtn" value="play">

    <script type="text/javascript" charset="utf-8">

        var w, container, carousel, item, radius, itemLength, rY, ticker, fps;
        var mouseX = 0;
        var mouseY = 0;
        var mouseZ = 0;
        var addX = 0;

        var fps_counter = {

            tick: function ()
            {
                // this has to clone the array every tick so that
                // separate instances won't share state
                this.times = this.times.concat(+new Date());
                var seconds, times = this.times;

                if (times.length > this.span + 1)
                {
                    times.shift(); // ditch the oldest time
                    seconds = (times[times.length - 1] - times[0]) / 1000;
                    return Math.round(this.span / seconds);
                }
                else return null;
            },

            times: [],
            span: 20
        };
        var counter = Object.create(fps_counter);



        function delay()
        {
            mouseX = 0.22;
        }

        function delay2()
        {
            mouseX = 0.09;
        }

        function showCoords(event) {
            var x = event.clientX;
            var y = event.clientY;
            var coords = "X coords: " + x + ", Y coords: " + y;
            alert(coords);
        }

        HTMLCanvasElement.prototype.relMouseCoords = function (event) {
            var totalOffsetX = 0;
            var totalOffsetY = 0;
            var canvasX = 0;
            var canvasY = 0;
            var currentElement = this;

            do {
                totalOffsetX += currentElement.offsetLeft;
                totalOffsetY += currentElement.offsetTop;
            }
            while (currentElement = currentElement.offsetParent)

            canvasX = event.pageX - totalOffsetX;
            canvasY = event.pageY - totalOffsetY;

            // Fix for variable canvas width
            canvasX = Math.round( canvasX * (this.width / this.offsetWidth) /5 );
            canvasY = Math.round( canvasY * (this.height / this.offsetHeight) );


            return {x:canvasX, y:canvasY}
        }
        function playsound()
        {
            jQuery("#sound").trigger('play')
        }

        function rolling()
        {
            setTimeout(playsound, 2000);
            mouseX = 1.2;
            mouseY = -1;
            mouseZ = -1500;
            looper();

          //  window.addEventListener( "mousemove", onMouseMove, false );
            setTimeout(delay, 12000);
            setTimeout(delay2, 16000);
            setTimeout(stop, 20000);
        }

        $(document).ready( init )

        function init()
        {
            w = $(window);
            container = $( '#contentContainer' );
            carousel = $( '#carouselContainer' );
            item = $( '.carouselItem' );
            itemLength = $( '.carouselItem' ).length;
            fps = $('#fps');
            rY = 360 / itemLength;
            radius = Math.round( (250) / Math.tan( Math.PI / itemLength ) );

            // set container 3d props
            TweenMax.set(container, {perspective:600})
            TweenMax.set(carousel, {z:-(radius)})

            // create carousel item props

            for ( var i = 0; i < itemLength; i++ )
            {
                var $item = item.eq(i);
                var $block = $item.find('.carouselItemInner');

                TweenMax.set($item, {rotationY:rY * i, z:radius, transformOrigin:"50% 50% " + -radius + "px"});

                animateIn( $item, $block )
            }



            ticker = setInterval( looper, 1000/60 );
        }

        function animateIn( $item, $block )
        {
            var $nrX = 360 * getRandomInt(2);
            var $nrY = 360 * getRandomInt(2);

            var $nx = -(1000) + getRandomInt( 4000 )
            var $ny = -(2000) + getRandomInt( 4000 )
            var $nz = -4
            000 +  getRandomInt( 4000 )

            var $s = 1.5 + (getRandomInt( 10 ) * .1)
            var $d = 1 - (getRandomInt( 8 ) * .1)

            TweenMax.set( $item, { autoAlpha:1, delay:$d } )
            TweenMax.set( $block, { z:$nz, rotationY:$nrY, rotationX:$nrX, x:$nx, y:$ny, autoAlpha:0} )
            TweenMax.to( $block, $s, { delay:$d, rotationY:0, rotationX:0, z:0,  ease:Expo.easeInOut} )
            TweenMax.to( $block, $s-.5, { delay:$d, x:0, y:0, autoAlpha:1, ease:Expo.easeInOut} )
        }

        function onMouseMove(event)
        {
            //mouseX = -(-(window.innerWidth * .5) + event.pageX) * .0025;
           // mouseY = -(-(window.innerHeight * .5) + event.pageY ) * .01;
          //  mouseZ = -(radius) - (Math.abs(-(window.innerHeight * .5) + event.pageY ) - 200);
            var coords = event.pageX + ' ' + event.pageY + ' ' + mouseZ;
            document.getElementById("demo").innerHTML = coords;
        }

        // loops and sets the carousel 3d properties
        function looper()
        {
            addX += mouseX
            TweenMax.to( carousel, 1, { rotationY:addX, rotationX:mouseY, ease:Quint.easeOut } )
            TweenMax.set( carousel, {z:mouseZ } )
            fps.text( 'Framerate: ' + counter.tick() + '/60 FPS' )
        }

        function getRandomInt( $n )
        {
            return Math.floor((Math.random()*$n)+1);
        }

        $('#logo').click(function(){

            setTimeout(rolling, 300);

        });

        var result = 0;

        function stop()
        {
            mouseX = 0;
            result = 1;
            setTimeout(findResult, 500);
        }

        function findResult()
        {
            var $closestToRegion = $.nearest({x: 659, y: 169}, 'img');
            var result_id = $closestToRegion.attr('id');
            if(result == 1 && result_id)
            {
               // $('#contentContainer').remove();
                var url = '<?php echo HOST ?>test/get-result';
                $.post(url, {
                    id : result_id
                }, function(data){
                    data=$.parseJSON(data);
                    if(data.photo)
                    {
                        var url = '/photo/guest/'+ result_id + '/' + data.photo;
                    }
                    else
                    {
                        url = '../photo/guest/1434415893095981272312.jpg';
                    }
                    var id = '#'+result_id;
                    $(id).parent().addClass('shake shake-little shake-constant');
                    $(id).css("width", "350px");                 
                    $(id).css("border", "6px solid white");
                    $(id).parent().css("width", "370px");
                    $(id).parent().parent().css("top", "40%");
                    $('#title').addClass('title-result');                  
                    $('#title').html(data.name + '-' + data.shop);
                    $(id).after($('#title').show());

               //     $('#result').show();
                });
            }
        }

        var boolean = 0;

        sevr = new EventSource("<?php echo HOST ?>test/server");
        sevr.onmessage = function(e){
        var data = JSON.parse(event.data);
            if(data.data == 1)
            {
                if(boolean == 0)
                    {                       
                        rolling();
                        boolean = 1;
                    }   
            }


            if(data.reset == 1)
            {
                var url_reset = '<?php echo HOST ?>test/reset'; 
                $.post(url_reset, {
                    id : 1
                }, function(data){
                    
                });
                setTimeout(location.reload(true), 200);
            }

            
        };

        /*(function( $ ) {

            var obj = new Array();
            var finish = 0;
            var bug = 0;
            var UID = <?= $this->recipientUid ?>;
            var ok = 0;

            NotifierSSE = (function() {
                var _stateNode1 = $('.notificationNum1'),

                    _timeNode = $('#time'),
                    _src,
                    _handler = {
                        onMessage : function(event) {
                            var data = JSON.parse(event.data);
                            _stateNode1.val(data.updatedNotificationNum1);

                            if(data.updatedNotificationNum1 == 1 && ok != 1)
                            {
                                ok = 1;
                                setTimeout(rolling, 300);
                                e.preventDefault();
                            }
                        }
                    };
                return {
                    init : function () {
                        _src = new EventSource("<?php echo HOST ?>test/phone");
                        _src.addEventListener('message', _handler.onMessage, false);
                    }
                }
            }());


            // Document is ready
            $(document).bind('ready.app', function() {
                setTimeout(NotifierSSE.init, 3000);
            });

        })( jQuery );*/

   
    </script>