<?php 
	// print_r($this->params);
	// echo "<br/>";
	// print_r($this->log);

	$area_id = $this->log[0]['area_id'];
	$area_name = $this->log[0]['area_name'];
?>

<style type="text/css">
* {
	font-size: 10px;
	font-family: Arial;
}

</style>

<!-- A4 Size [794 × 1122] -->
<table border="0" style="width:1122px;">
	<tr style="height:30px;">
		<th>THAI OPPO CO.,LTD</th>
	</tr>
	<tr style="height:20px;">
		<th>
			<table cellspacing="0" border="0">
				<tr>
					<td>COMMISSION FOR <?php echo $this->params['from_date']." - ".$this->params['to_date'];  ?></td>
				</tr>
			</table>
		</th>
	</tr>
	<tr>
		<th>
			<table cellspacing="0" border="1">
				<tr>
					<td align="center" style="width:50px;">ZONE : </td>
					<td align="center" style="width:150px;"><?php echo $area_name; ?></td>
				</tr>
			</table>
		</th>
	</tr>
	<tr>
		<td>
			<table cellspacing="0" border="1" style="width:1122px;">
				<tr align="center">
					<td style="width:50px;">ITEM</td>
					<td>ID Staff</td>
					<td>NAME</td>
					<td>Position</td>
					<td>ZONE</td>
					<td>Unit</td>
					<td>Sale Amount</td>
					<td>Commission</td>
					<td>Remark</td>
				</tr>

				<?php 
				
					$data = $this->log;
					//print_r($data);
					
					$cnt = 0;
					$total_sum_sellin = $total_sum_m_total = $total_com_rate = 0;

					for ($i=0;$i<count($data);$i++) {

						$cnt = $i+1;

						echo "<tr>";
						echo "<td><div align='center'>".$cnt."</div></td>";
						echo "<td><div align='center'>".$data[$i]['staff_code']."</div></td>";
						echo "<td><div align='left'>".$data[$i]['staff_name']."</div></td>";
						echo "<td><div align='center'>".$data[$i]['staff_group']."</div></td>";
						echo "<td><div align='center'>".$data[$i]['area_name']."</div></td>";
						echo "<td><div align='right'>".number_format($data[$i]['sum_sellin'])."</div></td>";
						echo "<td><div align='right'>".number_format($data[$i]['sum_m_total'],2)."</div></td>";
						echo "<td><div align='right'>".number_format($data[$i]['com_rate'])."</div></td>";
						echo "<td></td>";
						echo "</tr>";

						$total_sum_sellin = $total_sum_sellin + $data[$i]['sum_sellin'];
						$total_sum_m_total = $total_sum_m_total + $data[$i]['sum_m_total'];
						$total_com_rate = $total_com_rate + $data[$i]['com_rate'];

					}

					// Last Row
					echo "<tr>";
					echo "<td colspan='5'><div align='center'>Total</div></td>";
					echo "<td><div align='right'>".number_format($total_sum_sellin)."</div></td>";
					echo "<td><div align='right'>".number_format($total_sum_m_total,2)."</div></td>";
					echo "<td><div align='right'>".number_format($total_com_rate)."</div></td>";
					echo "<td></td>";
					echo "</tr>";
					
				?>

			</table>
		</td>
	</tr>
</table>

<div style="height:50px;"></div>

<table border="0" style="width:1122px;">
	<tr>
		<td align="right" style="width:260px;">Prepared By</td>
		<td align="left">.................................................................</td>
		<td align="right">ASM/RD</td>
		<td align="left">.................................................................</td>
	</tr>
	<tr>
		<td></td>
		<td align="left" style="padding-left:50px">( HR Department )</td>
		<td></td>
		<td align="left" style="padding-left:50px">( Sale Department )</td>
	</tr>
	<tr style="height:10px;"><td colspan="4"></td></tr>
	<tr>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
	</tr>
	<tr style="height:30px;"><td colspan="4"></td></tr>
	<tr>
		<td align="right">Checked By</td>
		<td align="left">.................................................................</td>
		<td align="right">Approve By</td>
		<td align="left">.................................................................</td>
	</tr>
	<tr style="height:20px;"><td colspan="4"></td></tr>
	<tr>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
	</tr>
</table>