<?php 
	//print_r($this->params);
	//echo "<br/>";
	//print_r($this->log);

	$area_id = $this->log[0]['area_id'];
	$area_name = $this->log[0]['area_name'];

	
	//print_r($data);

?>

<style type="text/css">
* {
	font-size: 10px;
	font-family: Arial;
}

</style>

<!-- A4 Size [794 × 1122] -->
<table border="0" style="width:1122px;">
	<tr style="height:30px;">
		<th>THAI OPPO CO.,LTD</th>
	</tr>
	<tr style="height:20px;">
		<th>
			<table cellspacing="0" border="0">
				<tr>
					<td>COMMISSION FOR <?php echo $this->params['from_date']." - ".$this->params['to_date'];  ?></td>
				</tr>
			</table>
		</th>
	</tr>
	<tr>
		<th>
			<table cellspacing="0" border="1">
				<tr>
					<td align="center" style="width:50px;">NAME : </td>
					<td align="center" style="width:150px;"><?php echo $this->params['asm_name']; ?></td>
				</tr>
				<tr>
					<td align="center" style="width:50px;">ZONE : </td>
					<td align="center" style="width:150px;"><?php echo $area_name; ?></td>
				</tr>
			</table>
		</th>
	</tr>
	<tr>
		<td>
			<table cellspacing="0" border="1" style="width:1122px;">
				<tr align="center">
					<td style="width:50px;">ITEM</td>
					<td>ID Staff</td>
					<td>NAME</td>
					<td>Position</td>
					<td>ZONE</td>
					<td>Total Unit</td>
					<td>Commission Sale</td>
					<td>Commission Store Share</td>
					<td>Total Commission</td>
					<td>Total Price</td>
				</tr>

				<?php 
					$data = $this->log;

					$cnt_data = count($data);
					$cnt = 0;

					$sum_unit = 0;
					$sum_com_rate = 0;
					$sum_store_share = 0;
					$sum_total_com_rate = 0;
					$sum_total_price = 0;

					for ($i=0;$i<$cnt_data;$i++) { 

						if ($data[$i]['group_id'] <> AM_ID) { 

							$cnt = $cnt + 1;
							$total_com_rate = $data[$i]['com_rate'] + $data[$i]['store_share'];

							echo "<tr>";
							echo 	"<td align='center'>".$cnt."</td>";
							echo 	"<td align='center'>".$data[$i]['staff_code']."</td>";
							echo 	"<td>".$data[$i]['staff_name']."</td>";
							echo 	"<td>".$data[$i]['group_name']."</td>";
							echo 	"<td>".$data[$i]['area_name']."</td>";
							echo 	"<td align='right'>".number_format($data[$i]['total_unit'])."</td>";
							echo 	"<td align='right'>".number_format($data[$i]['com_rate'])."</td>";
							echo 	"<td align='right'>".number_format($data[$i]['store_share'])."</td>";
							echo 	"<td align='right'>".number_format($total_com_rate)."</td>";
							echo 	"<td align='right'>".number_format($data[$i]['total_price'], 2)."</td>";
							echo "</tr>";

							$sum_unit = $sum_unit + $data[$i]['total_unit'];
							$sum_com_rate = $sum_com_rate + $data[$i]['com_rate'];
							$sum_store_share = $sum_store_share + $data[$i]['store_share'];
							$sum_total_com_rate = $sum_total_com_rate + $total_com_rate;
							$sum_total_price = $sum_total_price + $data[$i]['total_price'];
						}

					}

				?>

				<tr>
					<td colspan="5" align="center">TOTAL</td>
					<td align="right"><?php echo number_format($sum_unit); ?></td>
					<td align="right"><?php echo number_format($sum_com_rate); ?></td>
					<td align="right"><?php echo number_format($sum_store_share); ?></td>
					<td align="right"><?php echo number_format($sum_total_com_rate); ?></td>
					<td align="right"><?php echo number_format($sum_total_price, 2); ?></td>
				</tr>

			</table>
		</td>
	</tr>
</table>

<div style="height:50px;"></div>

<table border="0" style="width:1122px;">
	<tr>
		<td align="right" style="width:260px;">Prepared By</td>
		<td align="left">.................................................................</td>
		<td align="right">ASM/RM</td>
		<td align="left">.................................................................</td>
	</tr>
	<tr>
		<td></td>
		<td align="left" style="padding-left:50px">( HR Department )</td>
		<td></td>
		<td align="left" style="padding-left:50px">( Sale Department )</td>
	</tr>
	<tr style="height:10px;"><td colspan="4"></td></tr>
	<tr>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
	</tr>
	<tr style="height:30px;"><td colspan="4"></td></tr>
	<tr>
		<td align="right">Checked By</td>
		<td align="left">.................................................................</td>
		<td align="right">Approve By</td>
		<td align="left">.................................................................</td>
	</tr>
	<tr style="height:20px;"><td colspan="4"></td></tr>
	<tr>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
		<td align="right">Date</td>
		<td align="left">.................................................................</td>
	</tr>
</table>