  <?php
  
    $staff= $this->staff;
  
   if(isset($this->staff) and $this->staff) : ?>     
   <!-- <h6 class="bigstats"></h6>    -->
   <div class="container">
    <div class="row">
	<center>
	<?php $userStorage = Zend_Auth::getInstance()->getStorage()->read();

    $QGroup = NEW Application_Model_Group();

    $grou = $QGroup->get_cache();
	
	if($userStorage->photo != '')
					{
					?>
					<li><img src="http://center.oppo.in.th/photo/staff/<?php echo $userStorage->id;?>/<?php echo $userStorage->photo;?>" width ="100" height="100">
					</li>
					<?php } ?>
					</center>
					<br />
        <div class="span6">
             <label class="control-group span2">Staff Code/ລະຫັດ</label>
             <label class="control-group span2"><?php if(isset($staff['code'])) echo $staff['code']; ?></label>
        </div>
        
        <div class="span6">
             <label class="control-group span2">Name/ຊື່</label>
             <label class="control-group span2"><?php echo $staff['firstname'].' '.$staff['lastname'];?></label>
        </div>
        
        <div class="span6">
             <label class="control-group span2">Position/ຕຳແໜ່ງ</label>
             <label class="control-group span2"><?php echo $grou[$staff['group_id']];?></label>
        </div>
        
        <div class="span6">
             <label class="control-group span2">Tel/ເບີໂທລະສັບ</label>
             <label class="control-group span2"><?php echo $staff['phone_number'];?></label>
        </div>
        
    </div>
    
     <div class="row">
        <div class="span6">
             <label class="control-group span2">Area/ເຂດ</label>
             <label class="control-group span2"><?php if(isset($this->area['name']) and $this->area['name']) echo $this->area['name']; ?></label>
        </div>
        
        <div class="span6">
             <label class="control-group span2">Province/ແຂວງ</label>
             <label class="control-group span2"><?php if(isset($this->regional_market['name']) and $this->regional_market['name'])  echo $this->regional_market['name'];?></label>
        </div>
        
 
        
    </div>
   </div>
   
  
        
    </div>
    </div>
      <?php if(isset($this->off) and $this->off) : ?>  
    <h6 class="bigstats">ລາຍການທ້າຍເດືອນ</h6>   
   <div class="container">
    <div class="row">
    <?php foreach($this->off as $k=>$v): ?>
        
        <div class="span6">
            <label>ທ້າຍວັນ</label>
            <label class="control-group span2"><?php if(isset($v['date']) and $v['date']) echo date('d/m/Y', strtotime($v['date']));  ?></label>
        </div>
        
        <div class="span6">
            <label>ລະດູການ</label>
            <label class="control-group span2"><?php if(isset($v['reason']) and $v['reason']) echo $v['reason'];  ?></label>
        </div>
            
        
    <?php endforeach; ?>    
    </div>
    </div>
    <?php endif ?>
    
    
   
    
<?php endif; ?>