<div class="table-responsive">

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">#</div></th>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">Area</div></th>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">Store ID</div></th>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">Store Name</div></th>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">Store Type</div></th>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">Status</div></th>
      <th rowspan="2" style="vertical-align: middle;"><div align="center">PC</div></th>
      <th><div align="center">Store Target</div></th>
      <th><div align="center">Sellout</div></th>
      <th><div align="center">Sale Amount</div></th>
    </tr>
  </thead>
  <tbody>
    <?php
      $data = $this->store_am;

      $StoreStaff = new Application_Model_StoreStaff();

      $sum_sellout = $sum_price = 0;

      for ($i=0;$i<count($data);$i++) {

        $cnt = $i + 1;

        if ($data[$i]['st_del'] == 1) { $st_status = "<span class='label label-important'>Disable</span>"; }
        else { $st_status = "<span class='label label-success'>Active</span>";  }

        $result_pc = $StoreStaff->getPC($data[$i]['st_id']);
        $cnt_pc = count($result_pc);

        echo "<tr>";
        echo  "<td><div align='center'>".$cnt."</div></td>";
        echo  "<td><div align='center'>".$data[$i]['area_name']."</div></td>";
        echo  "<td><div align='center'>".$data[$i]['st_id']."</div></td>";
        echo  "<td><div align='center'>".$data[$i]['st_name']."</div></td>";
        echo  "<td><div align='center'>".$data[$i]['st_type']."</div></td>";
        echo  "<td><div align='center'>".$st_status."</div></td>";
        echo  "<td><div align='center'>".$cnt_pc."</div></td>";
        echo  "<td><div align='center'>".$data[$i]['st_target']."</div></td>";
        echo  "<td><div align='center'>".number_format($data[$i]['st_sellout'])."</div></td>";
        echo  "<td><div align='right'>".number_format($data[$i]['st_price'])."</div></td>";
        echo "</tr>";

        $sum_sellout = $sum_sellout + $data[$i]['st_sellout'];
        $sum_price = $sum_price + $data[$i]['st_price'];
      }

      echo "<tr>";
      echo  "<td colspan='8'><div align='center'>Summary</div></td>";
      echo  "<td><div align='center'>".number_format($sum_sellout)."</div></td>";
      echo  "<td><div align='center'>".number_format($sum_price)."</div></td>";
      echo "</tr>";

    ?>
    
  </tbody>
</table>
</div>