<div class="row-fluid">
    <div class="span12">
        <p>Enter district name, then press Enter to search</p>
        <input type="text" class="form-control" id="a_storename" placeholder="District" name="a_storename" />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <p>Result</p>
        <div class="load-ajax">
            <?php echo $this->partial('ajax/store-search-new.phtml',array()); ?>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <button type="button" id="btn_bind" class="btn btn-primary pull-right">Add to Province</button>
    </div>
</div>
