<?php
/* xu ly noi dung :)*/
$v = $this->v;

$this->luong = $luong= $this->l;

$kpi = $luong[$v['id']]['kpi'];

 ?>
<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
line-height:11.0pt;mso-line-height-rule:exactly;mso-list:l1 level1 lfo1;
tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Tổng tiền lương đã bao gồm phụ cấp trách nhiệm, BHXH, BHYT, BHTN, phép năm và các khoản phụ cấp khác (nếu có): &nbsp;<span style="color:blue"> </span><b><span style="color:blue"><?php if(isset($this->luong)) echo $this->luong[$v['id']]['bonus_salary'] ?></span></b><span style="color:blue"> &nbsp;</span>đồng/tháng trong đó:<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">*<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Các khoản phụ cấp có thể thay đổi tùy theo tình hình thực tế của công ty;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><?php if(isset($kpi) and $kpi) echo $kpi; ?><o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Thưởng theo doanh số hàng tháng (nếu có);<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;font-style:italic;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">*<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Các khoản phụ cấp có thể thay đổi tùy theo tình hình thực tế của Công ty<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Hình thức trả lương, thưởng:  Chuyển khoản/tiền mặt;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Được trả lương vào ngày 10 hàng tháng.<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Chế độ nâng lương:  Tùy theo thể hiện trong công việc và chính sách của công ty;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Được trang bị bảo hộ lao động : theo nhu cầu công việc;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Chế độ nghỉ ngơi (nghỉ hàng tuần, phép năm, lễ tết …): theo quy định của Bộ luật Lao động;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Bảo hiểm xã hội và bảo hiểm y tế: Được trả trực tiếp trong lương theo Luật quy định;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Chế độ đào tạo: Không;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Những thoả thuận khác: Không.<o:p></o:p></p>
