<?php
/* xu ly noi dung :)*/
$v = $this->v;

$this->luong = $this->l;

 ?>
<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Tổng tiền lương đã bao gồm phụ cấp trách nhiệm:  &nbsp; <b><span style="color:blue"> <?php if(isset($this->luong)) echo intval($this->luong[$v['id']]['probation_salary']); ?></span></b><span style="color:blue"> &nbsp;</span>đồng/tháng; <o:p></o:p></p>


<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Phụ cấp khác chưa bao gồm trong lương (Các khoản phụ cấp có thể thay đổi tùy theo tình hình hoạt động kinh doanh của Công ty):<o:p></o:p></p>

<p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:2.0pt;
margin-left:1.0in;text-indent:-.25in;line-height:18.0pt;mso-line-height-rule:
exactly;mso-list:l1 level2 lfo2;tab-stops:list 1.0in"><span style="font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol">•<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in">Phụ cấp cơm trưa: </span><b><?php if(isset($this->luong)) echo $this->luong[$v['id']]['allowance_1'] ?></b><b><span style="border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in"> </span></b><span style="border:none windowtext 1.0pt;mso-border-alt:none windowtext 0in;
padding:0in">đồng/người/tháng;</span><o:p></o:p></p>

<p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:6.0pt;
margin-left:1.0in;text-indent:-.25in;line-height:10.0pt;mso-line-height-rule:
exactly;mso-list:l1 level2 lfo2;tab-stops:list 1.0in"><span style="font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol">•<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in">Phụ cấp xăng xe: </span><b><?php if(isset($this->luong)) echo $this->luong[$v['id']]['allowance_2'] ?></b><b><span style="border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in"> </span></b><span style="border:none windowtext 1.0pt;mso-border-alt:none windowtext 0in;
padding:0in">đồng/người/tháng;</span><o:p></o:p></p>

<p class="MsoNormal" style="margin-top:0in;margin-right:0in;margin-bottom:6.0pt;
margin-left:1.0in;text-indent:-.25in;line-height:10.0pt;mso-line-height-rule:
exactly;mso-list:l1 level2 lfo2;tab-stops:list 1.0in"><span style="font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol">•<span style="font-stretch: normal; font-size: 7pt; line-height: normal; font-family: 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in">Phụ cấp điện thoại: </span><b><?php if(isset($this->luong)) echo $this->luong[$v['id']]['allowance_3'] ?></b><b><span style="border:none windowtext 1.0pt;
mso-border-alt:none windowtext 0in;padding:0in"> </span></b><span style="border:none windowtext 1.0pt;mso-border-alt:none windowtext 0in;
padding:0in">đồng/người/tháng;</span><o:p></o:p></p>



<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Hình thức trả lương, thưởng:  Chuyển khoản/tiền mặt;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Được trả lương và thưởng doanh số vào ngày 10 hàng tháng;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Được trang bị bảo hộ lao động : theo nhu cầu
công việc<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Chế độ nghỉ ngơi: nghỉ 01 ngày/ tuần;<o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Chế độ đào tạo: Theo quy định của Công ty và yêu cầu công việc. <o:p></o:p></p>

<p  style="margin-left:.5in;text-align:justify;text-indent:-.25in;
mso-list:l1 level1 lfo1;tab-stops:list .5in left 207.0pt 4.5in"><span style="font-family:VNI-Times;mso-fareast-font-family:VNI-Times;mso-bidi-font-family:
VNI-Times">-<span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span>Những thoả thuận khác: không có.<o:p></o:p></p>