<style>
body{
  font-family: phetsarath ot;
}

/* Main */
#menu {
    width: 320px;
    margin: 0;
    padding: 10px 0 0 0;
    list-style: none;
    background-color: #111;
    background-image: linear-gradient(#444, #111);
    border-radius: 20px;
    box-shadow: 0 2px 1px green;
    text-align: center;
}

#menu li {
    float: left;
    padding: 0 0 10px 0;
    position: relative;
}

#menu a {
    float: left;
    height: 25px;
    padding: 0 15px;
    color: #999;
    text-transform: uppercase;
    font: bold 12px/25px Arial, Helvetica;
    text-decoration: none;
    text-shadow: 0 1px 0 #000;
}

#menu li:hover > a {
    color: #fafafa;
}

*html #menu li a:hover { /* IE6 */
    color: #fafafa;
}

#menu li:hover > ul {
    display: block;
}

/* Sub-menu */
#menu ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: none;
    position: absolute;
    top: 35px;
    left: 0;
    z-index: 99999;
    background-color: #444;
    background-image: linear-gradient(#444, #111);
    -moz-border-radius: 5px;
    border-radius: 5px;
}

#menu ul li {
    float: none;
    margin: 0;
    padding: 0;
    display: block;
    box-shadow: 0 1px 0 #111111,
                0 2px 0 #777777;
}

#menu ul li:last-child {
    box-shadow: none;
}

#menu ul a {
    padding: 10px;
    height: auto;
    line-height: 1;
    display: block;
    white-space: nowrap;
    float: none;
    text-transform: none;
}

*html #menu ul a { /* IE6 */
    height: 10px;
    width: 150px;
}

*:first-child+html #menu ul a { /* IE7 */
    height: 10px;
    width: 150px;
}

#menu ul a:hover {
    background-color: #0186ba;
    background-image: linear-gradient(#04acec, #0186ba);
}

#menu ul li:first-child a {
    border-radius: 5px 5px 0 0;
}

#menu ul li:first-child a:after {
    content: '';
    position: absolute;
    left: 30px;
    top: -8px;
    width: 0;
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-bottom: 8px solid #444;
}

#menu ul li:first-child a:hover:after {
    border-bottom-color: #04acec;
}

#menu ul li:last-child a {
    border-radius: 0 0 5px 5px;
}

/* Clear floated elements */
#menu:after {
    visibility: hidden;
    display: block;
    font-size: 0;
    content: " ";
    clear: both;
    height: 0;
}

#menu ul li:first-child a:after {
    content: '';
    position: absolute;
    left: 30px;
    top: -8px;
    width: 0;
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-bottom: 8px solid #444;
}

#menu ul li:first-child a:hover:after {
    border-bottom-color: #04acec;
}

</style> 
<br>
<center>

 <ul id="menu">
    <li>
        <a href="#" style="font-family: phetsarath ot; font-size: 18px;">ວິດີໂອ</a>
        <ul>
            <li><a href="#" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີລາຍງານຍອດ</a></li>
            <li><a href="#" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີກວດເບິ່ງ imei</a></li>
            <li><a href="#" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີເບິ່ງ imei ທີ່ຂາຍໄປແລ້ວ</a></li>
            <li><a href="#" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີເບິ່ງ imei ທີ່ລາຍງານບໍ່ໄດ້</a></li>
            <li><a href="#" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີການໃຊ້ Guideline</a></li>
            <li><a href="#" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີປ່ຽນລະຫັດຜ່ານ</a></li>
        </ul>
    </li>

    <li>
        <a href="#" style="font-family: phetsarath ot; font-size: 18px;">ເອກະສານ</a>
        <ul>
            <li><a href="https://drive.google.com/file/d/1H3VWKk60orMu-43SmOZm0_wtCZMzynEW/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີລາຍງານຍອດ</a></li>
            <li><a href="https://drive.google.com/file/d/12AyEzC-PekSbVWaHnTSO6U9tplXOgbhX/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີກວດເບິ່ງ imei</a></li>
            <!-- <li><a href="https://drive.google.com/file/d/1eGmKKz8KqMXaxSkvZlYybG3W4XOPf35v/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີເບິ່ງ imei ທີ່ຂາຍໄປແລ້ວ</a></li>
            <li><a href="https://drive.google.com/file/d/1rzidAYgerZNkbVrICIDUPAiStT-Jp_nJ/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີເບິ່ງ imei ທີ່ລາຍງານບໍ່ໄດ້</a></li> -->
            <li><a href="https://drive.google.com/file/d/1LHEFFwLHjQmaF0VBWBDeqSfcmmxTDBuV/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີການໃຊ້ Guideline</a></li>
            <li><a href="https://drive.google.com/file/d/1ZAsyg8z8jzVTcAThGjwiY_XP-quLcQ93/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີກວດເບິ່ງລາຍງານ Report</a></li>
            <li><a href="https://drive.google.com/file/d/1xepmx3Y7NWjm_GTAC0oMeSEEMwg5kSBG/view?usp=sharing" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ວິທີປ່ຽນລະຫັດຜ່ານ</a></li>
        </ul>
    </li>

    <li>
        <a href="#" style="font-family: phetsarath ot; font-size: 18px;">ແບບຟອມ</a>
        <ul>
            <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSegZP-gw1YmVBkw297namiCUceeTrcpAzB_RhXulJUzZQ6PXQ/viewform?usp=sf_link" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ພະນັກງານໃໝ່</a></li>
            <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSegZP-gw1YmVBkw297namiCUceeTrcpAzB_RhXulJUzZQ6PXQ/viewform?usp=sf_link" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ພະນັກງານບໍ່ມີຮ້ານ</a></li>
            <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSexYCDX5VVxhzLfzLWGQDnOKd6aXjOLK3Xbhf5iGh7-8dsRkg/viewform?usp=sf_link" style="font-family: phetsarath ot; font-size: 14px; text-align: left;">ພະນັກງານເຂົ້າລະບົບບໍ່ໄດ້</a></li>
        </ul>
    </li>
</ul>

</center>

<br><br><br><br><br><br><br><br><br><br><br><br>

<script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript">
    $(function() {
      if ($.browser.msie && $.browser.version.substr(0,1)<7)
      {
        $('li').has('ul').mouseover(function(){
            $(this).children('ul').show();
            }).mouseout(function(){
            $(this).children('ul').hide();
            })
      }
    });
</script>

