    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="text-align: center;" width="5%">No.</th>
            <th style="text-align: center;" width="30%">Name</th>
            <th style="text-align: center;" width="30%">Description</th>
            <th style="text-align: center;" width="20%">From Date</th>
            <th style="text-align: center;" width="20%">To Date</th>
            <th style="text-align: center;" width="10%">Number of questions</th>
            <th style="text-align: center;" width="10%">Status</th>
            <th style="text-align: center;" width="10%">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php
        $count = 0;
        if (isset($this->list) and $this->list)
            foreach ($this->list as $k => $item) {

                if ($item['id'] == 0) {
                    $db = Zend_Registry::get('db');

                    $query = $db->select()
                        ->from(array('paq' => 'pc_active_questions'))
                        ->where('paq.parent_id <> ?', 0);

                    $pc_active = $db->fetchAll($query);

                    $count_questions = count($pc_active);
                } else {
                    $count_questions = $item['count_questions'];
                }

                ?>
                <tr>
                    <td style="text-align: center;"><?php echo $this->offset + $k + 1; ?></td>
                    <td><?php echo isset($item['name']) ? $item['name'] : ''; ?></td>
                    <td><?php echo isset($item['description']) ? $item['description'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['from_date']) ? $item['from_date'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['to_date']) ? $item['to_date'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo $count_questions; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['id']) ? EnableDisplay($item['enable']) : ''; ?></td>
                    <td title="View" style="text-align: center;">
                        <a title="Edit" href="/trainer/manage-shop-check-create?id=<?php echo $item['id']; ?>"
                           style="padding-right: 0.4em;"><i class="icon-edit"></i></a>&nbsp;
                        <?php if ($item['id'] > 0) { ?>
                        <a title="Delete" href="/trainer/manage-shop-check-delete?id=<?php echo $item['id']; ?>" onclick="return confirm('Are you sure to remove?');"><i class="icon-trash"></i></a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>