<form id="search_form" class="form-search form-horizontal" method="get"
      action="/trainer/manage-shop-check/manage-shop-check">
    <div class="row" style="padding-top: 20px;">
        <div class="span5">
            <div class="control-group">
                <label for="title" class="span2">Name</label>
                <input id="title" name="name" type="text" class="search-query form-control span2"
                       value="<?php isset($this->params['name']) and printf($this->params['name']); ?>">
            </div>
        </div>
        <div class="span5"></div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>