<div class="container">
    <div class="row">
        <div class="main-timeline">

<!--
            <div class="timeline">
                <div class="timeline-icon"></div>
                <div class="timeline-content">
                    <span class="date">Apr 2013 - Mar 2014</span>
                    <h5 class="title">Web Desginer</h5>
                    <p class="description">
                        Lorem ipsum dolor sit amet
                    </p>
                </div>
            </div>
-->

            <?php

                if ( isset($this->pc_info_list) and $this->pc_info_list ) {

                    $data = $this->pc_info_list;

                    for ($i=0;$i<count($data);$i++) {

                        echo "<div class='timeline'>";
                        echo    "<div class='timeline-icon'></div>";
                        echo    "<div class='timeline-content'>";

                        echo    "<span class='date'>".date("Y-m-d", strtotime($data[$i]['flag_date']))."</span>";
                        echo    "<h5 class='title'>".$data[$i]['flag_name']."</h5>";

                        switch ($data[$i]['flag_id']) {

                            case 1:
                                echo "<p class='description'>Level : ".$data[$i]['staff_level']."</p>";
                                echo "<p class='description'>Updated By : ".$data[$i]['set_by_group']."</p>";
                                break;

                            case 2:
                                echo "<p class='description'>Store ID : ".$data[$i]['st_id']."</p>";
                                echo "<p class='description'>Store Name : ".$data[$i]['st_name']."</p>";
                                echo "<p class='description'>Store Type : ".$data[$i]['st_type']."</p>";
                                break;

                            case 3:
                                echo "<p class='description'>Topic : ".$data[$i]['topic_name']."</p>";
                                echo "<p class='description'>Pass : ".$data[$i]['sc_status']."</p>";
                                break;

                            case 4:
                                $avg_score = ROUND(( $data[$i]['sum_answer_score'] / $data[$i]['sum_total_score'] ) * 100, 0);

                                echo "<p class='description'>Coverage : ".$data[$i]['question_pass']." / ".$data[$i]['question_total']."</p>";
                                echo "<p class='description'>Average Score : ".$avg_score."%</p>";
                                break;
                            
                            default: 
                                break;
                        }

                        echo    "</div>";
                        echo "</div>";

                    }

                }

            ?>

        </div>
    </div>
</div>

<br/>

<div align="center"><h2>Shop Binding</h2></div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align="center">Store ID</div></th>
        <th><div align="center">Store Name</div></th>
        <th><div align="center">Store Type</div></th>
        <th><div align="center">Joined At</div></th>
        <th><div align="center">Released At</div></th>
    </tr>
    </thead>
    <tbody>

    <?php 

        if (isset($this->shop_binding) and $this->shop_binding) {

            $data = $this->shop_binding;

            for ($i=0;$i<count($data);$i++) { 

                echo "<tr>";
                echo    "<td width='10%'><div align='center'>".$data[$i]['st_id']."</div></td>";
                echo    "<td width='40%'><div align='left'>".$data[$i]['st_name']."</div></td>";
                echo    "<td width='20%'><div align='center'>".$data[$i]['st_type']."</div></td>";
                echo    "<td width='15%'><div align='center'>".$data[$i]['flag_date']."</div></td>";
                echo    "<td width='15%'><div align='center'>".$data[$i]['released_at']."</div></td>";
                echo "</tr>";

            }

        }

    ?>

    </tbody>
</table>

<br/>

<div align="center"><h2>Shop Check</h2></div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align="center">No.</div></th>
        <th><div align="center">Topic Name</div></th>
        <th><div align="center">Status</div></th>
        <th><div align="center">Checked Date</div></th>
    </tr>
    </thead>
    <tbody>

    <?php 

        if (isset($this->shop_check) and $this->shop_check) {

            $data = $this->shop_check;
            $cnt = 0;

            for ($i=0;$i<count($data);$i++) { 

                $cnt = $i + 1;

                echo "<tr>";
                echo    "<td width='10%'><div align='center'>".$cnt."</div></td>";
                echo    "<td width='60%'><div align='left'>".$data[$i]['topic_name']."</div></td>";
                echo    "<td width='15%'><div align='center'>".$data[$i]['sc_status']."</div></td>";
                echo    "<td width='15%'><div align='center'>".$data[$i]['flag_date']."</div></td>";
                echo "</tr>";

            }

        }

    ?>

    </tbody>
</table>

<br/>

<div align="center"><h2>Monthly E-Test</h2></div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align="center">No.</div></th>
        <th><div align="center">Date</div></th>
        <th><div align="center">Pass Question</div></th>
        <th><div align="center">Total Question</div></th>
        <th><div align="center">Score</div></th>
        <th><div align="center">Total Score</div></th>
        <th><div align="center">Average Score</div></th>
    </tr>
    </thead>
    <tbody>

    <?php 

        if (isset($this->pc_e_test) and $this->pc_e_test) {

            $data = $this->pc_e_test;
            $cnt = 0;

            for ($i=0;$i<count($data);$i++) { 

                $avg_score = ROUND(( $data[$i]['sum_answer_score'] / $data[$i]['sum_total_score'] ) * 100, 0);

                $cnt = $i + 1;

                echo "<tr>";
                echo    "<td width='10%'><div align='center'>".$cnt."</div></td>";
                echo    "<td width='20%'><div align='center'>".$data[$i]['flag_date']."</div></td>";
                echo    "<td width='10%'><div align='right'>".$data[$i]['question_pass']."</div></td>";
                echo    "<td width='10%'><div align='right'>".$data[$i]['question_total']."</div></td>";
                echo    "<td width='10%'><div align='right'>".$data[$i]['sum_answer_score']."</div></td>";
                echo    "<td width='10%'><div align='right'>".$data[$i]['sum_total_score']."</div></td>";
                echo    "<td width='30%'><div align='center'>".$avg_score."%</div></td>";
                echo "</tr>";

            }

        }

    ?>

    </tbody>
</table>

<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>

<script>

    $(document).ready(function () {

        $modal = $('#modal');
        $('.view_details').click(function(){

            _self = $(this);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>trainer/pc-level-by-area-detail',
                {
                    area_id : _self.data('area-id'),
                    type_id : _self.data('type-id'),
                },
                function(data){
                    //alert(data);
                    $modal.html(data);
                    $modal.modal();
                    // var name = _self.parents('tr').children('td:nth-child(7)').html();
                    // $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
        });

    });
    
</script>