<form class="form-search form-horizontal" method="get" action="/trainer/list-push-notification">
    <div class="row">
        <div class="span4">
            <div class="control-group">
                <label for="Asset" class="span2">Title</label>
                <input id="title" name="title" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
            </div>
        </div>
        <div class="span4">
            <div class="control-group">
                <select name="action_status">
                    <option value="">-- All Status --</option>
                    <?php $status = array('1'=>'Drafts','2'=>'Send'); foreach($status as $key => $value):?>
                        <option value="<?php echo $key;?>" <?php if (isset($this->params['action']) and $this->params['action'] == $key):?> selected <?php endif;?> > <?php echo $value;?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
<!--        <div class="span3">-->
<!--            <div class="control-group">-->
<!--                <select name="enable">-->
<!--                    <option value="">-- All Display --</option>-->
<!--                    --><?php //$type = array('Y'=>'Open','N'=>'Close'); foreach($type as $key => $value):?>
<!--                        <option value="--><?php //echo $key;?><!--" --><?php //if (isset($this->params['enable']) and $this->params['enable'] == $key):?><!-- selected --><?php //endif;?><!-- > --><?php //echo $value;?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div>-->
<!--        </div>-->
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
    <a href="/trainer/list-push-notification"><input type="button" class="btn btn-warning" value="Reset"/> </a>
</form>