<div class="page-header">
    <h1>Report By Store</h1>
    <small>ລາຍງານຍອດຂາຍຕາມຮ້ານຄ້າ</small>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                <!-- Search --> <b style="color: #916b68; font-weight: bold; font-size:15px;" >Filter <b style="font-size:18px;"><span class="icon-filter"></span></b></b>
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('timing/partials/report_search_store.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="pull-right">
    <!-- <strong>Sell Out: <?php echo $this->total_quantity['total_sellout']; ?> | Activated: <?php echo $this->total_quantity['total_activated']; ?></strong> -->
    
    <?php 
        $selected_product_name = "";
        $cnt_selected = count($this->params['selected_product']);
        for ($i=0;$i<$cnt_selected;$i++) {

            if ($cnt_selected > 3) {
                $selected_product_name = $cnt_selected." Product";
            } else {
                $selected_product_name = $selected_product_name.$this->goods[ $this->params['selected_product'][$i] ]['name'];
                if ($i != $cnt_selected-1) { $selected_product_name = $selected_product_name.", "; }
            }

        }

        echo "<h4><strong>Total Sellout : ".number_format($this->total_quantity['total_sellout'],0)." | Activated : ".$this->total_quantity['total_activated']." &nbsp;&nbsp;&nbsp;&nbsp;</strong></h4>";
        //echo "<strong>Sellout : ".$this->total_quantity['total_sellout']." | ".$this->goods[ $this->params['selected_product'] ]['name']." : ".$this->total_quantity['total_sellout_hero']."</strong>";
    ?>

</div>
<div class="clearfix"></div>

<div class="table-responsive load-ajax">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th><div align="center">No</div></th>
                <!-- <th><div align="center">Type</div></th> -->
                <th><div align="center">Store Code</div></th>
                <th><div align="center">Store Name</div></th>
                <!-- <th><div align="center">Market Type</div></th>
                <th><div align="center">[ID] Market Name</div></th> -->
                <th><div align="center">Area</div></th>
                <th><div align="center">Province</div></th>
                <!-- <th><div align="center">District</div></th> -->
                <th><div align="center">Sale Code</div></th>
                <th><div align="center">PC Code [Current]</div></th>
                <!-- <th><div align="center">PCDB Code</div></th> -->
                <!-- <th><div align="center">PC Stand By [Current]</div></th> -->
                <th><div align="center">Last 2 Months</div></th>
                <th><div align="center">Last 1 Month</div></th>
                <th><div align="center">Sellout</div></th>
                <!-- <th><div align="center">Price</div></th> -->
                <!-- <th><div align="center"><?php echo "[".$selected_product_name."] "; ?>Sellout</div></th> -->
            </tr>
        </thead>
        <tbody>
            <?php

            $QStoreMarket = new Application_Model_StoreMarket();
            $QStoreStaff = new Application_Model_StoreStaff();

            if (isset($this->sales) and $this->sales)
                $inc = $this->offset + 1;
                foreach ($this->sales as $sale):  

                    $result_sm = $QStoreMarket->getMarketInfo($sale['st_id']);
                    $result_ss_sale = $QStoreStaff->getSale($sale['st_id']);

            ?>
            <tr>
                <td>
                    <?php

                        echo $inc++;
                        //echo "-".$sale['store_id'];;
                    ?>
                </td>
                <!-- <td><?php echo $sale['st_type']; ?></td> -->
                <td><?php echo $sale['st_code'];?></td>
                <td><?php echo $sale['st_name']; ?></td>
                <!-- <td><?php echo $result_sm['market_type_name']; ?></td>
                <td><?php echo "[".$result_sm['market_name_id']."] ".$result_sm['market_name']; ?></td> -->
                <td><?php echo $sale['area']; ?></td>
                <td><?php echo $sale['province']; ?></td>
                <!-- <td><?php echo $sale['district']; ?></td> -->
                <td><?php echo $result_ss_sale['sale_code']; ?></td>
                <td>
                    <?php 
                        $staff_list = $QStoreStaff->getPC($sale['st_id'], 0);
                        
                        $cnt = count($staff_list);

                        if ($cnt > 0 ) {
                            for ($i=0;$i<$cnt;$i++) {
                                echo $staff_list[$i]['pc_code'];
                                if ($i != $cnt-1) { echo "<strong> / </strong>"; }
                            }
                        } else { echo "-"; }
                    ?>
                </td>
                <!-- <td>
                    <?php 
                        $staff_list = $QStoreStaff->getPCDB($sale['st_id'], 0);
                        
                        $cnt = count($staff_list);

                        if ($cnt > 0 ) {
                            for ($i=0;$i<$cnt;$i++) {
                                echo $staff_list[$i]['pcdb_name_lastname'];
                                if ($i != $cnt-1) { echo "<strong> / </strong>"; }
                            }
                        } else { echo "-"; }
                    ?>
                </td> -->
                <td style="text-align:center;"><?php echo $sale['last_02']; ?></td>
                <td style="text-align:center;"><?php echo $sale['last_01']; ?></td>
                <td style="text-align:center; font-weight:bold;"><?php echo !empty($sale['sellout']) ? '<span class="badge badge-success" data-store-id="'.$sale['st_id'].'">'.$sale['sellout'].'</span>' : '0' ?></td>
                <!-- <td><?php echo !empty($sale['total_price']) ? number_format($sale['total_price'],0) : '0' ?></td> -->
                <!-- <td><?php echo !empty($sale['sellout_hero']) ? $sale['sellout_hero'] : '0' ?></td> -->
            </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
</div>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>

<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $modal = $('#modal');
        $('.badge.badge-success').click(function(){
            _self = $(this);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>/timing/store-short-report',
                {
                    from            : $('#from').val(),
                    to              : $('#to').val(),
                    name            : $('#name').val(),
                    area            : $('#area').val(),
                    regional_market : $('#regional_market').val(),
                    store_id        : _self.data('store-id')
                },
                function(data){
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(2)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
        });
/*
        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $('button, .btn, input').prop('disabled', true);
            $.get("/analytics-store/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#district, #regional_market').multiselect("destroy").multiselect(options);
                    _self.nextAll('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }

                            $('#district').multiselect("destroy").multiselect(options);
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });
*/
    });
    
</script>
<?php echo $this->load('combobox');?>
