<div class="page-header">
    <h1>Report By PC/Sale</h1>
    <small> ລາຍງານຍອດຂາຍຕາມຜູ້ລາຍງານ </small>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>


							
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                <!-- Search --> <b style="color: #916b68; font-weight: bold; font-size:15px;" >Filter <b style="font-size:18px;"><span class="icon-filter"></span></b></b>
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
			         echo $this->render('timing/partials/report_search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
						

<div class="pull-right">
    <strong>&nbsp;||&nbsp;Activated: 
        <?php 
            $cnt = count($this->total_sales);

            $cnt_activated = 0;
            foreach ($this->total_sales as $k=>$sale) {
                $cnt_activated = $cnt_activated + $sale['activated_total'];
            }

            echo $cnt_activated;
        ?> 
    </strong>
</div>

<div class="pull-right">
    <strong>&nbsp;&nbsp;Total Sales: 
        <?php 

            $cnt_total = 0;
            foreach ($this->total_sales as $k=>$sale) {
                $cnt_total = $cnt_total + $sale['total'];
            }

            echo $cnt_total;

        ?> 
    </strong>
</div>

<!-- <div class="pull-right">
    <strong>Total Price: 
        <?php 

            $cnt_total = 0;
            foreach ($this->total_sales as $k=>$sale) {
                $cnt_total = $cnt_total + $sale['total_price'];
            }

            echo number_format($cnt_total);

        ?> 
    </strong>
</div> -->

<div class="clearfix"></div>

<div class="table-responsive load-ajax">
    <table class="table table-bordered">
        <thead>
            <tr>
                <?php 
                    echo $this->sorting(array(
                        '#',
			            'code'            => 'Code', 
                        'name'            => 'Name',
                        'title'           => 'Position',
                        'area'            => 'Area',
                        'regional_market' => 'Province',
                        // 'total_price'     => 'Total Price',
                        'product_count'   => 'Product Count',
                    ),
                    $this->url, $this->current_col, $this->desc); 
                ?>
            </tr>
        </thead>
			
        <tbody>
            <?php
                if (isset($this->sales) and $this->sales)
                    $inc = $this->offset + 1;
                    foreach ($this->sales as $k=>$sale): 
            ?>
            <tr>
                <td>
                    <?php
                        echo $inc++;
                    ?>
                </td>
		<td><font color="#ee7700"><?php echo $sale['code']?></font></td>
                <td><?php echo $sale['firstname'].' '.$sale['lastname'];?></td>
                <td><?php if (isset($this->teams[$sale['title']])) echo $this->teams[$sale['title']] ;?></td>
                <td><?php echo $sale['area'];?></td>
                <td><?php echo $sale['regional_market'];?></td>
                <!-- <td><?php echo !empty($sale['total_price']) ? $sale['total_price'] : '0' ?></td> -->
                <td style="text-align:center"><?php echo !empty($sale['total']) ? '<span class="badge badge-success" data-staff-id="'.$k.'">'.$sale['total'].'</span>' : '0' ?></td>
            </tr>
            <?php   endforeach; ?>

        </tbody>
						
    </table>
</div>


<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $modal = $('#modal');
        $('.badge.badge-success').click(function(){
            _self = $(this);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>/timing/short-report',
                {
                    from            : $('#from').val(),
                    to              : $('#to').val(),
                    phone_number    : $('#phone_number').val(),
                    name            : $('#name').val(),
                    // area            : $('#area').val(),
                    // regional_market : $('#regional_market').val(),
                    staff_id : _self.data('staff-id')
                },
                function(data){
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(2)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
        });
    
    });

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {
        multi();

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    $('button, .btn, input').prop('disabled', false);
                    // $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#district').change(function(){
            $('.loading').remove();
            $('button, .btn, input').prop('disabled', true);
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var regional_market = $(this).val();
            $.get("<?php echo HOST ?>staff/load-sales-team",
                {district: regional_market}
                ,function(data,status){
                    var obj         = $.parseJSON( data );
                    var stores      = obj.stores;

                    $('#store').find('option').remove();
                    for (var i = 0; i < stores.length; i++) {
                        $('#store').append('<option value="'+stores[i]['id']+'">'+stores[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    // $('#store').multiselect("destroy").multiselect(options);

                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }

                            // $('#district,#store').multiselect("destroy").multiselect(options);
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });
    });
</script>
<?php echo $this->load('combobox');?>
