<div class="page-header">
    <h1>Shop Inventory</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('timing/partials/report_search_shop_inventory.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="pull-right">
    <strong>Total Store: <?php echo $this->total;?></strong> | 
    <strong>Total Stock: <?php echo $this->total_sales; ?></strong>
</div>
<div class="clearfix"></div>

<div class="table-responsive load-ajax">
    <table class="table table-bordered">
        <thead>
            <tr>
                <?php echo $this->sorting(array(
                        '#',
                        'st_id'      => 'Store ID',
                        'st_name'    => 'Store Name',
                        'st_area'    => 'Area',
                        'st_province'=> 'Province',
                        'st_district'=> 'District',
                        'sale_name'  => 'ASM / Sale',
                        'sale_group' => 'Group',
                        'st_stock'   => 'Stock',
                        'st_sellout' => 'Sellout',
                ),
            $this->url, $this->current_col, $this->desc); ?>
            </tr>
        </thead>
        <tbody>
            <?php 
            if (isset($this->sales) and $this->sales)
                $inc = $this->offset + 1;
                foreach ($this->sales as $sale): ?>
            <tr>
                <td><?php echo $inc++; ?></td>
                <td><?php echo $sale['st_id'];?></td>
                <td><?php echo $sale['st_name'];?></td>
                <td><?php echo $sale['st_area'];?></td>
                <td><?php echo $sale['st_province'];?></td>
                <td><?php echo $sale['st_district'];?></td>
                <td><?php echo $sale['sale_name'];?></td>
                <td><?php echo $sale['sale_group'];?></td>
                <td>
                    <?php 
                    echo !empty($sale['st_stock']) ? 
                        '<span class="badge badge-default" data-type="1" 
                            data-store-id="'.$sale['st_id'].'" 
                            data-from="'.$this->params['from'].'" 
                            data-to="'.$this->params['to'].'" 
                        >'.$sale['st_stock'].'</span>' : '0'; 
                    ?>
                </td>
                <td>
                    <?php echo !empty($sale['st_sellout']) ? 
                        '<span class="badge badge-default" data-type="2" 
                            data-store-id="'.$sale['st_id'].'" 
                            data-from="'.$this->params['from'].'" 
                            data-to="'.$this->params['to'].'" 
                        >'.$sale['st_sellout'].'</span>' : '0'; 
                    ?>
                </td>
            </tr>
            <?php endforeach;?>

        </tbody>
    </table>
</div>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>

<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>
    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {
        multi();

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $modal = $('#modal');
        $('.badge.badge-default').click(function(){
            _self = $(this);
            var type = _self.data('type')
            var tmp = "";

            if (type == 1) { tmp = '/timing/stock-shop-short-report'; }
            if (type == 2) { tmp = '/timing/stock-shop-sellout-short-report'; }
            
            // alert('<?php echo HOST ?>'+tmp);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>'+tmp,
                {
                    store_id        : _self.data('store-id'),
                    from            : _self.data('from'),
                    to              : _self.data('to')
                },
                function(data){
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(3)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
        });

        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#district').change(function(){
            $('.loading').remove();
            $('button, .btn, input').prop('disabled', true);
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var regional_market = $(this).val();
            $.get("<?php echo HOST ?>staff/load-sales-team",
                {district: regional_market}
                ,function(data,status){
                    var obj         = $.parseJSON( data );
                    var stores      = obj.stores;

                    $('#store').find('option').remove();
                    for (var i = 0; i < stores.length; i++) {
                        $('#store').append('<option value="'+stores[i]['id']+'">'+stores[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#store').multiselect("destroy").multiselect(options);

                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }

                            $('#district,#store').multiselect("destroy").multiselect(options);
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });
    });
</script>
<?php echo $this->load('combobox');?>
