<div class="page-header">
    <h1>Stock Shop Timing</h1>
</div>
<style>
	textarea { resize: none; }
</style>

<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<div class="control-group">
	<label for="store_id" class="">Store</label>
	<select id="store_id" name="store_id" class="span4 js-example-basic-single">
		<option value="0">Select</option>
			<?php
            	if ($this->store_list) :
					foreach ($this->store_list as $store):
			?>
						<option value="<?php echo $store->id;?>" <?php if (isset($this->params['store_id']) and $this->params['store_id']==$store->id):?>selected<?php endif;?>><?php echo $store->name;?></option>
			<?php
					endforeach;
				endif;
			?>
	</select>
</div>

<div class="row-fluid">
    <form role="form" id="timing_form" method="get" class="row-fluid" action="">
        <div class="span4">
        	<p>Put IMEI, 1 IMEI per line</p>
        	<textarea name="imei" id="imei" cols="20" rows="10"></textarea>
        </div>
        <div class="clearfix"></div>
        <button id="valid_btn" type="button" class="btn btn-primary">Imei Timing</button>
    </form>
</div>

<div class="row-fluid">
    <div class="span12">
        <div id="result">
            
        </div>
    </div>
</div>
<script>
	$(document).ready(function(){

		$(".js-example-basic-single").select2();


		$('#valid_btn').click(function(){
			_self = $(this);
			_self.nextAll('span').addClass('loading');
			imei = $('#imei').val();
			store_id = $('#store_id').val();

			if (store_id == 0) {
				alert("กรุณาเลือก Store ค่ะ!");
			} else {
				$.post(
					"<?php echo HOST . 'timing/stock-shop-save'?>",
					{
						value : imei,
						store_id : store_id,
						is_check : 1
					},
					function(data){
						$('#result').html( data );

						_self.nextAll('span').removeClass('loading');
				});			
			}

		});

	});
</script>