<div class="page-header">
    <h1>Timing Control</h1>
    <small>ຄວບຄຸມການລາຍງານຍອດ</small>
</div>

<?php
if (isset($this->messages_success) and $this->messages_success)
    foreach ($this->messages_success as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;

    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
        ?>
        
        <div class="accordion" id="accordion2">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                        Search
                    </a>
                </div>
                <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
                    <div class="accordion-inner">
                        <?php
                        echo $this->render('timing/partials/timing-control-search.phtml');
                        ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="pull-right" style="padding-bottom: 15px">
            <div class="span12">
                <a class="btn btn-success" href="/timing/timing-control-add"><i class="icon-plus"></i></a>
            </div>
        </div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>IMEI</th>
                    <th>Product Name</th>
                    <th>Product Color</th>
                    <th>Creator</th>
                    <th>Created Time</th>
                    <th>Allow to verify (Y/N)</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($this->data as $item): ?>
                <tr class="item">
                    <td></td>
                    <td><?php echo $item['imei']; ?></td>
                    <td><?php echo $this->brands[$item['brand_id']]; ?> <?php echo $item['good_name']; ?></td>
                    <td><?php echo $item['color_name']; ?></td>
                    <td><?php echo $item['staff_name']; ?></td>
                    <td><?php echo $item['create_at']; ?></td>
                    <td><span class="btn btn-success"> YES </span>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>

    <?php echo $this->load(); ?>