<table class="table table-bordered">
    <thead>
    <tr>
        <th>No.</th>
        <th>Check In Date</th>
        <th>Area</th>
        <th>Public ID</th>
        <th>Staff Code</th>
        <th>Staff Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Actoin</th>
    </tr>
    </thead>
    <tbody>
    <?php

    $QStaff = new Application_Model_Staff();

    if (isset($this->staff_list) and $this->staff_list)
        foreach ($this->staff_list as $k=>$staff_list): 

            $where = array();
            $where[] = $QStaff->getAdapter()->quoteInto("public_id = ?", $staff_list['public_id']);
            $result = $QStaff->fetchRow($where);
    ?>
            <tr>
                <td>
                    <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                    ?>
                </td>
                <td><?php echo $staff_list['check_in']; ?></td>
                <td><?php echo $staff_list['area_name'];?></td>
                <td><?php echo $staff_list['public_id'];?></td>
                <td><?php echo $result['code'];?></td>
                <td><?php echo $staff_list['staff_name'];?></td>
                <td><?php echo $staff_list['email'];?></td>
                <td><?php echo $staff_list['phone_number'];?></td>
                <td>
                    <a title="View" href="/trainer/pc-first-training-edit?id=<?php echo $staff_list['pft_id'];?>"> <i class="icon-eye-open"></i></a>
                </td>
            </tr>
        <?php endforeach;?>

    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

