<table class="table table-bordered">
    <thead>
    <tr>
        <th style="text-align: center;">No.</th>
        <th style="text-align: center;">Event</th>
        <th style="text-align: center;">Booth</th>
        <th style="text-align: center;">Staff</th>
        <th style="text-align: center;">Check in</th>
        <th style="text-align: center;">Check out</th>
        <th style="text-align: center;">Get Money</th>
        <th style="text-align: center;">Get Food 1</th>
        <th style="text-align: center;">Get Food 2</th>
        <th style="text-align: center;">Work Day</th>
        <th style="text-align: center;">Actoin</th>
    </tr>
    </thead>
    <tbody id="tbView">
    <tbody>
    <?php
//    echo '<pre>';
//    print_r($this->staff_list);
//    echo '</pre>';
    if (isset($this->staff_list) and $this->staff_list)
        foreach ($this->staff_list as $k => $staff_list): ?>
            <tr>
                <td style="text-align: center;">
                    <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                    ?>
                </td>
                <td><?php echo $staff_list['event_name']; ?></td>
                <td style="text-align: center;"><?php echo $staff_list['event_booth']; ?></td>
                <td style="text-align: center;">
                    <?php echo $staff_list['staff_code'].'<br>'.$staff_list['staff_name']; ?>
                </td>
                <td>
                    <div align='center'>
                        <?php
                        $path = "http://api.oppo.in.th/images/oppo_pc_new/" . date("Y", strtotime($staff_list['check_in'])) . "/" . date("Y-m", strtotime($staff_list['check_in'])) . "/" . date("Y-m-d", strtotime($staff_list['check_in'])) . "/" . $staff_list['filepic'];
                        $show_pic = "<a id='single_image' href='" . $path . "'><img src='" . $path . "' height='75' width='75'/></a>";
                        $show_pic .= "<p style='padding-top: 10px;'><span class='label label-success'>Check In</span> : <i class='icon-ok' style='color: #12aa00;'></i> : ".date('d/m/Y H:i', strtotime($staff_list['check_in']))."</p>";
                        echo $show_pic;
                        ?>
                    </div>
                </td>
                <td style="text-align: center;">
                    <?php echo isset($staff_list["check_out"]) ? "<span class='label label-danger'>Check Out</span><p style='margin-top: 10px;'>".date("d/m/Y H:i", strtotime($staff_list["check_out"]))." </p>" : "-"; ?>
                <td>
                    <div align='center'>
                        <?php echo isset($staff_list['events_pay_img']) ? getImgPhoto($staff_list['events_pay_img'], $staff_list['events_pay_at']) : '<p style="color: #F7B240;"><i class="icon-time"></i> Waiting</p>'; ?>
                    </div>
                </td>
                <td>
                    <div align='center'>
                        <?php echo isset($staff_list['events_lunch_img_1']) ? getImgPhoto($staff_list['events_lunch_img_1'], $staff_list['events_lunch_at_1']) : '<p style="color: #F7B240;"><i class="icon-time"></i> Waiting</p>'; ?>
                    </div>
                </td>
                <td>
                    <div align='center'>
                        <?php
                        $lunch_img = ($staff_list['events_lunch_img_2'] == $staff_list['events_lunch_img_1']) ? null : $staff_list['events_lunch_img_2'];
                        echo isset($lunch_img) ? getImgPhoto($staff_list['events_lunch_img_2'], $staff_list['events_lunch_at_2']) : '<p style="color: #F7B240;"><i class="icon-time"></i> Waiting</p>';
                        ?>
                    </div>
                </td>
                <td>
                    <div align='center'>
                        <p><?php echo $staff_list['work_day']; ?></p>
                    </div>
                </td>
                <td style="text-align: center;">
                    <a title="Edit" href="/manage/event-checklist-edit?id=<?php echo $staff_list['id']; ?>"> <i class="icon-eye-open"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url); ?>
</div>

<?php

function getImgPhoto($img_name, $created_at)
{
    $path = "http://api.oppo.in.th/images/oppo_event/" . date("Y", strtotime($created_at)) . "/" . date("Y-m", strtotime($created_at)) . "/" . date("Y-m-d", strtotime($created_at)) . "/" . $img_name;
    $show_pic = "<a id='single_image' href='" . $path . "'><img src='" . $path . "' height='75' width='75'/></a>";
    $show_pic .= "<p style='padding-top: 10px;'><i class='icon-ok' style='color: #12aa00;'></i> : ".date('d/m/Y H:i', strtotime($created_at))."</p>";

    return $show_pic;
}

?>

