<form id="search_form" class="form-search form-horizontal" method="get" action="/manage/event-checklist/event-checklist">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="event_id" class="span2">Event</label>
                <select id="event_id" name="event_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->event) :
                        foreach ($this->event as $event):
                            ?>
                            <option value="<?php echo $event['id'];?>" <?php if (isset($this->params['event_id']) and ( (is_array($this->params['event_id']) && in_array($event['id'], $this->params['event_id']) || $event['id']==$this->params['event_id'])) ):?>selected<?php endif;?>><?php echo $event['name'];?></option>
                            <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
            <div class="control-group">
                <label for="staff_code" class="span2">Staff Code</label>
                <input id="staff_code" name="staff_code" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['staff_code']) and printf($this->params['staff_code']);?>">
            </div>
            <div class="control-group">
                <label for="staff_name" class="span2">Staff Name</label>
                <input id="staff_name" name="staff_name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['staff_name']) and printf($this->params['staff_name']);?>">
            </div>
            <div class="control-group" style="display: none;">
                <label for="chk_bkk" class="span2">Select Only BKK</label>
                <input id="chk_bkk" name="chk_bkk" type="checkbox" value="1" <?php if (isset($this->params['chk_bkk'])) { echo "checked"; } ?>>
            </div>
        </div>
        <div class="span5">

            <div class="control-group">
                <label for="date" class="span2">From</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>
            <div class="control-group">
                <label for="get_money" class="span2">Status Get Money</label>
                <input type="checkbox" name="get_money[]" value="0" <?php if (isset($this->params['get_money']) and ( (is_array($this->params['get_money']) && in_array(0, $this->params['get_money']) )) ):?>checked<?php endif;?>> Get Money &nbsp;
                <input type="checkbox" name="get_money[]" value="1" <?php if (isset($this->params['get_money']) and ( (is_array($this->params['get_money']) && in_array(1, $this->params['get_money']) )) ):?>checked<?php endif;?>> Waiting &nbsp;
            </div>
            <div class="control-group">
                <label for="get_food" class="span2">Status Get Food</label>
                <input type="checkbox" name="get_food[]" value="0" <?php if (isset($this->params['get_food']) and ( (is_array($this->params['get_food']) && in_array(0, $this->params['get_food']) )) ):?>checked<?php endif;?>> Get Money &nbsp;
                <input type="checkbox" name="get_food[]" value="1" <?php if (isset($this->params['get_food']) and ( (is_array($this->params['get_food']) && in_array(1, $this->params['get_food']) )) ):?>checked<?php endif;?>> Waiting &nbsp;
            </div>

            <div class="control-group" style="display: none;">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group" style="display: none;">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>


        </div>
    </div>
    
    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 2,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    function openNewWindow(path, type) {

        $('#search_form').attr('action', path);
        $('#search_form').attr('target', '_blank');
        $('#search_form').submit();

        $('#search_form').attr('action', '/manage/event-checklist/event-checklist');
        $('#search_form').removeAttr("target");

    }

    $(document).ready(function () {

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        multi();
        
        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

    });
</script>