<?php 
    //print_r($this->params);

    if (isset($this->store_acc_list) and $this->store_acc_list) {

        $data = $this->store_acc_list;
        // echo "<pre>"; print_r($data);

        echo "<table class='table table-bordered'>";
        echo    "<thead>";
        echo        "<tr>";
        echo            "<th style='vertical-align:middle;'><div align='center'>No.</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Area</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Store ID</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Store Name</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Store Type</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Model</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Color</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Stock</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Action</div></th>";
        echo        "</tr>";
        echo    "</thead>";
        echo    "<tbody>";

        for ($i=0;$i<count($data);$i++) {

            // Data for List
            $cnt = $i + 1;

            echo    "<tr>";
            echo        "<td width='3%'><div align='center'>".$cnt."</div></td>";
            echo        "<td width='10%'><div align='center'>".$data[$i]['area_name']."</div></td>";
            echo        "<td width='8%'><div align='center'>".$data[$i]['st_id']."</div></td>";
            echo        "<td>".$data[$i]['st_name']."</td>";
            echo        "<td width='15%'><div align='center'>".$data[$i]['st_type']."</div></td>";
            echo        "<td><div align='left'>[".$data[$i]['good_code']."] ".$data[$i]['good_name']."</div></td>";
            echo        "<td width='8%'><div align='center'>".$data[$i]['color_name']."</div></td>";
            echo        "<td width='5%'><div align='right'>".$data[$i]['stock']."</div></td>";
            echo        "<td width='5%'>
                            <div align='center'>
                                <a title='Stock Log' href='".HOST."timing/acc-report-log?store_id=".$data[$i]['st_id']."&good_id=".$data[$i]['good_id']."&color_id=".$data[$i]['color_id']."' >
                                    <i class='icon-eye-open'></i>
                                </a>
                            </div>
                        </td>";
            echo    "</tr>";  

        } 

        echo    "</tbody>";
        echo    "</table>";

    }

?>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">

    $(document).ready(function () {


    });

</script>