<form class="form-search form-horizontal" method="get" action="/timing/acc-report/acc-report">
    <div class="row">
        <div class="span5">

            <div class="control-group">
                <label for="store_id" class="span2">Store ID</label>
                <input id="store_id" name="store_id" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['store_id']) and printf($this->params['store_id']);?>">
            </div>
            <div class="control-group">
                <label for="store_name" class="span2">Store Name</label>
                <input id="store_name" name="store_name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['store_name']) and printf($this->params['store_name']);?>">
            </div>

            <div class="control-group">
                <label for="good_id" class="span2">Model</label>
                <select id="good_id" name="good_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    $data = $this->goods;
                    if ($this->goods) :
                        foreach ($this->goods as $good_list):
                            ?>
                            <option value="<?php echo $good_list['id'];?>" <?php if (isset($this->params['good_id']) and ( (is_array($this->params['good_id']) && in_array($good_list['id'], $this->params['good_id']) || $good_list['id']==$this->params['good_id'])) ):?>selected<?php endif;?>><?php echo $good_list['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="color_id" class="span2">Color</label>
                <select id="color_id" name="color_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    $data = $this->colors;
                    if ($this->colors) :
                        foreach ($this->colors as $color_list):
                            ?>
                            <option value="<?php echo $color_list['id'];?>" <?php if (isset($this->params['color_id']) and ( (is_array($this->params['color_id']) && in_array($color_list['id'], $this->params['color_id']) || $color_list['id']==$this->params['color_id'])) ):?>selected<?php endif;?>><?php echo $color_list['name'];?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

        </div>
        <div class="span5">

            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area['id'];?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="district" class="span2">District</label>
                <select id="district" name="district[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->districts) :
                        foreach ($this->districts as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['district']) and ( (is_array($this->params['district']) && in_array($regional_market['id'], $this->params['district']) || $regional_market['id']==$this->params['district'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-primary">Export Excel</button>
    <!-- <button type="submit" name="export" value="2" class="btn btn-primary">Product Report</button> -->
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        multi();
        
        $('#good_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var good_id = $(this).val();
            
            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/hr-report/load-good-color",
                {good_id: good_id}
                ,function(data,status){  
                    var obj = $.parseJSON( data );
                    $('#color_id').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#color_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    //$('button, .btn, input').prop('disabled', false);
                    $('#color_id').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    //$('button, .btn, input').prop('disabled', false);
                    $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }

                            $('#district,#store').multiselect("destroy").multiselect(options);
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });

    });
</script>