<div class="row-fluid add_casual">
    <div class="span12">
        <label for="keyword">Search</label>
        <div class="input-append">
            <input type="text" placeholder="Email or Staff Code" id="keyword" name="keyword" value="" />  
            <button class="btn btn-info" id="search_btn" type="button"><i class="icon-search"></i></button>
        </div>
        <hr />
        <label for="result">Result - Choose a staff to assign</label>
        <select name="result" id="result" size="4" required></select>

        <label for="area_id">Assign to Area</label>
        <select name="area_id" id="area_id" required>
            <option value>---</option>

            <?php if (isset($this->areas) && $this->areas): ?>
                <?php foreach ($this->areas as $key => $value): ?>
                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                <?php endforeach ?>
            <?php endif ?>
        </select>
        <label for="note">Note</label>
        <textarea name="note" id="note" cols="" rows="4"></textarea>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <button class="btn btn-info" type="button" id="assign_btn">Assign</button>
    </div>
    <div class="span12">
        <p id="result_message"></p>
    </div>
</div>