<?php 
    if(isset($this->staff_id) AND $this->staff_id):
?>
<div class="row-fluid">
    <div class="span12">
        <p><button type="button" class="btn btn-info add_transfer_btn"><i class="icon-plus"></i> Add Transfer...</button></p>
    </div>
</div>

<div class="row-fluid">
    <div class="span12" id="table_transfer_content">
        <!-- ajax load -->
    </div>
</div>

<div id="transfer_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">    
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 id="myModalLabel">Add New Transfer</h3>
            </div>

            <div class="modal-body">
                <form class="" id="form_transfer">

                    <div class="control-group">
                        <label class="control-label">Company</label>
                        <div class="controls">
                            <select name="transfer_company" id="company" class="company" >
                                <option value>---</option>
                                <?php if (isset($this->companies) && $this->companies): ?>
                                    <?php foreach ($this->companies as $key => $value): ?>
                                        <option value="<?php echo $key ?>"
                                            <?php if(isset($this->staff['company_id']) && $this->staff['company_id']==$key) echo "selected" ?>><?php echo $value ?></option>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="area_id" class="control-label">Area</label>
                        <div class="controls">
                            <select class="area_id" name="transfer_area_id" >
                                <option value>Choose</option>
                                <?php
                                if (isset($this->areas) && $this->areas) :
                                    foreach ($this->areas as $_key => $_value):
                                        ?>
                                        <option value="<?php echo $_key ;?>" <?php if ($this->area and $this->area->id == $_key):?>selected<?php endif;?>><?php echo $_value;?></option>
                                    <?php
                                    endforeach;
                                endif;
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">Province</label>
                        <div class="controls">
                            <select name="transfer_regional_market" class="regional_market" >
                                <option value>Choose</option>
                                <?php
                                if ($this->regional_markets) :
                                    foreach ($this->regional_markets as $regional_market):?>
                                        <option value="<?php echo $regional_market->id;?>" <?php if ($this->staff->regional_market==$regional_market->id):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                                    <?php
                                    endforeach;
                                endif;
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">Department</label>
                        <div class="controls">
                            <select name="transfer_department" id="department" class="department" >
                                <option value="">Choose</option>
                                <?php if (isset($this->recursiveDeparmentTeamTitle)): ?>
                                    <?php foreach ($this->recursiveDeparmentTeamTitle as $item_id => $item):?>
                                        <option value="<?php echo $item_id;?>" <?php if (isset($this->staff) and $this->staff and $item_id==$this->staff->department):?>selected<?php endif;?>><?php echo $item['name'];?></option>
                                    <?php endforeach;?>
                                <?php endif ?>
                                
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">Team</label>
                        <div class="controls">
                            <select name="transfer_team" class="team" >
                                <option value>Choose</option>
                                <?php if (isset($this->recursiveDeparmentTeamTitle[$this->staff->department]['children'])): ?>
                                    <?php foreach ($this->recursiveDeparmentTeamTitle[$this->staff->department]['children'] as $item_id => $item):?>
                                        <option value="<?php echo $item_id;?>" <?php if (isset($this->staff) and $this->staff and $item_id==$this->staff->team):?>selected<?php endif;?>><?php echo $item['name'];?></option>
                                    <?php endforeach;?>
                                <?php endif ?>
                            </select>
                            
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="group" class="control-label">Group</label>
                        <div class="controls">
                            <select class="group" name="transfer_group_id" >
                                <option value>----</option>
                                <?php 
                                    if( isset($this->groups) AND $this->groups):
                                        foreach ($this->groups as $_key => $_value):
                                ?>
                                        <option value="<?php echo $_key;?>" <?php if (isset($this->staff['group_id']) and $_key == $this->staff['group_id']):?>selected<?php endif;?>><?php echo $_value;?></option>
                                <?php 
                                        endforeach;
                                    endif;
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="title" class="control-label">Job Title</label>
                        <div class="controls">
                                <select name="transfer_title" class="title" >
                                    <option value>Choose</option>
                                    <?php if (isset($this->recursiveDeparmentTeamTitle[$this->staff->department]['children'][$this->staff->team]['children'])): ?>
                                        <?php foreach ($this->recursiveDeparmentTeamTitle[$this->staff->department]['children'][$this->staff->team]['children'] as $item_id => $item):?>
                                            <option value="<?php echo $item_id;?>" <?php if (isset($this->staff) and $this->staff and $item_id==$this->staff->title):?>selected<?php endif;?>><?php echo $item['name'];?></option>
                                        <?php endforeach;?>
                                    <?php endif ?>
                                </select>
                           <!--  <input type="text" class="title"  placeholder="Enter Last name" name="transfer_title" value="<?php isset($this->staff) and $this->staff and printf($this->staff->title);?>"> -->
                        </div>
                    </div>

                    <div class="control-group">
                        <label for="from_date" class="control-label">From date</label>
                        <div class="controls">
                            <input type="text" name="transfer_from_date" value="<?php echo date('Y-m-d')?>" class="from_date" />
                        </div>
                    </div>

                    <input type="hidden" name="transfer_id" class="transfer_id" value=""/>
                    <input type="hidden" name="region_tmp" class="region_tmp"/>

                </form><!-- end form -->
                <p class="message_error " style="color: red; font-weight: bold; text-align: center"></p>
            </div>

            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-primary"  id="submit_transfer" type="button">Save changes</button>
            </div>
        </div>
    </div>
</div><!-- end -->
<?php endif;?>
<style>
.origin, .origin:hover, .origin:active{
    background: #dff0d8 !important;
}
</style>