<table class="table table-bordered">
    <thead>
    <tr>
        <?php echo $this->sorting(array(
                '#',
                'Action'
            ),
            $this->url, $this->sort, $this->desc); ?>
    </tr>
    </thead>
    <tbody>


    </tbody>
</table>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>
<?php echo $this->load();?>
