<form class="form-search form-horizontal" method="get" onsubmit="return false;">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="name" class="span2">Name</label>
                <input id="name" name="name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
            </div>
            <div class="control-group">
                <label for="email" class="span2">Email</label>
                <input id="email" name="email" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['email']) and printf($this->params['email']);?>">
            </div>
            <div class="control-group">
                <label for="off" class="span2">Working status</label>
                <select name="off" id="off" class="span3">
                    <option value="-1">Choose</option>
                    <option value="1" <?php if (isset($this->params['off']) and $this->params['off']==1):?>selected<?php endif;?>>On work</option>
                    <option value="2" <?php if (isset($this->params['off']) and $this->params['off']==2):?>selected<?php endif;?>>Off</option>
                </select>
            </div>
            

            <div class="control-group">
                <label for="is_officer" class="span2">Is Head Office</label>
                <select name="is_officer" id="is_officer" class="span3">
                    <option value>Choose</option>
                    <option value="1" <?php if (isset($this->params['is_officer']) and $this->params['is_officer']==1):?>selected<?php endif;?>>Is Head Office</option>
                    <option value="2" <?php if (isset($this->params['is_officer']) and $this->params['is_officer']==2):?>selected<?php endif;?>>No</option>
                </select>
            </div>

            <div class="control-group">
                <label for="myTags" class="span2">Tags</label>
                <ul class="form-control span3" id="myTags"><?php
                    if (isset($this->params['tags']) and $this->params['tags']):
                        foreach ($this->params['tags'] as $ta)
                            echo '<li>'.$ta.'</li>';
                    endif;
                    ?></ul>
            </div>

        </div>
        <div class="span5">
            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="department" class="span2">Department</label>
                <select name="department[]" id="department" class="span3 multiselect" multiple="multiple">
                    <?php foreach ($this->departments as $id=>$item):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['department']) and ( (is_array($this->params['department']) && in_array($id, $this->params['department']) || $id==$this->params['department'])) ):?>selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="control-group">
                <label for="team" class="span2">Team</label>
                <!--<input id="team" name="team" type="text" class="input-large search-query form-control" value="<?php /*isset($this->params['team']) and printf($this->params['team']);*/?>">-->
                <select name="team[]" id="team" class="span3 multiselect" multiple="multiple">
                    <?php foreach ($this->teams as $id=>$item):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['team']) and ( (is_array($this->params['team']) && in_array($id, $this->params['team']) || $id==$this->params['team'])) ):?>selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary" id="btn_search">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>