<form class="form-search form-horizontal" method="get" action="/timing/store-focus/store-focus">
    <div class="row">
        <div class="span5">
	       <div class="control-group">
                <label for="store_id" class="span2">Store ID</label>
                <input id="store_id" name="store_id" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['store_id']) and printf($this->params['store_id']);?>">
            </div>
            <div class="control-group">
                <label for="store_name" class="span2">Store Name</label>
                <input id="store_name" name="store_name" type="text" class="input-medium search-query form-control" value="<?php isset($this->params['store_name']) and printf($this->params['store_name']);?>">
            </div>

            <div class="control-group">
                <label for="oppo_product_id" class="span2">OPPO</label>
                <select id="oppo_product_id" name="oppo_product_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->oppo_product_list) :
                        foreach ($this->oppo_product_list as $oppo_product_list):
                            ?>
                            <option value="<?php echo $oppo_product_list['id'];?>" <?php if (isset($this->params['oppo_product_id']) and ( (is_array($this->params['oppo_product_id']) && in_array($oppo_product_list['id'], $this->params['oppo_product_id']) || $oppo_product_list['id']==$this->params['oppo_product_id'])) ):?>selected<?php endif;?>><?php echo $oppo_product_list['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="huawei_product_id" class="span2">Huawei</label>
                <select id="huawei_product_id" name="huawei_product_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->huawei_product_list) :
                        foreach ($this->huawei_product_list as $huawei_product_list):
                            ?>
                            <option value="<?php echo $huawei_product_list['id'];?>" <?php if (isset($this->params['huawei_product_id']) and ( (is_array($this->params['huawei_product_id']) && in_array($huawei_product_list['id'], $this->params['huawei_product_id']) || $huawei_product_list['id']==$this->params['huawei_product_id'])) ):?>selected<?php endif;?>><?php echo $huawei_product_list['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="vivo_product_id" class="span2">VIVO</label>
                <select id="vivo_product_id" name="vivo_product_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->vivo_product_list) :
                        foreach ($this->vivo_product_list as $vivo_product_list):
                            ?>
                            <option value="<?php echo $vivo_product_list['id'];?>" <?php if (isset($this->params['vivo_product_id']) and ( (is_array($this->params['vivo_product_id']) && in_array($vivo_product_list['id'], $this->params['vivo_product_id']) || $vivo_product_list['id']==$this->params['vivo_product_id'])) ):?>selected<?php endif;?>><?php echo $vivo_product_list['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="samsung_product_id" class="span2">Samsung</label>
                <select id="samsung_product_id" name="samsung_product_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->samsung_product_list) :
                        foreach ($this->samsung_product_list as $samsung_product_list):
                            ?>
                            <option value="<?php echo $samsung_product_list['id'];?>" <?php if (isset($this->params['samsung_product_id']) and ( (is_array($this->params['samsung_product_id']) && in_array($samsung_product_list['id'], $this->params['samsung_product_id']) || $samsung_product_list['id']==$this->params['samsung_product_id'])) ):?>selected<?php endif;?>><?php echo $samsung_product_list['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

        </div>
        <div class="span5">

            <div class="control-group">
                <label for="date" class="span2">From</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>

            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area['id'];?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="district" class="span2">District</label>
                <select id="district" name="district[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->districts) :
                        foreach ($this->districts as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['district']) and ( (is_array($this->params['district']) && in_array($regional_market['id'], $this->params['district']) || $regional_market['id']==$this->params['district'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <!-- <div class="control-group">
                <label for="status_id" class="span2">Status</label>
                <select id="status_id" name="status_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->status_list) :
                        foreach ($this->status_list as $status):
                            ?>
                            <option value="<?php echo $status['id'];?>" <?php if (isset($this->params['status_id']) and ( (is_array($this->params['status_id']) && in_array($status['id'], $this->params['status_id']) || $status['id']==$this->params['status_id'])) ):?>selected<?php endif;?>><?php echo $status['name'];?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div> -->


        </div>
    </div>
    

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-primary">Export Excel</button>

</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 2,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        multi();
        
        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    //$('button, .btn, input').prop('disabled', false);
                    $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }

                            $('#district,#store').multiselect("destroy").multiselect(options);
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });
/*
        $('#brand_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var brand_id = $(this).val();

            $('.btn, input').prop('readonly', true);
            $('button').prop('disabled', true);
            //$('button, .btn, input').prop('disabled', true);
            $.get("/ajax/load-competitor-product",
                {brand_id: brand_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#product_id').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#product_id').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.btn, input').prop('readonly', false);
                    $('button').prop('disabled', false);
                    //$('button, .btn, input').prop('disabled', false);
                    $('#product_id').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });
*/
        
    });
</script>