<div class="page-header">
    <form action="/" method="get">
        <h1>List Notification</h1>
        <div class="row">
            <div class="span12">
                <p class="pull-right">
                    <a href="<?php echo HOST ?>manage/notification-mass-upload" class="btn btn-info"><i class="icon-list"></i> Mass Upload</a> 
                    <a href="<?php echo HOST ?>manage/notification-create" class="btn btn-success"><i class="icon-plus"></i> Create</a>
                </p>
            </div>
        </div>
    </form>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('manage/notification/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php
    echo $this->render('manage/notification/partials/list.phtml');
    ?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>
<?php echo $this->confirm();?>