<style>
    iframe {
        width: 100%;
        height: 155px;
        scrolling: no;
        seamless: seamless;
        overflow: hidden;
    }

    .bar {
        line-height: 18px;
    }

    textarea {
        width: 100%;
        max-width: 100%;
        min-height: 200px;
    }

    select {
        max-width: 100%;
    }
</style>

<div class="page-header">
    <h1>Notification <small>Mass Upload</small></h1>
</div>

<div class="row-fluid">
    <div class="span12">
        <form action="<?php echo HOST ?>manage/notification-mass-upload-save" id="form" target="iframe" class="form-inline" method="post" enctype="multipart/form-data">
            <div class="row-fluid">
                <div class="span12">
                    <p class="pull-right">
                        <input type="hidden" name="id" id="id" value="<?php if (isset($this->notification['id'])) echo $this->notification['id'];?>">
                        <button type="submit" id="submit_btn" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-danger" onclick="window.location='<?php echo HOST ?>manage/notification'">Go back</button>
                    </p>
                </div>
            </div>
            
            <div class="row-fluid">
                <div class="span12">
                    <iframe src="" frameborder="0" name="iframe" id="iframe"></iframe>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span6">
                    <div class="control-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control span6" id="title" name="title" required="required" value="<?php if (isset($this->notification)): echo $this->notification->title; endif;?>">
                    </div>
                </div>

                <div class="span3">
                    <?php echo $this->render('manage/notification/partials/select-category.phtml') ?>
                </div>
                <div class="span3">
                    <div class="control-group">
                        <label for="file" class="control-label">Data File</label>
                    <input type="file" class="form-control" name="file" id="file" required />
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span12">
                    <div class="control-group">
                        <label for="content">Content</label>
                        <textarea name="content" id="content" required></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>

    
</div>

<?php echo $this->render('manage/notification/partials/new-category-modal.phtml') ?>

<script src="<?php echo HOST ?>js/ckeditor.js"></script>
<script src="<?php echo HOST ?>js/jsrender.min.js"></script>

<script id="alert_div" type="text/x-jsrender">
    <div class="alert alert-{{:type}}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{:message}}
    </div>
</script>

<script>
config = {};
config.toolbar = [
    { name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] },
    { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] },
    { name: 'about', items: [ 'Source' ] },
    '/',

    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
    { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] },
    { name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
    '/',
    { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
    { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
    { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
    { name: 'others', items: [ '-' ] }
];

config.enterMode = CKEDITOR.ENTER_BR;
config.shiftEnterMode = CKEDITOR.ENTER_P;

    CKEDITOR.replace( 'content' , config);
</script>

<script language="javascript" type="text/javascript" src="/js/manage.notification.category.js"></script>
<script>
    function confirmExit() {
        return "Mass upload is processing...";
    }

    function set_progress(percent) {
        $('.bar').css('width', percent+'%');
        $('.bar').html(percent+'%');
    }

    $(document).ready(function () {
        $('form').bind('submit',function(e){
            $('.bar').css('width', '0%');
            $('.bar').html('');

            if (typeof $('#iframe').get(0).contentWindow.clear_content != "undefined")
                $('#iframe').get(0).contentWindow.clear_content();

            $('form button, form input, form select').prop('readonly', true);
            $('.loading').remove();
            $(this).after('<span class="pre_loading">Processing </span><span class="loading"></span>');
            window.onbeforeunload = confirmExit;
        });
    });
</script>