<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<form action="<?php echo HOST ?>manage/sub-area" class="form-horizontal form-search" method="get">
    <div class="control-group">
        <label class="control-label" for="name">Name : </label>
        <div class="controls">
            <input type="text" name="name" value="<?php if(isset($this->params['name']) && $this->params['name']) echo $this->params['name'] ?>">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="staff_id">Staff : </label>
        <div class="controls">
            <select name="staff_id" id="staff_id">
                <option value> Choose </option>
                <?php if (isset($this->staffs) && $this->staffs): ?>
                    <?php foreach ($this->staffs as $key => $value): ?>
                        <option value="<?php echo $value['staff_id'] ?>" <?php if(isset($this->params['staff_id']) && $this->params['staff_id'] == $value['staff_id']): ?> selected <?php endif; ?> >[<?php echo $value['staff_code'] ?>] <?php echo $value['staff_name'] ?></option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>
        </div>
    </div>  

    <div class="control-group">
        <label class="control-label"> Status : </label>
        <div class="controls">
            <select name="status" id="status"> 
                <option value="">Please Selected</option>
                <option value="1" <?php if(isset($this->params['status']) && $this->params['status'] == 1): ?> selected <?php endif; ?> > Active </option>
                <option value="2" <?php if(isset($this->params['status']) && $this->params['status'] == 2): ?> selected <?php endif; ?> > Disable </option>
            </select>
        </div>
    </div>      

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-info">Search</button>
            <button type="reset" class="btn btn-warning">Reset</button>
        </div>
    </div>    
</form>

<script type="text/javascript">
    $('#staff_id').select2();
</script>