<form action="<?php echo HOST ?>manage/district" class="form-horizontal form-search" method="get">
    <div class="control-group">
        <label class="control-label" for="name">Name</label>
        <div class="controls">
            <input type="text" name="name" value="<?php if(isset($this->params['name']) && $this->params['name']) echo $this->params['name'] ?>">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="province">Province</label>
        <div class="controls">
            <select name="province" id="province">
                <option value>---</option>
                <?php if (isset($this->provinces) && $this->provinces): ?>
                    <?php foreach ($this->provinces as $key => $value): ?>
                        <option value="<?php echo $key ?>"
                            <?php if(isset($this->params['parent']) && $this->params['parent'] == $key) echo 'selected' ?>><?php echo $value ?></option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>
        </div>
    </div>        

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-info">Search</button>
            <button type="reset" class="btn btn-warning">Reset</button>
        </div>
    </div>    
</form>