<div class="page-header">
    <h1>Analytics <small>Overall</small></h1>
</div>
<button type="button" class="btn btn-primary show-as-image" title="Save chart as image" data-name="chart_by_area">Save Chart As</button>
<div id="chart_by_area"></div>
<div id="view-content">
	<table class="table">
		<?php foreach ($this->staffs as $key => $v): ?>
			<tr>
				<?php foreach ($v as $key => $value): ?>
					<td><?php if(isset($value)) echo $value; else echo "0"; ?></td>
				<?php endforeach ?>
			</tr>
		<?php endforeach ?>
	</table>
	<p>Total: <?php if(isset($this->sum)) echo $this->sum ?></p>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);
      var chart;
      var data;

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        // data = new google.visualization.DataTable();
        // data.addColumn('string', 'Area');
        // data.addColumn('number', 'PG');
        // data.addColumn('number', 'Sales');
        // data.addColumn('number', 'Sales Admin');
        // data.addColumn('number', 'Training');
     
        sdata = $.parseJSON('<?php echo $this->out; ?>');
		data = google.visualization.arrayToDataTable(sdata);
        // data.addRows(sdata);
        // var view = new google.visualization.DataView(data);
        // view.setColumns([0,1,2,3,4]);

        // Set chart options
        var options = {
						'title' : 'Staff Analytics',
						'height' : 750,
						hAxis : {title: 'Department', titleTextStyle: {color: 'red'}}
                   };

        // Instantiate and draw our chart, passing in some options.
        chart = new google.visualization.ColumnChart(document.getElementById('chart_by_area'));
        chart.draw(data, options);

        // google.visualization.events.addListener(chart, 'select', selectHandler);
      }

      // function selectHandler(e) {
      //   var item = chart.getSelection()[0];
      //   var region = data.getFormattedValue( item.row, 1 );
      //   window.location = '<?php echo HOST . "staff/analytics?regional_market=" ?>' + region;
      // }

      $(document).ready(function () {
          $( '.show-as-image' ).click(function (){
              // grChartImg.ShowImage('chart', true);
              l = grChartImg.GetImageData( $(this).data('name') );
              a = document.createElement('a');
              a.style.display = 'none';
              a.href = l;
              a.download = "chart.png";
              a.click();
          });
      });
</script>
<script type="text/javascript" src="/js/canvg/canvg.js"></script>
<script type="text/javascript" src="/js/canvg/rgbcolor.js"></script>
<script type="text/javascript" src="/js/grChartImg.js"></script>