<div class="page-header">
    <h1>Overall Analytics</h1>
</div>
<div id="view-content">
    <button type="button" class="btn-primary show-as-image" data-name="chart_by_area" title="Save chart as image">Save Chart As</button>
    <span>Tổng số NV: <?php echo $this->sum ?></span>
  <div id="chart_by_area"></div>
  <button type="button" class="btn-primary show-as-image" data-name="chart" title="Save chart as image">Save Chart As</button>
	<div id="chart"></div>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);
      var chart;
      var data;

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        data = new google.visualization.DataTable();
        data.addColumn('string', 'Vùng kinh doanh');
        data.addColumn('number', 'ID');
        data.addColumn('number', 'Số NV');
        sdata = '<?php echo $this->data; ?>';
        sdata = $.parseJSON('<?php echo $this->data; ?>');

        data.addRows(sdata);
        var view = new google.visualization.DataView(data);
        view.setColumns([0,2]);

        // Set chart options
        var options = {'title':'Staffs Analytics by Regional Market',
                       'width':1000,
                       'height':2000,
                     'chartArea': {'height': '95%'}
                   };

        // Instantiate and draw our chart, passing in some options.
        chart = new google.visualization.BarChart(document.getElementById('chart'));
        chart.draw(view, options);

        google.visualization.events.addListener(chart, 'select', selectHandler);
///////////////////////////////////
        // Create the data table.
        data2 = new google.visualization.DataTable();
        data2.addColumn('string', 'Area');
        data2.addColumn('number', 'ID');
        data2.addColumn('number', 'Số NV');
        sdata2 = $.parseJSON('<?php echo $this->data2; ?>');

        data2.addRows(sdata2);
        var view2 = new google.visualization.DataView(data2);
        view2.setColumns([0,2]);

        // Set chart options
        var options2 = {'title':'Staffs Analytics by Area',
                       'width':1000,
                       'height':600
                   };

        // Instantiate and draw our chart, passing in some options.
        chart2 = new google.visualization.PieChart(document.getElementById('chart_by_area'));
        chart2.draw(view2, options2);
      }

      function selectHandler(e) {
        var item = chart.getSelection()[0];
        var region = data.getFormattedValue( item.row, 1 );
        window.location = '<?php echo HOST . "staff/analytics?regional_market=" ?>' + region;
      }

      $(document).ready(function () {
          $( '.show-as-image' ).click(function (){
              // grChartImg.ShowImage('chart', true);
              l = grChartImg.GetImageData( $(this).data('name') );
              a = document.createElement('a');
              a.style.display = 'none';
              a.href = l;
              a.download = "chart.png";
              a.click();
          });
      });
</script>
<script type="text/javascript" src="/js/canvg/canvg.js"></script>
<script type="text/javascript" src="/js/canvg/rgbcolor.js"></script>
<script type="text/javascript" src="/js/grChartImg.js"></script>