<div class="page-header">
    <h1>Staff <small>Assign to Company</small></h1>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
            <?php
            if (isset($this->companies) and $this->companies)
                foreach ($this->companies as $k=>$company): ?>
            <tr>
                <td>
                    <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                    ?>
                </td>
                <td><a href="<?php echo HOST ?>staff/company-edit?id=<?php echo $company['id'] ?>"><?php echo $company['name'];?></a></td>
            </tr>
            <?php endforeach;?>

        </tbody>
    </table>
</div>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>