`<style>
    #myTags {
        margin: 0;
        height: 7em;
    }

    .table_list {
        counter-reset: rowNumber;
    }

    .table_list tbody tr {
        counter-increment: rowNumber;
    }

    .table_list tbody tr td:first-child::before {
        content: counter(rowNumber);
        min-width: 1em;
        margin-right: 0.5em;
    }

    table {
        padding-bottom: 20px;
        margin-bottom: 20px;
        border-bottom: 1px solid white;
    }
    
    table caption {
        font-weight: bold;
        font-style: italic;
        font-size: 16px;
    }

    .approval {
        border-top: 2px solid #ccc;
        padding: 5px;
        height: 2em;
        background: rgba(0, 186, 139, 0.25);
        width: 57%;
    }

    .approval .new_value {
        line-height: 2em;
        height: 2em;
        overflow: hidden;
        display: inline-block;
        background: none;
        border: none;
        box-shadow: none;
        padding: 0;
    }

    .text-warning {
        color: #b94a48;
    }
    body{
        font-family: phetsarath ot;
    }
</style>


<div class="page-header">
    <?php if (isset($this->staff) and $this->staff):?>
        <h1>Edit Staff ແກ້ໄຂພະນັກງານ</h1>
    <?php else:?>
        <h1>Create Staff ເພີ່ມພະນັກງານ</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<?php echo $this->render('staff/partials/form.phtml'); ?>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script src="../js/tag-it.min.js" type="text/javascript" charset="utf-8"></script>
<link href="../css/jquery.tagit.css" rel="stylesheet" type="text/css">
<link href="../css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">

<?php echo $this->confirm();?>
<script type="text/javascript">

    $.fn.extend({
        ajax_validate : function(url, param, form) { // param: [{name:'param_name', element: form_element}, {name:'param_name', element: form_element}]
            _self = $(this);
            is_checking = false;

            _self.blur(function(e){
                if (is_checking || _self.val()=='') return;
                is_checking = true;

                _s = $(e.target);

                var get_url = '';
                get_url = url;
                get_url += '?';

                for (var i = 0; i < param.length; i++) {
                    get_url += param[i].name + '=' + param[i].element.val() + '&';
                };

                if (_s.next('.loading').length == 0) {
                    _s.after('<span class="loading"></span>');
                    _s.parent().removeClass('error');
                    _s.nextAll('.help-inline').remove();
                }

                $('button[type=submit]').prop('disabled', true);
                $('form').bind('submit',function(e){e.preventDefault();});

                $.get(get_url, function(data,status){
                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');

                    _s.nextAll('.loading').remove();
                    if (data == 1 || data == -1) {
                        _s.parent().addClass('error');
                        _s.after('<span class="help-inline">Invalid</span>');
                        form.bind("submit", function(){
                            return false;
                        });
                    } else {
                        form.unbind("submit");
                    }
                    is_checking = false;
                });
            });
        }
    });

    checkPCStandBy();
    function checkPCStandBy() {
        if ( $("#group").val() == <?php echo PGPB_ID; ?> ) {
            $("#pc_stand_by").prop("disabled", false);
        } else {
            $("#pc_stand_by").prop("disabled", true);
        }
    }

    function initTag(){
/*
        $('#myTags').tagit({
            allowSpaces: true,
            fieldName: 'tags[]',
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: "<?php echo HOST;?>ajax/get-tags"
            }
        });
*/
    }

    function checkNotHeadOffice(department_id, team_id, title_id){
        var JSONString = '<?php echo json_encode(unserialize(CONFIG_NOT_HEAD_OFFICE));?>';
        var $arrNotHeadOffice = JSON.parse(JSONString);

        for (var key in $arrNotHeadOffice) {
            if ($arrNotHeadOffice[key] == department_id)
                return true;

            if (typeof $arrNotHeadOffice[key] === 'object'){
                for (var key2 in $arrNotHeadOffice[key]){
                    if (key2 == team_id){
                        for (var key3 in $arrNotHeadOffice[key][key2]){
                            if (key3 == title_id){
                                return true;
                            }
                        }
                    }
                }
            }

        }
        return false;
    }

    function initSelectHeadOffice(){
        var _is_head_office = $('#is_officer');
        if (typeof _is_head_office !== 'undefined'){
            var $isNotHeadOffice = checkNotHeadOffice($('#department').val(), $('#team').val(), $('#title').val());
            if ($isNotHeadOffice){
                _is_head_office.removeAttr('checked');
            } else{
                _is_head_office.attr('checked', 'checked');
            }
        }
    }

    $(document).ready(function () {

        initTag();
        initPreview();


        $('#group,.group').change(function(){
            var val = parseInt($('#group').val(),10);
            var val2 = [4, 5, 9, 17, 25];

            if(jQuery.inArray(val, val2) != -1) {
                $("#shirt_size").prop('required',true);
            } else {
                $("#shirt_size").prop('required',false);
            }
        });

        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
        $( '.from_date' ).datepicker({ dateFormat: "yy-mm-dd" });
        $('#btn-change-pass').click(function(){
            $('#password').toggleClass('hidden');
            if ($('#change-pass').val()==1)
                $('#change-pass').val(0);
            else
                $('#change-pass').val(1);
        });

        var url = "<?php echo HOST.'staff/check' ?>";
        var codes1 = [
            {name: 'id', element: $('#id')},
            {name: 'code', element: $('#code')}
        ];
        var codes2 = [
            {name: 'id', element: $('#id')},
            {name: 'email', element: $('#email')}
        ];
        $('#code').ajax_validate(url, codes1, $('#form'));
        $('#email').ajax_validate(url, codes2, $('#form'));

        $('#area_id,.area_id').change(function(){
        	$('button[type=submit]').prop('disabled', true);
        	$('form').bind('submit',function(e){e.preventDefault();});

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();

            select_company();

            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market,.regional_market').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market,.regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button[type=submit]').prop('disabled', false);
                    $('form').unbind('submit');
                    _self.nextAll('.loading').remove();
                }).done(function(){
                updateSelectedRegion();
            });
            updateSelectedRegion();
        });

        $('#department,.department').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');

            //auto select is head office
            initSelectHeadOffice();

            var _self = $(this);
            var department_id = $(this).val();
            $('form').bind('submit',function(e){e.preventDefault();});
            $('button, .btn, input, select').prop('disabled', true);
            $.get("/ajax/load-team",
                {department_id: [department_id]}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#team,.team').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#team,.team').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input, select').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });
        });

        $('#team,.team').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');

            //auto select is head office
            initSelectHeadOffice();

            var _self = $(this);
            var team_id = $(this).val();
            $('form').bind('submit',function(e){e.preventDefault();});
            $('button, .btn, input, select').prop('disabled', true);
            $.get("/ajax/load-title",
                {team_id: [team_id]}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#title,.title').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#title,.title').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input, select').prop('disabled', false);
                    $('form').unbind('submit');
                    $('.loading').remove();
                });
        });

        $('#title').change(function(){
            //auto select is head office
            initSelectHeadOffice();
        });

        $('form').bind('submit',function(e){
        	$('button[type=submit]').prop('disabled', true);
        });

        $('.province').change(load_district);
        
        $('.add_education_btn').click(load_add_education);
        $('.item .edit_btn').click(show_edit_edu);
        
        $('.add_experience_btn').click(load_add_experience);
        $('.item .edit_exp_btn').click(show_edit_exp);
        
        $('.add_relative_btn').click(load_add_relative);
        $('.item .edit_rlt_btn').click(show_edit_rlt);

        $('.copy_to_birth_btn').click(copy_to_birth);

        $(".confirmLink").click(delete_item);

        $('.add_transfer_btn').click(add_transfer);
        
        $('#team, #is_officer').change(select_company);

        $('#group, #group').change();

        initTransfer();
        <?php 
            if(isset($this->staff_id) AND $this->staff_id):
        ?>
        loadTableTransfer(<?php echo $this->staff_id;?>)
        <?php 
            endif;
        ?>
        $('#ID_number').on('keyup', do_check_id_card_number);

    });

    var check_id_timeout;

    function do_check_id_card_number(e) {
        window.clearTimeout(check_id_timeout);

        check_id_timeout = window.setTimeout(function() {
            var id_number = $('#ID_number').val().trim();
            var staff_id = $('#ID_number').data('id');
            check_id_card_number(id_number, staff_id);
        }, 500);
    }

    function check_id_card_number(id_number, staff_id) {
        $('#id_card_validate').html('');

        $.ajax({
            url: '<?php echo HOST ?>ajax/check-id-number',
            type: 'post',
            dataType: 'html',
            data: {id_number: id_number, id: staff_id},
        })
        .done(function(html) {
            console.log("success");

            if (html) $('#id_card_validate').html(html);
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            console.log("complete");
        });
        
    }

    function load_district(e) {
        $('.loading').remove();

        _self = $(e.target);
        province_id = _self.val();

        console.log(province_id);

        if (province_id) {
            _self.after('<span class="loading"></span>');
            $('button, input, select, textarea').prop('disabled', true);
            $('form').bind('submit',function(e){e.preventDefault();});

            $.ajax({
                url: '<?php echo HOST ?>ajax/get-district-cbb',
                type: 'post',
                dataType: 'json',
                data: {region: province_id},
            })
            .done(function(data) {
                console.log("success");
                district_cbb = _self.parents('fieldset').find('.district')
                district_cbb.find('option:not(:first)').remove();

                try {
                    for (index in data) {
                        district_cbb.append('<option value="'+data[index]['id']+'">'+data[index]['name']+'</option>');
                    }
                } catch (err) {}
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                console.log("complete");

                $('button, input, select, textarea').prop('disabled', false);
                $('form').unbind('submit');
                $('.loading').remove();
            });
            
        }
    }
    /////////////////////////////////
    function load_add_education(e) {
        $('.education_list tbody').append(education_div);
        //$('.add_education_btn').unbind('click').prop('disabled', true);
        $('#alert').text('').fadeOut();

        $('.item.new .save_btn').click(save_edu);
        $('.item.new .cancel_btn').click(cancel_edu);
        $('.item.new .edit_btn').click(show_edit_edu);

        $('.item.new').removeClass('new');
        //Kiểm tra
        initCheckDefaultLevel();
    }

    function save_edu(e) {
        _item = $(e.target).parents('.item');

        $('.loading').remove();
        $('#alert').text('').fadeOut();
        
        id             = _item.find('.education_id').val();
        staff_id       = _item.find('.staff_id').val();
        level          = _item.find('.level').val();
        school         = _item.find('.school').val();
        field_of_study = _item.find('.field_of_study').val();
        graduated_year = _item.find('.graduated_year').val();
        grade          = _item.find('.grade').val();
        mode_of_study  = _item.find('.mode_of_study').val();

        if (staff_id) {
            _item.find('input, button').prop('disabled', true);
            _item.find('td').last().append('<span class="loading"></span>');

            $.ajax({
                url: '<?php echo HOST ?>ajax/staff-edu-save',
                type: 'post',
                dataType: 'json',
                data: {
                    id             : id,
                    staff_id       : staff_id,
                    level          : level,
                    school         : school,
                    field_of_study : field_of_study,
                    graduated_year : graduated_year,
                    grade          : grade,
                    mode_of_study  : mode_of_study
                },
            })
            .done(function(data) {
                console.log("success");

                try {
                    $('.loading').remove();
                    $('.add_education_btn').bind('click', load_add_education).prop('disabled', false);

                    if (data && typeof data.result !== "undefined" && data.result && data.id) {
                        _item.find('.level_txt').text( level );
                        _item.find('.school_txt').text( school );
                        _item.find('.field_of_study_txt').text( field_of_study );
                        _item.find('.graduated_year_txt').text( graduated_year );
                        _item.find('.grade_txt').text( grade );
                        _item.find('.mode_of_study_txt').text( mode_of_study );

                        _item.find('.education_id').val( data.id );

                        _item.find('input, button').prop('disabled', false);
                        _item.find('input').hide();
                        _item.find('button').unbind('click').hide();
                        _item.find('.edit_btn').show();
                        _item.find('.edit_btn').click(show_edit_edu);
                        _item.find(".confirmLink").click(delete_item);
                        _item.find('.editable').show();

                    } else if (data && typeof data.error != 'undefined') {
                        $('#alert').text(data.error).fadeIn();
                    }
                } catch(err){ console.log (err); }
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                console.log("complete");
            });
            
        }

    }

    function show_edit_edu(e) {
        _item = $(e.target).parents('.item');
        $('.loading').remove();
        $('#alert').text('').fadeOut();

        $('.add_education_btn').unbind('click').prop('disabled', true);

        _item.find('input').show();
        _item.find('.editable').hide();
        _item.find('button, .confirmLink').unbind('click').hide();
        _item.find('.save_btn').click(save_edu).show();
        _item.find('.cancel_btn').click(cancel_edu).show();

        $('.item').removeClass('new');

    }

    function cancel_edu(e) {
        _item = $(e.target).parents('.item');

        id = _item.find('.education_id').val();
        $('#alert').text('').fadeOut();

        if (id) {
            _item.find('input').hide();
            _item.find('.editable').show();
            _item.find('button').unbind('click').hide();
            _item.find('.edit_btn').click(show_edit_edu).show();
            _item.find(".confirmLink").click(delete_item);
        } else {
            _item.remove();
        }       

        $('.add_education_btn').bind('click', load_add_education).prop('disabled', false);
    }
    /////////////////////////////////
    function load_add_experience(e) {
        $('.experience_list tbody').append(experience_div);
        //$('.add_experience_btn').unbind('click').prop('disabled', true);
        $('#alert').text('').fadeOut();

        $('.item.new .save_exp_btn').click(save_exp);
        $('.item.new .cancel_exp_btn').click(cancel_exp);
        $('.item.new .edit_exp_btn').click(show_edit_exp);
        $('.item.new .date').datepicker({ dateFormat: "dd/mm/yy" });

        $('.item.new').removeClass('new');
    }

    function save_exp(e) {
        _item = $(e.target).parents('.item');

        $('.loading').remove();
        $('#alert').text('').fadeOut();
        
        id                 = _item.find('.experience_id').val();
        staff_id           = _item.find('.staff_id').val();
        company_name       = _item.find('.company_name').val();
        job_position       = _item.find('.job_position').val();
        from_date          = _item.find('.from_date').val();
        to_date            = _item.find('.to_date').val();
        reason_for_leaving = _item.find('.reason_for_leaving').val();

        if (staff_id) {
            _item.find('input, button').prop('disabled', true);
            _item.find('td').last().append('<span class="loading"></span>');

            $.ajax({
                url: '<?php echo HOST ?>ajax/staff-exp-save',
                type: 'post',
                dataType: 'json',
                data: {
                    id                 : id,
                    staff_id           : staff_id,
                    company_name       : company_name,
                    job_position       : job_position,
                    from_date          : from_date,
                    to_date            : to_date,
                    reason_for_leaving : reason_for_leaving,
                },
            })
            .done(function(data) {
                console.log("success");

                try {
                    $('.loading').remove();
                    $('.add_experience_btn').bind('click', load_add_experience).prop('disabled', false);
                    
                    if (data && typeof data.result !== "undefined" && data.result && data.id) {
                        _item.find('.company_name_txt').text( company_name );
                        _item.find('.job_position_txt').text( job_position );
                        _item.find('.from_date_txt').text( from_date );
                        _item.find('.to_date_txt').text( to_date );
                        _item.find('.reason_for_leaving_txt').text( reason_for_leaving );
                        _item.find('.epxerience_id').val( data.id );
                        _item.find('input, button').prop('disabled', false);
                        _item.find('input').hide();
                        _item.find('button').unbind('click').hide();
                        _item.find('.edit_exp_btn').show();
                        _item.find(".confirmLink").click(delete_item);
                        _item.find('.edit_exp_btn').click(show_edit_exp);
                        _item.find('.editable').show();

                    } else if (data && typeof data.error != 'undefined') {
                        $('#alert').text(data.error).fadeIn();
                    }
                } catch(err){ console.log (err); }
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                console.log("complete");
            });
            
        }

    }

    function show_edit_exp(e) {
        _item = $(e.target).parents('.item');
        $('.loading').remove();
        $('#alert').text('').fadeOut();

        $('.add_experience_btn').unbind('click').prop('disabled', true);

        _item.find('input').show();
        _item.find('.editable').hide();
        _item.find('.edit_exp_btn, .confirmLink').unbind('click').hide();
        _item.find('.save_exp_btn').click(save_exp).show();
        _item.find('.cancel_exp_btn').click(cancel_exp).show();

        $('.item').removeClass('new');

    }

    function cancel_exp(e) {
        _item = $(e.target).parents('.item');
        $('#alert').text('').fadeOut();

        id = _item.find('.experience_id').val();

        if (id) {
            _item.find('input').hide();
            _item.find('.editable').show();
            _item.find('.save_exp_btn, .cancel_exp_btn').unbind('click').hide();
            _item.find('.edit_exp_btn').click(show_edit_exp).show();
            _item.find(".confirmLink").click(delete_item);
        } else {
            _item.remove();
        }       

        $('.add_experience_btn').bind('click', load_add_experience).prop('disabled', false);
    }
    /////////////////////////////////
    function load_add_relative(e) {
        $('.relative_list tbody').append(relative_div);
        //$('.add_relative_btn').unbind('click').prop('disabled', true);

        $('.item.new .save_rlt_btn').click(save_rlt);
        $('.item.new .cancel_rlt_btn').click(cancel_rlt);
        $('.item.new .edit_rlt_btn').click(show_edit_rlt);
        $('#alert').text('').fadeOut();

        $('.item.new').removeClass('new');
    }

    function save_rlt(e) {
        _item = $(e.target).parents('.item');

        $('.loading').remove();
        $('#alert').text('').fadeOut();

        id            = _item.find('.relative_id').val();
        staff_id      = _item.find('.staff_id').val();
        relative_type = _item.find('.relative_type').val();
        gender        = _item.find('.gender:checked').val();
        full_name     = _item.find('.full_name').val();
        birth_year    = _item.find('.birth_year').val();
        job           = _item.find('.job').val();
        work_place    = _item.find('.work_place').val();

        if (staff_id) {
            _item.find('select, input, button').prop('disabled', true);
            _item.find('td').last().append('<span class="loading"></span>');

            $.ajax({
                url: '<?php echo HOST ?>ajax/staff-relative-save',
                type: 'post',
                dataType: 'json',
                data: {
                    id            : id,
                    staff_id      : staff_id,
                    relative_type : relative_type,
                    gender        : gender,
                    full_name     : full_name,
                    birth_year    : birth_year,
                    job           : job,
                    work_place    : work_place
                },
            })
            .done(function(data) {
                console.log("success");

                try {
                    $('.loading').remove();
                    $('.add_relative_btn').bind('click', load_add_relative).prop('disabled', false);

                    if (data && typeof data.result !== "undefined" && data.result && data.id) {
                        _item.find('.full_name_txt').text( full_name );
                        _item.find('.job_txt').text( job );
                        _item.find('.work_place_txt').text( work_place );
                        _item.find('.birth_year_txt').text( birth_year );
                        _item.find('.relative_type_txt').text( _item.find('.relative_type option:selected').text() );
                        _item.find('.gender_txt').text( parseInt(gender) ? 'Male' : 'Female' );

                        _item.find('.relative_id').val( data.id );

                        _item.find('input, button, select').prop('disabled', false);
                        _item.find('input, select, .gender').hide();
                        _item.find('button').unbind('click').hide();
                        _item.find('.edit_rlt_btn').show();
                        _item.find('.edit_rlt_btn').click(show_edit_rlt);
                        _item.find(".confirmLink").click(delete_item);
                        _item.find('.editable').show();

                    } else if (data && typeof data.error != 'undefined') {
                        $('#alert').text(data.error).fadeIn();
                    }
                } catch(err){ console.log (err); }
            })
            .fail(function() {
                console.log("error");
            })
            .always(function() {
                console.log("complete");
            });
            
        }

    }

    function show_edit_rlt(e) {
        _item = $(e.target).parents('.item');
        $('.loading').remove();
        $('#alert').text('').fadeOut();

        $('.add_relative_btn').unbind('click').prop('disabled', true);

        _item.find('input, select, label').show();
        _item.find('.editable').hide();
        _item.find('.edit_rlt_btn, .confirmLink').unbind('click').hide();
        _item.find('.save_rlt_btn').click(save_rlt).show();
        _item.find('.cancel_rlt_btn').click(cancel_rlt).show();

        $('.item').removeClass('new');

    }

    function cancel_rlt(e) {
        _item = $(e.target).parents('.item');
        $('#alert').text('').fadeOut();

        id = _item.find('.relative_id').val();

        if (id) {
            _item.find('input, select, label').hide();
            _item.find('.editable').show();
            _item.find('.save_rlt_btn, .cancel_rlt_btn').unbind('click').hide();
            _item.find('.edit_rlt_btn').click(show_edit_rlt).show();
            _item.find(".confirmLink").click(delete_item);
        } else {
            _item.remove();
        }       

        $('.add_relative_btn').bind('click', load_add_relative).prop('disabled', false);
    }
    /////////////////////////////////
    function delete_item(e) {
        e.preventDefault();
        $('#alert').text('').fadeOut();
        
        var targetUrl = $(this).attr("href");

        $("#dialog").dialog({
            buttons : {
                "Confirm" : function() {
                    $('.loading').remove();
                    _item = $(e.target).parents('.item');
                    _item.find('button').prop('disabled', true);
                    _item.find('td').last().append('<span class="loading"></span>');
                    $("#dialog").dialog("close");

                    $.ajax({
                        url: targetUrl,
                        type: 'get',
                        dataType: 'json'
                    })
                    .done(function(data) {
                        console.log("success");

                        $('.loading').remove();
                        _item.find('button').prop('disabled', false);

                        if (data && typeof data.result !== "undefined" && data.result) {
                            _item.remove();
                            _item = $(e.target).parents('.item');
                        } else if (data && typeof data.error != 'undefined') {
                            $('#alert').text(data.error).fadeIn();
                        }
                    })
                    .fail(function() {
                        console.log("error");
                    })
                    .always(function() {
                        console.log("complete");
                    });
                    
                },
                "Cancel" : function() {
                    $(this).dialog("close");
                }
            }
        });

        $("#dialog").dialog("open");
    }

    /////////////////////////////////

    function copy_to_birth() {
        $('#birth_ward').val( $('#perm_ward').val() );
        $('#birth_province').val( $('#perm_province').val() );
        $('#birth_district').html( $('#perm_district').html() );
        $('#birth_district').val( $('#perm_district').val() );
    }

    function add_transfer(e) {
        $('.message_error').html('');
        $('#transfer_modal .transfer_id').val('');
        $('#myModalLabel').html('Add New Transfer')
        $('#transfer_modal').modal('show');
    }

    function load_log_info(e) {
        _item  = $(e.target).parents('.item');
        parent = $(e.target).parents('td');
        type   = $(e.target).val();
        staff  = _item.find('.staff_id').val();

        $('.loading').remove();
        parent.nextAll('td').html('');
        parent.append('<span class="loading"></span>');

        $.ajax({
            url: '<?php echo HOST ?>partition/staff-transfer',
            type: 'post',
            dataType: 'html',
            data: {type : type, staff : staff},
        })
        .done(function(html) {
            console.log("success");
            parent.nextAll('td').remove();
            parent.after(html);
            _item.find( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
            $('.save_transfer_btn').click(save_transfer);
            $('.cancel_transfer_btn').click(cancel_transfer);
            $('.loading').remove();
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            console.log("complete");
        });
        
    }

    function save_transfer() {
        var staff_id        = '<?php echo $this->staff_id;?>';
        var company         = $("#transfer_modal .company").val();
        var area_id         = $('#transfer_modal .area_id').val();
        var regional_market = $('#transfer_modal .regional_market').val();
        var department      = $("#transfer_modal .department").val();
        var team            = $("#transfer_modal .team").val();
        var from_date       = $("#transfer_modal .from_date").val();
        var group           = $("#transfer_modal .group").val();
        var title           = $("#transfer_modal .title").val();
        var transfer_id     = $("#transfer_modal .transfer_id").val();
        var params = {'staff_id':staff_id,'company':company,'area_id':area_id,'regional_market':regional_market,
            'department':department,'team':team,'from_date':from_date, 'group':group,'title':title,'transfer_id':transfer_id
        };
        $.ajax({
            type: 'get',
            url: "<?php echo HOST.'staff/save-transfer';?>",
            data: params,
            dataType: 'json',
            success: function(data){
                if(data.status == 0){
                    $(".message_error").html('ERROR: '+data.message);
                }else{
                    loadTableTransfer(staff_id);
                    $('#transfer_modal').modal('hide');

                    //update basic form
                    $('#department').val(department);
                    $('#team').val(team);
                    $('#status').val(status);
                    $('#area_id').val(area_id);
                    $('#regional_market').val(regional_market);
                    $('#company_id').val(company);
                    $("#group").val(group);
                    $("#title").val(title);
                    $('#transfer_modal').modal('hide');

                }
            }
        });
    }

    ////////////////////////////////
    function select_company(e) {
        team       = $('#team').val()*1;
        area       = $('#area_id').val()*1;
        is_officer = $('#is_officer').attr('checked');

        if (team && area) {
            var area_arr = [1,4,7,10,13,24,25,26,32,33,34,40,41,43];
            var team_arr = [75,119,16];
            
            if (area_arr.indexOf(area) > -1 && team_arr.indexOf(team) > -1 && !is_officer) {
                $('#company_id').val(2);
            } else {
                $('#company_id').val(1);
            }
        }

    }

    function updateTransfer(e){
        var transfer_id = $(this).attr('data-transfer');
        $('#myModalLabel').html('Update Transfer')
        $.ajax({
            type: 'get',
            url: '<?php echo HOST.'ajax/get-transfer-info'?>',
            data: {'transfer_id': transfer_id},
            dataType: 'json',
            success: function(data){
                if(data.code == 1){
                    alert(data.message);
                }else{
                    $("#transfer_modal .company").val(data.result.company);
                    $("#transfer_modal .area_id").val(data.result.area);
                    $("#transfer_modal .region_tmp").val(data.result.region);
                    $('.area_id').trigger('change');
                    //$("#transfer_modal .regional_market").val(data.result.region);
                    $("#transfer_modal .department").val(data.result.department);
                    $("#transfer_modal .team").val(data.result.team);
                    $("#transfer_modal .group").val(data.result.group);
                    $("#transfer_modal .title").val(data.result.title);
                    $("#transfer_modal .from_date").val(data.result.from_date);
                    $("#transfer_modal .transfer_id").val(transfer_id);
                    $('.message_error').html('');
                    $('#transfer_modal').modal('show');
                }
            }
        });
    }

    function deleteTransfer(e){
        e.preventDefault();
        var staff_id   = '<?php echo $this->staff_id;?>';
        var _this = $(this);
        var link = $(this).attr('href');
        $("#dialog").dialog({
            buttons:{
                'Ok':function(){
                    $.ajax({
                        type: 'get',
                        url: link,
                        success:function(data){
                            if(data.code == 1){
                                alert(data.message);
                            }else{
                                loadTableTransfer(staff_id);
                                console.log(data.message);
                            }
                        }
                    });
                    $(this).dialog('close');
                },
                'Cancel':function(){
                    $(this).dialog('close');
                }
            }
        });
        $("#dialog").dialog("open");
    }

    function initTransfer(){
        $('#submit_transfer').click(save_transfer);
        $(".edit_transfer").click(updateTransfer);
        $(".del_transfer").click(deleteTransfer);

    }

    function updateSelectedRegion(){
        $("#transfer_modal .regional_market").val($("#transfer_modal .region_tmp").val());
    }

    function loadTableTransfer(staff_id){
        $.ajax({
            type: 'get',
            url: '<?php echo HOST.'ajax/load-table-transfer'?>',
            data:{'staff_id':staff_id},
            success: function(data){
                $("#table_transfer_content").html(data);
                $(".edit_transfer").click(updateTransfer);
                $(".del_transfer").click(deleteTransfer);
            }
        });
    }

    function initPreview(){
        $('.has-preview').change(function (){
            readURL($(this));
        });
    }

    function readURL(jqueryObject) {
        var input = $(jqueryObject).get(0);

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $(jqueryObject).next('.gen-img-preview').remove();
                $(jqueryObject).after('<img class="gen-img-preview" width="150" height="150" />');
                $(jqueryObject).next('.gen-img-preview').attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    checkSizeIDCard();
    function checkSizeIDCard(){
        $("#id_photo,#id_photo_back").change(function(){
            var _this = $(this);
            var iSize = ($(this)[0].files[0].size / 1024);
            if(iSize > 2048){
                _this.replaceWith(_this = _this.clone(true));
                iSize = (Math.round(iSize / 1024 * 100) / 100);
                var mess = '<div><p>Image size must be less than 2MB, current file size is: '+iSize +' Mb</p></div>';
                $(mess).dialog({
                    title: 'Confirm',
                    resizable: false,
                    buttons: {
                        'Ok':function(){
                            $(this).dialog('close');
                        }
                    }
                });
            }
        });
    }

    initCheckDefaultLevel();
    function initCheckDefaultLevel(){
        $('#form').submit(function(e){
            
            var num = $('.default_level').length;
            if(num >= 1){
                var check = 0;
                $('.default_level').each(function(){
                    if($(this).val() == 1){
                        check = 1;
                    }
                });
                if(check == 0){
                    $("<div><p>Please select default level</p></div>").dialog({
                        title: 'Confirm',
                        resizable: false,
                        buttons: {
                            'Ok':function(){
                                $(this).dialog('close');
                                $('button[type=submit]').prop('disabled', false);
                            }
                        }
                    });
                    return false;
                }
            }
            
        });

        $('.default_level').change(function(){
            var _this = $(this);
            if(_this.val() == 1){
                $(".default_level").val(0);
                _this.val(1);
            }
        })
    }

</script>
<?php echo $this->load('combobox');?>
