<div class="page-header">
    <?php if (isset($this->staff) and $this->staff):?>
        <h1>Edit Staff</h1>
    <?php else:?>
        <h1>Create Staff</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<form role="form" id="form" class="form-horizontal" method="post" enctype="multipart/form-data">

    <div class="row-fluid">
        <div class="span12">
            <?php if (isset($this->currentStaff) and $this->currentStaff): ?>
                <legend>
                    <?php if (isset($this->currentStaff['firstname'])) echo $this->currentStaff['firstname'] ?> <?php if (isset($this->currentStaff['lastname'])) echo $this->currentStaff['lastname'] ?>
                    -
                    <small>
                        <?php $info = array(); ?>
                        <?php if (isset($this->currentStaff['code'])) $info[] = $this->currentStaff['code'] ?>
                        <?php if (isset($this->currentStaff['gender']) && $this->currentStaff['gender']) $info[] = "Male"; else $info[] = "Female"; ?>
                        <?php if (isset($this->currentStaff['email'])) $info[] = $this->currentStaff['email'] ?>
                        <?php echo implode(' - ', $info) ?>
                    </small>

                    <?php
                    $stt = '';
                    switch ($this->currentStaff['status']) {
                        case My_Staff_Status::On:
                            $stt = 'success';
                            break;
                        case My_Staff_Status::Off:
                            $stt = 'important';
                            break;
                        case My_Staff_Status::Temporary_Off:
                            $stt = 'warning';
                            break;
                        default:
                            $stt = 'default';
                            break;
                    }
                    ?>
                    <span class="label label-<?php echo $stt ?>"><?php echo My_Staff_Status::get($this->currentStaff['status']) ?></span>
                </legend>

            <?php endif ?>

        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <p class="pull-right">
                <input type="hidden" name="staff_id" id="staff_id" value="<?php echo ((isset($this->currentStaff['id']) and $this->currentStaff['id']) ? $this->currentStaff['id'] : '') ;?>">

                <button type="submit" class="btn btn-primary">Submit</button>

                <input type="hidden" name="back_url" id="back_url" value="<?php if ( isset($this->back_url) and $this->back_url) echo $this->back_url;?>">
                <a href="<?php echo ((isset($this->back_url) and $this->back_url) ? $this->back_url : '/staff/list-basic') ?>" class="btn btn-danger go-back">Go back</a>
            </p>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span4">
            <div class="control-group">
                <label for="photo" class="control-label">Staff Photo</label>
                <div class="controls">
                    <?php if(isset($this->currentStaff) and !empty($this->currentStaff['photo'])){?>
                        <a target="_blank" title="View" href="<?php printf(HOST.'photo/staff/'.$this->currentStaff['id'].'/'.$this->currentStaff['photo']);  ?>"><img class="staff-photo" src="<?php printf(HOST.'photo/staff/'.$this->currentStaff['id'].'/'.$this->currentStaff['photo']);  ?>" /></a>
                    <?php }?>
                    <div class="clear"></div>
                    <input type="file" id="photo" name="photo" class="has-preview" />
                    <div class="clear"></div>
                    <div class="control-group">
                        <label for="del_photo" class="pull-left">Delete Photo</label>
                        <input type="checkbox" class="pull-left" name="del_photo" id="del_photo" />
                    </div>
                </div>
            </div>

        </div>
    </div>

</form>


<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script type="text/javascript" src="/js/jquery.qtip.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.qtip.min.css"/>

<?php echo $this->confirm();?>
<script type="text/javascript">
    function initPreview(){
        $('.has-preview').change(function (){
            readURL($(this));
        });
    }

    function readURL(jqueryObject) {
        var input = $(jqueryObject).get(0);

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $(jqueryObject).next('.gen-img-preview').remove();
                $(jqueryObject).after('<img class="gen-img-preview" width="150" height="150" />');
                $(jqueryObject).next('.gen-img-preview').attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function checkSizePhoto(){
        $("#photo").change(function(){
            var _this = $(this);
            var iSize = ($(this)[0].files[0].size / 1024);
            if(iSize > 2048){
                _this.replaceWith(_this = _this.clone(true));
                iSize = (Math.round(iSize / 1024 * 100) / 100);
                var mess = '<div><p>Image size must be less than 2MB, current file size is: '+iSize +' Mb</p></div>';
                $(mess).dialog({
                    title: 'Confirm',
                    resizable: false,
                    buttons: {
                        'Ok':function(){
                            $(this).dialog('close');
                        }
                    }
                });
            }
        });
    }

    $(document).ready(function () {
        initPreview();
        checkSizePhoto();
    });

</script>
<?php echo $this->load('combobox');?>
