<div class="page-header">
    <?php if (isset($this->dashboard) and $this->dashboard):?>
        <h1>Edit Dashboard</h1>
    <?php else:?>
        <h1>Create Dashboard</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>
<div class="row-fluid">
    <div class="span12">
        
        <form role="form" id="form" action="<?php echo HOST.'config/dashboard-save';?>" method="post">
            <div class="row-fluid">
                <div class="span6">
                    <div class="row-fluid">
                        <div class="control-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control span3" id="name" name="name" required="required" value="<?php if (isset($this->dashboard['name'])): echo $this->dashboard['name']; endif;?>">
                        </div>
                    </div>
                    
                    <div class="row-fluid">
                        <div class="control-group">
                            <label for="content">Description</label>
                            <textarea name="description" class="span3" id="description" rows="5"><?php if(isset( $this->dashboard['description'] )) echo $this->dashboard['description'] ?></textarea>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="control-group">
                            <label for="table">Table</label>
                            <input type="text" class="form-control span3" id="table" name="table" required="required" value="<?php if (isset($this->dashboard['table'])): echo $this->dashboard['table']; endif;?>">
                        </div>
                    </div>
                    
                    <div class="row-fluid">
                        <div class="control-group">
                            <label for="cols_existed">Columns Existed</label>
                            <textarea name="cols_existed" class="span3" id="cols_existed" rows="5"><?php if(isset( $this->dashboard['cols_existed'] )) echo $this->dashboard['cols_existed'] ?></textarea>
                        </div>
                    </div>
                    
                    <div class="row-fluid">
                        <div class="control-group">
                            <label for="cols_needed">Columns Needed</label>
                            <textarea name="cols_needed" class="span3" id="cols_needed" rows="5"><?php if(isset( $this->dashboard['cols_needed'] )) echo $this->dashboard['cols_needed'] ?></textarea>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="control-group">
                            <p>
                            	<span>
                            		Allow Edit: <input type="checkbox" name="editable" id="editable" value="1" <?php if(isset( $this->dashboard['editable'] ) && $this->dashboard['editable'] == 1) echo 'checked="checked"' ?> />
                            	</span>
                            </p>
                        </div>
                        <div class="control-group">
                            <p>
                            	<span>
                            		Allow Note: <input type="checkbox" name="add_note" id="add_note" value="1" <?php if(isset( $this->dashboard['add_note'] ) && $this->dashboard['add_note'] == 1) echo 'checked="checked"' ?> />
                            	</span>
                            </p>
                        </div>
                        <div class="control-group">
                            <p>
                            	<span>
                            		Allow Email: <input type="checkbox" name="add_email" id="add_email" value="1" <?php if(isset( $this->dashboard['add_email'] ) && $this->dashboard['add_email'] == 1) echo 'checked="checked"' ?> />
                            	</span>
                            </p>
                        </div>
                        <div class="control-group">
                            <p>
                            	<span>
                            		In Use: <input type="checkbox" name="status" id="status" value="1" <?php if(isset( $this->dashboard['status'] ) && $this->dashboard['status'] == 1) echo 'checked="checked"' ?> />
                            	</span>
                            </p>
                        </div>
                    </div>

                </div>

                <div class="span6">
                    <div class="row-fluid">
                        <div class="span3">
                        	<div class="control-group">
	                            <label for="group_ids">Notify Groups:</label>
	                            <?php foreach ( $this->groups as $id=>$name ): ?>
	                            <p>
	                                <span><input <?php if ( isset($this->group_ids) and in_array($id, $this->group_ids) ): ?> checked<?php endif;?> type="checkbox" name="group_ids[]" value="<?php echo $id;?>"><?php echo $name;?></span>
	                            </p>
	                            <?php endforeach;?>
	                        </div>
                        </div>
                        <div class="span9">
                    		<div class="row-fluid">
                            	<label for="group_ids">Notify Staffs:</label>
                        	</div>
                    		<div class="row-fluid">
		                        <select name="pg_name" id="pg_name" class="span12" size="15" multiple="multiple">
		                            <?php if ($this->staffs): ?>
		                            <?php foreach ($this->staffs as $k=>$staff): ?>
		                                <option value="<?php echo $staff->id ?>"><?php echo $staff->firstname . ' ' . $staff->lastname. ' | '. preg_replace('/oppomobile.vn/', '', $staff['email']) .  (isset($this->regional_market_all[$staff['regional_market']]) ? (' | ' . $this->regional_market_all[$staff['regional_market']] ): '') ?></option>
		                            <?php endforeach ?>
		                            <?php endif ?>
		                        </select>
		                        
		                        <input id="pic" name="pic" type="hidden" value="" />
                        	</div>
                    		<div class="row-fluid">
			                    <div class="control-group">
			                        <button id="remove_pg_btn" class="btn btn-danger pull-right" type="button">Remove</button>
			                    </div>
                        	</div>
                        </div>
                    </div>  
                    <div class="row-fluid">
                    	<div class="span12">
		                    <div class="row-fluid">
			                    <legend>Search</legend>
			                </div>
			                <div class="row-fluid">
			                    <div class="control-group">
			                        <label for="s_name">Staff Name</label>
			                        <input type="text" class="form-control span6" id="s_name" placeholder="Enter Staff name then press ENTER" name="s_name" />
			                    </div>
			                </div>
			                <div class="row-fluid">
			                    <div class="control-group">
			                        <label for="">Result</label>
			                        <div class="load-ajax">
			                            <?php echo $this->partial('staff/partials/searchname.phtml',array()); ?>
			                        </div>
			                    </div>
			                </div>
			                <div class="row-fluid">
			                    <div class="control-group">
			                        <button id="add_pg_btn" class="btn btn-success pull-right" type="button">Add Staff</button>
			                    </div>
			                </div> 
		                </div>
                    </div>  
                </div>
                
            </div>
            <div class="row-fluid">
                <input type="hidden" name="id" id="id" value="<?php isset($this->dashboard) and $this->dashboard and printf($this->dashboard['id']);?>">
                <button type="submit" id="submit_btn" class="btn btn-primary">Submit</button>
                <input type="hidden" name="back_url" id="back_url" value="<?php isset($this->back_url) and $this->back_url and printf($this->back_url);?>">
                <button type="button" class="btn btn-danger go-back">Go back</button>
            </div>

        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });

        $( "#s_name" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();
                $('.loading').remove();
                var _self = $(this);
                var targetUrl = '<?php echo HOST."staff?sname=1&name=" ?>' + $('#s_name').val();

                //get ajax content
                var aj = _self.parent().parent().next().find('.load-ajax');
                if (aj.length){
                    _self.after("<span class=\'loading\'></span>");
                    $.get(targetUrl
                        ,function(data,status){
                            aj.html(data);
                            _self.next('.loading').remove();
                        });
                }

                return false;
            }
        });

        $('#add_pg_btn').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists( $(item[i]).attr('value'), false) ) {
                    _des = $('#pg_name');
                    _des.append(item[i]);
                }
            }
        });

        $('#remove_pg_btn').click(function(){
            _self = $('#pg_name');
            item = _self.children('option:selected').remove();

            _name = $('#pg_name option');
            id_str = '';

            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }

            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);
        });

        $('#form').submit(function(event){
            event.preventDefault();
            _name = $('#pg_name option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);

            $(this).unbind( event );

            //submit
            $(this).submit();

        });

        
    });

	function is_exists(id, is_leader) {
        if(is_leader) {
            _des = $('#leader_name');
        } else {
            _des = $('#pg_name');
        }

        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }
</script>
