<div class="row-fluid">
    <div class="span9">
        <div class="control-group">
            <label for="title">Title</label>
            <input type="text" class="form-control span9" id="title" name="title" required="required" value="<?php if (isset($this->inform)): echo $this->inform->title; endif;?>">
        </div>
    </div>
    <div class="span3">
        <div class="control-group">
            <label for="content">Category</label>
            <select name="category" id="category" class="form-control">
                <option value>---</option>
                <?php if (isset($this->category_string_cache) && $this->category_string_cache): ?>
                    <?php foreach ($this->category_string_cache as $key => $value): ?>
                        <option value="<?php echo $key ?>"
                                <?php if (isset($this->inform['category_id']) && $this->inform['category_id'] == $key) echo "selected" ?>><?php 
                                echo $value ?></option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>
            <button class="btn btn-default btn-mini" id="add_category_btn" type="button"><i class="icon-plus"></i></button>
        </div>
    </div>   
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="control-group">
            <label for="content">Content</label>
            <textarea name="content" id="content"><?php isset($this->inform) and print($this->inform->content);?></textarea>
        </div>
    </div>
</div>

<div id="modal_new_category" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newCategoryLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="newCategoryLabel">Add new category</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    <label for="category_name">Name</label>
                    <input type="text" name="category_name" id="category_name" class="form-control">
                </div>
            </div>            
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" type="button" id="save_category_btn">Save</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
</div>



<div class="upload_files">
    <div class="row-fluid file_list">
        <?php if (isset($this->files) && $this->files): ?>
            <?php foreach ($this->files as $key => $value): ?>
                <div class="span2 file_item">
                    <?php $hash = hash("sha256", md5($this->userStorage->id) . $value['name'] . $value['id']); ?>
                    <?php $src = HOST . 'download/inform?id='. $value['id'] . '&filename='. $value['name'].'&hash='. $hash ?>

                    <a href="<?php echo $src ?>" class="thumbnail">
                        <?php if ( preg_match('/\.(jpg)|(png)|(jpeg)$/', $value['name']) ): ?>
                            <img src="<?php echo $src ?>" alt="<?php echo $value['file_display_name'] ?>">
                        <?php else: ?>
                            <span><i class="icon-file"></i></span>
                        <?php endif ?>
                    </a>
                    <p class="attachment_name"><?php echo $value['file_display_name'] ?></p>
                </div>
            <?php endforeach ?>
        <?php endif ?>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <div class="control-group">
                <label class="control-label" for="">Attach Files</label>
                <div class="controls">
                    <p><strong>Kích thước file phải nhỏ hơn 5MB</strong></p>
                    <div class="file-uploader"></div>
                    <input type="hidden" name="photo" />
                    <input type="hidden" class="onprogress" />
                    <p class="help-block"></p>
                </div>
            </div>
        </div>
    </div>
</div>