<div class="page-header">
    <h1>Distributor Day of Inventory (DOI) for Executive</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a id="search_bar" class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('timing/distributor-doi-ex/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div align="right">
    <strong> DOI : <?php echo $this->params['doi_rate']." / Day"; ?></strong>
</div>

<div class="table-responsive">
    <?php echo $this->render('timing/distributor-doi-ex/partials/list.phtml'); ?>
</div>

