<div class="page-header">
    <h3>
        Confirm Order
    </h3>
</div>
<div class="row-fluid">
    <div class="span12">
        <iframe name="iframe" id="iframe" width="100%" frameBorder="0" height="0"></iframe>
        <form class="form-inline" method="post" action="/trainer/do-confirm-order" target="iframe">
            <div class="row-fluid">
                <div class="span12">
                    <div class="widget widget-nopad">
                        <div class="widget-header"> <i class="icon-list-alt"></i>
                            <h3>CONFIRM ORDER</h3>
                        </div>
                        <div class="widget-content">
                            <div class="widget big-stats-container">
                                <div class="widget-content">
                                    <?php
                                      echo $this->render('/trainer/partials/view-detail-order.phtml');
                                    ?>
                                    <div class="pull-right">
                                        <div class="span2">
                                            <input type="submit" value="Confirm" class="btn btn-primary"/>
                                            <a class="btn btn-danger" href="<?php echo $this->back_url;?>">Go Back</a>
                                            <input type="hidden" name="order_id" value="<?php echo (isset($this->order_id)and $this->order_id) ? $this->order_id:''?>"
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>