<div class="page-header">
    <?php if (isset($this->notification) and $this->notification): ?>
        <h1>Edit Push Notification</h1>
    <?php else: ?>
        <h1>Create Push Notification</h1>
    <?php endif; ?>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">' . $message . '</div>';
    endforeach;
// print_r($this->notification);
?>
<div class="row">
    <div class="row-fluid">
        <form role="form" id="form" enctype="multipart/form-data"
              action="<?php echo HOST . 'trainer/push-notification-save'; ?>" method="post">
            <div class="span6">
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="name">Title</label>
                        <input type="text" class="span6" id="title" name="title" required="required"
                               value="<?php if (isset($this->notification)): echo $this->notification->title; endif; ?>">
                    </div>

                    <div class="row-fluid">
                        <div class="control-group">
                            <label for="content">Message text</label>
                            <textarea name="message_text" id="message_text" rows="10" style="width: 100%;"><?php if (isset($this->notification)): echo $this->notification->message; endif; ?></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="image">Upload Image</label>
                        <?php if (isset($this->notification->file_link) && ($this->notification->file_link != '')): ?>
                            <a target="_blank" title="View" href="/<?php echo 'trainer/' . $this->notification->file_link; ?>">
                                <img class="staff-photo" src="<?php echo HOST.'trainer/' . $this->notification->file_link; ?>" width="40%"></a>
                        <?php endif; ?>
                        <input type="file" class="span6" name="file_link"/>
                        <input type="hidden" name="file_edit"
                               value="<?php if (isset($this->notification)): echo $this->notification->file_link; endif; ?>"/>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="form-group">
                        <label>Status</label>
                        <div class="radio">
                            <label>
                                <input type="radio" name="action_status" value="1" <?php if (isset($this->notification) && ($this->notification->action == '1')): echo "checked"; else: echo "checked"; endif; ?>>Drafts
                            </label>
                        </div>
                        <div class="radio">
                            <label>
                                <input type="radio" name="action_status" value="2" <?php if (isset($this->notification) && ($this->notification->action == '2')): echo "checked"; endif;?>>Send
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="back_url" id="back_url"
                   value="<?php isset($this->back_url) and $this->back_url and printf($this->back_url); ?>">
            <input type="hidden" name="id" id="id"
                   value="<?php isset($this->notification) and $this->notification and printf($this->notification->id); ?>">
                <div class="clearfix">
            <div class="span12 control-group" style="padding-bottom: 1em; padding-top: 1em">
                    <button id="add_btn" class="btn btn-primary" type="submit"><i class="icon-check"></i> Submit</button>
            </div>
            <div class="clearfix">
        </form>
    </div>
</div>
