<?php  $orderOut = $this->order_out; ?>
<div class="page-header">
    <?php if($orderOut and isset($orderOut)):?>
        <h3>EDIT ORDER OUT</h3>
    <?php else: ?>
        <h3>CREATE OUTPUT ORDER</h3>
    <?php endif;?>
</div>
<div class="row-fluid">
    <div class="span12">
        <iframe name="iframe" id="iframe" width="100%" frameBorder="0" height="0"></iframe>
        <form class="form-inline" action="/trainer/save-order-out" method="post" target="iframe">
            <div class="widget widget-nopad">
                <div class="widget-header"> <i class="icon-list-alt"></i>
                    <?php if($orderOut and isset($orderOut)):?>
                        <h3>EDIT ORDER OUT</h3>
                    <?php else: ?>
                        <h3>CREATE OUTPUT ORDER</h3>
                    <?php endif;?>
                </div>
                <div class="widget-content">
                    <div class="widget big-stats-container">
                        <div class="widget-content">
                            <div id="row-detail">
                                <?php if($orderOut and isset($orderOut)) :  foreach($orderOut as $key => $value):?>
                                    <div class="row-order-detail">
                                        <table class="table table-responsive">
                                            <tr>
                                                <?php if($key ==0):?>
                                                <td class="span1">Date</td>
                                                <td class="span3">
                                                    <input type="text" name="date" class="date" required="required" value="<?php echo (isset($this->date) and $this->date)? $this->date:'' ?>"/>
                                                </td>
                                                <?php endif;?>
                                                <td class="span2">
                                                    Type Asset
                                                </td>
                                                <td class="span4" <?php echo ($key !=0)? 'colspan="3"':null?>>
                                                    <div class="span4">
                                                        <select id="asset" name="asset[]" required="required">
                                                            <option value="">Please select</option>
                                                            <?php if($this->type_asset) foreach($this->type_asset as $k => $val):?>
                                                                <option value="<?php echo $k;?>" <?php if(isset($value['asset_id']) and $value['asset_id'] == $k):?> selected <?php endif;?>> <?php echo $val;?></option>
                                                            <?php endforeach;?>
                                                        </select>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="span1">Quantity</td>
                                                <td class="span3">
                                                    <input type="number" name="quantity[]" required="required" value="<?php echo (isset($value['quantity']) and $value['quantity'])? $value['quantity']:'' ?>"/>
                                                </td>
                                                <td class="span2">Note</td>
                                                <td class="span4">
                                                    <textarea name="note[]"><?php echo (isset($value['note']) and $value['note'])? $value['note']:'' ?></textarea>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="span2">Output To Trainer</td>
                                                <td class="span3" colspan="3">
                                                    <select name="output_to_staff_id[]" required="required">
                                                        <option value="">Select</option>
                                                        <?php if($this->list_trainer) foreach($this->list_trainer as $k => $val):?>
                                                            <option value="<?php echo $k;?>" <?php if(isset($value['output_to_staff_id']) and $value['output_to_staff_id'] == $k):?> selected <?php endif;?>> <?php echo $val;?></option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="4">
                                                    <div class="pull-right">
                                                        <input type="button" value="+" class="btn btn-primary add_order_out"/>
                                                        <?php if($key !=0):?>
                                                        <input type="button" value="-" class="btn btn-danger remove_order_out"/>
                                                        <?php endif;?>
                                                        <input type="hidden" name="ids[]" value="<?php echo (isset($value['id']) and $value['id'])? $value['id']:'' ?>" />
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                <?php endforeach;?>
                                <?php else:?>
                                    <div class="row-order-detail">
                                        <table class="table table-responsive">
                                            <tr>
                                                <td class="span1">Date</td>
                                                <td class="span3">
                                                    <input type="text" name="date" class="date" required="required"/>
                                                </td>
                                                <td class="span2">
                                                    Type Asset
                                                </td>
                                                <td class="span4">
                                                    <div class="span4">
                                                        <select id="asset" name="asset[]" required="required">
                                                            <option value="">Please select</option>
                                                            <?php if($this->type_asset) foreach($this->type_asset as $key => $value):?>
                                                                <option value="<?php echo $key;?>"> <?php echo $value;?></option>
                                                            <?php endforeach;?>
                                                        </select>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="span1">Quantity</td>
                                                <td class="span3">
                                                    <input type="number" name="quantity[]" required="required" value=""/>
                                                </td>
                                                <td class="span2">Note</td>
                                                <td class="span4">
                                                    <textarea name="note[]"></textarea>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="span2">Output To Trainer</td>
                                                <td class="span3" colspan="3">
                                                    <select name="output_to_staff_id[]" required="required">
                                                        <option value="">Select</option>
                                                        <?php if($this->list_trainer) foreach($this->list_trainer as $key => $value):?>
                                                            <option value="<?php echo $key;?>"> <?php echo $value;?></option>
                                                        <?php endforeach;?>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="4">
                                                    <div class="pull-right">
                                                        <input type="button" value="+" class="btn btn-primary add_order_out"/>
                                                        <input type="hidden" name="ids[]" value="" />
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                <?php endif;?>
                            </div>

                            <div class="pull-right">
                                <div class="span2">
                                    <button class="btn btn-primary" type="submit">Submit</button>
                                    <a class="btn btn-danger" href="<?php echo $this->back_url;?>">Go Back</a>
                                    <?php if($orderOut and isset($orderOut)):?>
                                        <input type="hidden" name="order_out_id" value="<?php echo (isset($this->order_out_id) and $this->order_out_id)?$this->order_out_id:''?>" />
                                    <?php endif;?>
                                </div>
                            </div>
                            <div class="div-add" style="display:none">
                                <table class="table table-responsive">
                                    <tr>
                                        <td class="span2">
                                            Type Asset
                                        </td>
                                        <td class="span4" colspan="3">
                                            <div class="span4">
                                                <select id="asset" name="asset[]" disabled>
                                                    <option value="">Please select</option>
                                                    <?php if($this->type_asset) foreach($this->type_asset as $key => $value):?>
                                                        <option value="<?php echo $key;?>"> <?php echo $value;?></option>
                                                    <?php endforeach;?>
                                                </select>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="span1">Quantity</td>
                                        <td class="span3">
                                            <input type="number" name="quantity[]"  disabled/>
                                        </td>
                                        <td class="span2">Note</td>
                                        <td class="span4">
                                            <textarea name="note[]" disabled></textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="span2">Output To Trainer</td>
                                        <td class="span3" colspan="3">
                                            <select name="output_to_staff_id[]" disabled>
                                                <option value="">Select</option>
                                                <?php if($this->list_trainer) foreach($this->list_trainer as $key => $value):?>
                                                    <option value="<?php echo $key;?>"> <?php echo $value;?></option>
                                                <?php endforeach;?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="4">
                                            <div class="pull-right">
                                                <input type="button" value="+" class="btn btn-primary add_order_out"/>
                                                <input type="button" value="-" class="btn btn-danger remove_order_out"/>
                                                <input type="hidden" name="ids[]" disabled value="" />
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                <hr style="width: 3px;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function()
    {
        add();
        initdate();
        initRemove();
    });

    function initdate()
    {
        $('.date').mousedown( function(){
            $(this).datepicker({ dateFormat: "yy-mm-dd" });
        });
    }

    function add()
    {
        $('.add_order_out').click(function(){
            var old_div = $('.div-add');
            var new_div = old_div.clone();
            new_div.removeClass('div-add').find('select, input, textarea').removeAttr('disabled');
            new_div.find('select, input').attr('required','true');
            $('#row-detail').append(new_div);
            new_div.show();
            initRemove();
            initdate();
            add();
        });
    }

    function initRemove(){
        $('.remove_order_out').click(function(e){
            $(this).parent().parent().parent().parent().parent().parent().remove();
            return false;
        });
    }
</script>