<div class="page-header">
    <h3>Event Report</h3>
</div>
<form action="/trainer/event-report" class="form-control" method="post" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="span12">
            <div class="span4">
                <div class="widget widget-nopad">
                    <div class="widget-header"> <i class="icon-list-alt"></i>
                        <h3>Trainer Information </h3>
                    </div>
                    <div class="widget-content">
                        <div class="widget big-stats-container">
                            <div class="widget-content">
                                <table class="table">
                                    <tr>
                                        <td>Name:</td>
                                        <td><?php echo (($this->info_trainer['firstname']).' '.($this->info_trainer['lastname']) ? ($this->info_trainer['firstname']).' '.($this->info_trainer['lastname']):'' )?></td>
                                    </tr>
                                    <tr>
                                        <td>Gender</td>
                                        <td><?php if((isset($this->info_trainer['gender']) and ($this->info_trainer['gender']) == 1)){?> Male  <?php }elseif((isset($this->info_trainer['gender']) and ($this->info_trainer['gender']) == 0)){?> Female<?php }?></td>
                                    </tr>
                                    <tr>
                                        <td>Phone</td>
                                        <td><?php echo ((isset($this->info_trainer['phone_number']) and ($this->info_trainer['phone_number'])) ? ($this->info_trainer['phone_number']): '')?></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span7">
                <div class="widget widget-nopad">
                    <div class="widget-header"> <i class="icon-list-alt"></i>
                        <h3>Event Report </h3>
                    </div>
                    <div class="widget-content">
                        <div class="widget big-stats-container">
                            <div class="widget-content">
                                <table class="table">
                                    <tr>
                                        <td class="span1">Date</td>
                                        <td class="span1">
                                            <input type="text" required="required" value="<?php echo (isset($this->info_event_report) and ($this->info_event_report['date'])) ? $this->info_event_report['date']: ''?>" name="date" class="span1 date" />
                                        </td>
                                        <td class="span1">
                                            Visitors
                                        </td>
                                        <td class="span1">
                                            <input type="text" required="required"  value="<?php echo (isset($this->info_event_report) and ($this->info_event_report['visitors'])) ? $this->info_event_report['visitors']: ''?>" name="visitors" class="span1" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="span1">Dealer</td>
                                        <td colspan="3">
                                            <div class="span3">
                                                <input type="text" value="" name="search_dealer" id="search_dealer" autocomplete="off" placeholder='Select a Dealer'/>
                                                <select id="dealer" name="dealer" required="required" size="5" >
                                                    <option value="">Please select</option>
                                                    <?php foreach($this->dealer as $key => $value):?>
                                                        <option value="<?php echo $key;?>" <?php if(isset($this->info_event_report) and ($this->info_event_report['dealer_id'] ==$key)):?> selected <?php endif; ?>> <?php echo $value;?></option>
                                                    <?php endforeach;?>
                                                </select>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Store</td>
                                        <td colspan="3">
                                            <select id="store" name="store" class="span7" required="required" >
                                                <option value="">Please select</option>
                                                <?php if(isset($this->array_store) and $this->array_store):?>
                                                    <?php foreach($this->array_store as $key => $value):?>
                                                        <option value="<?php echo $key?>"  <?php if(isset($this->info_event_report) and ($this->info_event_report['store_id'] ==$key)):?> selected <?php endif; ?>><?php echo $value?></option>
                                                    <?php endforeach;?>
                                                <?php endif;?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Note</td>
                                        <td colspan="3"><textarea name="note"><?php echo (isset($this->info_event_report) and ($this->info_event_report['note'])) ? $this->info_event_report['note']: ''?></textarea></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="span11">
                <div class="widget widget-nopad">
                    <div class="widget-header"> <i class="icon-list-alt"></i>
                        <h3>Upload Event Pictures </h3>
                    </div>
                    <div class="widget-content">
                        <div class="widget big-stats-container">
                            <div class="widget-content">
                                <table class="table" id="table_picture_training">
                                    <tr id="picture_training">
                                        <td>
                                            <input type="file" name="event_picture[]" value=""/>
                                        </td>
                                        <td>
                                            <input id="add" type="button" class="btn btn-info" value="+"/>
                                        </td>
                                    </tr>
                                </table>
                                <?php if(isset($this->picture_event) and ($this->picture_event)):?>
                                        <?php foreach($this->picture_event as $key => $value):?>
                                                <?php if (isset($value) and $value):?>
                                                    <div class="span2" id="<?php echo $key ?>">
                                                        <table class="table">
                                                            <tr>
                                                                <td>
                                                                    <a data-featherlight="image" href="<?php echo ($value) ?>">
                                                                        <img src="<?php echo ($value) ?>" alt="" class="img-rounded" style="pading:10" width="140" height="140">
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td style="text-align: center">
                                                                    <button class="btn btn-danger del" rel="<?php echo $key ?>">Delete</button>
                                                                    <input type="hidden" name="picture_event_report_haved[]" value="<?php echo $key ?>"/>
                                                                </td>
                                                            </tr>
                                                        </table>

                                                    </div>
                                                <?php endif;?>
                                        <?php endforeach;?>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="row-fluid">
        <div class="span10">
            <button class="btn btn-primary pull-right">Submit</button>
            <input type="hidden" name="id" value="<?php echo (isset($this->info_event_report) and ($this->info_event_report['id'])) ? $this->info_event_report['id']: ''?>"/>
        </div>
        <div class="span2">
            <a href="<?php echo (isset($this->back_url) and ($this->back_url)) ? ($this->back_url):'/training/list-event-report'?>" class="btn btn-danger">Go Back</a>
        </div>

    </div>
</form>

<script type="text/javascript" src="/public/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/public/css/jquery-ui-1.8.12.custom.css"/>
<script src="/public/js/jquery.ui.timepicker.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="/public/css/featherlight.css" title="Featherlight Styles" />
<link type="text/css" rel="stylesheet" href="/public/css/featherlight.gallery.css" title="Featherlight Styles" />
<script src="/public/js/featherlight.js" type="text/javascript" charset="utf-8"></script>
<style type="text/css">
    @media all {
        .lightbox { display: none; }
        .fl-page h1,
        .fl-page h3,
        .fl-page h4 {
            font-family: 'HelveticaNeue-UltraLight', 'Helvetica Neue UltraLight', 'Helvetica Neue', Arial, Helvetica, sans-serif;
            font-weight: 100;
            letter-spacing: 1px;
        }
        .fl-page h1 { font-size: 110px; margin-bottom: 0.5em; }
        .fl-page h1 i { font-style: normal; color: #ddd; }
        .fl-page h1 span { font-size: 30px; color: #333;}
        .fl-page h3 { text-align: right; }
        .fl-page h3 { font-size: 15px; }
        .fl-page h4 { font-size: 2em; }
        .fl-page .jumbotron { margin-top: 2em; }
        .fl-page .btn-download { float: right; margin-top: -40px; }
        .fl-page .btn-default { vertical-align: bottom; }

        .fl-page .row { margin-top: 2em;}

        .fl-page .btn-lg span { font-size: 0.7em; }
        .fl-page .footer { margin-top: 3em; color: #aaa; font-size: 0.9em;}
        .fl-page .footer a { color: #999; text-decoration: none; margin-right: 0.75em;}
        .fl-page .github { margin: 2em 0; }
        .fl-page .github a { vertical-align: top; }

        /* customized gallery */

        .featherlight-gallery2 {
            background: rgba(100,100,100,0.5);
        }
        .featherlight-gallery2 .featherlight-content {
            background: #000;
        }
        .featherlight-gallery2 .featherlight-next:hover,
        .featherlight-gallery2 .featherlight-previous:hover {
            background: rgba(0,0,0,0.5);
        }
        .featherlight-gallery2 .featherlight-next:hover span,
        .featherlight-gallery2 .featherlight-previous:hover span {
            font-size: 25px;
            line-height: 25px;
            margin-top: -12.5px;
            color: #fff;
        }
        .featherlight-gallery2  .featherlight-close {
            background: transparent;
            color: #fff;
            font-size: 1.2em;
        }

        /* text slide */
        .thumbnail a { text-decoration: none; }
        .blurb {
            display: inline-block;
            width: 150px;
            height: 150px;
        }
        .blurb h2 { text-align: center;}
        .blurb .detail { display: none;}
        .blurb .teaser {
            font-style: italic;
            text-align: center;
        }
        .featherlight .blurb {
            display: inline-block;
            width: 500px;
            height: 300px;
            color: #99f;
        }
        .featherlight .blurb .detail {
            color: #ddf;
            font-size: large;
            display: inherit;
        }
        .featherlight .blurb .teaser { display: none;}

    }
    @media(max-width: 768px){
        .fl-page h1 span { display: block; }
        .fl-page .btn-download { float: none; margin-bottom: 1em; }
    }
</style>
<script>
$(document).ready(function(){
    $('.date' ).datepicker({ dateFormat: "yy-mm-dd" });
    getShop();
    addPicture();
    minusPicture();
    delPicture();
    initSearchOption('dealer','search_dealer');
});
function getShop()
{
    $('#dealer').change(function(){
       var dealer_id =  $('#dealer').val();
        $.ajax
        ({
            url : '/trainer/get-shop',
            type : 'POST',
            data : {'dealer_id':dealer_id},
            dataType: 'json',
            success : function(result)
            {
                $('#store').find('option:not(:first)').remove();
                $.each(result, function (i, item) {
                    $('#store').append('<option value="'+i+'">'+item+'</option>');
                });
            },
            error: function()
            {
                alert("Not Found !!!");
            }

        });
    });
}
function addPicture()
{
    $('#add').click(function(){
        var row = '<tr><td><input type="file" name="picture_training[]" value=""/></td><td><input type="button" class="btn btn-danger minus" value="-"/></td></tr>';
        $('#table_picture_training').append(row);
        minusPicture();
    });
}
function minusPicture()
{
    $('.minus').click(function(){

        $(this).parent().parent().remove();
    });
}

function delPicture()
{
    $('.del').click(function(){
        var id = $(this).attr('rel');
        $('#'+id).remove();
    });
}

</script>
