<div class="page-header">
    <h1>Inventory History</h1>
</div>
<div class="row-fluid">
    <div class="span12">
        <form class="form-search form-horizontal" method="POST" action="/trainer/inventory-history-asset">
            <div class="row">
                <div class="span4">
                    <div class="control-group">
                        <label for="Asset" class="span1">Asset</label>
                        <select id="asset_id" name="asset_id" class="span3">
                            <option value="">Select</option>
                            <?php
                            if ($this->type_asset) :
                                foreach ($this->type_asset as $key => $value):
                                    ?>
                                    <option value="<?php echo $key;?>" <?php if (isset($this->params['asset_id']) and ( (is_array($this->params['asset_id']) && in_array($key, $this->params['asset_id']) || $key == $this->params['asset_id'])) ):?>selected<?php endif;?>><?php echo (isset($value) and $value) ? $value :'';?></option>
                                <?php
                                endforeach;
                            endif;
                            ?>
                        </select>
                    </div>
                </div>
                <div class="span4">
                    <button type="submit" class="btn btn-primary">View</button>
                    <button class="btn btn-danger" type="submit" value="1" name="export">Export</button>
                    <a href="/trainer/inventory-history-asset"><input type="button" class="btn btn-warning" value="Reset"/> </a>
                </div>
            </div>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>#</th>
                        <th>Name</th>
                        <th>Total First</th>
                        <th>Total In</th>
                        <th>Total Out</th>
                        <th>Total End</th>
                        <th>Created At</th>
                        <th>Created By</th>
                    </thead>

                    <tbody>

                    <?php
                    $count =0;
                    if (isset($this->list) and $this->list)
                        foreach ($this->list as $k=>$item):
                            ?>
                            <tr>
                                <td><?php echo $k+1;?></td>
                                <td><?php echo isset($this->cached_asset[$item['asset_id']]) ? $this->cached_asset[$item['asset_id']]  : '';?></td>
                                <td><?php echo isset($item['inventory_first']) ? number_format($item['inventory_first'])  : '';?></td>
                                <td><?php echo isset($item['inventory_in']) ? number_format($item['inventory_in'])  : '';?></td>
                                <td><?php echo isset($item['inventory_out']) ? number_format($item['inventory_out'])  : '';?></td>
                                <td><?php echo isset($item['inventory_end']) ? number_format($item['inventory_end'])  : '';?></td>
                                <td><?php echo isset($item['created_at']) ? $item['created_at']  : '';?></td>
                                <td><?php echo isset($this->staff_cached[$item['created_by']]) ? $this->staff_cached[$item['created_by']]  : '';?></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>

                <div class="paging">
                    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
                </div>
            </div>
        </div>
    </div>
</div>
