<div class="page-header">
    <h3>LIST NEW STAFF</h3>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
if (isset($this->message_success) and $this->message_success)
    foreach ($this->message_success as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <div class="row">
                <form class="form-control" action="/trainer/list-new-staff" method="get">
                    <div class="span5">
                        <div class="control-group">
                            <label for="name" class="span2">Name</label>
                            <input id="name" name="name" type="text" class="input-medium search-query" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
                        </div>
                        <div class="control-group">
                            <label for="name" class="span2">CMND</label>
                            <input id="cmnd" name="cmnd" type="text" class="input-medium search-query" value="<?php isset($this->params['cmnd']) and printf($this->params['cmnd']);?>">
                        </div>
                    </div>

                    <div class="span5">

                        <div class="control-group">
                            <label for="area_id" class="span2">Area</label>
                            <select id="area_id" name="area_id" class="span3">
                                <option value="">Select</option>
                                <?php
                                if ($this->area_trainer) :
                                    foreach ($this->area_trainer as $key => $value):
                                        ?>
                                        <option value="<?php echo $key;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($key, $this->params['area_id']) || $key == $this->params['area_id'])) ):?>selected<?php endif;?>><?php echo (isset($value) and $value) ? $value :'';?></option>
                                    <?php
                                    endforeach;
                                endif;
                                ?>
                            </select>
                        </div>

                        <div class="control-group">
                            <label for="regional_market" class="span2">Province</label>
                            <select id="regional_market" name="regional_market" class="span3">
                                <option value="">Select</option>
                                <?php
                                if ($this->province_search) :
                                    foreach ($this->province_search as $key => $value):
                                        ?>
                                        <option value="<?php echo $key;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($key, $this->params['regional_market']) || $key == $this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo (isset($value) and $value) ? $value :'';?></option>
                                    <?php
                                    endforeach;
                                endif;
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="row span12">
                        <button type="submit" class="btn btn-success">Search</button>
                        <a href="/trainer/list-new-staff" class="btn btn-primary">Reset</a>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <table class="table table-bordered">
            <tr>
                <thead>
                <?php echo $this->sorting(array(
                        '#',
                        'First Name',
                        'Last Name',
                        'CMND',
                        'Gender',
                        'Area',
                        'Province',
                        'Action'
                    ),
                    $this->url, $this->sort, $this->desc); ?>
                </thead>
            </tr>
            <tbody>
            <?php if(isset($this->list)and $this->list):?>
                <?php
                $k =0;
                foreach($this->list as $key =>$value):?>
                    <tr>
                        <td><?php echo $k=$k+1?></td>
                        <td><?php echo (isset($value['firstname']) and $value['firstname']) ? $value['firstname'] : null?></td>
                        <td><?php echo (isset($value['lastname']) and $value['lastname']) ? $value['lastname'] : null?></td>
                        <td><?php echo (isset($value['cmnd']) and $value['cmnd']) ? $value['cmnd'] : null?></td>
                        <td><?php echo (isset($value['gender']) and $value['gender']) ? 'Nam' : 'Nữ'?></td>
                        <td><?php echo (isset($this->cached_area[$value['area_id']]) and $this->cached_area[$value['area_id']]) ? $this->cached_area[$value['area_id']] : null?></td>
                        <td><?php echo (isset($this->cached_regional_market[$value['regional_market']]) and $this->cached_regional_market[$value['regional_market']]) ? $this->cached_regional_market[$value['regional_market']] : null?></td>
                        <td>
                            <div class="btn-group">
                                <button class="btn dropdown-toggle" data-toggle="dropdown">
                                    Action
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <ul class="dropdown-menu">
                                        <li><a href="javascript:void(0);" rel="<?php echo $value['id']?>" class="edit">Edit</a></li>
                                        <li><a href="/trainer/delete-new-staff?id=<?php echo $value['id'] ?>" class="confirmLink">Delete</a></li>
                                    </ul>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
    </div>
</div>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<div id="myModal" class="modal modal-lg fade" role="dialog" style="left: 37%; width: 900px">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit New Staff</h4>
            </div>
            <div class="modal-body">
                <form action="/trainer/save-new-pg" method="post">
                    <table class="table table-responsive">
                        <tr>
                            <td>First Name:</td>
                            <td><input type="text" id="firstname_new_staff" name="firstname" value=""/></td>
                        </tr>
                        <tr>
                            <td>Last Name:</td>
                            <td><input type="text" id="lastname_new_staff" name="lastname" value=""/></td>
                        </tr>
                        <tr>
                            <td>Gender</td>
                            <td>
                                <select name="gender" id="gender">
                                    <option value="">Select</option>
                                    <option value="1">Nam</option>
                                    <option value="0">Nữ</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>CMND</td>
                            <td>
                                <input type="text" name="cmnd" id="cmnd_new_staff" value=""/>
                            </td>
                        </tr>
                        <tr>
                            <td>Area</td>
                            <td>
                                <select id="area_id_new_staff" name="area_id">
                                    <option value="">Select</option>
                                    <?php
                                    if ($this->area_trainer) :
                                        foreach ($this->area_trainer as $key => $value):
                                            ?>
                                            <option value="<?php echo $key;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($key, $this->params['area_id']) || $key == $this->params['area_id'])) ):?>selected<?php endif;?>><?php echo (isset($value) and $value) ? $value :'';?></option>
                                        <?php
                                        endforeach;
                                    endif;
                                    ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>Province</td>
                            <td>
                                <select name="regional_market" id="regional_market_new_staff">
                                    <option value="">Select</option>
                                </select>
                            </td>
                        </tr>
                    </table>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-info">Save</button>
                <input type="hidden" id="id_new_staff" name="id_new_staff" value=""/>
             </form>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/public/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>
<script>
    $(document).ready(function(){
        getProvince();
        edit();
    });
    function getProvince()
    {
        $('#area_id').change(function(){
            var area     =  $('#area_id').val();
            var staff_id =  '<?php echo (isset($this->staff_id) ? $this->staff_id :null)?>';
            $.ajax
            ({
                url : '/trainer/get-province',
                type : 'POST',
                data : {'staff_id':staff_id,'area':area},
                dataType: 'json',
                success : function(result)
                {
                    $('#regional_market').find('option:not(:first)').remove();
                    $.each(result, function (i, item) {
                        $('#regional_market').append('<option value="'+i+'">'+item+'</option>');
                    });
                },
                error: function()
                {
                    $('#regional_market').find('option').remove();
                    $('#regional_market').append('<option value="">'+'Select'+'</option>');
                    alert("Not Found !!!");
                }

            });
        });
    }

    function edit()
    {
        $('.edit').click(function(){
            var id = $(this).attr('rel');
            $('#id_new_staff').val(id);
            var staff_id =  '<?php echo (isset($this->staff_id) ? $this->staff_id :null)?>';
            $.ajax
            ({
                url : '/trainer/get-info-new-staff',
                type : 'POST',
                data : {id:id},
                dataType: 'json',
                success : function(result)
                {
                    $('#firstname_new_staff').val(result.firstname);
                    $('#lastname_new_staff').val(result.lastname);
                    $('#gender').find("option[value="+result.gender+"]").attr('selected', true);
                    $('#cmnd_new_staff').val(result.cmnd);
                    $('#area_id_new_staff').find("option[value="+result.area_id+"]").attr('selected', true);
                    getProvinceForEditStaff(result.area_id,staff_id,result.regional_market);
                    getProvinceEditChangeArea();
                    $('#myModal').modal();
                },
                error: function()
                {

                }

            });


        });
    }

    function getProvinceForEditStaff(area_id,staff_id,selected)
    {
        $.ajax
        ({
            url : '/trainer/get-province',
            type : 'POST',
            data : {'staff_id':staff_id,'area':area_id},
            dataType: 'json',
            success : function(result)
            {
                $('#regional_market_new_staff').find('option:not(:first)').remove();
                $.each(result, function (i, item) {
                    $('#regional_market_new_staff').append('<option value="'+i+'">'+item+'</option>');
                });
                $('#regional_market_new_staff').find("option[value="+selected+"]").attr('selected', true);
            },
            error: function()
            {
                $('#regional_market').find('option').remove();
                $('#regional_market').append('<option value="">'+'Select'+'</option>');
                alert("Not Found !!!");
            }

        });
    }

    function getProvinceEditChangeArea()
    {
        $('#area_id_new_staff').change(function(){
            var area     =  $('#area_id_new_staff').val();
            var staff_id =  '<?php echo (isset($this->staff_id) ? $this->staff_id :null)?>';
            $.ajax
            ({
                url : '/trainer/get-province',
                type : 'POST',
                data : {'staff_id':staff_id,'area':area},
                dataType: 'json',
                success : function(result)
                {
                    $('#regional_market_new_staff').find('option:not(:first)').remove();
                    $.each(result, function (i, item) {
                        $('#regional_market_new_staff').append('<option value="'+i+'">'+item+'</option>');
                    });
                },
                error: function()
                {
                    $('#regional_market_new_staff').find('option').remove();
                    $('#regional_market_new_staff').append('<option value="">'+'Select'+'</option>');
                    alert("Not Found !!!");
                }

            });
        });
    }
</script>