<div class="page-header">
    <h3>REWARD - WARNING PG - SALE</h3>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
if (isset($this->message_success) and $this->message_success)
    foreach ($this->message_success as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;
?>
<div class="row-fluid">
    <div class="span5">
        <div class="widget widget-nopad">
            <div class="widget-header"> <i class="icon-list-alt"></i>
                <h3>PG - SALE INFORMATION</h3>
            </div>
            <div class="widget-content">
                <div class="widget big-stats-container">
                    <div class="widget-content">
                        <table class="table table-striped">
                            <tr>
                                <td>Name:</td>
                                <td><?php echo (($this->staff['firstname']).' '.($this->staff['lastname']) ? ($this->staff['firstname']).' '.($this->staff['lastname']):'' )?></td>
                            </tr>
                            <tr>
                                <td>Gender:</td>
                                <td><?php if((isset($this->staff['gender']) and ($this->staff['gender']) == 1)){?> Male  <?php }elseif((isset($this->staff['gender']) and ($this->staff['gender']) == 0)){?> Female<?php }?></td>
                            </tr>
                            <tr>
                                <td>Phone:</td>
                                <td><?php echo ((isset($this->staff['phone_number']) and ($this->staff['phone_number'])) ? ($this->staff['phone_number']):'' )?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form action="/trainer/reward-warning" method="post">
        <div class="span7">
            <div class="widget widget-nopad">
                <div class="widget-header"> <i class="icon-list-alt"></i>
                    <h3>Reward - Warning</h3>
                </div>
                <div class="widget-content">
                    <div class="widget big-stats-container">
                        <div class="widget-content">
                            <table class="table">
                                <tr>
                                    <td>
                                        Month
                                    </td>
                                    <td>
                                        <input type="text" name="month_year" value="" class="date" required="required"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="span1">Type</td>
                                    <td class="span5">
                                        <select name="type" required="required">
                                            <option value="">Select</option>
                                            <?php
                                            $typePG = unserialize(TYPE_PG);
                                            foreach($typePG as $key => $value):?>
                                                <option  value="<?php echo $key;?>"><?php echo $value;?></option>
                                            <?php endforeach;?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="span1">Content</td>
                                    <td class="span5">
                                        <textarea required="required" name="content" rows="9" cols="25" style=" height: 158px; width:562px "></textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </td>
                                    <td class="span6">
                                        <a class="btn btn-danger" href="<?php echo ((isset($this->back_url) and($this->back_url)) ? ($this->back_url):'/trainer')?>">Go Back</a>
                                        <input type="hidden" name="staff_id" value="<?php echo ($this->staff['id']) ?>"/>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>
<div class="row">
    <div class="span12">
        <div class="widget widget-nopad">
            <div class="widget-header"> <i class="icon-list-alt"></i>
                <h3>HISTORY</h3>
            </div>
            <div class="widget-content">
                <div class="widget big-stats-container">
                    <div class="widget-content">
                        <table class="table table-striped">
                            <tr>
                                <td>#</td>
                                <td>Type</td>
                                <td>Content</td>
                                <td>Month</td>
                                <td>Year</td>
                                <td>Action</td>
                            </tr>
                            <?php $k=0;?>
                            <?php if(isset($this->staffHistory) and ($this->staffHistory)):?>
                                <?php foreach($this->staffHistory as $key=>$value):?>
                                    <tr id="<?php echo (isset($value['id']) and $value['id']) ? ($value['id']):'' ?>">
                                        <td>
                                            <?php echo $k = $k+1?>
                                        </td>
                                        <td>
                                            <?php $typePG = unserialize(TYPE_PG); echo (isset($typePG[$value['type']]) and $typePG[$value['type']]) ? $typePG[$value['type']]:''; ?>
                                        </td>
                                        <td>
                                            <?php echo ((isset($value['content']) and $value['content']) ? $value['content'] : '')?>
                                        </td>
                                        <td>
                                            <?php echo ((isset($value['month']) and $value['month']) ? $value['month'] : '')?>
                                        </td>
                                        <td>
                                            <?php echo ((isset($value['year']) and $value['year']) ? $value['year'] : '')?>
                                        </td>
                                        <td>
                                            <a href="javascript:void(0)"><button class="button btn-danger del"  rel="<?php echo (isset($value['id']) and $value['id']) ? ($value['id']):'' ?>">X</button></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="paging">
            <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
        </div>
    </div>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function()
    {
        $('.del').click(function(){
            var id = $(this).attr('rel');
            if (confirm('Are you sure you want to delete that?')) {
                $.ajax
                ({
                    url : '/trainer/del-history',
                    type : 'POST',
                    data : {'id':id},
                    dataType: 'json',
                    async: false,
                    success : function (result)
                    {
                        if(result ==1)
                        {
                            $('#'+id).remove();
                            location.reload();
                        }
                        else
                        {
                            alert('Can not delete');
                        }
                    },
                    error : function ()
                    {
                       alert('Can not delete');
                    }
                });
            }


        });

        $('.date').datepicker({
            dateFormat: 'mm-yy',
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,

            onClose: function(dateText, inst) {
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).val($.datepicker.formatDate('mm-yy', new Date(year, month, 1)));
            }
        });

        $('.date').focus(function () {
            $(".ui-datepicker-calendar").hide();
            $("#ui-datepicker-div").position({
                my: "center top",
                at: "center bottom",
                of: $(this)
            });
        });

    });

</script>