<div class="page-header">
    <div>
        <h3>MANAGE TYPE ASSET TRAINER</h3>
    </div>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;

if (isset($this->messages_error) and $this->messages_error)
    foreach ($this->messages_error as $messages_error):
        echo '<div class="alert alert-danger">'.$messages_error.'</div>';
    endforeach;
?>
<div class="row-fluid page-header">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info btn-lg pull-right" data-toggle="modal" data-target="#myModal">Create New</button>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="accordion" id="accordion2">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                        Search
                    </a>
                </div>
                <div id="collapseTwo" class="accordion-body collapse" style="height:0px;">
                    <div class="accordion-inner">
                        <form class="form-search form-horizontal" method="get">
                            <div class="row">
                                <div class="span5">
                                    <div class="control-group">
                                        <label for="name" class="span2">Name</label>
                                        <input id="name" name="name" type="text" class="input-medium search-query form-control" value="<?php echo ((isset($this->params['name']) and $this->params['name'])? $this->params['name']:'')?>">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-bordered">
            <tr class="label label-info">
                <td>#</td>
                <td>Name</td>
                <td>Action</td>
            </tr>
            <?php $count =  0; if($this->assets)
            foreach($this->assets as $key => $value):
            ?>
                <tr>
                    <td><?php echo $count = $count + 1 ; ?></td>
                    <td>
                        <?php echo (isset($value['name']) and $value['name']) ? $value['name']:'';?>
                        <input type="hidden" value="<?php echo (isset($value['name']) and $value['name']) ? $value['name']:'';?>" id="name_<?php echo (isset($value['id']) and $value['id']) ? $value['id']:null;?>"/>
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                Action
                                <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <?php if ($this->access('trainer', 'save-asset')):?>
                                <li>
                                    <a title="Edit" class="edit" rel="<?php echo (isset($value['id']) and $value['id']) ? $value['id']:'';?>" href='javascript:void(0);'>Edit</a>
                                </li>
                                <?php endif;?>
                                <?php if ($this->access('trainer', 'del-asset')):?>
                                <li>
                                    <a  class="confirmLink" href='/trainer/del-asset?id=<?php echo (isset($value['id']) and $value['id']) ? $value['id']:'';?>'>Delete</a>
                                </li>
                                <?php endif;?>
                            </ul>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</div>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<!-- Modal Create New -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create New Asset</h4>
            </div>
            <div class="modal-body">
                <form action="/trainer/save-asset" method="post">
                    <div class="row-fluid form-inline">
                        <input type="text" name="asset" value="" />
                        <input type="submit" class="btn btn-primary" value="OK" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<!-- Modal Edit -->
<div id="myModalEdit" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Asset</h4>
            </div>
            <div class="modal-body">
                <form action="/trainer/save-asset" method="post">
                    <div class="row-fluid form-inline">
                        <input type="text" name="asset" value="" id="modal_edit" />
                        <input type="hidden" name="id" value="" id="modal_id"/>
                        <input type="submit" class="btn btn-primary" value="OK" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>

<script>
    $(document).ready(function () {
        edit();
    });

    function edit()
    {
        $('.edit').click(function(){
            var id = $(this).attr('rel');
            // lay cai ten
            var name = $('#name_'+id).val();
            // dưa vào Modal
            $('#modal_edit').val(name);
            $('#modal_id').val(id);
            $('#myModalEdit').modal();

        });
    }
</script>