<div class="page-header">
    <h3>VIEW ORDER</h3>
</div>

<div class="row-fluid">
    <div class="span12">
            <div class="widget widget-nopad">
                <div class="widget-header"> <i class="icon-list-alt"></i>
                    <h3>VIEW ORDER</h3>
                </div>
                <div class="widget-content">
                    <div class="widget big-stats-container">
                        <div class="widget-content">
                            <?php
                                echo $this->render('/trainer/partials/view-detail-order.phtml');
                            ?>
                            <div class="pull-right">
                                <div class="span2">
                                    <a class="btn btn-danger" href="<?php echo $this->back_url;?>">Go Back</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>