<style type="text/css">
    .remove_area_btn,
    .remove_region_btn {
        margin-bottom: 9px;
    }

    .alert-msg {
        background: #F9EEB8;
        border-bottom-right-radius: 4px;
        border-bottom-left-radius: 4px;
        border-top: 2px solid #e55;
        /*display: none;*/
        margin: 0;
        /*margin-left: -200px;*/
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 9999;
    }

    .alert-msg.show {
        display: inline-block;
    }

    .alert-msg p {
        font-weight: bold;
        font-size: 12px;
        font-family: tahoma, arial;
        margin: 0 10px;
        line-height: 2em;
        text-align: center;
    }

</style>
<div class="page-header">
    <h1>Penalty Charge By Store : Create</h1>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-success">'.$message.'</div>';
    endforeach;
?>


<?php if (isset($this->WARNING_TIMING_MESSAGES) and $this->WARNING_TIMING_MESSAGES):?>
<div class="alert-msg">
    <p class="msg"><?php echo $this->WARNING_TIMING_MESSAGES;?></p>
</div>
<?php endif;?>

<?php $area_binding = $this->store_control_binding; ?>
<iframe name="ifrmSave" id="ifrmSave" height="300px" width="100%" style="display:none;"></iframe>
<form role="form" id="form" action="<?php echo HOST ?>manage/penalty-charge-create-store-save" method="post" target="ifrmSave">
<input type="hidden" id="pms_id" name="pms_id" value="<?php echo isset($this->pms_detail['id']) ? $this->pms_detail['id'] : ""; ?>" />
    <div class="row">
        <div class="span6">
            <p><span><strong>- Date Range -</strong></span></p>
            <table class="table-striped" width="100%" >
                <tr>
                    <td width="120px">From</td>
                    <td style="padding-left: 5px;"><input type="text" class="form-control search-query date span2" id="from_date" name="from_date" value="<?php isset($this->pms_detail['from_date']) and printf(date('d/m/Y', strtotime($this->pms_detail['from_date'])));?>" required="required"></td>
                </tr>
                <tr>
                    <td width="120px">To</td>
                    <td style="padding-left: 5px;"><input type="text" class="form-control search-query date span2" id="to_date" name="to_date" value="<?php isset($this->pms_detail['to_date']) and printf(date('d/m/Y', strtotime($this->pms_detail['to_date'])));?>" required="required"></td>
                </tr>
                <tr>
                    <td width="120px">Remark</td>
                    <td style="padding-left: 5px;"><input type="text" class="span3" id="remark" name="remark" value="<?php isset($this->pms_detail['remark']) and printf($this->pms_detail['remark']);?>" /></td>
                </tr>
            </table>

            <br/>

            <p><span><strong>- Role Effected -</strong></span></p>
            <table class="table-striped" width="100%" >
                <tr>
                    <td width="120px">GFk Calculation</td>
                    <td style="padding-left: 5px;"><input type="checkbox" id="chk_gfk" name="chk_gfk" value="1" <?php echo isset($this->pms_detail['flag_gfk']) && $this->pms_detail['flag_gfk'] == 1 ? "checked" : ""; ?> ></td>
                </tr>
                <tr>
                    <td width="120px">RD / RD Stand By</td>
                    <td style="padding-left: 5px; display:;"><input type="checkbox" id="chk_rd" name="chk_rd" value="1" <?php echo isset($this->pms_detail['flag_rd']) && $this->pms_detail['flag_rd'] == 1 ? "checked" : ""; ?>></td>
                </tr>
                <tr>
                    <td width="120px">ASM / ASM Stand By</td>
                    <td style="padding-left: 5px;"><input type="checkbox" id="chk_asm" name="chk_asm" value="1" <?php echo isset($this->pms_detail['flag_asm']) && $this->pms_detail['flag_asm'] == 1 ? "checked" : ""; ?>></td>
                </tr>
                <tr>
                    <td width="120px">Sale</td>
                    <td style="padding-left: 5px;"><input type="checkbox" id="chk_sale" name="chk_sale" value="1" <?php echo isset($this->pms_detail['flag_sale']) && $this->pms_detail['flag_sale'] == 1 ? "checked" : ""; ?>></td>
                </tr>
                <tr>
                    <td width="120px">PC</td>
                    <td style="padding-left: 5px;"><input type="checkbox" id="chk_pc" name="chk_pc" value="1" <?php echo isset($this->pms_detail['flag_pc']) && $this->pms_detail['flag_pc'] == 1 ? "checked" : ""; ?>></td>
                </tr>
            </table>

        </div>

        <div class="span6">
            <div class="row-fluid">
                <div class="control-group">
                    <label for="a_storename"><p><span><strong>- Search Store -</strong></span></p></label>
                    <input type="text" class="form-control span4" id="a_storename" name="a_storename" placeholder="Enter Store name then press ENTER"  />
                </div>
            </div>
            <div class="row-fluid">
                <div class="control-group">
                    <label for="a_storeresult"><p><span><strong>- Result -</strong></span></p></label>
                    <div class="load-ajax">
                        <select class="span6 search_result" id="a_storeresult" name="a_storeresult" multiple="multiple" size="8"></select>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <button id="btn_add_store" class="btn btn-success" type="button">Add Store</button>

                <button type="submit" id="btn_submit" class="btn btn-primary" disabled="disabled">Submit</button>

                <input type="hidden" name="back_url" id="back_url" value="<?php if (isset($this->back_url) and $this->back_url) echo $this->back_url;?>">
                <button type="button" class="btn btn-danger go-back">Go back</button>
            </div>

        </div>

    </div>

    <br />

<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align='center'>No.</div></th>
        <th><div align='center'>Area</div></th>
        <th><div align='center'>Store ID</div></th>
        <th><div align='center'>Store Name</div></th>
        <th><div align='center'>Store Type</div></th>
        <th><div align='center'>Status</div></th>
        <th><div align='center'>ASM / Sale</div></th>
        <th><div align='center'>PC</div></th>
        <th><div align='center'>Action</div></th>
    </tr>
    </thead>
    <tbody class="store_list">
        <?php 
            $QStoreStaff = new Application_Model_StoreStaff();

            if ($this->store_list) {
                $data = $this->store_list;

                for($i=0;$i<count($data);$i++) { 

                    $pc_list = $QStoreStaff->getPC($data[$i]['st_id']);

                    if ( $data[$i]['st_status'] == 1 ) { $st_status = "<span class='label label-important'>Disable</span>"; }
                    else { $st_status = "<span class='label label-success'>Active</span>"; }

                    $cnt = $i + 1;
                    echo "<tr class='store' data-id='".$data[$i]['st_id']."'>";
                    echo    "<td><div align='center'>".$cnt."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['st_area']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['st_id']."</div></td>";
                    echo    "<td>".$data[$i]['st_name']."</td>";
                    echo    "<td>".$data[$i]['st_type']."</td>";
                    echo    "<td><div align='center'>".$st_status."</div></td>";

                    if (isset($data[$i]['sale_code'])) {
                        echo "<td>[ ".$data[$i]['sale_code']." ] ".$data[$i]['sale_name']."</td>";
                    } else {
                        echo "<td></td>";
                    }
                    
                    echo    "<td>";

                    for ($j=0;$j<count($pc_list);$j++) { echo "<div>[ ".$pc_list[$j]['pc_code']." ] ".$pc_list[$j]['pc_name']."</div>"; }

                    echo    "</td>";

                    echo    "<td>";
                    echo        "<div align='center'>";
                    echo            "<button class='btn btn-warning btn-mini btn_remove'>Remove</button>";
                    echo            "<input type='hidden' id='store' name='store[]' value='".$data[$i]['st_id']."' />";
                    echo        "</div>";
                    echo    "</td>";

                    echo "</tr>";
                }

            }
        ?>
    </tbody>
</table>

</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">

    $(document).ready(function () {

        // Allow Submit for Edit Mode
        if ( $("#pms_id").val() != '' ) { $('#btn_submit').prop("disabled", false); }

        remove_store();

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });

    
        $( "#a_storename" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();

                $('form').bind('submit',function(e){e.preventDefault();});
                $('form button, form input, form select').prop('disabled', true);

                $('.loading').remove();
                var _self = $(this);
                var targetUrl = '<?php echo HOST."ajax/get-store-for-leader?store_name=" ?>' + $('#a_storename').val();

                //get ajax content
                var aj = _self.parent().parent().next().find('.load-ajax');
                if (aj.length){
                    _self.after("<span class=\'loading\'></span>");
                    $.get(targetUrl
                        ,function(data,status){

                            $('form').unbind('submit');
                            $('form button, form input, form select').prop('disabled', false);

                            aj.html(data);
                            _self.next('.loading').remove();

                            $('#a_storeresult').attr("multiple", true);
                            $('#btn_submit').prop("disabled", true);
                        });
                }

                return false;
            }
        });

        $('#btn_add_store').click(function(){
            _self = $('#a_storeresult');
            item = _self.children('option:selected');

            for (var i = 0; i < item.length; i++) {
                if ( ! is_exists( $(item[i]).data('id') ) ) {

                    if ($(item[i]).data('del') == 1) { st_status = "<span class='label label-important'>Disable</span>"; }
                    else { st_status = "<span class='label label-success'>Active</span>";  }

                    elm = '<tr class="store" data-id="'+$(item[i]).data('id')+'" >'
                            + '<td><div align="center">-</div></td>'
                            + '<td><div align="center">'+$(item[i]).data('area-name')+'</div></td>'
                            + '<td><div align="center">'+$(item[i]).data('id')+'</div></td>'
                            + '<td>'+$(item[i]).data('name')+'</td>'
                            + '<td>'+$(item[i]).data('type')+'</td>'
                            + '<td><div align="center">'+st_status+'</div></td>';

                    //if ($(item[i]).data('sc') == '') {
                        elm += '<td colspan=2><div align="center"></div></td>'
                                + '<td><div align="center"><button class="btn btn-warning btn-mini btn_remove">Remove</button><input type="hidden" id="store" name="store[]" value="'+$(item[i]).data('id')+'" /></div></td>'
                                + '</tr>';
                    // } else {
                    //     elm += '<td colspan=2><div align="center">Store Control : '+$(item[i]).data('sc')+'</div></td>'
                    //             + '<td><div align="center">-</div></td>'
                    //             + '</tr>';
                    // }

                    $('.store_list').append(elm);
                }
            }

            remove_store();

            $('#btn_submit').prop("disabled", false);
            
        });


    });


    function palert(msg){
        $('.alert-error').remove();
        $('.page-header').after('<div class="alert alert-error">'+msg+'</div>');
        $('form#form button').prop('disabled', false);
        return;
    }

    function is_exists(id) {
        _des = $('.store_list');
        items = _des.children('.store');

        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).data('id') == id) {
                return true;
            }
        }
        return false;
    }

    function remove_store() {
        $('.btn_remove').click(function(){
            _self = $(this);
            _self.parents('tr').remove();

            $('#btn_submit').prop("disabled", false);
        });
    }
    

</script>