<div class="page-header">
    <h1>Penalty Charge</h1>
    <span class="pull-right">
        <form action="/manage/penalty-charge-create-staff" method="get">
            &ensp;<button class="btn-success" type="submit"><i class="icon-plus">&ensp;By Staff</i></button>
        </form>
    </span>
    &ensp;&ensp;
    <span class="pull-right">
        <form action="/manage/penalty-charge-create-store" method="get">
            <button class="btn-success" type="submit"><i class="icon-plus">&ensp;By Store</i></button>
        </form>
    </span>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('manage/penalty-charge/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <?php
    if ($this->params['penalty_type_id'] == 1) {
        echo $this->render('manage/penalty-charge/partials/list_store.phtml');
    } else {
        echo $this->render('manage/penalty-charge/partials/list_staff.phtml');
    }
    ?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>
<?php echo $this->confirm();?>