<!-- <div class="footer">
    <div class="footer-inner">
        <div class="container">
            <div class="row">
                <div class="span9"> &copy; <?php echo date("Y") ?> OPPO Mobile Laos  <?php if (defined("VERSION")) echo " - Version " ,VERSION ?></div>
                <div class="span3" style="text-align: right;">  <strong>Contact: +856 20 2945 0680 (Sone) </strong> </div>
            </div>
        </div>
    </div>
</div> -->