<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>OWAY Catty System - Login</title>
    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
     <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://trusted-cdn.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'none';">

    <link rel="icon" type="image/ico" href="/img/mini-icon.png" />
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/font-awesome.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <link href="/css/pages/signin.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/bootstrap-5/css/bootstrap.min.css">



</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #1caf47;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img width="100px" src="/img/New-logo.png"/></a>
    </div>
</nav>

<?php echo $this->layout()->content; ?>

<script src="/js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/bootstrap-5/js/bootstrap.js"></script>

<script src="/js/signin.js"></script>

</body>

</html>
