<?php 
    
    $userStorage = Zend_Auth::getInstance()->getStorage()->read();
    if($userStorage->firstname == '')
    {
      echo '<script langquage="javascript">
      window.location='.HOST.'"user/logout";
    </script>';
    }
?>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container"> 
        	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        		<?php if (isset($this->recent_notifications) && count($this->recent_notifications) > 0): ?>
                   <span class="badge badge-important"><?php echo count($this->recent_notifications) ?></span>
               <?php else: ?>
                 <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> 
             <?php endif	?>
         </a>
         <!-- <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> </a> -->
         <a class="brand" href="/"><img width="100px" src="/img/New-logo.png"/></a>
     <div class="nav-collapse">

        <ul class="nav pull-right">
            <?php 
            if (  in_array($userStorage->group_id, array(ADMINISTRATOR_ID, SALES_ADMIN_ID, SALES_EXT_ID)) ):?>

            <li><a href="/manage/cache?del=1">Clear cache</a></li>

        <?php endif;?>

        <!-- <?php echo $this->render('notification-list.phtml') ?> -->


        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">

           <?php 
           if($userStorage->photo != '')
           {
               ?>
               <img src="<?php echo HOST;?>photo/staff/<?php echo $userStorage->id;?>/<?php echo $userStorage->photo;?>" width ="30" height="30">

               <?php } else { ?>
               <i
               class="icon-user"></i>
               <?php } ?>
               <?php echo $userStorage->firstname;?> <b class="caret"></b></a>
               <ul class="dropdown-menu">
                <li><a href="/user/change-pass">Change Password</a></li>
                <li><a href="/user/logout">Logout</a></li>
            </ul>
        </li>
    </ul>
                <!--
                <form class="navbar-search pull-right">
                    <input type="text" class="search-query" placeholder="Search">
                </form>
            -->
        </div>
        <!--/.nav-collapse -->
    </div>
    <!-- /container -->
</div>
<!-- /navbar-inner -->
</div>