<div class="page-header">
    <?php if (isset($this->sales_team) and $this->sales_team):?>
        <h1>Edit Sales team</h1>
    <?php else:?>
        <h1>Create Sales team</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<div class="row-fluid">
    <div class="span12">
        <iframe name="ifrmSave" id="ifrmSave" width="100%" style="display:none;"></iframe>
        <form role="form" id="form" action="<?php echo HOST.'manage/sales-team-save';?>" method="post" target="ifrmSave">
        <div class="row-fluid">
            <div class="span6">
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="name">Name</label>
                        <input type="text" class="span6 form-control" id="name" name="name" required="required" value="<?php if (isset($this->sales_team)): echo $this->sales_team->name; endif;?>">
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="area_id">Area</label>
                        <select id="area_id" name="area_id" class="span3" required="required">
                            <option value="">Choose</option>
                            <?php
                            if ($this->areas) :
                                foreach ($this->areas as $area):
                                    ?>
                                    <option value="<?php echo $area->id;?>" <?php if (isset($this->sales_team->area_id) and $this->sales_team->area_id==$area->id):?>selected<?php endif;?>><?php echo $area->name;?></option>
                                <?php
                                endforeach;
                            endif;
                            ?>
                        </select>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="regional_market">Province</label>
                        <select id="regional_market" name="regional_market" class="span3" required="required">
                            <option value="">Choose</option>
                            <?php
                            if ($this->regional_markets) :
                                foreach ($this->regional_markets as $regional_market):?>
                                    <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->sales_team->regional_market) and $this->sales_team->regional_market==$regional_market->id):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                                <?php
                                endforeach;
                            endif;
                            ?>
                        </select>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <legend>Leader</legend>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <select name="leader_name" id="leader_name" class="span6" multiple="multiple">
                            <?php if ($this->staffs1): ?>
                            <?php foreach ($this->staffs1 as $k=>$staff): ?>
                                <option value="<?php echo $staff->id ?>"><?php echo $staff->firstname . ' ' . $staff->lastname . ' | '. preg_replace('/oppomobile.vn/', '', $staff['email']) .  (isset($this->regional_market_all[$staff['regional_market']]) ? (' | ' . $this->regional_market_all[$staff['regional_market']] ): '') ?></option>
                            <?php endforeach ?>
                            <?php endif ?>
                        </select>
                        

                        <input id="pic1" name="pic1" type="hidden" value="" />

                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <button id="remove_leader_btn" class="btn btn-danger pull-right" type="button">Remove</button>
                    </div>
                </div>

                <div class="row-fluid">
                    <legend>PG&PB</legend>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <select name="pg_name" id="pg_name" class="span6" multiple="multiple">
                            <?php if ($this->staffs): ?>
                            <?php foreach ($this->staffs as $k=>$staff): ?>
                                <option value="<?php echo $staff->id ?>"><?php echo $staff->firstname . ' ' . $staff->lastname. ' | '. preg_replace('/oppomobile.vn/', '', $staff['email']) .  (isset($this->regional_market_all[$staff['regional_market']]) ? (' | ' . $this->regional_market_all[$staff['regional_market']] ): '') ?></option>
                            <?php endforeach ?>
                            <?php endif ?>
                        </select>
                        
                        <input id="pic" name="pic" type="hidden" value="" />

                    </div>
                    <div class="control-group">
                        <button id="remove_pg_btn" class="btn btn-danger pull-right" type="button">Remove</button>
                    </div>
                </div>
            </div>
            <div class="span6">
                
                <div class="row-fluid">
                    <legend>Search</legend>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="s_name">Staff Name</label>
                        <input type="text" class="form-control span6" id="s_name" placeholder="Enter Staff name then press ENTER" name="s_name" />
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <label for="">Result</label>
                        <div class="load-ajax">
                            <?php echo $this->partial('staff/partials/searchname.phtml',array()); ?>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <button id="add_leader_btn" class="btn btn-primary" type="button">Add as LEADER</button>
                        <button id="add_pg_btn" class="btn btn-warning" type="button">Add as PG-PB</button>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="control-group">
                        <span class="help-block">Search, then click Add as Leader or Add as PG-PB</span>
                    </div>
                </div>
            </div>

            
        </div>
        <div class="row-fluid">
            <div class="span6">
                <input type="hidden" name="id" id="id" value="<?php isset($this->sales_team) and $this->sales_team and printf($this->sales_team->id);?>">
                <input type="hidden" name="back_url" id="back_url" value="<?php isset($this->back_url) and $this->back_url and printf($this->back_url);?>">
                <button type="submit" id="submit_btn" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-danger go-back">Go back</button>
            </div>
        </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    function palert(msg){
        $('.alert-error').remove();
        $('.page-header').after('<div class="alert alert-error">'+msg+'</div>');

        return;
    }

    $(document).ready(function () {
        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });

        $('#area_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                    _self.nextAll('.loading').remove();
                });
        });

        $( "#s_name1" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();
                $('.loading').remove();
                var _self = $(this);
                var targetUrl = '<?php echo HOST."staff?sname=1&name=" ?>' + $('#s_name1').val();

                //get ajax content
                var aj = _self.parent().parent().next().find('.load-ajax');
                if (aj.length){
                    _self.after("<span class=\'loading\'></span>");
                    $.get(targetUrl
                        ,function(data,status){
                            aj.html(data);
                            _self.next('.loading').remove();
                        });
                }

                return false;
            }
        });

        $( "#s_name" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();
                $('.loading').remove();
                var _self = $(this);
                var targetUrl = '<?php echo HOST."staff?sname=1&name=" ?>' + $('#s_name').val();

                //get ajax content
                var aj = _self.parent().parent().next().find('.load-ajax');
                if (aj.length){
                    _self.after("<span class=\'loading\'></span>");
                    $.get(targetUrl
                        ,function(data,status){
                            aj.html(data);
                            _self.next('.loading').remove();
                        });
                }

                return false;
            }
        });

////////////////////
        $('#add_leader_btn').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists( $(item[i]).attr('value'), true ) ) {
                    _des = $('#leader_name');
                    _des.append(item[i]);
                }
            }
        });

        $('#remove_leader_btn').click(function(){
            _self = $('#leader_name');
            item = _self.children('option:selected').remove();

            _name = $('#leader_name option');
            id_str = '';

            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }

            id_str = id_str.replace(/\,$/, '');
            $('#pic1').val(id_str);
        });

        $('#add_pg_btn').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists( $(item[i]).attr('value'), false) ) {
                    _des = $('#pg_name');
                    _des.append(item[i]);
                }
            }
        });

        $('#remove_pg_btn').click(function(){
            _self = $('#pg_name');
            item = _self.children('option:selected').remove();

            _name = $('#pg_name option');
            id_str = '';

            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }

            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);
        });

        $('#form').submit(function(event){
            event.preventDefault();

            _name = $('#leader_name option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic1').val(id_str);

            if ( $('#pic1').val() == '' ) {
            	alert('Leader cannot blank');
            	return false;
            }
            ////////////////////////////////
            _name = $('#pg_name option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);

            $(this).unbind( event );

            //submit
            $(this).submit();

        });

        function is_exists(id, is_leader) {
            if(is_leader) {
                _des = $('#leader_name');
            } else {
                _des = $('#pg_name');
            }

            items = _des.children('option');
            for(var i = 0; i < items.length; i++) {
                if ($(items[i]).attr('value') == id) {
                    return true;
                }
            }
            return false;
        }
    });
</script>