<div class="page-header">
    <form action="/manage/sales-team-create" method="get">
        <h1>List Sales team</h1>
        <span class="pull-right"><button class="btn-success" type="submit"><i class="icon-plus"></i></button></span>
    </form>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php echo $this->render('manage/sales-team/partials/search.phtml') ?>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Area</th>
            <th>Province</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            <?php
            if (isset($this->sales_teams) and $this->sales_teams)
                foreach ($this->sales_teams as $k=>$sales_team): ?>
            <tr>
                <td>
                    <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                    ?>
                </td>
                <td><?php echo $sales_team['name'];?></td>
                <td><?php echo ( isset($this->cached_areas[$sales_team['area_id']]) ? $this->cached_areas[$sales_team['area_id']] : '' );?></td>
                <td><?php echo ( isset($this->cached_regional_markets[$sales_team['regional_market']]) ? $this->cached_regional_markets[$sales_team['regional_market']] : '' );?></td>
                <td class="">
                    <a title="Edit" href="/manage/sales-team-create?id=<?php echo $sales_team['id'];?>"> <i class="icon-edit"></i></a>
                    <a title="Delete" class="confirmLink" href="/manage/sales-team-del?id=<?php echo $sales_team['id'];?>"> <i class="icon-trash"></i></a>
                </td>
            </tr>
            <?php endforeach;?>

        </tbody>
    </table>
</div>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>