<div class="page-header">
    <h1>Distributor of Inventory (DOI)</h1>
    <small> ກວດສະຕ໋ອກຂອງຮ້ານຄ້າ </small>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a id="search_bar" class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                <!-- Search --> <b style="color: #916b68; font-weight: bold; font-size:15px;" >Filter <b style="font-size:18px;"><span class="icon-filter"></span></b></b>
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('timing/distributor-doi/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <!-- <div class='pull-left'><strong> DOI : <?php echo $this->params['doi_rate']." / Day"; ?></strong></div> -->
    <div class='pull-right'><b><u style="font-size: 18px;"><strong> Total Stock : <b style="color: blue;"><?php echo $this->total_count['sum_stock']; ?></b></strong></u></b></div>
</div>

<div class="table-responsive">
    <?php echo $this->render('timing/distributor-doi/partials/list.phtml'); ?>
</div>

