<form class="form-search form-horizontal" method="get" action="/manage/bypass-imei/bypass-imei">
    <div class="row">
        <div class="span5">
	       <div class="control-group">
                <label for="imei" class="span1">Imei</label>
                <textarea id="imei" name="imei" cols="20" rows="6" style="resize: none;"><?php 
                    if (isset($this->params['imei'])) {
                        $tmp = implode("\n", $this->params['imei']);
                        echo $tmp;
                    }
                ?></textarea>
            </div>

        </div>
        <div class="span5">

        </div>
    </div>
    

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <!-- <button type="submit" name="export" value="1" class="btn btn-primary">Export By Staff</button> -->

</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>

    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 2,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        multi();
        
        
    });
    
</script>