<?php 
    // print_r($this->params);
    $period_loop = $this->params['week_no'];
?>

<div id='fr_by_week_chart'></div>
<br />
<table class="table table-bordered">
    <thead>
    <tr>
        <th style="vertical-align:middle;"><div align="center">No.</div></th>
        <th style="vertical-align:middle;"><div align="center">Model</div></th>
        <th style="vertical-align:middle;"><div align="center">Channel</div></th>
        <?php  
            for ($i=1;$i<=$period_loop;$i++) {
                echo "<th style='vertical-align:middle;'><div align='center'>Week #".$i."</div></th>";
            }
        ?>
        <th style="vertical-align:middle;"><div align="center">Total</div></th>
    </tr>
    </thead>
    <tbody>
    <?php

        // Data for List
        if (isset($this->sellout_by_channel) and $this->sellout_by_channel) {

            $data = $this->sellout_by_channel;
            
            for ($i=0;$i<count($data);$i++) {

                $cnt = $i + 1;

                echo "<tr>";
                echo "<td><div align='center'>".$cnt."</div></td>";
                echo "<td>".$data[$i]['product_name']."</td>";
                echo "<td>".$data[$i]['channel_name']."</td>";

                for ($j=1;$j<=$period_loop;$j++) {

                    echo "<td><div align='right'>".$data[$i]['W'.$j]."</div></td>";

                    // $series[$i]['values'][$j] = $data[$i][$day_text];
                    // if ($data[$i][$day_text] >= $y_temp) { $y_temp = $data[$i][$day_text]; }

                    $sum_day['W'.$j] += $data[$i]['W'.$j];

                }

                echo "<td><div align='right'>".$data[$i]['sellout']."</div></td>";
                echo "</tr>";

                $sum_sellout += $data[$i]['sellout'];

            } 

            echo "<tr style='background-color:#BDBDBD;'>";
            echo "<td colspan='3'><div align='center'>Total</div></td>";

            for ($i=1;$i<=$period_loop;$i++) {
                echo "<td><div align='right'>".$sum_day['W'.$i]."</div></td>";
            }

            echo "<td><div align='right'>".$sum_sellout."</div></td>";
            echo "</tr>";

        }

        // Data for Chart
        $y_max = $y_temp = 0;
        $series = array();

        
        if (isset($this->sellout_by_product) and $this->sellout_by_product) {

            $data = $this->sellout_by_product;

            for ($i=0;$i<count($data);$i++) {

                $series[$i] = array(
                    'text'       => $data[$i]['product_name'],
                    // 'line-color' => '#4dbac0',
                    'line-width' => '2px',
                    'shadow'     => 0,
                    'palette'    => $i,
                    'marker'     => array(
                                        'background-color' => '#fff',
                                        'size'             => 3,
                                        'border-width'     => 1,
                                        // 'border-color'     => '#36a2a8',
                                        'shadow'           => 0,
                                    ),
                    // 'guideLabel'=> array( 'text' => $data[$i]['model_name'].' : %v%'),

                );

                for ($j=0;$j<=$period_loop;$j++) {

                    $week_txt = $j + 1;

                    $series[$i]['values'][$j] = $data[$i]['W'.$week_txt];
                    if ($data[$i]['W'.$week_txt] >= $y_temp) { $y_temp = $data[$i]['W'.$week_txt]; }

                }

            }

        }

        // echo "<pre>"; print_r($data);
        // echo "<pre>"; print_r($sum_day);

        $y_max = ceil($y_temp/10) * 10;
        $series = json_encode($series, JSON_NUMERIC_CHECK);

        // echo $y_max; echo "<br/>";
        // echo $series; echo "<br/>";


    ?>

    </tbody>
</table>
<br/>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script src= "https://cdn.zingchart.com/zingchart.min.js"></script>
<script> 
    zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";
    ZC.LICENSE = ["569d52cefae586f634c54f86dc99e6a9","ee6b7db5b51705a13dc2339db3edaf6d"];
</script>

<script type="text/javascript">

var period_loop = <?php echo $period_loop; ?>;

// KA Sellout
var y_max = '<?php echo $y_max; ?>';
var series = '<?php echo $series; ?>';

var x_list = [];
var i;

for (i = 0; i < period_loop; i++) { 
    var week_txt = i + 1;
    x_string = 'Week #' + week_txt; 
    x_list.push(x_string);
}

/*https://www.zingchart.com/gallery/chart/#!dashboard-custom-tokens*/
zingchart.THEME = "classic";

var fr_by_week_config = {
    "background-color":"#ecf2f6",
    "graphset":[
        {
            "type":"line",
            "background-color":"#fff",
            "border-color":"#dae5ec",
            "border-width":"1px",
            "width":"96%",
            "height":"80%",
            "x":"2%",
            "y":"3%",
            "title":{
                "margin-top":"7px",
                "margin-left":"12px",
                "text":"Factory Report By Week",
                "background-color":"none",
                "shadow":0,
                "text-align":"center",
                "font-family":"Arial",
                "font-size":"11px",
                "font-color":"#707d94"
            },
            "plot":{
                "animation":{
                    "delay":500,
                    "effect":"ANIMATION_SLIDE_LEFT"
                },
                "value-box": {},
            },
            "plotarea":{
                "margin":"50px 25px 70px 46px"
            },
            "scale-y":{
                "auto-fit":true,
                // "values":"0:"+y_max+":500",
                "line-color":"none",
                "guide":{
                    "line-style":"solid",
                    "line-color":"#d2dae2",
                    "line-width":"1px",
                    "alpha":0.5
                },
                "tick":{
                    "visible":false
                },
                "item":{
                    "font-color":"#8391a5",
                    "font-family":"Arial",
                    "font-size":"10px",
                    "padding-right":"5px"
                }
            },
            "scale-x":{
                "line-color":"#d2dae2",
                "line-width":"2px",
                "values":x_list,
                "tick":{
                    "line-color":"#d2dae2",
                    "line-width":"1px"
                },
                "guide":{
                    "visible":false
                },
                "item":{
                    "font-color":"#8391a5",
                    "font-family":"Arial",
                    "font-size":"10px",
                    "padding-top":"5px"
                }
            },
            "legend":{
                "layout":"x6",
                "background-color":"none",
                "shadow":0,
                "margin":"425 auto 0 auto",
                "border-width":"0px",
                "item":{
                    "font-color":"#707d94",
                    "font-family":"Arial",
                    "padding":"0px",
                    "margin":"0px",
                    "font-size":"9px"
                },
                "marker":{
                    "show-line":"true",
                    "type":"match",
                    "font-family":"Arial",
                    "font-size":"10px",
                    "size":4,
                    "line-width":2,
                    "padding":"3px"
                }
            },
            "crosshair-x":{
                "lineWidth":1,
                "line-color":"#707d94",
                "plotLabel":{
                    "shadow":false,
                    "font-color":"#000",
                    "font-family":"Arial",
                    "font-size":"10px",
                    "padding":"5px 10px",
                    "border-radius":"5px",
                    "alpha":1
                },
                "scale-label":{
                    "font-color":"#ffffff",
                    "background-color":"#707d94",
                    "font-family":"Arial",
                    "font-size":"10px",
                    "padding":"5px 10px",
                    "border-radius":"5px"
                }
            },
            "tooltip":{
                "visible":false
            },
            "series":JSON.parse(series),
            
        }
    ]
};

zingchart.render({ 
    id : 'fr_by_week_chart', 
    data : fr_by_week_config, 
    height: 500, 
    width: '100%' 
});

</script>