<div class="page-header">
   <h1>Store Focus By Brand</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('timing/store-focus-by-brand/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>

<!-- <div align="right">
    <strong> Huawei : <?php echo $this->total_count['cnt_com1']; ?> |</strong>
    <strong> VIVO : <?php echo $this->total_count['cnt_com2']; ?> |</strong>
    <strong> Samsung : <?php echo $this->total_count['cnt_com3']; ?> |</strong>
    <strong> All Brand : <?php echo $this->total_count['cnt_total']; ?></strong>
</div> -->

<div class="table-responsive">
    <?php
    echo $this->render('timing/store-focus-by-brand/partials/list.phtml');
    ?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>
<?php echo $this->confirm();?>