<table class="table table-bordered">
    <thead>
    <tr>
        <th><div align="center">No.</div></th>
        <th><div align="center">From</div></th>
        <th><div align="center">To</div></th>
        <th><div align="center">Area</div></th>
        <th><div align="center">Staff Code</div></th>
        <th><div align="center">Group</div></th>
        <th><div align="center">Staff Name</div></th>
        <th><div align="center">Prinish Type</div></th>
        <th><div align="center">Price</div></th>
        <th><div align="center">Remark</div></th>
        <th><div align="center">Action</div></th>
    </tr>
    </thead>
    <tbody>
        <?php 


            if ($this->penalty_list) {
                $data = $this->penalty_list;
                //print_r($data);

                for($i=0;$i<count($data);$i++) { 

                    $cnt = $i + 1;
                    echo "<tr>";
                    echo    "<td>".$cnt."</td>";
                    echo    "<td><div align='center'>".$data[$i]['from_date']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['to_date']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['area_name']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['staff_code']."</div></td>";
                    echo    "<td><div align='center'>".$data[$i]['staff_group']."</div></td>";
                    echo    "<td>".$data[$i]['staff_name']."</td>";
                    echo    "<td><div align='center'>".$data[$i]['punish_type']."</div></td>";
                    echo    "<td><div align='right'>".number_format($data[$i]['price'])."</div></td>";
                    echo    "<td>".$data[$i]['pm_remark']."</td>";
                    echo    "<td>
                                <div align='center'>
                                    <a title='Edit' href='/manage/penalty-charge-create-staff?id=".$data[$i]['pm_id']."'> <i class='icon-edit'></i></a>
                                    <a title='Delete' class='confirmLink' href='/manage/penalty-charge-staff-del?id=".$data[$i]['pm_id']."'> <i class='icon-trash'></i></a>
                                </div>
                            </td>";
                    echo "</tr>";
                }

            }
        ?>
    </tbody>
</table>

<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>

<script>
    /*
    $(document).ready(function () {

        $modal = $('#modal');
        $('.badge.badge-default').click(function(){

            _self = $(this);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>manage/store-control-short-report',
                {
                    store_control_id : _self.data('store-control-id')
                },
                function(data){
                    //alert(data);
                    $modal.html(data);
                    $modal.modal();
                    var name = _self.parents('tr').children('td:nth-child(2)').html();
                    $modal.find('h3').append(' <small>&bull; '+name+'</small>');
            });
        });
    
    });
    */
</script>