<div class="page-header">
    <h1>List AM</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
    if (isset($this->messages_success) and $this->messages_success)
        foreach ($this->messages_success as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<div class="row-fluid">
    <div class="span12">
        <?php 
            echo $this->partial('manage/am/partials/am.phtml', 
                    array(
                        'list' => $this->list[ AM_ID ],
                        'org' => $this->org
                    )); 
        ?>
    </div>
</div>
