<style>
    .div_li {
        position: absolute;
        left: 30px;
        top: 5px;
        font-size: 20px;
    }
</style>

<?php
$params = $this->params;

//echo '<pre>';
//print_r($params);
//echo '</pre>';

?>
<div class="page-header">
    <h1><?php echo $params['staff_name'].' - ครั้งที่ '.$params['time']; ?></h1>
</div>
<form role="form" action="<?php echo HOST.'trainer/pc-first-training-save';?>" method="post">

    <div class="row">

        <div class="span6">
            <p><span><strong>- E-Test Answer -</strong></span></p>
            <table class="table-striped" width="100%" >
                <tr>
                    <td width="120px">Topic E-Test</td>
                    <td style="padding-left: 5px;">: <?php echo isset($staff_list['topic']) ? $staff_list['topic'] : "-"; ?></td>
                </tr>
                <tr>
                    <td width="120px">Created At</td>
                    <td style="padding-left: 5px;">: <?php echo isset($staff_list['created_at']) ? $staff_list['created_at'] : "-"; ?></td>
                </tr>
<!--                <tr>-->
<!--                    <td width="120px">Score</td>-->
<!--                    <td style="padding-left: 5px;">: --><?php //echo isset($staff_list['score']) ? ($staff_list['score']*10)." / 100" : "-"; ?><!--</td>-->
<!--                </tr>-->
            </table>
        </div>
        
        <div class="span6">

            <p><span><strong>- Personal Info -</strong></span></p>
            <table class="table-striped" width="100%" >
                <tr>
                    <td width="120px">Area Name</td>
                    <td style="padding-left: 5px;">: <?php echo isset($staff_list['area_name']) ? $staff_list['area_name'] : "-"; ?></td>
                </tr>
                <tr>
                    <td width="120px">Staff Code</td>
                    <td style="padding-left: 5px;">: <?php echo isset($staff_list['staff_code']) ? $staff_list['staff_code'] : "-"; ?></td>
                </tr>
                <tr>
                    <td width="120px">Staff Name</td>
                    <td style="padding-left: 5px;">: <?php echo isset($staff_list['staff_name']) ? $staff_list['staff_name'] : "-"; ?></td>
                </tr>
                <tr>
                    <td width="120px">Staff Group</td>
                    <td style="padding-left: 5px;">: <?php echo isset($staff_list['group_name']) ? $staff_list['group_name'] : "-"; ?></td>
                </tr>
            </table>

        </div>

    </div>

    <br/>
    <br/>

    <input type="hidden" name="pft_id" id="pft_id" value="<?php echo $staff_list['pft_id']; ?>">
    <input type="hidden" name="back_url" id="back_url" value="<?php echo $this->back_url; ?>">

    <button type="button" class="btn btn-inverse go-back">Go Back</button>

</form>

<script type="text/javascript">
    $(document).ready(function () {
        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();
            return false;
        });
    });
</script>