<div class="page-header">
    <h1>Knowledge Base Type</h1>
</div>
<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-success">' . $message . '</div>';
    endforeach;
?>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                echo $this->render('trainer/knowledge-base-type/partials/search.phtml');
                ?>
            </div>
        </div>
    </div>
</div>


<a title="Create Knowledge Base Type" class="btn btn-success" href="/trainer/knowledge-base-type-edit"><i class="icon-plus"></i> Create Type</a><br /><br />
<div class="table-responsive">
    <?php
    echo $this->render('trainer/knowledge-base-type/partials/list.phtml');
    ?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $('.form-search button:reset').click(function (e) {
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
        $('.navbar').hide();
        $('.subnavbar-inner').hide();
        $('.footer').hide();
        $('body').css('padding-top', 0);
        $('.main').css('border-bottom', 0);
    });
</script>
<?php

echo $this->confirm();

function EnableDisplay($value)
{
    if ($value == 'Y') {
        return '<i class="icon-ok" style="color: #009a2a;"></i>';
    } else if ($value == 'P') {
        return '<i class="icon-play-sign" style="color: #e6a000;"></i>';
    } else {
        return '<i class="icon-remove" style="color: #e60400;"></i>';
    }
}

?>