<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<!--<script type="text/javascript" src="/js/bootstrap-modal.js"></script>-->
<!--<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>-->
<!--<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>-->

<style>
    .p-model .remove-model {
        margin-bottom: 9px;
    }

    .alert-msg {
        background: #F9EEB8;
        border-bottom-right-radius: 4px;
        border-bottom-left-radius: 4px;
        border-top: 2px solid #e55;
        /*display: none;*/
        margin: 0;
        /*margin-left: -200px;*/
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 9999;
    }

    .alert-msg.show {
        display: inline-block;
    }

    .alert-msg p {
        font-weight: bold;
        font-size: 12px;
        font-family: tahoma, arial;
        margin: 0 10px;
        line-height: 2em;
        text-align: center;
    }
    body{
        font-family: phetsarath ot;
    }
</style>

<?php
    if ( isset($this->area_permission) && !empty($this->area_permission) ) {
        $area_permission = json_encode($this->area_permission); 
    } else {
        $area_permission = '';
    }

$status_active = array(
    'Y' => '<i class="icon-ok" style="color: #12aa00;"></i> Active',
    'N' => '<i class="icon-remove" style="color: #e60400;"></i> Not Active',
    'W' => '<i class="icon-time" style="color: #e6a208;"></i> Wait',
);

    $userStorage = Zend_Auth::getInstance()->getStorage()->read();

?>

<div class="page-header">
    <?php if (isset($this->store) and $this->store): ?>
        <h1>
            Edit Store ແກ້ໄຂຮ້ານຄ້າ

            <?php if ($this->store['active_status'] == "W") { ?>
                <span style="float: right; color: #333333;"><?php echo $status_active[$this->store['active_status']]; ?></span>

            <?php } else { ?>

                <a href="#modal_detail" data-toggle="modal">
                    <span style="float: right; color: #333333;"><?php echo $status_active[$this->store['active_status']]; ?></span>
                </a>
                
            <?php } ?>

        </h1>

        <div id="modal_detail" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" style="width: 100%">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="myModalLabel"><i class="icon-file-text-alt"></i> Detail</h3>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <p>
                            <span><strong>Status : </strong></span> <?php echo $status_active[$this->store['active_status']]; ?>
                        </p>
                    </div>
                    <div class="form-group">
                        <?php
                        $db = Zend_Registry::get('db');

                        $get = array(
                            'staff_name' => new Zend_Db_Expr("CONCAT(sf.firstname, ' ', sf.lastname)"),
                        );

                        $select = $db->select()
                            ->from(array('sf' => 'staff'), $get)
                            ->where("sf.id = (?)", $this->store['active_by']);

                        if ($this->store['active_status'] != null && $this->store['active_status'] != "W") {
                            $active_by = $db->fetchRow($select);
                        }

                        ?>
                        <p><span><strong>Active By : </strong></span> <?php echo $active_by['staff_name']; ?></p>
                    </div>
                    <div class="form-group">
                        <p>
                            <span><strong>Active At : </strong></span><?php echo date("d/m/Y H:m:s", strtotime($this->store['active_at'])); ?>
                        </p>
                    </div>
                    <?php if ($this->store['active_status'] == "N") { ?>
                        <div class="form-group">
                            <p><span><strong>Remark : </strong></span><?php echo $this->store['active_remark']; ?></p>
                        </div>
                    <?php } ?>

                    <?php

                    $get = array(
                        'photo_name' => 'sp.photo_name',
                    );
                    $select = $db->select()
                        ->from(array('sp' => 'store_photos'), $get)
                        ->where("sp.store_id = (?)", $this->store['id'])
                        ->order('sp.created_at DESC')
                        ->limit(3);

                    $store_img = $db->fetchAll($select);

                    $path_photo = date("Y", strtotime($this->store['active_at'])) . '/' . date("Y-m", strtotime($this->store['active_at'])) . '/' . date("Y-m-d", strtotime($this->store['active_at']));

                    $count_photo = count($store_img);

                    for ($i = 0; $i < $count_photo; $i++) {
                        echo "<img style='margin-top: 10px; display: block; margin: 0 auto;' src=http://api.oppo.in.th/images/oppo_store_photos/" . $path_photo . '/' . $store_img[$i]['photo_name'] . "><br>";
                    }

                    ?>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
        </div>
    <?php else: ?>
        <h1>Create Store</h1>
    <?php endif; ?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<?php if (isset($this->WARNING_TIMING_MESSAGES) and $this->WARNING_TIMING_MESSAGES):?>
<div class="alert-msg">
    <p class="msg"><?php echo $this->WARNING_TIMING_MESSAGES;?></p>
</div>
<?php endif;?>

<div class="row-fluid">
    <div class="span12">
        <iframe name="ifrmSave" id="ifrmSave" height="500" width="100%" style="display:none;"></iframe>
        <form role="form" id="form" action="<?php echo HOST.'manage/store-save';?>" method="post" target="ifrmSave">
            <div class="row-fluid">
                <div class="span12">
                    <?php echo $this->render('manage/store/partials/store-info.phtml'); ?>
                </div>

<!-- <div class="span6"> -->

                        <!-- <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <legend style="color: blue; font-style: bold;">Distributor Change ( WMS ID ):</legend>
                                    <input type="hidden" id="d_id" name="d_id" value="<?php echo $this->d_chain1->id; ?>" />
                                    <table class="table">
                                        <?php 

                                            if ($userStorage->group_id == ADMINISTRATOR_ID || !isset($this->store) ) {

                                                echo "<tr>";
                                                echo "<td>ລະຫັດ WMS</td>";
                                                echo "<td> : </td>";
                                                echo "  <td style='padding-left: 10px;'>
                                                            <div class='input-append'>
                                                                <input type='text' id='d_id_search' name='d_id_search' />
                                                                <button id='btn_bind_d_chain1' class='btn btn-success' type='button'>Bind</button>
                                                            </div>
                                                        </td>";
                                                echo "</tr>";
                                            } 

                                        ?>

                                        <tr>
                                            <td>ລະຫັດຮ້ານຄ້າ</td>
                                            <td> : </td>
                                            <td style="padding-left: 10px;" id="d_id_txt"><?php echo $this->d_chain1->id; ?></td>
                                        </tr>
                                        <tr>
                                            <td>ຊື່ຮ້ານຄ້າ</td>
                                            <td> : </td>
                                            <td style="padding-left: 10px;" id="d_name" ><?php echo $this->d_chain1->title; ?></td>
                                        </tr>
                                        <tr>
                                            <td>ທີ່ຢູ່</td>
                                            <td> : </td>
                                            <td style="padding-left: 10px;" id="d_add"><?php echo $this->d_chain1->add; ?></td>
                                        </tr>
                                    </table>

                                </div>
                            </div>
                        </div> -->

                <!-- </div> -->

            </div>


            <button type="submit" id="check_btn" style="display:none;"></button>
        </form>
    </div>
</div>

<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

<script type="text/javascript">

    $("#market_type,#org,#market_name,#store_level,#dis_id,#agency,#attribute,#area_id,#district,#regional_market,#sale_type").select2();

        $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
    });


    var showOnlyOptionsSimilarToText = function (selectionEl, str, isCaseSensitive, callback) {
        if (typeof isCaseSensitive == 'undefined')
            isCaseSensitive = true;
        if (isCaseSensitive)
            str = str.toLowerCase();

        var $el = $(selectionEl);

        $el.children("option:selected").removeAttr('selected');
        $el.val('');
        $el.children("option").hide();

        $el.children("option").filter(function () {
            var text = $(this).text();
            if (isCaseSensitive)
                text = text.toLowerCase();

            if (text.indexOf(str) > -1)
                return true;

            return false;
        }).show();

        if (callback)
            eval(callback+'();');
    };

    function initSearchOption(){
        var timeout;
        $("#SearchBox").on("keyup", function () {
            var userInput = $("#SearchBox").val();
            window.clearTimeout(timeout);
            timeout = window.setTimeout(function() {
                showOnlyOptionsSimilarToText($("#d_id"), userInput, true);
            }, 500);

        });
    }

    function checkStoreNameFromStoreType(){
        var storeName = $("#name").val().trim();
        storeName = storeName.toUpperCase();

        if ( storeName.indexOf('TELEWIZ') >= 0 || storeName.indexOf('เทเลวิซ') >= 0 ) { $("#org").val(41); }
    }

    function checkStoreName(e){
        var timeout;
        $("#name").on("keyup", function () {
            var id = $("#id").val().trim();
            var storeName = $("#name").val().trim();
            window.clearTimeout(timeout);
            timeout = window.setTimeout(function() {
                checkStoreNameAction(id, storeName);
            }, 500);

        });
    }

    function checkStoreNameAction(id, storeName) {
        $("#store_name_check").html('');
        storeName = storeName.toUpperCase();
        
        if ( storeName.indexOf('TELEWIZ') >= 0 || storeName.indexOf('เทเลวิซ') >= 0 ) { $("#org").val(41); }

        if (storeName) {
            $.ajax({
                    url: '<?php echo HOST ?>ajax/check-store-name',
                    type: 'post',
                    dataType: 'html',
                    data: {id : id, store_name : storeName},
                })
                .done(function(data) {
                    console.log("success");

                    if (data) {
                        $("#store_name_check").html(data);
                    }
                })
                .fail(function() {
                    console.log("error");
                })
                .always(function() {
                    console.log("complete");
                });
                    
        }
    }

    function refreshMarketName() {

        var group_id = '<?php echo $userStorage->group_id; ?>';
        var st_id = $('#id').val();

        $('form').bind('submit',function(e){e.preventDefault();});
        $('form button, form input, form select').prop('disabled', true);
        $('.loading').remove();

        $('#market_type').after('<span class="loading"></span>');
        var _self = $('#market_type');
        var market_type_id = $('#market_type').val();
        var area_id = '<?php echo $area_permission; ?>';

        $.get("/manage/load-market-name",
            {
                market_type_id: market_type_id,
                area_id : area_id
            }
            ,function(data,status){
                $('form').unbind('submit');
                $('form button, form input, form select').prop('disabled', false);
                if (st_id != '') {
                    if (group_id != 1) { $('#org').prop('disabled', true); $('#store_level').prop('disabled', true); }
                } else {
                    if (group_id != 1) { $('#store_level').prop('disabled', true); }
                }

                /*
                var bkk_list = ["73","74","75","76","77","78","79","80"];
                var area_id = $('#area_id').val();

                if ( bkk_list.indexOf(area_id) == "-1" ) {

                } else {
                    $("#sub_district").prop('disabled', true);
                    $("#sub_district").prop('required', false);
                }*/

                var obj = $.parseJSON( data );
                $('#market_name').find('option:not(:first)').remove();
                for (var i = 0; i < obj.length; i++) {
                    $('#market_name').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                }

                $('.loading').remove();
            });
    }

    function saveMarketName() {

        var market_name_id  = $('#modal_mn_id').val();
        var market_name     = $('#modal_mn_name').val();
        var market_type_id  = $('#modal_mt_id').val();

        $.post('<?php echo HOST ?>manage/save-market-name',
        {
            market_name_id  : market_name_id,
            market_name     : market_name,
            market_type_id  : market_type_id
        },
        function(data){
            //alert("Update Successful!");
            refreshMarketName();
            /*
            console.log(market_name_id);
            console.log('1');
            refreshMarketName();
            console.log('2');
            console.log($('#market_name').val());
            $("#market_name").select2().select2("val", null);
            $("#market_name").select2().select2("val", 242);
            $('#market_name').val(242);

            //$('#market_name').select2('data', {id: market_name_id, a_key: market_name});
            //$("#market_name").select2("val", market_name_id);
            //$('#market_name').val(market_name_id);
            console.log('3');
            console.log($('#market_name').val());
            //alert(data);*/
        });
    }

    $(document).ready(function () {
        initSearchOption();
        checkStoreName();

        var group_id = '<?php echo $userStorage->group_id; ?>';
        var st_id = $('#id').val();
        // alert($('#id').val());

        $(".js-example-basic-single").select2();

        $('#market_type').change(function(){
            $("#mn_edit").attr("data-mt", $('#market_type').val());
            $("#mn_add").attr("data-mt", $('#market_type').val());
            
            refreshMarketName();
        });

        $('#market_name').change(function(){
            $("#mn_edit").attr("data-id", $('#market_name').val());
            $("#mn_edit").attr("data-name", $('#market_name option:selected').text());
        });

        $modal = $('#modal');
        $modal_market_name = $('#modal_market_name');

        $('.badge').click(function(){

            if ($('#market_type option:selected').text() !== 'Choose') {

                _self = $(this);
                $('body').modalmanager('loading');

                $.post('<?php echo HOST ?>manage/edit-market-name',
                    {
                        market_name_id  : _self.data('id'),
                        market_name     : _self.data('name'),
                        market_type_id  : _self.data('mt'),
                    },
                    function(data){
                        //alert(data);
                        $modal.html(data);
                        $modal.modal();
                        var market_type = $('#market_type option:selected').text();
                        $modal.find('h3').append(' <small>&bull; '+market_type+'</small>');
                });

            } else {
                alert("Please Select Market Type First");
            }
            
        });

//////////////////////////////////////////////// 


        $('.go-back').click(function(e){
            window.location.href = $('#back_url').val();

            return false;
        });

        $('#btn_bind_d_chain1').click(function(e) {
            var d_id = $('#d_id_search').val();
            $.get("/ajax/load-retailer-info",
                {d_id: d_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    //alert(data);

                    if (data != '[]') {
                        $('#d_id').val(obj[0]['id']);
                        $('#d_id_txt').html("<font color='green'>" + obj[0]['id'] + "</font>");
                        $('#d_name').html("<font color='green'>" + obj[0]['title'] + "</font>");
                        $('#d_add').html("<font color='green'>" + obj[0]['add'] + "</font>");
                        $('#shipping_address').val(obj[0]['add']);
                        $('#agency_name').val(obj[0]['name']);
                        $('#phone_number').val(obj[0]['tel']);
                        $('#contact_email').val(obj[0]['email']);

                    } else {

                        $('#d_id_txt').html("<font color='red'>Distributor Not Found!</font>");
                        $('#d_name').html("<font color='red'>-</font>");
                        $('#d_add').html("<font color='red'>-</font>");
                    }
                    
                });
        });

        $('#area_id').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    $('form').unbind('submit');
                    $('form button, form input, form select').prop('disabled', false);
                    $('#district').prop('disabled', true);
                    $('#sub_district').prop('disabled', true);

                    if (st_id != '') {
                        if (group_id != 1) { $('#org').prop('disabled', true); $('#store_level').prop('disabled', true); }
                    } else {
                        if (group_id != 1) { $('#store_level').prop('disabled', true); }
                    }

                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option:not(:first)').remove();
                    $('#district').find('option:not(:first)').remove();
                    $('#sub_district').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("/ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    
                    $('#district').find('option:not(:first)').remove();
                    $('#sub_district').find('option:not(:first)').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                                
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }                        
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                        $('#sub_district').prop('disabled', true);

                        if (st_id != '') {
                            if (group_id != 1) { $('#org').prop('disabled', true); $('#store_level').prop('disabled', true); }
                        } else {
                            if (group_id != 1) { $('#store_level').prop('disabled', true); }
                        }

                    }
                });
        });

        $('#district').change(function(){

            // var bkk_list = ["73","74","75","76","77","78","79","80"];
            // var area_id = $('#area_id').val();

            //if ( bkk_list.indexOf(area_id) == "-1" ) {

                $("#sub_district").prop('required', true);

                $('form').bind('submit',function(e){e.preventDefault();});
                $('form button, form input, form select').prop('disabled', true);
                $('.loading').remove();

                $(this).after('<span class="loading"></span>');
                var _self = $(this);
                var region = $(this).val();
                $.post("/ajax/get-sub-district-cbb", {
                        region: region
                    }
                    ,function(data,status){
                        $('#sub_district').find('option:not(:first)').remove();
                        
                        try {
                            if (data) {
                                var obj = $.parseJSON( data );
                                
                                for (var i = 0; i < obj.length; i++) {
                                    $('#sub_district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                                }                        
                            }

                        } catch(err) {

                        } finally {
                            $('.loading').remove();
                            $('form').unbind('submit');
                            $('form button, form input, form select').prop('disabled', false);

                            if (st_id != '') {
                                if (group_id != 1) { $('#org').prop('disabled', true); $('#store_level').prop('disabled', true); }
                            } else {
                                if (group_id != 1) { $('#store_level').prop('disabled', true); }
                            }
                            
                        }
                    });
            //} else {
                //$("#sub_district").prop('required', false);
            //}

        });

        $('#th_province').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var th_province_id = $(this).val();
            $.get("/staff/load-th-amphure",
                {th_province_id: th_province_id}
                ,function(data,status){
                    
                    $('form').unbind('submit');
                    $('form button, form input, form select').prop('disabled', false);
                    $('#th_district').prop('disabled', true);

                    if (st_id != '') {
                        if (group_id != 1) { $('#org').prop('disabled', true); $('#store_level').prop('disabled', true); }
                    } else {
                        if (group_id != 1) { $('#store_level').prop('disabled', true); }
                    }

                    var obj = $.parseJSON( data );

                    $('#th_amphure').find('option:not(:first)').remove();
                    $('#th_district').find('option:not(:first)').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#th_amphure').append('<option value="'+obj[i]['id']+'">'+obj[i]['name_th']+'</option>');
                    }

                    $('.loading').remove();
                    
                });
        });

        $('#th_amphure').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var th_amphure_id = $(this).val();
            $.get("/staff/load-th-district",
                {th_amphure_id: th_amphure_id}
                ,function(data,status){
                    
                    $('form').unbind('submit');
                    $('form button, form input, form select').prop('disabled', false);

                    if (st_id != '') {
                        if (group_id != 1) { $('#org').prop('disabled', true); $('#store_level').prop('disabled', true); }
                    } else {
                        if (group_id != 1) { $('#store_level').prop('disabled', true); }
                    }

                    var obj = $.parseJSON( data );

                    $('#th_district').find('option:not(:first)').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#th_district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name_th']+'</option>');
                    }

                    $('.loading').remove();
                    
                });
        });

        $( "#s_name" ).keypress(function( event ) {
            if ( event.which == 13 ) {
                event.preventDefault();

                $('form').bind('submit',function(e){e.preventDefault();});
                $('form button, form input, form select').prop('disabled', true);

                $('.loading').remove();
                var _self = $(this);
                var targetUrl = '<?php echo HOST."staff?sname=1&code=" ?>' + $('#s_name').val();

                //get ajax content
                var aj = _self.parent().parent().next().find('.load-ajax');
                if (aj.length){
                    _self.after("<span class=\'loading\'></span>");
                    $.get(targetUrl
                        ,function(data,status){
                            $('form').unbind('submit');
                            $('form button, form input, form select').prop('disabled', false);

                            /*
                            var bkk_list = ["73","74","75","76","77","78","79","80"];
                            var area_id = $('#area_id').val();

                            if ( bkk_list.indexOf(area_id) == "-1" ) {

                            } else {
                                $("#sub_district").prop('disabled', true);
                                $("#sub_district").prop('required', false);
                            }*/

                            aj.html(data);
                            _self.next('.loading').remove();
                        });
                }

                return false;
            }
        });

        $('#add_btn_asm').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_asm( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_asm');
                    _des.append(item[i]);
                }
            }
        });

        // js for store_staff [ BM, PCM, Sale, PC ]
        $('#add_btn_bm').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_bm( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_bm');
                    _des.append(item[i]);
                }
            }
        });

        $('#add_btn_pcm').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_pcm( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_pcm');
                    _des.append(item[i]);
                }
            }
        });

        $('#add_btn_sales').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_sales( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_sales');
                    _des.append(item[i]);
                }
            }
        });

           // mkt Case
        $('#add_btn_mkt').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_mkt( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_mkt');
                    _des.append(item[i]);
                }
            }
        })

       $('#add_btn_pcdb').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_pcdb( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_pcdb');
                    _des.append(item[i]);
                }
            }
        })

         $('#add_btn_rd').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_rd( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_rd');
                    _des.append(item[i]);
                }
            }
        })

        $('#add_btn_pg').click(function(){
            _self = $('#name_result');
            item = _self.children('option:selected').clone();
            list = $(item);

            for (var i = 0; i < item.length; i++) {

                if ( ! is_exists_pg( $(item[i]).attr('value') ) ) {
                    _des = $('#pic_name_pg');
                    _des.append(item[i]);
                }
            }
        });

        $('#remove_btn_asm').click(function(){
            _self = $('#pic_name_asm');
            item = _self.children('option:selected').remove();
        });

        $('#remove_btn_bm').click(function(){
            _self = $('#pic_name_bm');
            item = _self.children('option:selected').remove();
        });

        $('#remove_btn_pcm').click(function(){
            _self = $('#pic_name_pcm');
            item = _self.children('option:selected').remove();
        });

        $('#remove_btn_sales').click(function(){
            _self = $('#pic_name_sales');
            item = _self.children('option:selected').remove();
        });

        $('#remove_btn_pg').click(function(){
            _self = $('#pic_name_pg');
            item = _self.children('option:selected').remove();
        });

          $('#remove_btn_mkt').click(function(){
            _self = $('#pic_name_mkt');
            item = _self.children('option:selected').remove();
        })

         $('#remove_btn_pcdb').click(function(){
            _self = $('#pic_name_pcdb');
            item = _self.children('option:selected').remove();
        })

         $('#remove_btn_rd').click(function(){
            _self = $('#pic_name_rd');
            item = _self.children('option:selected').remove();
        })

        $('#submit_btn').click(function(){
            if ( ! $('#form')[0].checkValidity() ) {
                $('#check_btn').click();
                return false;
            }

            $('form#form button').prop('disabled', true);

            // pc
            _name = $('#pic_name_pg option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic').val(id_str);

            // leader
            _name = $('#pic_name_sales option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic1').val(id_str);


            // asm 
            _name = $('#pic_name_asm option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic4').val(id_str);

             //mkt
            _name = $('#pic_name_mkt option');
            id_str = '';

             for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic5').val(id_str);


            // pcm 
            _name = $('#pic_name_pcm option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic2').val(id_str);

            // rd
            _name = $('#pic_name_rd option');
            id_str = '';

             for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic6').val(id_str);

           // PCDB
            _name = $('#pic_name_pcdb option');
            id_str = '';

             for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }
            
            id_str = id_str.replace(/\,$/, '');
            $('#pic7').val(id_str);

            // bm
            _name = $('#pic_name_bm option');
            id_str = '';
            
            for(var i = 0; i < _name.length; i++) {
                id_str += $(_name[i]).attr('value') + ',';
            }

            id_str = id_str.replace(/\,$/, '');
            $('#pic3').val(id_str);

            $('#form').submit();
        });

    });

  //mkt case
    function is_exists_mkt(id){
          _des = $('#pic_name_mkt');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function is_exists_asm(id) {
        _des = $('#pic_name_asm');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function is_exists_bm(id) {
        _des = $('#pic_name_bm');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }
    
    function is_exists_pcm(id) {
        _des = $('#pic_name_pcm');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function is_exists_pcdb(id) {
        _des = $('#pic_name_pcdb');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

     function is_exists_rd(id) {
        _des = $('#pic_name_rd');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function is_exists_sales(id) {
        _des = $('#pic_name_sales');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function is_exists_pg(id) {
        _des = $('#pic_name_pg');
        items = _des.children('option');
        for(var i = 0; i < items.length; i++) {
            if ($(items[i]).attr('value') == id) {
                return true;
            }
        }
        return false;
    }

    function palert(msg){
        $('.alert-error').remove();
        $('.page-header').after('<div class="alert alert-error">'+msg+'</div>');
        $('form#form button').prop('disabled', false);
        return;
    }
</script>