<style type="text/css">
    .remove_area_btn,
    .remove_region_btn {
        margin-bottom: 9px;
    }
</style>
<div class="page-header">
    <h1>Edit ASM Standby</h1>
</div>
<form action="<?php echo HOST ?>manage/asm-standby-save" method="post">
<div class="row-fluid">
    <div class="span4">
        <?php if (isset($this->staffs[ $this->id ]) && $this->staffs[ $this->id ]): ?>
            <p>ASM Standby: <strong><?php echo $this->staffs[ $this->id ]; ?></strong></p>
        <?php endif ?>
    </div>

    <div class="span4">
        <div class="control-group">
            <label id="area_anchor">Area</label>
            <?php if (isset($this->asm) && $this->asm): ?>
                <?php foreach ($this->asm as $value): ?>
                        <div class="area_select">
                            <select name="area[]" class="form-control">
                                <option value>---</option>
                                <?php if (isset($this->areas) && $this->areas): ?>
                                    <?php foreach ($this->areas as $a_id => $a_name): ?>
                                        <option value="<?php echo $a_id ?>" <?php if($a_id == $value['area_id']) echo 'selected' ?>><?php echo $a_name ?></option>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </select>
                            <button type="button" class="btn btn-default remove_area_btn">&times;</button>
                        </div>
                <?php endforeach ?>
            <?php endif ?>
        </div>
        <div class="control-group">
            <button class="btn btn-default" id="add_area_btn" type="button">Add more</button>
        </div>
    </div>
    
    <div class="span4">
        <div class="control-group">
            <label id="region_anchor">Province</label>
            <?php if (isset($this->asm_region) && $this->asm_region): ?>
                <?php foreach ($this->asm_region as $value): ?>
                        <div class="region_select">
                            <select name="region[]" class="form-control">
                                <option value>---</option>
                                <?php if (isset($this->regions) && $this->regions): ?>
                                    <?php foreach ($this->regions as $a_id => $reg): ?>
                                        <option value="<?php echo $a_id ?>"
                                            data-area="<?php echo $reg["area_id"] ?>"
                                            <?php if($a_id == $value['area_id']) echo 'selected' ?>><?php echo $reg['name'] ?></option>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </select>
                            <button type="button" class="btn btn-default remove_region_btn">&times;</button>
                        </div>
                <?php endforeach ?>
            <?php endif ?>
        </div>
        <div class="control-group">
            <button class="btn btn-default" id="add_region_btn" type="button">Add more</button>
        </div>
    </div>
    
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="form-actions">
            <input type="hidden" name="id" value="<?php if(isset($this->id) && $this->id) echo $this->id ?>">
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-danger" type="button" onclick="window.location='<?php echo HOST ?>manage/asm-standby'">Cancel</button>
        </div>
    </div>
</div>
</form>

<script type="text/javascript">
    select_area = 
'<div class="area_select">'+
    '<select name="area[]" class="form-control">'+
        '<option value>---</option>'+
        '<?php if (isset($this->areas) && $this->areas): ?>'+
            '<?php foreach ($this->areas as $a_id => $a_name): ?>'+
                '<option value="<?php echo $a_id ?>"><?php echo $a_name ?></option>'+
            '<?php endforeach ?>'+
        '<?php endif ?>'+
    '</select>'+
    ' <button type="button" class="btn btn-default remove_area_btn">&times;</button>'+
'</div>';

    select_region = 
'<div class="region_select">'+
    '<select name="region[]" class="form-control">'+
        '<option value>---</option>'+
        '<?php if (isset($this->regions) && $this->regions): ?>'+
            '<?php foreach ($this->regions as $a_id => $reg): ?>'+
                '<option value="<?php echo $a_id ?>" data-area="<?php echo $reg["area_id"] ?>"><?php echo $reg["name"] ?></option>'+
            '<?php endforeach ?>'+
        '<?php endif ?>'+
    '</select>'+
    ' <button type="button" class="btn btn-default remove_region_btn">&times;</button>'+
'</div>';

    $(document).ready(function() {
        $('#add_area_btn').click(function() {
            $('#area_anchor').parent('.control-group').append(select_area);
            init_area_remove();
        });

        $('#add_region_btn').click(function() {
            $('#region_anchor').parent('.control-group').append(select_region);
            init_region_remove();
        });

        init_area_remove();
        init_region_remove();
    });

    function init_area_remove() {
        $('.remove_area_btn').click(function() {
            $(this).parent('.area_select').remove();
        });
    }

    function init_region_remove() {
        $('.remove_region_btn').click(function() {
            $(this).parent('.region_select').remove();
        });
    }
</script>