<form id="search_form" class="form-search form-horizontal" method="get"
      action="/trainer/knowledge-base-type/knowledge-base-type">
    <div class="row" style="padding-top: 20px;">
        <div class="span5">
            <div class="control-group">
                <label for="name" class="span2">Name</label>
                <input id="name" name="name" type="text" class="search-query form-control span2"
                       value="<?php isset($this->params['name']) and printf($this->params['name']); ?>">
            </div>
        </div>

        <div class="span5">
            <div class="control-group">
                <label for="enable" class="span2">Display</label>
                <select id="enable" name="enable">
                    <option value=""></option>
                    <?php $type = array('Y' => 'Open', 'N' => 'Close');
                    foreach ($type as $key => $value): ?>
                        <option value="<?php echo $key; ?>" <?php if (isset($this->params['enable']) and $this->params['enable'] == $key): ?> selected <?php endif; ?> > <?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>