<style type="text/css">
    .status {
        max-width: 20%;
    }  
</style>

<table class="table table-bordered">
    <thead>
        <tr>
            <th style="text-align:center; color:#0db393; font-size:16px; ">#</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">ຊື່ລູກຄ້າ</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">ເບີໂທລູກຄ້າ</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">Model ລຸ້ນ</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">Color ສີ</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">IMEI</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">Store ຊື່ຮ້ານ</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">ວັນທີລາຍງານຍອດ</th>
            <th style="text-align:center; color:#0db393; font-size:16px; ">ວັນທີ Activate</th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($this->expires) && $this->expires): ?>
            <?php foreach ($this->expires as $key => $expire): ?>
                <tr class="item">
                    <td><?php echo ($this->offset + $key + 1) ?></td>
                    <td><?php echo $expire['customer_name'] ?></td>
                    <td><?php echo $expire['customer_phone'] ?></td>
                    <td><?php if(isset($this->color_cache[ $expire['model_id'] ])) echo $this->color_cache[ $expire['model_id'] ] ?></td>
                    <td><?php echo $expire['brand_name']; ?>  <?php if(isset($this->good_cache[ $expire['product_id'] ])) echo $this->good_cache[ $expire['product_id'] ] ?></td>
                    <!-- <td class="imei_customer" data-toggle="tooltip" title="Customer: <?php echo $expire['customer_name'] ?> / <?php echo $expire['customer_phone'] ?>"><?php echo $expire['imei'] ?></td> -->
                    <td><?php echo $expire['imei'] ?></td>
                    <td><?php echo $expire['name'] ?></td>
                    <td><?php if(isset($expire['from']) && strtotime($expire['from'])) echo date('d/m/Y', strtotime($expire['from'])) ?></td>
                    <td><?php if(isset($expire['activated_date']) && strtotime($expire['activated_date'])) echo date('d/m/Y', strtotime($expire['activated_date'])) ?></td>
                </tr>
            <?php endforeach ?>
        <?php endif ?>
    </tbody>
</table>

<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>

<?php echo $this->load(); ?>