<style>

	.fix-msg {
		background: #F9EEB8;
		border-bottom-right-radius: 4px; 
		border-bottom-left-radius: 4px; 
		border-top: 2px solid #e55;
		display: none;
		margin: 0;
		margin-left: -250px;
		position: fixed;
		top: 0;
		left: 50%;
		width: 500px;
		z-index: 9999;
	}

	.fix-msg.show {
		display: inline-block;
	}

	.fix-msg p {
		font-weight: bold;
		font-size: 15px;
		font-family: tahoma, arial;
		margin: 0 10px;
		line-height: 2em;
		text-align: center;
	}
</style>

<div class="fix-msg">
	<p class="msg">Uploading...</p>
</div>
