<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/jquery.ui.timepicker.css"/>

<form class="form-horizontal" method="get" action="<?php echo HOST ?>timing/kpi-overview">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label class="control-label" for="from">From</label>
                <div class="controls">
                    <input type="text" id="from" name="from" class="date" value="<?php if(isset($this->params['from'])) echo $this->params['from'] ?>">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="to">To</label>
                <div class="controls">
                    <input type="text" id="to" name="to" class="date" value="<?php if(isset($this->params['to'])) echo $this->params['to'] ?>">
                </div>
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </div>
</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>

<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
    });
</script>