<form class="form-search form-horizontal" method="get" action="/timing/kpi">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and $this->params['area_id']==$area->id):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and $this->params['regional_market']==$regional_market->id):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="district" class="span2">District</label>
                <select id="district" name="district" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->districts) :
                        foreach ($this->districts as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['district']) and $this->params['district']==$regional_market->id):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="store" class="span2">Store</label>
                <select id="store" name="store" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->stores) :
                        foreach ($this->stores as $store):?>
                            <option value="<?php echo $store->id;?>" <?php if (isset($this->params['store']) and $this->params['store']==$store->id):?>selected<?php endif;?>><?php echo $store->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="from" class="span2">From Date</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">
            </div>

            <div class="control-group">
                <label for="to" class="span2">To Date</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>

            <div class="control-group">
                <label for="imei" class="span2">IMEI</label>
                <input type="text" class="form-control search-query span2" id="imei" name="imei" value="<?php isset($this->params['imei']) and printf($this->params['imei']);?>">
            </div>
        </div>
    </div>
    
    <input type="hidden" name="type" value="<?php echo $this->type; ?>">
    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('#area_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $.get("<?php echo HOST ?>staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option:not(:first)').remove();
                    $('#district').find('option:not(:first)').remove();
                    $('#store').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                    $('.loading').remove();
                });
        });

        $('#district').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var district = $(this).val();
            $.get("<?php echo HOST ?>staff/load-sales-team",
                {district: district}
                ,function(data,status){
                    var obj         = $.parseJSON( data );
                    var stores      = obj.stores;

                    $('#store').find('option:not(:first)').remove();
                    for (var i = 0; i < stores.length; i++) {
                        $('#store').append('<option value="'+stores[i]['id']+'">'+stores[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option:not(:first)').remove();
                    $('#store').find('option:not(:first)').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }                        
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });

    });
</script>