<form class="form-search form-horizontal" method="get" action="/timing/shop-inventory">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="store_id" class="span2">Store ID</label>
                <input id="store_id" name="store_id" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['store_id']) and printf($this->params['store_id']);?>">
            </div>

            <div class="control-group">
                <label for="store_name" class="span2">Store Name</label>
                <input id="store_name" name="store_name" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['store_name']) and printf($this->params['store_name']);?>">
            </div>

            <div class="control-group">
                <label for="name" class="span2">Model</label>
                <select id="name" name="name[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    $data = $this->goods;
                    if ($this->goods) :
                        foreach ($this->goods as $good_list):
                            ?>
                            <option value="<?php echo $good_list->id;?>" <?php if (isset($this->params['name']) and ( (is_array($this->params['name']) && in_array($good_list['id'], $this->params['name']) || $good_list['id']==$this->params['name'])) ):?>selected<?php endif;?>><?php echo $good_list->name;?></option>
                        <?php
                        endforeach;
                        
                    endif;
                    ?>
                </select>
            </div>

        </div>
        <div class="span5">

            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="district" class="span2">District</label>
                <select id="district" name="district[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->districts) :
                        foreach ($this->districts as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['district']) and ( (is_array($this->params['district']) && in_array($regional_market['id'], $this->params['district']) || $regional_market['id']==$this->params['district'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="store" class="span2">Store</label>
                <select id="store" name="store[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->stores) :
                        foreach ($this->stores as $store):?>
                            <option value="<?php echo $store->id;?>" <?php if (isset($this->params['store']) and ( (is_array($this->params['store']) && in_array($store['id'], $this->params['store']) || $store['id']==$this->params['store'])) ):?>selected<?php endif;?>><?php echo $store->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
            
            <div class="control-group">
                <label for="date" class="span2">From Date</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To Date</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>
<!--
            <div class="control-group">
                <label for="sales_from" class="span2">Sales >=</label>
                <input type="number" min="0" value="<?php if (isset($this->params['sales_from'])) echo $this->params['sales_from'];?>" id="sales_from" name="sales_from" />
            </div>

            <div class="control-group">
                <label for="sales_to" class="span2">Sales <=</label>
                <input type="number" min="0" value="<?php if (isset($this->params['sales_to'])) echo $this->params['sales_to'];?>" id="sales_to" name="sales_to" />
            </div>
-->
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" name="export" value="1" class="btn btn-primary">Export Excel</button>
    <!-- 
	<?php if ($this->access('sales-report', 'area')): ?>
        <button type="submit" name="export" value="1" class="btn btn-primary">Export Excel</button>
    <?php endif ?>
    -->

</form>