<form class="form-search form-horizontal" method="get" action="/timing/analytics-product">
    <div class="row">
        <div class="span5">

            <div class="control-group">
                <label for="brand_id" class="span2"><span style="font-size: 16px; font-style: bold;">Brand | ຢີ່ຫໍ້ : </span></label>
                <select id="brand_id" name="brand_id[]" class="js-example-basic-multiple span3" multiple="multiple">
                    <?php foreach($this->brands as $item) : ?>
                     <option value="<?php echo $item['id'] ?>" <?php if (isset($this->params['brand']) and ( (is_array($this->params['brand']) && in_array($item['id'], $this->params['brand']) || $item['id']==$this->params['brand'])) ):?>selected<?php endif;?>>
                        <?php echo $item['name'] ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="control-group">
            <label for="name" class="span2"><span>Products | ລຸ້ນ :</span></label>
            <select id="name" name="name[]" class="span3 js-example-basic-multiple" multiple="multiple">
                <?php
                $data = $this->goods;
                if ($this->goods) :
                    foreach ($this->goods as $good_list):
                        ?>
                        <option value="<?php echo $good_list['id'];?>" <?php if (isset($this->params['name']) and ( (is_array($this->params['name']) && in_array($good_list['id'], $this->params['name']) || $good_list['id']==$this->params['name'])) ):?>selected<?php endif;?>><?php echo $good_list['brand_name'] ?> <?php echo $good_list['name'];?></option>
                        <?php
                    endforeach;
                    
                endif;
                ?>
            </select>
        </div>

        <div class="control-group">
            <label for="area_id" class="span2">ເຂດ | Area</label>
            <select id="area_id" name="area_id[]" class="span3 js-example-basic-multiple" multiple="multiple">
                <?php
                if ($this->areas) :
                    foreach ($this->areas as $area):
                        ?>
                        <option value="<?php echo $area['id'];?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area['name'];?></option>
                        <?php
                    endforeach;
                endif;
                ?>
            </select>
        </div>

        <div class="control-group">
            <label for="regional_market" class="span2">ເເຂວງ | Province</label>
            <select id="regional_market" name="regional_market[]" class="span3 js-example-basic-multiple" multiple="multiple">
                <?php
                if ($this->regional_markets) :
                    foreach ($this->regional_markets as $regional_market):?>
                        <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                    endforeach;
                endif;
                ?>
            </select>
        </div>

        <div class="control-group">
            <label for="district" class="span2">ເມືອງ | District</label>
            <select id="district" name="district[]" class="span3 js-example-basic-multiple" multiple="multiple">
                <?php
                if ($this->districts) :
                    foreach ($this->districts as $regional_market):?>
                        <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['district']) and ( (is_array($this->params['district']) && in_array($regional_market['id'], $this->params['district']) || $regional_market['id']==$this->params['district'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                    endforeach;
                endif;
                ?>
            </select>
        </div>

        <div class="control-group">
            <label for="store" class="span2">ຮ້ານຄ້າ | Store</label>
            <select id="store" name="store[]" class="span3 js-example-basic-multiple" multiple="multiple">
                <?php
                if ($this->stores) :
                    foreach ($this->stores as $store):?>
                        <option value="<?php echo $store->id;?>" <?php if (isset($this->params['store']) and ( (is_array($this->params['store']) && in_array($store['id'], $this->params['store']) || $store['id']==$this->params['store'])) ):?>selected<?php endif;?>><?php echo $store->name;?></option>
                        <?php
                    endforeach;
                endif;
                ?>
            </select>
        </div>
    </div>
    <div class="span5">
        <div class="control-group">
            <label for="date" class="span2">ຄົ້ນຫາຈາກວັນທີ | From Date</label>
            <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

        </div>
        <div class="control-group">
            <label for="date" class="span2"> ຫາວັນທີ | To Date</label>
            <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
        </div>

        <div class="control-group">
            <label for="d_tag" class="span2"><span style="font-size: 16px; font-style: bold;">Distributor Tag :</span></label>
            <select id="d_tag" name="d_tag" class="span3">
                <option value="">Selected</option>
                <option value="1" <?php if($this->params['d_tag'] == 1): ?> selected <?php endif; ?>>Agent Store</option>
            </select>
        </div>
<!--
            <div class="control-group">
                <label for="sales_from" class="span2">Sales >=</label>
                <input type="number" min="0" value="<?php if (isset($this->params['sales_from'])) echo $this->params['sales_from'];?>" id="sales_from" name="sales_from" />
            </div>

            <div class="control-group">
                <label for="sales_to" class="span2">Sales <=</label>
                <input type="number" min="0" value="<?php if (isset($this->params['sales_to'])) echo $this->params['sales_to'];?>" id="sales_to" name="sales_to" />
            </div>
        -->
    </div>
</div>
<button type="submit" class="btn btn-primary"><span style="font-size: 18px; font-family:'Noto sans lao'">Search</span></button>
<button type="reset" class="btn btn-warning">Reset</button>
<?php if ($this->access('sales-report', 'area')): ?>
    <button type="submit" name="export" value="1" class="btn btn-success">Export Excel</button>
    <button type="submit" name="export" value="2" class="btn btn-success">Export By Model</button>
<?php endif ?>


	<!--
	 <?php if ($this->access('sales-report', 'area')): ?>
        <button type="submit" name="reportproductexport" value="2" formaction="http://whtest.oppo.in.th/centerreport/index.php" class="btn btn-info">Export Store in Area</button>
    <?php endif ?>
	
	 <?php if ($this->access('sales-report', 'area')): ?>
        <button type="submit" name="reportproductexport" value="3" formaction="http://whtest.oppo.in.th/centerreport/index.php" class="btn btn-info">Export Staff in Area</button>
    Select Area and Date
	<?php endif ?>
	<br /><br />
    <?php if ($this->access('sales-report', 'area')): ?>
        <button type="submit" name="reportproductexportstaffarea" value="1" formaction="http://whtest.oppo.in.th/centerreport/index.php" class="btn btn-info">Staff in Area ON Mobile</button>
    Select Area and Date
	<?php endif ?>
	<br /><br />
	 <?php if ($this->access('sales-report', 'area')): ?>
        <button type="submit" name="reportproductexport" value="4" formaction="http://whtest.oppo.in.th/centerreport/index.php" class="btn btn-info">Export All Area</button>
Select Date   
   <?php endif ?>
-->


<!-- <button type="submit" name="export" value="1" class="btn btn-info">Export</button> -->
</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<script>

    $(".js-example-basic-multiple").select2();

    $(document).ready(function () {

        $('#brand_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var brand_id = $(this).val();
            $.get("/tool/get-product",
                {brand_id: brand_id}
                ,function(data,status){
                    var data = $.parseJSON( data );
                    var obj = data.brands;

                    $("#name").empty();

                    for (var i = 0; i < obj.length; i++) {
                        $('#name').append('<option value="'+obj[i]['id']+'">'+obj[i]['brand_name']+' '+obj[i]['name']+'</option>');
                    }
                    _self.nextAll('.loading').remove();
                });
        });


        $('#area_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option:not(:first)').remove();
                    $('#store').find('option:not(:first)').remove();
                    $('#district').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                    _self.nextAll('.loading').remove();
                });
        });


        $('#regional_market').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var regional_market = $(this).val();
            $.get("<?php echo HOST ?>staff/load-sales-by-provience",

                {regional_market: regional_market}
                ,function(data,status){
                    var obj         = $.parseJSON( data );
                    var stores      = obj.stores;

                    $('#store').find('option:not(:first)').remove();
                    for (var i = 0; i < stores.length; i++) {
                        $('#store').append('<option value="'+stores[i]['id']+'">'+stores[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });



        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                region: region
            }
            ,function(data,status){
                $('#district').find('option:not(:first)').remove();
                $('#store').find('option:not(:first)').remove();

                try {
                    if (data) {
                        var obj = $.parseJSON( data );

                        for (var i = 0; i < obj.length; i++) {
                            $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                        }
                    }

                } catch(err) {

                } finally {
                    $('.loading').remove();
                    $('form').unbind('submit');
                    $('form button, form input, form select').prop('disabled', false);
                }
            });
        });
    });

</script>