<form class="form-search form-horizontal" method="get" action="/timing/manage-not-activated">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="name" class="span2">Name</label>
                <input id="name" name="name" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
            </div>

            <div class="control-group">
                <label for="from_date" class="span2">From Date</label>
                <input type="text" class="form-control search-query date span2" id="from_date" name="from_date" value="<?php isset($this->params['from_date']) and printf($this->params['from_date']);?>">
            </div>

            <div class="control-group">
                <label for="to_date" class="span2">To Date</label>
                <input type="text" class="form-control search-query date span2" id="to_date" name="to_date" value="<?php isset($this->params['to_date']) and printf($this->params['to_date']);?>">
            </div>

        </div>
        <div class="span5">
            <div class="control-group">
                <label for="department" class="span2">Department</label>
                <select name="department" id="department" class="span2">
                    <option value="">Choose</option>
                    <?php foreach ($this->departments as $id=>$item):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['department']) and $id==$this->params['department']):?>selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="control-group">
                <label for="team" class="span2">Team</label>
                <select name="team" id="team" class="span2">
                    <option value="">Choose</option>
                    <?php foreach ($this->teams as $id=>$item):?>
                        <option value="<?php echo $id;?>" <?php if (isset($this->params['team']) and $id==$this->params['team']):?>selected<?php endif;?>><?php echo $item;?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and $this->params['area_id']==$area->id):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
        </div>

        <div class="span5">
            <div class="control-group">
                <label for="store" class="span2">Store</label>
                <select id="store" name="store" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->stores) :
                        foreach ($this->stores as $store):?>
                            <option value="<?php echo $store->id;?>" <?php if (isset($this->params['store']) and $this->params['store']==$store->id):?>selected<?php endif;?>><?php echo $store->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and $this->params['regional_market']==$regional_market->id):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="sales_team" class="span2">Sales team</label>
                <select id="sales_team" name="sales_team" class="span3">
                    <option value="">Choose</option>
                    <?php
                    if ($this->sales_teams) :
                        foreach ($this->sales_teams as $item):?>
                            <option value="<?php echo $item->id;?>" <?php if (isset($this->params['sales_team']) and $this->params['sales_team']==$item->id):?>selected<?php endif;?>><?php echo $item->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="imei" class="span2">IMEI</label>
                <input id="imei" name="imei" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['imei']) and printf($this->params['imei']);?>">
            </div>
        </div>
        <div class="span5">
            <div class="control-group">
                <label for="email" class="span2">Email</label>
                <input id="email" name="email" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['email']) and printf($this->params['email']);?>">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>
<script>
    $(document).ready(function () {
        $('#area_id').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option:not(:first)').remove();
                    $('#sales_team').find('option:not(:first)').remove();
                    $('#store').find('option:not(:first)').remove();
                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }
                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var regional_market = $(this).val();
            $.get("/staff/load-sales-team",
                {regional_market: regional_market}
                ,function(data,status){
                    var obj         = $.parseJSON( data );
                    var sales_team  = obj.sales_team;
                    var stores      = obj.stores;

                    $('#sales_team').find('option:not(:first)').remove();
                    for (var i = 0; i < sales_team.length; i++) {
                        $('#sales_team').append('<option value="'+sales_team[i]['id']+'">'+sales_team[i]['name']+'</option>');
                    }

                    $('#store').find('option:not(:first)').remove();
                    for (var i = 0; i < stores.length; i++) {
                        $('#store').append('<option value="'+stores[i]['id']+'">'+stores[i]['name']+'</option>');
                    }

                    $('.loading').remove();
                });
        });

		$('#short_btn').popover({
        	placement: 'bottom',
        	trigger: 'hover'
        });
    });
</script>