<form class="form-search form-horizontal" method="get" action="/timing/shop-inventory-logs">
    <div class="row">
        <div class="span5">
            <div class="control-group">
                <label for="store_id" class="span2">Store ID</label>
                <input id="store_id" name="store_id" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['store_id']) and printf($this->params['store_id']);?>">
            </div>

            <div class="control-group">
                <label for="name" class="span2">Store Name</label>
                <input id="name" name="name" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
            </div>

            <div class="control-group">
                <label for="staff_name" class="span2">Staff Name</label>
                <input id="staff_name" name="staff_name" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['staff_name']) and printf($this->params['staff_name']);?>">
            </div>

            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>

            <!-- <div class="control-group">
                <label for="district" class="span2">District</label>
                <select id="district" name="district[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->districts) :
                        foreach ($this->districts as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['district']) and ( (is_array($this->params['district']) && in_array($regional_market['id'], $this->params['district']) || $regional_market['id']==$this->params['district'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div> -->

            <!-- <div class="control-group">
                <label for="store" class="span2">Store</label>
                <select id="store" name="store[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->stores) :
                        foreach ($this->stores as $store):?>
                            <option value="<?php echo $store->id;?>" <?php if (isset($this->params['store']) and ( (is_array($this->params['store']) && in_array($store['id'], $this->params['store']) || $store['id']==$this->params['store'])) ):?>selected<?php endif;?>><?php echo $store->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div> -->

            <!-- <div class="control-group">
                <label for="org" class="span2">Store Type</label>
                <select id="org" name="org[]" class="span3 multiselect" multiple="multiple">
                    <?php if (isset($this->org) && $this->org): ?>

                        <?php 
                            $arr = $this->org;
                                    
                            for($i=0;$i<=count($arr)-1;$i++) { 
                                $sel = "";
                                if(is_array($_GET['org']) && in_array($arr[$i]['org_id'],$_GET['org'])) {
                                    $sel = 'selected'; 
                                } else if ($arr[$i]['org_id'] == $_GET['org']) {
                                    $sel = 'selected';
                                }
                                echo "<option value='".$arr[$i]['org_id']."' ". $sel ." >".$arr[$i]['org_name']."</option>";
                            } 
                        ?>
                    <?php endif ?>
                </select>
            </div> -->

        </div>

        <div class="span5">
            
            <div class="control-group">
                <label for="date" class="span2">From</label>
                <input type="text" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To</label>
                <input type="text" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>

            <!-- <div class="control-group">
                <label for="sales_from" class="span2">Sales >=</label>
                <input type="number" min="0" value="<?php if (isset($this->params['sales_from'])) echo $this->params['sales_from'];?>" id="sales_from" name="sales_from" />
            </div>

            <div class="control-group">
                <label for="sales_to" class="span2">Sales <=</label>
                <input type="number" min="0" value="<?php if (isset($this->params['sales_to'])) echo $this->params['sales_to'];?>" id="sales_to" name="sales_to" />
            </div> -->

            <!-- <div class="control-group">
                <label for="staff_code" class="span2">Staff Code</label>
                <input id="staff_code" name="staff_code" type="text" class="input-medium search-query form-control span2" value="<?php isset($this->params['staff_code']) and printf($this->params['staff_code']);?>">
            </div> -->

        </div>
    </div>



    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-warning">Reset</button>
  
    <br /><br />

    <!-- <?php if ($this->access('sales-report', 'store')): ?>
        <button type="submit" name="export" class="btn btn-primary" value="1">Export sell all brand</button>
    <?php endif;?>
    <button type="submit" name="export" value="2" class="btn btn-primary">Export Excel</button> -->


	
</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>
    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 3,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }


    $(document).ready(function () {
        multi();

        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data,status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });

        $('#district').change(function(){
            $('.loading').remove();
            $('button, .btn, input').prop('disabled', true);
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var regional_market = $(this).val();
            $.get("<?php echo HOST ?>staff/load-sales-team",
                {district: regional_market}
                ,function(data,status){
                    var obj         = $.parseJSON( data );
                    var stores      = obj.stores;

                    $('#store').find('option').remove();
                    for (var i = 0; i < stores.length; i++) {
                        $('#store').append('<option value="'+stores[i]['id']+'">'+stores[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#store').multiselect("destroy").multiselect(options);

                    $('.loading').remove();
                });
        });

        $('#regional_market').change(function(){
            $('form').bind('submit',function(e){e.preventDefault();});
            $('form button, form input, form select').prop('disabled', true);
            $('.loading').remove();

            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var region = $(this).val();
            $.post("<?php echo HOST ?>ajax/get-district-cbb", {
                    region: region
                }
                ,function(data,status){
                    $('#district').find('option').remove();
                    $('#store').find('option').remove();
                    
                    try {
                        if (data) {
                            var obj = $.parseJSON( data );
                            
                            for (var i = 0; i < obj.length; i++) {
                                $('#district').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                            }

                            $('#district,#store').multiselect("destroy").multiselect(options);
                        }

                    } catch(err) {

                    } finally {
                        $('.loading').remove();
                        $('form').unbind('submit');
                        $('form button, form input, form select').prop('disabled', false);
                    }
                });
        });
    });
</script> 