<div class="page-header">
    <h1>List Users</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Group</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            <?php
            if (isset($this->users) and $this->users)
                foreach ($this->users as $k=>$user): ?>
            <tr>
                <td>
                    <?php
                    $inc = $this->offset + $k + 1;
                    echo $inc;
                    ?>
                </td>
                <td><?php echo $user['name'];?></td>
                <td><?php echo $user['username'];?></td>
                <td><?php echo $user['email'];?></td>
                <td><?php echo $user['group_name'];?></td>
                <td><?php echo $user['created_at'];?></td>
                <td><?php echo $user['updated_at'];?></td>
                <td class="">
                    <a title="Edit" href="/user/create?id=<?php echo $user['id'];?>"> <i class="icon-edit"></i></a>
                    <a title="Delete" class="confirmLink" href="/user/del?id=<?php echo $user['id'];?>"> <i class="icon-trash"></i></a>
                </td>
            </tr>
            <?php endforeach;?>

        </tbody>
    </table>
</div>
<div class="paging">
    <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
</div>
<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<?php echo $this->confirm();?>