<?php 
    //print_r($this->params);

    $d1 = explode('/', $this->params['from']);
    $d2 = explode('/', $this->params['to']);

    $from = $d1[2].'-'.$d1[1].'-'.$d1[0];
    $to = $d2[2].'-'.$d2[1].'-'.$d2[0];

    $month = date('M', strtotime($to));
    $month_last = date('M', strtotime("-31 Days", strtotime($to)));

    $month_text = $d1[0]."-".$d2[0]." ".$month;
    $month_last_text = $d1[0]."-".$d2[0]." ".$month_last;

    if (isset($this->kr_sellout) and $this->kr_sellout) {

        $data = $this->kr_sellout;
        // echo "<pre>"; print_r($data);

        echo "<table class='table table-bordered'>";
        echo    "<thead>";
        echo        "<tr>";
        echo            "<th style='vertical-align:middle;'><div align='center'>No.</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Distributor ID</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Distributor Name</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>".$month_last_text."</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>".$month_text."</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Diff</div></th>";
        echo            "<th style='vertical-align:middle;'><div align='center'>Growth</div></th>";
        echo        "</tr>";
        echo    "</thead>";
        echo    "<tbody>";

        $sum_sellout = $sum_sellout_last = $sellout_diff = $growth_rate = 0;

        for ($i=0;$i<count($data);$i++) {

            $sellout_diff = $data[$i]['sellout'] - $data[$i]['sellout_last'];
            $growth_rate = round( ( $sellout_diff / $data[$i]['sellout_last'] ) * 100, 0);

            $color_01 = $color_02 = "";
            if ( $sellout_diff < 0 ) { $color_01 = "color='red'"; }
            if ( $sellout_diff >= 0 ) { $color_01 = "color='green'"; }

            if ( $growth_rate < 0 ) { $color_02 = "color='red'"; }
            if ( $growth_rate >= 0 ) { $color_02 = "color='green'"; }

            // Data for List
            $cnt = $i + 1;

            echo    "<tr>";
            echo        "<td width='5%'><div align='center'>".$cnt."</div></td>";
            echo        "<td width='10%'><div align='center'>".$data[$i]['d_id']."</div></td>";
            echo        "<td>".$data[$i]['d_name']."</td>";
            echo        "<td width='10%'><div align='center'>".$data[$i]['sellout_last']."</div></td>";
            echo        "<td width='10%'><div align='center'>".$data[$i]['sellout']."</div></td>";
            echo        "<td width='10%'><div align='center'><font ".$color_01." >".$sellout_diff."</font></div></td>";
            echo        "<td width='10%'><div align='center'><font ".$color_02." >".$growth_rate."%</font></div></td>";
            echo    "</tr>";
            
            $sum_sellout_last += $data[$i]['sellout_last'];
            $sum_sellout += $data[$i]['sellout'];

        } 

        $sellout_diff = $sum_sellout - $sum_sellout_last;
        $growth_rate = round( ( $sellout_diff / $sum_sellout_last ) * 100, 0);

        $color_01 = $color_02 = "";
        if ( $sellout_diff < 0 ) { $color_01 = "color='red'"; }
        if ( $sellout_diff >= 0 ) { $color_01 = "color='green'"; }

        if ( $growth_rate < 0 ) { $color_02 = "color='red'"; }
        if ( $growth_rate >= 0 ) { $color_02 = "color='green'"; }

        echo    "</tbody>";
        echo    "<tfoot>";
        echo        "<tr style='background-color:#BDBDBD;'>";
        echo            "<td colspan='3'><div align='center'>Grand Total</div></td>";
        echo            "<td><div align='center'>".$sum_sellout_last."</div></td>";
        echo            "<td><div align='center'>".$sum_sellout."</div></td>";
        echo            "<td><div align='center'><font ".$color_01." >".$sellout_diff."</font></div></td>";
        echo            "<td><div align='center'><font ".$color_02." >".$growth_rate."%</font></div></td>";
        echo        "</tr>";
        echo    "</tfoot>";
        echo    "</table>";

    }

?>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>

<script type="text/javascript">

    $(document).ready(function () {


    });

</script>