<script type="text/javascript" src="/js/select2.full.js"></script>
<link href="/css/select2.min.css" type="text/css" rel="stylesheet" />

<div class="page-header">
    <?php if (isset($this->sub_area) and $this->sub_area):?>
        <h1>Edit Sub Area <small><?php echo $this->sub_area['name'] ?></small></h1>
    <?php else:?>
        <h1>Create Sub Area</h1>
    <?php endif;?>
</div>

<?php
if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-error">'.$message.'</div>';
    endforeach;
?>

<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;
?>

<form action="<?php echo HOST ?>manage/sub-area-save" method="post" class="form-horizontal">

    <div class="row" style="border-style: solid; padding: 20px 30px 20px 30px; border-color: lavender;">

    <div class="control-group">
        <label class="control-label" for="name">Sub Area Name : </label>
        <div class="controls">
            <input type="text" id="name" name="name" placeholder="Name" required 
                value="<?php if (isset($this->sub_area['name']) && $this->sub_area['name']) 
                            echo $this->sub_area['name'] ?>">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="name">Staff Name : </label>
        <div class="controls">
            <select name="staff_id" id="staff_id">
                <option value="0"> NO Staff </option>
                <?php if (isset($this->staff) && $this->staff): ?>
                    <?php foreach ($this->staff as $key => $value): ?>
                        <option value="<?php echo $value['staff_id']?>"
                            <?php if (isset($this->sub_area['staff_id']) && $value['staff_id'] == $this->sub_area['staff_id']) 
                                    echo "selected" ?>>[<?php echo $value['staff_code'] ?>] <?php echo $value['staff_name'] ?></option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label"> Status : <span style="color: red">*</span></label>
        <div class="controls">
            <select name="status" id="status">
                <option value="1" <?php if(isset($this->sub_area['status']) && $this->sub_area['status'] == 1) : ?> selected <?php endif; ?> > Active </option>
                <option value="2" <?php if(isset($this->sub_area['status']) && $this->sub_area['status'] == 2) : ?> selected <?php endif; ?> > Disable </option>
            </select>
        </div>
    </div>

        <div style="padding-top: 20px;">
        <input type="hidden" name="id" value="<?php if(isset($this->sub_area['id']) && $this->sub_area['id']) echo$this->sub_area['id'] ?>">
        <button type="submit" class="btn btn-primary">Submit</button>
        <button class="btn btn-danger" onclick="window.location='<?php echo HOST ?>manage/sub-area'">Go Back</button>
    </div>

    </div>




</form>

<script type="text/javascript">
    $('#staff').select2();
</script>