<link rel="stylesheet" type="text/css" href="/css/jquery-ui-1.8.12.custom.css"/>
<link rel="stylesheet" type="text/css" href="/css/jquery.ui.timepicker.css"/>

<form class="form-search form-horizontal" method="get" action="<?php echo HOST ?>hr-report/settings">
    <div class="span5">
        <div class="control-group">
            <label for="name" class="control-label">Product Name</label>
            <div class="controls">
                <input id="name" name="name" type="text" class="search-query" value="<?php isset($this->params['name']) and printf($this->params['name']);?>">
            </div>
        </div>
        
        <div class="control-group">
            <label for="type" class="control-label">KPI For</label>
            <div class="controls">
                <select name="type" id="type" class="search-query">
                    <option value>---</option>
                    <?php foreach (My_Kpi_Object::$name as $key => $value): ?>
                        <option value="<?php echo $key ?>" <?php if(isset($this->params['type']) && $this->params['type'] == $key) echo "selected" ?>><?php echo $value ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>

        <div class="clearfix">
            <button type="submit" class="btn btn-primary">Search</button>
            <button type="reset" class="btn btn-warning">Reset</button>
            <button type="submit" name="export" value="1" class="btn btn-success">Export PDF</button>
	    <button type="submit" name="export" value="2" class="btn btn-success">Export Excel</button>
        </div>

    </div>

    <div class="span5">
        <div class="control-group">
            <label for="from" class="control-label">From Date</label>
            <div class="controls">
                <input type="text" class="search-query date" id="from" name="from" value="<?php if(isset($this->params['from'])) echo $this->params['from'];?>">
            </div>
        </div>
        <div class="control-group">
            <label for="to" class="control-label">To Date</label>
            <div class="controls">
                <input type="text" class="search-query date" id="to" name="to" value="<?php if(isset($this->params['to'])) echo $this->params['to'];?>">
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</form>

<script type="text/javascript" src="/js/jquery-ui-1.8.12.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>

<script>
    $(document).ready(function () {
        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });
    });
</script>