mail.smtp.auth = "login"
mail.smtp.charset = "UTF8"
mail.smtp.ssl = "ssl"
mail.smtp.host = "mail.oppomobile.vn"
mail.smtp.port = "465"
mail.smtp.user = "oppo@oppomobile.vn"
mail.smtp.pass = "skysimon2012"
mail.smtp.from = "oppo@oppomobile.vn"

mail.smtp.fromname2 = "HR"
mail.smtp.user2 = "hr@oppomobile.vn"
mail.smtp.pass2 = "hroppo123.vn"
mail.smtp.from2 = "hr@oppomobile.vn"

;database
resources.db.adapter = "pdo_mysql"
resources.db.params.host = "54.254.19.195"
resources.db.params.username = "oppo"
resources.db.params.password = "B@5M@BT@s5G@OfKd"
resources.db.params.dbname = "hr"
resources.db.profiler.enabled   = false
resources.db.isDefaultTableAdapter = true
resources.db.params.charset     = utf8
;database sell system
resources.db2.params.host = "54.254.19.195"
resources.db2.params.username = "oppo"
resources.db2.params.password = "B@5M@BT@s5G@OfKd"
resources.db2.params.dbname = "warehouse"
;resources.db.params.driver_options = "SET NAMES utf8;"

resources.db_tunnel.adapter = "pdo_mysql"
resources.db_tunnel.params.host = "54.254.19.195"
resources.db_tunnel.params.username = "oppo"
resources.db_tunnel.params.password = "B@5M@BT@s5G@OfKd"
resources.db_tunnel.params.dbname = "bi"
resources.db_tunnel.params.dbnamewh = "warehouse_live"
resources.db_tunnel.params.dbnamecenter = "hr"
resources.db_tunnel.params.charset     = utf8
resources.db_tunnel.params.port     = 3306

[production]
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0
includePaths.library = APPLICATION_PATH "/../library"
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
appnamespace = "Application"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"
resources.frontController.params.displayExceptions = 0

resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts/"
[staging : production]

[testing : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1

[development : production]
resources.db.profiler.enabled   = true
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
resources.frontController.params.displayExceptions = 1

[cli:testing]
phpSettings.assert.bail = 1
phpSettings.error_reporting = E_ALL
bootstrap.path = APPLICATION_PATH "/BootstrapCli.php"

bootstrap.class = "BootstrapCli"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers-cli"
