<div class="page-header">
    <h1>List Attendance Record by Month</h1>
</div>
<?php
    if (isset($this->messages) and $this->messages)
        foreach ($this->messages as $message):
            echo '<div class="alert alert-success">'.$message.'</div>';
        endforeach;

    if (isset($this->messages_error) and $this->messages_error)
        foreach ($this->messages_error as $message):
            echo '<div class="alert alert-error">'.$message.'</div>';
        endforeach;
?>
<div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Search
            </a>
        </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px;">
            <div class="accordion-inner">
                <?php
                    echo $this->render('time/partials/search-month.phtml');
                ?>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive">
    <?php
        echo $this->render('time/partials/list-month.phtml');
    ?>
</div>
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>
<script type="text/javascript" src="/js/bootstrap-modal.js"></script>
<script type="text/javascript" src="/js/bootstrap-modalmanager.js"></script>
<link rel="stylesheet" type="text/css" href="/css/bootstrap-modal.css"/>
<script>
options = {
            selectAllText: 'Select All',
            includeSelectAllOption: true,
            includeSelectAllIfMoreThan: 3,
            disableIfEmpty: true
        };
    $(document).ready(function () {
      $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });
        multi();
        
        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        $modal = $('#modal');

        $('#short_btn').click(function(){
            _self = $(this);
            $('body').modalmanager('loading');

            $.post('<?php echo HOST ?>/ajax/pg-short-report',
                {
					from : $('#from_date').val().trim(),
					to : $('#to_date').val().trim()
                },
                function(data){
                    $modal.html(data);
                    $modal.modal();
            	}
            );
        });
    });

    
    function multi() {
        $('.multiselect').multiselect(options);
    }
</script>
<?php echo $this->load('combobox');?>