<div class="page-header">
    <h1>System Calculate Off Day For All Staff</h1>
</div>
<?php

if (isset($this->messages) and $this->messages)
    foreach ($this->messages as $message):
        echo '<div class="alert alert-success">' . $message . '</div>';
    endforeach;

if (isset($this->messages_error) and $this->messages_error)
    foreach ($this->messages_error as $message):
        echo '<div class="alert alert-error">' . $message . '</div>';
    endforeach;

?>


<div class="container">
	<div class="row form-group">
    
        <div class="span12">
                <label>Calculate for all staff</label>
                <button type="submit" id="calculate" class="btn btn-primary">Calculate</button>
             </div>
        </div>
        
       <div class="span12">
        	 <div class="progress" id="processBar">
             <div class="bar">
       </div>
       
</div>
        
</div>

<script>
      $('#calculate').click(function(){
            _self = $(this);
               var progressBar = $('#processBar .bar'),
               width = 0;
                
               progressBar.width(width);
                
               var interval = setInterval(function() {
                
                    width += 4;
                
                    progressBar.css('width', width + '%');
                
                    if (width >= 100) {
                        clearInterval(interval);
                    }
                }, 1000);

               $.post('<?php

echo HOST

?>/time/off',
                {
					month : 4
                },
                function(data){
                  if(data == 1)
                  {                    
                     progressBar.css('width', '100%');      
                     alert('Successful. System wil auto reload after 4 seconds !');
                     setTimeout(window.location.href = '<?php echo HOST. 'time/off-list'; ?>',4000); 
                  }
                  
                  else if(data == -1)
                  {
                      progressBar.css('width', '0%');      
                      alert('Error when update!');     
                  }
            	}
            );
        });

</script>