    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="text-align: center;" width="5%">No.</th>
            <th style="text-align: center;" width="45%">Name</th>
            <th style="text-align: center;" width="25%">Type</th>
            <th style="text-align: center;" width="10%">Status</th>
            <th style="text-align: center;" width="10%">Number of visitors</th>
            <th style="text-align: center;" width="10%">Action</th>
        </tr>
        </thead>
        <tbody>

        <?php
        $count = 0;
        if (isset($this->list) and $this->list)
            foreach ($this->list as $k => $item):
                ?>
                <tr>
                    <td style="text-align: center;"><?php echo $k + 1; ?></td>
                    <td><?php echo isset($item['id']) ? $item['title'] : ''; ?></td>
                    <td><?php echo isset($item['id']) ? $item['knowledge_type'] : ''; ?></td>
                    <td style="text-align: center;"><?php echo isset($item['id']) ? EnableDisplay($item['enable']) : ''; ?></td>
                    <td style="text-align: center;">
                        <a href="/trainer/knowledge-base-excel?id=<?php echo $item['id']; ?>&title=<?php echo $item['title']; ?>&category=<?php echo $item['knowledge_type']; ?>" style="padding-right: 0.8em;"><span class="badge"><?php echo $item['visitors']; ?></span></a>
                    </td>
                    <td title="View" style="text-align: center;">
                        <a title="Edit" href="/trainer/knowledge-base-edit?id=<?php echo $item['id']; ?>"
                           style="padding-right: 0.4em;"><i class="icon-edit"></i></a>&nbsp;
                        <a title="Delete" href="/trainer/knowledge-base-delete?id=<?php echo $item['id']; ?>" onclick="return confirm('Are you sure to remove?');"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="paging">
        <?php echo $this->paging($this->total, $this->limit, $this->offset, $this->url);?>
    </div>