<form id="search_form" class="form-search form-horizontal" method="get"
      action="/trainer/sales-knowledge-base/knowledge-base">
    <div class="row" style="padding-top: 20px;">
        <div class="span5">
            <div class="control-group">
                <label for="title" class="span2">Name</label>
                <input id="title" name="title" type="text" class="search-query form-control span2"
                       value="<?php isset($this->params['title']) and printf($this->params['title']); ?>">
            </div>
        </div>

        <div class="span5">
            <div class="control-group">
                <label for="knowledge_type" class="span2">Type</label>
                <select id="knowledge_type" name="knowledge_type" class="span3">
                    <option value=""></option>
                    <?php
                    if ($this->knowledge_type) :
                        foreach ($this->knowledge_type as $value):
                            ?>
                            <option value="<?php echo $value['id']; ?>"
                                    <?php if (isset($this->params['knowledge_type']) and ((is_array($this->params['knowledge_type']) && in_array($value['id'], $this->params['knowledge_type']) || $value['id'] == $this->params['knowledge_type']))): ?>selected<?php endif;
                            ?>><?php echo $value['name']; ?></option>
                            <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
            <div class="control-group">
                <label for="enable" class="span2">Display</label>
                <select id="enable" name="enable">
                    <option value=""></option>
                    <?php $type = array('Y' => 'Open', 'N' => 'Close', 'P' => 'Preview');
                    foreach ($type as $key => $value): ?>
                        <option value="<?php echo $key; ?>" <?php if (isset($this->params['enable']) and $this->params['enable'] == $key): ?> selected <?php endif; ?> > <?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
</form>