<form id="search_form" class="form-search form-horizontal" method="get"
      action="/trainer/apk-demo-statistics/apk-demo-statistics">
    <div class="row" style="padding-top: 20px;">
        <div class="span5">
            <div class="control-group">
                <label for="date" class="span2">From</label>
                <input type="text" autocomplete="off" class="form-control search-query date span2" id="from" name="from" value="<?php isset($this->params['from']) and printf($this->params['from']);?>">

            </div>
            <div class="control-group">
                <label for="date" class="span2">To</label>
                <input type="text" autocomplete="off" class="form-control search-query date span2" id="to" name="to" value="<?php isset($this->params['to']) and printf($this->params['to']);?>">
            </div>
        </div>

        <div class="span5" style="display: none;">
            <div class="control-group">
                <label for="area_id" class="span2">Area</label>
                <select id="area_id" name="area_id[]" class="span3 multiselect" multiple="multiple">
                    <?php

                    if ($this->areas) :
                        foreach ($this->areas as $area):
                            ?>
                            <option value="<?php echo $area->id;?>" <?php if (isset($this->params['area_id']) and ( (is_array($this->params['area_id']) && in_array($area['id'], $this->params['area_id']) || $area['id']==$this->params['area_id'])) ):?>selected<?php endif;?>><?php echo $area->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
            <div class="control-group">
                <label for="regional_market" class="span2">Province</label>
                <select id="regional_market" name="regional_market[]" class="span3 multiselect" multiple="multiple">
                    <?php
                    if ($this->regional_markets) :
                        foreach ($this->regional_markets as $regional_market):?>
                            <option value="<?php echo $regional_market->id;?>" <?php if (isset($this->params['regional_market']) and ( (is_array($this->params['regional_market']) && in_array($regional_market['id'], $this->params['regional_market']) || $regional_market['id']==$this->params['regional_market'])) ):?>selected<?php endif;?>><?php echo $regional_market->name;?></option>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </select>
            </div>
            <div class="control-group">
                <label for="chk_bkk" class="span2">Select Only BKK</label>
                <input id="chk_bkk" name="chk_bkk" type="checkbox" value="1" <?php if (isset($this->params['chk_bkk'])) { echo "checked"; } ?>>
            </div>
        </div>
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Search</button>
    <button type="reset" class="btn btn-warning">Reset</button>
    <button type="submit" id="export" name="export" value="1" class="btn btn-primary">Export By Store</button>
    <button type="submit" id="export" name="export" value="2" class="btn btn-success">Export By Staff</button>
</form>

<script type="text/javascript" src="<?php echo HOST ?>js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo HOST ?>css/bootstrap-multiselect.css" type="text/css"/>

<script>
    options = {
        selectAllText: 'Select All',
        includeSelectAllOption: true,
        includeSelectAllIfMoreThan: 2,
        disableIfEmpty: true
    };

    function multi() {
        $('.multiselect').multiselect(options);
    }

    $(document).ready(function () {

        $( '.date' ).datepicker({ dateFormat: "dd/mm/yy" });

        $('.form-search button:reset').click(function (e){
            $('.form-search input, .form-search select').val('');
            $('.form-search').submit();
            return false;
        });

        multi();

        $('#area_id').change(function(){
            $('.loading').remove();
            $(this).after('<span class="loading"></span>');
            var _self = $(this);
            var area_id = $(this).val();
            $('button, .btn, input').prop('disabled', true);
            $.get("/staff/load-province",
                {area_id: area_id}
                ,function(data, status){
                    var obj = $.parseJSON( data );
                    $('#regional_market').find('option').remove();

                    for (var i = 0; i < obj.length; i++) {
                        $('#regional_market').append('<option value="'+obj[i]['id']+'">'+obj[i]['name']+'</option>');
                    }

                    $('button, .btn, input').prop('disabled', false);
                    $('#regional_market, #district, #store').multiselect("destroy").multiselect(options);
                    $('.loading').remove();
                });
        });
    });
</script>
